#lang racket/base

(require racket/list racket/runtime-path rackunit
         "../../aloe/driver.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/type.rkt" exn:fail:aloe-type? type-of type->datum))

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define no-mark '(if #t (Option None) (Option Some (Position new 0 0))))
(define no-path '(if #t (Option None) (Option Some (Path new "/unused"))))
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (type st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))

;; Independent positional model: construct a zipper from logical order/focus.
(define (zipper order focus)
  `(AloemacsBuffers new (List of ,@(reverse (take order focus)))
                       ,(list-ref order focus) (List of ,@(drop order (add1 focus)))))
(define (fresh)
  `(AloemacsBuffer new
     (AloemacsEditor new ((Text from-string "") indexed-value)
                        (Position new 0 0) #f 0 0 (List empty) ,no-mark 0)
     ,no-path))
(define (state)
  (define st (make-driver))
  ;; No Fs or Term capability exists; collection sends cannot cause host I/O.
  (ev st `(load ,(path->string file-path)))
  (for ([name '(a b c d)] [n '(1 2 3 4)])
    (def! st name
      `(AloemacsBuffer new
         (AloemacsEditor new
           (Text indexed (List of ,(format "~a middle" name) ,(format "~a first" name))
                         ,(format "~a current-long" name)
                         (List of ,(format "~a last" name)) 2)
           (Position new 2 ,n) ,(odd? n) ,n ,(add1 n)
           (List of (UndoFrame new (Text from-string ,(format "old ~a" name))
                                  (Position new 0 ,n) ,(add1 n) ,n))
           (Option Some (Position new 1 ,n)) ,(+ n 4))
         ,(if (odd? n) '(Option Some (Path new "./same-path")) no-path))))
  st)
(define (same-collection st actual expected)
  (def! st 'comparison-actual actual)
  (def! st 'comparison-expected expected)
  (same st 'comparison-actual 'comparison-expected)
  (for ([field '(before current-buffer after)])
    (same st `(comparison-actual ,field) `(comparison-expected ,field))))

(test-case "checked collection signatures and invalid sends"
  (define st (state))
  (def! st 'buffers (zipper '(a b c) 1))
  (for ([send '((focus-next) (focus-previous) (insert-after d) (remove-current))])
    (check-equal? (type st `(buffers ,@send)) 'AloemacsBuffers)
    (check-not-exn (lambda () (ev st `(buffers ,@send)))))
  (for ([selector '(focus-next focus-previous remove-current)])
    (for ([expr (list `(buffers ,selector a) `(buffers ,selector a b)
                     `(a ,selector) `(1 ,selector) `(AloemacsBuffers ,selector)
                     `((List of a) ,selector))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st expr)) (format "reject ~s" expr))))
  (for ([expr '((buffers insert-after) (buffers insert-after a b)
               (buffers insert-after "a") (buffers insert-after (a editor))
               (buffers insert-after (Option Some a)) (buffers insert-after buffers)
               (buffers insert-after (Path new "a")) (a insert-after a)
               (1 insert-after a) (AloemacsBuffers insert-after a))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st expr)) (format "reject ~s" expr))))

(test-case "next and previous preserve complete payloads at every edge and wrap"
  (define st (state))
  (for ([order '((a) (a b) (a b c) (a b c d))])
    (for ([focus (in-range (length order))])
      (def! st 'source (zipper order focus))
      (define original (ev st 'source))
      (define next (modulo (add1 focus) (length order)))
      (define previous (modulo (sub1 focus) (length order)))
      (same-collection st '(source focus-next) (zipper order next))
      (same-collection st '(source focus-previous) (zipper order previous))
      (same-collection st '((source focus-next) focus-previous) 'source)
      (same-collection st '((source focus-previous) focus-next) 'source)
      (def! st 'cycle 'source)
      (for ([i (in-range (length order))]) (def! st 'cycle '(cycle focus-next)))
      (same-collection st 'cycle 'source)
      (for ([i (in-range (length order))]) (def! st 'cycle '(cycle focus-previous)))
      (same-collection st 'cycle 'source)
      (check-equal? (ev st 'source) original))))

(test-case "insertion selects immediately after first, middle, and last without rebuilding"
  (define st (state))
  (for ([order '((a) (a b) (a b c))])
    (for ([focus (in-range (length order))])
      (def! st 'source (zipper order focus))
      (define original (ev st 'source))
      (define new-order (append (take order (add1 focus)) '(d) (drop order (add1 focus))))
      (same-collection st '(source insert-after d) (zipper new-order (add1 focus)))
      (same-collection st '((source insert-after d) remove-current)
                       (zipper order (min (add1 focus) (sub1 (length order)))))
      (check-equal? (ev st 'source) original))))

(test-case "removal chooses following, preceding, then a completely fresh untitled editor"
  (define st (state))
  (for ([order '((a) (a b) (a b c))])
    (for ([focus (in-range (length order))])
      (def! st 'source (zipper order focus))
      (define original (ev st 'source))
      (define remaining (append (take order focus) (drop order (add1 focus))))
      (define expected (if (null? remaining) (zipper (list (fresh)) 0)
                           (zipper remaining (min focus (sub1 (length remaining))))))
      (same-collection st '(source remove-current) expected)
      (check-equal? (ev st 'source) original)))
  (def! st 'source (zipper '(a b c) 1))
  (for ([expected (list (zipper '(a c) 1) (zipper '(a) 0)
                       (zipper (list (fresh)) 0) (zipper (list (fresh)) 0))])
    (def! st 'source '(source remove-current))
    (same-collection st 'source expected))
  (check-equal? (ev st '((source current-buffer) name)) "untitled"))

(test-case "duplicate paths, names, and equal-valued buffers retain positions"
  (define st (state))
  (same st '(a path) '(c path))
  (check-equal? (ev st '(a name)) (ev st '(c name)))
  (check-equal? (ev st '(b name)) (ev st '(d name)))
  (for ([order '((a c b d) (a a b) (a b a) (a a a))])
    (for ([focus (in-range (length order))])
      (def! st 'source (zipper order focus))
      (define original (ev st 'source))
      (same-collection st '(source focus-next)
                       (zipper order (modulo (add1 focus) (length order))))
      (same-collection st '(source focus-previous)
                       (zipper order (modulo (sub1 focus) (length order))))
      (define remaining (append (take order focus) (drop order (add1 focus))))
      (same-collection st '(source remove-current)
                       (zipper remaining (min focus (sub1 (length remaining)))))
      (same-collection st '(source insert-after a)
                       (zipper (append (take order (add1 focus)) '(a)
                                       (drop order (add1 focus))) (add1 focus)))
      (check-equal? (ev st 'source) original))))
