#lang racket/base

(require racket/list racket/port racket/runtime-path racket/string rackunit
         "../../aloe/driver.rkt" "../../aloe/host.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/type.rkt" exn:fail:aloe-type? type-of type->datum)
         "../../host/racket/fs.rkt" "../../host/racket/aloemacs-run.rkt")

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define-runtime-path main-path "../../examples/aloemacs/main.aloe")
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))
(define (type st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))
(define no-path '(if #t (Option None) (Option Some (Path new ""))))
(define no-prompt '(if #t (Option None)
                       (Option Some (AloemacsPrompt new "" "" 0 "" (List empty)))))
(define history '(List of (UndoFrame new (Text from-string "undo") (Position new 0 1) 2 3)))
(define mark '(Option Some (Position new 1 1)))
(define (indexed lines [focus 0])
  `(Text indexed (List of ,@(reverse (take lines focus))) ,(list-ref lines focus)
     (List of ,@(drop lines (add1 focus))) ,focus))
(define (editor lines [line 0] [col 0] [top 0] [left 0] [height 17] [quit #f] [focus 0])
  `(AloemacsEditor new ,(indexed lines focus) (Position new ,line ,col)
     ,quit ,top ,left ,history ,mark ,height))
(define (buffer id ed [path #f])
  `(AloemacsBuffer new ,ed ,(if path `(Option Some (Path new ,path)) no-path) ,id))
(define (zipper bs [focus 0])
  `(AloemacsBuffers new (List of ,@(reverse (take bs focus))) ,(list-ref bs focus)
     (List of ,@(drop bs (add1 focus)))))
(define (leaf id [bid 41] [top 0] [left 0] [lock #f])
  `(AloemacsWindowTree Leaf (AloemacsView new ,id ,bid ,top ,left ,lock)))
(define (right a b) `(AloemacsWindowTree Right ,a ,b))
(define (below a b) `(AloemacsWindowTree Below ,a ,b))
(define (windows tree selected [w 9] [h 8]) `(AloemacsWindows new ,tree ,selected ,w ,h))
(define (prepared lines [text "x"] [col 1] [label "P:"] [note ""])
  `(Option Some (AloemacsPrompt new ,label ,text ,col ,note (List of ,@lines))))
(define (session bs tree [selected 7] [lines '("alpha.txt" "dir/")])
  `(AloemacsSession new ,bs (base fs) "saved" #f "old query" (Position new 1 2)
     #t #t (List of "ring" "older") (base pending) ,(prepared lines)
     (Option Some "previous") (Option Some (AloemacsCommand FindFile))
     ,(windows tree selected)))
(define (rebuild s #:buffers [bs `(,s buffers)] #:windows [ws `(,s windows)]
                 #:prompt [p `(,s prompt)] #:waiting [waiting `(,s waiting-command)]
                 #:submission [submission `(,s last-submission)] #:echo [echo `(,s echo)]
                 #:pending [pending `(,s pending)] #:searching [searching `(,s searching)]
                 #:query [query `(,s query)] #:wrapped [wrapped `(,s wrapped)]
                 #:failing [failing `(,s failing)])
  `(AloemacsSession new ,bs (,s fs) ,echo ,searching ,query (,s origin)
     ,wrapped ,failing (,s kill-ring) ,pending ,p ,submission ,waiting ,ws))

;; Ordered, changeable directory names; every Fs send remains observable.
(define default-listing '(("alpha.txt" file) ("alpine.txt" file) ("dir" directory)
                          ("beta.txt" file) ("bravo.txt" file)))
(define (counted-fs [host-name 'FsHost] [listing default-listing])
  (define names (box (map car listing)))
  (define disk (make-fs-double "/cwd"
    (for/hash ([entry (in-list (cons '("" directory) listing))])
      (values (if (equal? (car entry) "") "/cwd" (string-append "/cwd/" (car entry)))
              (cadr entry)))
    (for/hash ([entry (in-list listing)] #:when (eq? (cadr entry) 'file))
      (values (string-append "/cwd/" (car entry)) "disk contents"))))
  (define calls (box '()))
  (define (forward selector args)
    (set-box! calls (append (unbox calls) (list (cons selector args))))
    (define result (host-receiver-send disk selector args))
    (if (eq? selector 'names) (unbox names) result))
  (define interface
    (make-host-interface host-name
      (for/list ([m (in-list (host-interface-methods fs-interface))])
        (define selector (host-method-selector m))
        (define params (host-method-parameter-types m))
        (make-host-method selector params (host-method-return-type m)
          (case (length params)
            [(0) (lambda (_) (forward selector '()))]
            [(1) (lambda (_ a) (forward selector (list a)))]
            [(2) (lambda (_ a b) (forward selector (list a b)))])))))
  (values (make-host-receiver interface #f) calls names))
(define (state [host-name 'FsHost] [listing default-listing])
  (define st (make-driver))
  (define-values (host calls names) (counted-fs host-name listing))
  (driver-inject-host! st 'fs-host host)
  (ev st `(load ,(path->string main-path)))
  (def! st 'base 'aloemacs-editor)
  (values st calls names))
(define (effects calls selector)
  (filter (lambda (c) (eq? (car c) selector)) (unbox calls)))

;; Independent fixture arithmetic and ANSI composition, with literal witnesses
;; below. These helpers never send to product geometry or frame methods.
(define (clip s w) (substring s 0 (min w (string-length s))))
(define (safe s)
  (list->string (for/list ([c (in-string s)])
    (if (or (< (char->integer c) 32) (= (char->integer c) 127)) #\space c))))
(define (mode name w)
  (define label (clip (string-append name " ") w))
  (safe (string-append label (make-string (- w (string-length label)) #\-))))
(define (count-rows lines h) (if (< h 2) 0 (min (length lines) (max 0 (- h 2)))))
(define (root-height lines h) (if (< h 2) h (- h 1 (count-rows lines h))))
(define (text-height h) (if (>= h 2) (sub1 h) h))
(define (cursor row col) (format "\e[~a;~aH" row col))
(define (list-suffix lines w h)
  (define root (root-height lines h))
  (apply string-append
    (for/list ([line (in-list (take lines (count-rows lines h)))] [j (in-naturals 1)])
      (string-append (cursor (+ root j) 1) (safe (clip line w))))))
(define (text-cells lines w h top left)
  (for/list ([i (in-range top (+ top h))])
    (define row (if (< i (length lines)) (list-ref lines i) ""))
    (safe (clip (substring row (min left (string-length row))) w))))
(define (leaf-cells lines w h top left name)
  (append (for/list ([row (in-list (text-cells lines w (text-height h) top left))])
            (string-append row (make-string (- w (string-length row)) #\space)))
          (if (>= h 2) (list (mode name w)) '())))
(define (side a b) (map (lambda (l r) (string-append l "|" r)) a b))
(define (single body text-row text-col w h name echo lines final-row final-col)
  (string-append "\e[?25l\e[2J\e[H" body (cursor text-row text-col) "\e[?25h"
    (if (< h 2) ""
        (string-append "\e[?25l"
          (if (>= (root-height lines h) 2)
              (string-append (cursor (root-height lines h) 1) (mode name w)) "")
          (list-suffix lines w h) (cursor h 1) (safe (clip echo w))
          (cursor final-row final-col) "\e[?25h"))))
(define (multi rows w h echo lines final-row final-col)
  (string-append "\e[?25l\e[2J\e[H" (string-join rows "\r\n")
    (list-suffix lines w h)
    (if (>= h 2) (string-append (cursor h 1) (safe (clip echo w))) "")
    (cursor final-row final-col) "\e[?25h"))
(define (paint st s w h expected calls)
  (define before (ev st s))
  (define snapshot (unbox calls))
  (for ([i '(1 2)]) (check-equal? (ev st `(,s frame ,w ,h)) expected))
  (check-equal? (ev st s) before)
  (check-equal? (unbox calls) snapshot))

(test-case "three typed geometry sends retain session fields and concrete host identity"
  (define datums (call-with-input-file file-path (lambda (in) (port->list read in))))
  (define declaration (findf (lambda (d) (equal? (cadr d) '(AloemacsSession H))) datums))
  (define methods (cdr (cadddr declaration)))
  (for ([signature '((completion-row-count (rows Int) Int)
                    (root-rect (columns Int) (rows Int) AloemacsWindowRect)
                    (fit-rect (columns Int) (rows Int) AloemacsWindowRect))])
    (define m (assoc (car signature) methods))
    (check-equal? (and m (drop-right m 1)) signature))
  (check-equal? (length (cdr (caddr declaration))) 14)
  (for ([identity '(FsHost OtherFsHost)])
    (define-values (st calls names) (state identity))
    (for ([expr '((base completion-row-count 5) (base root-rect 9 5) (base fit-rect 9 5)
                  (base ensure-visible 9 5) (base frame 9 5))]
          [expected (list 'Int 'AloemacsWindowRect 'AloemacsWindowRect
                          (type st 'base) 'String)])
      (check-equal? (type st expr) expected)
      (ev st expr))
    (for ([bad '((base completion-row-count) (base completion-row-count 1 2)
                 (base completion-row-count "3") (base root-rect 9)
                 (base root-rect 9 5 1) (base root-rect "9" 5)
                 (base root-rect 9 "5") (base fit-rect 9)
                 (base fit-rect 9 5 1) (base fit-rect "9" 5)
                 (base fit-rect 9 "5") (1 root-rect 9 5)
                 ("x" fit-rect 9 5) (AloemacsSession completion-row-count 5))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
    (check-equal? (unbox calls) '())))

(test-case "stored counts and root formulas include short heights and absent prompts"
  (define-values (st calls names) (state))
  (for* ([n '(0 1 2 8)] [h '(-2 0 1 2 3 5 10 12)])
    (define lines (for/list ([i (in-range n)]) (format "name~a" i)))
    (def! st 's (session (zipper (list (buffer 41 (editor '("body"))))) (leaf 7) 7 lines))
    (check-equal? (ev st `(s completion-row-count ,h)) (count-rows lines h))
    (same st `(s root-rect 9 ,h) `(AloemacsWindowRect new 0 0 9 ,(root-height lines h))))
  (for ([h '(1 2 3 5 10 12)] [k '(0 0 1 3 8 8)] [root '(1 1 1 1 1 3)])
    (check-equal? (ev st `(s completion-row-count ,h)) k)
    (same st `(s root-rect 9 ,h) `(AloemacsWindowRect new 0 0 9 ,root)))
  (def! st 'absent (rebuild 's #:prompt no-prompt))
  (for ([h '(1 2 12)])
    (check-equal? (ev st `(absent completion-row-count ,h)) 0)
    (same st `(absent root-rect 9 ,h)
      `(AloemacsWindowRect new 0 0 9 ,(if (< h 2) h (sub1 h)))))
  ;; A selected lookup miss falls back to the root in an otherwise positive tree.
  (def! st 'missing (rebuild 's #:windows (windows (right (leaf 7) (leaf 3)) 99)))
  (same st '(missing fit-rect 9 12) '(AloemacsWindowRect new 0 0 9 3))
  (check-equal? (unbox calls) '()))

(test-case "one-view complete ANSI: raw names, slashes, summary and terminal truncation"
  (define-values (st calls names) (state))
  (define lines '("dir/" "\e[31m" "a\n\r\t\u0001\u007fZ" "abc\e" "five" "six" "seven" "...(+2)"))
  (def! st 's (session (zipper (list (buffer 41 (editor '("body"))))) (leaf 7) 7 lines))
  (for* ([w '(1 3 9 40)] [h '(1 2 3 5 10 12)])
    (define root (root-height lines h))
    (define body (string-join (text-cells '("body") w (text-height root) 0 0) "\r\n"))
    (paint st 's w h (single body 1 1 w h "untitled" "P:x" lines
                             (if (< h 2) 1 h) (if (< h 2) 1 (min w 4))) calls))
  (paint st 's 9 5
    "\e[?25l\e[2J\e[Hbody\e[1;1H\e[?25h\e[?25l\e[2;1Hdir/\e[3;1H [31m\e[4;1Ha     Z\e[5;1HP:x\e[5;4H\e[?25h" calls)
  (paint st 's 1 3
    "\e[?25l\e[2J\e[Hb\e[1;1H\e[?25h\e[?25l\e[2;1Hd\e[3;1HP\e[3;1H\e[?25h" calls)
  (same st '(s prompt) (prepared lines))
  (same st '(s completion-lines) `(List of ,@lines))
  (check-equal? (unbox calls) '()))

(define a-lines '("abcdef" "ghijkl" "mnopqr" "stuvwx" "yz0123"))
(define b-lines '("ABCDE" "FGHIJ" "KLMNO" "PQRST" "UVWXY"))
(define shown-lines '("alpha.txt" "dir/"))

(test-case "Right, Below, short modes and mixed T/cross rows occupy the shorter root"
  (define-values (st calls names) (state))
  (def! st 'a (buffer 41 (editor a-lines 3 2 3 1 17 #f 2) "/a"))
  (def! st 'b (buffer 9 (editor b-lines 3 4 99 101 13 #f 3) "/b"))
  (define l (leaf 7))
  (define r (leaf 3 41 3 1 #t))
  (define bs (zipper '(b a) 1))
  (for ([tree (list (right l r) (below l r))]
        [rect '((5 0 4 5) (0 3 9 2))]
        [rows (list (side (leaf-cells a-lines 4 5 0 0 "/a")
                          (leaf-cells a-lines 4 5 3 1 "/a"))
                    (append (leaf-cells a-lines 9 2 0 0 "/a") '("---------")
                            (leaf-cells a-lines 9 2 3 1 "/a")))])
    (def! st 's (session bs tree 3))
    (same st '(s root-rect 9 8) '(AloemacsWindowRect new 0 0 9 5))
    (same st '(s fit-rect 9 8) `(AloemacsWindowRect new ,@rect))
    (paint st 's 9 8 (multi rows 9 8 "P:x" shown-lines 8 4) calls)
    ;; The windows' command geometry still reserves only the echo row.
    (same st '((s windows) text-rect 9 8) '(AloemacsWindowRect new 0 0 9 7))
    (same st `((s windows) fit-rect 9 8)
      (if (eq? (cadr tree) 'Right) '(AloemacsWindowRect new 5 0 4 7)
                                  '(AloemacsWindowRect new 0 4 9 3))))
  (def! st 's (session bs (right l r) 3))
  (paint st 's 9 4
    "\e[?25l\e[2J\e[Habcd|tuvw\e[2;1Halpha.txt\e[3;1Hdir/\e[4;1HP:x\e[4;4H\e[?25h" calls)
  (for ([w '(3 4 31)])
    (define early (quotient w 2))
    (define late (- w early 1))
    (paint st 's w 8
      (multi (side (leaf-cells a-lines early 5 0 0 "/a")
                   (leaf-cells a-lines late 5 3 1 "/a"))
             w 8 "P:x" shown-lines 8 (min w 4)) calls))
  (paint st 's 3 4
    "\e[?25l\e[2J\e[Ha|t\e[2;1Halp\e[3;1Hdir\e[4;1HP:x\e[4;3H\e[?25h" calls)
  (paint st 's 1 4
    "\e[?25l\e[2J\e[Ht\e[1;2H\e[?25h\e[?25l\e[2;1Ha\e[3;1Hd\e[4;1HP\e[4;1H\e[?25h" calls)
  (def! st 's (session bs (below l r) 3))
  (same st '(s fit-rect 9 4) '(AloemacsWindowRect new 0 0 9 1))
  (paint st 's 9 4
    "\e[?25l\e[2J\e[Htuvwx\e[1;2H\e[?25h\e[?25l\e[2;1Halpha.txt\e[3;1Hdir/\e[4;1HP:x\e[4;4H\e[?25h" calls)
  ;; Nonselected b renders at its view's origin, not its editor's far origin.
  (define mixed (right (below l r) (leaf 55 9 1 2 #t)))
  (def! st 's (session bs mixed 3))
  (paint st 's 9 8
    "\e[?25l\e[2J\e[Habcd|HIJ \r\n/a -|MNO \r\n----+RST \r\ntuvw|WXY \r\n/a -|/b -\e[6;1Halpha.txt\e[7;1Hdir/\e[8;1HP:x\e[8;4H\e[?25h" calls)
  (for ([tree (list (right (below l r) (below (leaf 55) (leaf 8)))
                   (below (right l r) (right (leaf 55) (leaf 8))))]
        [rows (list '("abcd|abcd" "/a -|/a -" "----+----" "tuvw|abcd" "/a -|/a -")
                    '("abcd|tuvw" "/a -|/a -" "----+----" "abcd|abcd" "/a -|/a -"))])
    (def! st 's (session bs tree 3))
    (paint st 's 9 8 (multi rows 9 8 "P:x" shown-lines 8 4) calls))
  ;; Root h=4 gives a tall top leaf and a one-row bottom leaf with no mode.
  (def! st 's (session bs (below l r) 3))
  (paint st 's 9 7
    (multi '("abcdef   " "/a ------" "---------" "tuvwx    ") 9 7 "P:x" shown-lines 7 4) calls)
  (check-equal? (unbox calls) '()))

(test-case "global fallback tests every leaf even when selected nominal rectangle is positive"
  (define-values (st calls names) (state))
  (define tree (right (leaf 7 41 0 0 #t)
                      (below (leaf 3 41 99 101 #t) (leaf 55 41 2 1 #t))))
  (def! st 'a (buffer 41 (editor a-lines 3 2 0 0 17 #f 2) "/a"))
  (def! st 's (session (zipper '(a)) tree))
  ;; At terminal h=5, listed root h=2, selected left is 4x2 but right
  ;; contains a zero-height leaf. No-list command geometry is still positive.
  (same st '(((s windows) tree) rect-for 7 (AloemacsWindowRect new 0 0 9 2))
    '(Option Some (AloemacsWindowRect new 0 0 4 2)))
  (check-false (ev st '(((s windows) tree) positive-layout? (AloemacsWindowRect new 0 0 9 2))))
  (same st '(s fit-rect 9 5) '(AloemacsWindowRect new 0 0 9 2))
  (same st '((s windows) fit-rect 9 5) '(AloemacsWindowRect new 0 0 4 4))
  (def! st 'fit '(s ensure-visible 9 5))
  (same st 'fit (rebuild 's
    #:buffers (zipper (list (buffer 41 (editor a-lines 3 2 3 0 1 #f 2) "/a")))
    #:windows (windows (right (leaf 7 41 3 0 #t)
                         (below (leaf 3 41 99 101 #t) (leaf 55 41 2 1 #t))) 7 9 5)))
  (paint st 'fit 9 5
    "\e[?25l\e[2J\e[Hstuvwx\e[1;3H\e[?25h\e[?25l\e[2;1H/a ------\e[3;1Halpha.txt\e[4;1Hdir/\e[5;1HP:x\e[5;4H\e[?25h" calls)
  (same st '(fit ensure-visible 9 5) 'fit)
  (def! st 'grown '(fit ensure-visible 9 8))
  (same st '((grown windows) tree) '((fit windows) tree))
  (check-equal? (ev st '((grown editor) text-rows)) 4)
  (check-equal? (ev st '((grown editor) scroll-row)) 3)
  (paint st 'grown 9 8
    (multi '("stuv|    " "yz01|/a -" "    +----" "    |nopq" "/a -|/a -")
           9 8 "P:x" shown-lines 8 4) calls)
  (check-equal? (unbox calls) '()))

(test-case "rich selected fit is minimal, idempotent, mirrors one view and remembers full dimensions"
  (define-values (st calls names) (state))
  (define lines (for/list ([i (in-range 12)]) (format "abcdef~a" i)))
  (def! st 'a (buffer 41 (editor lines 4 5 0 0 17 #t 2) "/a"))
  (def! st 'b (buffer 9 (editor b-lines 3 4 99 101 13 #f 3) "/b"))
  (define tree (below (leaf 7 41 8 2 #t) (leaf 3 41 0 0 #t)))
  (def! st 's (session (zipper '(b a) 1) tree 3))
  (def! st 's (rebuild 's #:searching #t #:query "q\t"
                #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (define before (ev st 's))
  (for ([h '(6 10 12)] [height '(1 2 3)] [origin '(4 3 2)] [distance '(1 1 2)])
    (def! st 'fit `(s ensure-visible 4 ,h))
    (define fitted-tree (below (leaf 7 41 8 2 #t) (leaf 3 41 origin 2 #t)))
    (same st 'fit (rebuild 's
      #:buffers (zipper (list 'b (buffer 41 (editor lines 4 5 origin 2 height #t 2) "/a")) 1)
      #:windows (windows fitted-tree 3 4 h)))
    (same st `(fit ensure-visible 4 ,h) 'fit)
    (check-equal? (ev st '((fit editor) page-distance)) distance)
    ;; Direct page sends retain this remembered selected text height even
    ;; though prompt handling would ignore these named keys.
    (for ([send '(page-up page-down)] [line (list (- 4 distance) (+ 4 distance))])
      (def! st 'moved `(fit ,send))
      (check-equal? (ev st '((moved point) line)) line)
      (same st '((moved editor) history) history)
      (same st '((moved editor) mark) mark)
      (same st '(moved prompt) '(fit prompt)))
    (define fitted (ev st 'fit))
    (ev st `(fit frame 4 ,h))
    (ev st '(fit frame 19 16))
    (check-equal? (ev st 'fit) fitted))
  (check-equal? (ev st 's) before)
  ;; Shrink, growth and clearing never restore an older scroll origin.
  (def! st 'small '(s ensure-visible 4 6))
  (def! st 'large '(small ensure-visible 9 12))
  (check-equal? (ev st '((large editor) scroll-row)) 4)
  (check-equal? (ev st '((large editor) scroll-col)) 2)
  (check-equal? (ev st '((large editor) text-rows)) 3)
  (same st '((large windows) tree) '((small windows) tree))
  (def! st 'cleared '(large with-active-prompt
                      ((large prompt) case (Some (p) (p clear-completion))
                                           (None () (AloemacsPrompt new "" "" 0 "" (List empty))))))
  (def! st 'normal '(cleared ensure-visible 9 12))
  (same st '((normal windows) tree) '((large windows) tree))
  (check-equal? (ev st '((normal editor) text-rows)) 4)
  (same st '(normal prompt) '(cleared prompt))
  ;; Origin beyond the point clamps minimally to the point in each axis.
  (def! st 'far (rebuild 's #:buffers
    (zipper (list 'b (buffer 41 (editor lines 4 5 99 101 17 #t 2) "/a")) 1)))
  (def! st 'minimal '(far ensure-visible 4 6))
  (check-equal? (ev st '((minimal editor) scroll-row)) 4)
  (check-equal? (ev st '((minimal editor) scroll-col)) 5)
  (check-equal? (unbox calls) '()))

(test-case "actual Tab below, at and above eight stores raw names and paints only the prefix that fits"
  (define candidates '(("alpha" file) ("bravo" file) ("charlie" file) ("dir" directory)
                       ("echo" file) ("foxtrot" file) ("golf" file) ("hotel" file) ("india" file)))
  (for ([n '(2 8 9)])
    (define listing (take candidates n))
    (define-values (st calls names) (state 'FsHost listing))
    (def! st 's (session (zipper (list (buffer 41 (editor '("body"))))) (leaf 7) 7 '()))
    (def! st 's (rebuild 's #:prompt (prepared '() "/cwd/" 5)))
    (def! st 'done '(s handle-key "tab"))
    (define display (map (lambda (entry)
                          (string-append (car entry) (if (eq? (cadr entry) 'directory) "/" ""))) listing))
    (define stored (if (> n 8) (append (take display 7) '("...(+2)")) display))
    (same st 'done (rebuild 's #:prompt (prepared stored "/cwd/" 5)))
    (check-equal? (effects calls 'names) '((names "/cwd")))
    (check-equal? (effects calls 'read) '())
    (check-equal? (effects calls 'write) '())
    (define snapshot (unbox calls))
    (for* ([w '(4 20)] [h '(3 5 12)])
      (def! st 'fit `(done ensure-visible ,w ,h))
      (define body (string-join
        (text-cells '("body") w (text-height (root-height stored h)) 0 0) "\r\n"))
      (paint st 'fit w h (single body 1 1 w h "untitled" "P:/cwd/" stored h (min w 8)) calls)
      (same st '(fit completion-lines) `(List of ,@stored)))
    (check-equal? (unbox calls) snapshot)))

(test-case "motion retains lists; edits, zero backspace, Return and Escape restore geometry without lookup"
  (define-values (st calls names) (state))
  (define lines (for/list ([i (in-range 8)]) (format "abcdef~a" i)))
  (def! st 'a (buffer 41 (editor lines 4 5 0 0 17 #f 2) "/a"))
  (def! st 's (session (zipper '(a)) (leaf 7) 7 '()))
  (def! st 's (rebuild 's #:prompt (prepared '() "/cwd/alp" 1)))
  (def! st 's '(s handle-key "tab"))
  (same st '(s prompt) (prepared '("alpha.txt" "alpine.txt") "/cwd/alp" 1))
  (def! st 's '(s ensure-visible 9 8))
  (define snapshot (unbox calls))
  (for ([key '("left" "right" "line-start" "line-end")] [col '(0 2 0 8)])
    (def! st 'moved `(s handle-key ,key))
    (same st 'moved (rebuild 's #:prompt (prepared '("alpha.txt" "alpine.txt") "/cwd/alp" col)))
    (same st '(moved root-rect 9 8) '(AloemacsWindowRect new 0 0 9 5)))
  (for ([key '("up" "down" "page-up" "page-down" "undo" "mark" "save" "ctrl-x" "\n")])
    (same st `(s handle-key ,key) 's))
  (for ([key '("X" "backspace" "backspace")]
        [column '(1 1 0)] [text '("/Xcwd/alp" "cwd/alp" "/cwd/alp")]
        [result-column '(2 0 0)])
    (def! st 'source (rebuild 's #:prompt (prepared '("alpha.txt" "alpine.txt") "/cwd/alp" column)))
    (def! st 'cleared `(source handle-key ,key))
    (same st 'cleared (rebuild 'source #:prompt (prepared '() text result-column)))
    (same st '(cleared root-rect 9 8) '(AloemacsWindowRect new 0 0 9 7))
    (def! st 'normal '(cleared ensure-visible 9 8))
    (same st 'normal (rebuild 'cleared
      #:buffers (zipper (list (buffer 41 (editor lines 4 5 1 0 6 #f 2) "/a")))))
    (same st '(normal ensure-visible 9 8) 'normal))
  (def! st 'cancelled '(s handle-key "escape"))
  (same st 'cancelled (rebuild 's #:prompt no-prompt #:waiting '(Option None)))
  (same st '(cancelled root-rect 9 8) '(AloemacsWindowRect new 0 0 9 7))
  (check-equal? (unbox calls) snapshot)
  ;; Submission keeps only editable text and performs the inherited file action.
  (for ([command '(FindFile SaveAs)])
    (def! st 'submit (rebuild 's #:prompt (prepared '("alpha.txt" "alpine.txt") "/cwd/alpha.txt" 2)
                           #:waiting `(Option Some (AloemacsCommand ,command))))
    (set-box! calls '())
    (def! st 'done '(submit handle-key "return"))
    (same st '(done prompt) no-prompt)
    (same st '(done waiting-command) '(if #t (Option None) (Option Some (AloemacsCommand FindFile))))
    (same st '(done last-submission) '(Option Some "/cwd/alpha.txt"))
    (same st '(done root-rect 9 8) '(AloemacsWindowRect new 0 0 9 7))
    (check-equal? (effects calls 'names) '())
    (check-equal? (effects calls 'read) (if (eq? command 'FindFile) '((read "/cwd/alpha.txt")) '()))
    (check-equal? (effects calls 'write)
      (if (eq? command 'SaveAs) (list (list 'write "/cwd/alpha.txt" (string-join lines "\n"))) '()))
    (check-equal? (ev st '(done echo)) (if (eq? command 'FindFile) "" "saved"))))

(test-case "direct split keeps command geometry and prompt, then fits through the list-aware fallback"
  (define-values (st calls names) (state))
  (def! st 'a (buffer 41 (editor a-lines 3 2 1 1 17 #f 2) "/a"))
  (def! st 's (session (zipper '(a)) (leaf 7 41 1 1)))
  (def! st 's (rebuild 's #:windows (windows (leaf 7 41 1 1) 7 9 4)))
  (check-true (ev st '((s windows) split-allowed? #t)))
  (def! st 'split '(s split-below))
  (same st 'split (rebuild 's
    #:buffers (zipper (list (buffer 41 (editor a-lines 3 2 3 1 1 #f 2) "/a")))
    #:windows (windows (below (leaf 7 41 3 1) (leaf 8 41 1 1)) 7 9 4)))
  (same st '(split prompt) '(s prompt))
  (paint st 'split 9 4
    (single "tuvwx" 1 2 9 4 "/a" "P:x" shown-lines 4 4) calls)
  (check-equal? (unbox calls) '()))

(test-case "complete no-list frames retain idle, notes, search and saved/failed bytes"
  (define-values (st calls names) (state))
  (def! st 's (session (zipper (list (buffer 41 (editor '("body"))))) (leaf 7) 7 '()))
  (def! st 's (rebuild 's #:echo "" #:prompt no-prompt))
  (paint st 's 9 1 "\e[?25l\e[2J\e[Hbody\e[1;1H\e[?25h" calls)
  (paint st 's 9 2 "\e[?25l\e[2J\e[Hbody\e[1;1H\e[?25h\e[?25l\e[2;1Huntitled\e[1;1H\e[?25h" calls)
  (paint st 's 9 4 "\e[?25l\e[2J\e[Hbody\r\n\e[1;1H\e[?25h\e[?25l\e[3;1Huntitled \e[4;1H\e[1;1H\e[?25h" calls)
  (for ([echo '("saved" "failed")])
    (def! st 'status `(s with-echo ,echo))
    (paint st 'status 9 4 (single "body\r\n" 1 1 9 4 "untitled"
                          (string-append echo ": untitled") '() 1 1) calls))
  (for ([wrapped '(#f #t #t)] [failing '(#f #f #t)]
        [shown '("search: q\t" "wrapped: q\t" "failing: q\t")])
    (def! st 'search (rebuild 's #:searching #t #:query "q\t" #:wrapped wrapped #:failing failing))
    (paint st 'search 9 4 (single "body\r\n" 1 1 9 4 "untitled" shown '() 1 1) calls))
  (def! st 'noted (rebuild 's #:prompt (prepared '() "x" 1 "P:" " [No match]")))
  (paint st 'noted 9 4
    "\e[?25l\e[2J\e[Hbody\r\n\e[1;1H\e[?25h\e[?25l\e[3;1Huntitled \e[4;1HP:x [No m\e[4;4H\e[?25h" calls)
  (def! st 'split (rebuild 's #:windows (windows (right (leaf 7) (leaf 3)) 7)))
  (paint st 'split 9 4 "\e[?25l\e[2J\e[Hbody|body\r\n    |    \r\nunti|unti\e[4;1H\e[1;1H\e[?25h" calls)
  (def! st 'fallback (rebuild 's #:windows (windows (below (leaf 7) (leaf 3)) 7)))
  (paint st 'fallback 9 2 "\e[?25l\e[2J\e[Hbody\e[1;1H\e[?25h\e[?25l\e[2;1Huntitled\e[1;1H\e[?25h" calls)
  (check-equal? (unbox calls) '()))

(test-case "production runner fits before one write through Tab, resize, clearing, repeated lookup and submission"
  (define-values (host calls names) (counted-fs))
  (set-box! names '("alpha.txt" "beta.txt"))
  ;; Each row describes a drawn iteration BEFORE its key is handled:
  ;; key, full height, literal fitted text, text cursor, prompt echo,
  ;; stored lines, prompt column (or #f). Distinct c/d rows prove refitting.
  (define steps
    '(("a" 6 "\r\n\r\n\r\n" 1 1 "" () #f)
      ("return" 6 "a\r\n\r\n\r\n" 1 2 "" () #f)
      ("b" 6 "a\r\n\r\n\r\n" 2 1 "" () #f)
      ("return" 6 "a\r\nb\r\n\r\n" 2 2 "" () #f)
      ("c" 6 "a\r\nb\r\n\r\n" 3 1 "" () #f)
      ("return" 6 "a\r\nb\r\nc\r\n" 3 2 "" () #f)
      ("d" 6 "a\r\nb\r\nc\r\n" 4 1 "" () #f)
      ("return" 6 "a\r\nb\r\nc\r\nd" 4 2 "" () #f)
      ("e" 6 "b\r\nc\r\nd\r\n" 4 1 "" () #f)
      ("up" 6 "b\r\nc\r\nd\r\ne" 4 2 "" () #f)
      ("line-end" 6 "b\r\nc\r\nd\r\ne" 3 2 "" () #f)
      ("ctrl-x" 6 "b\r\nc\r\nd\r\ne" 3 2 "" () #f)
      ("find" 6 "b\r\nc\r\nd\r\ne" 3 2 "" () #f)
      ("tab" 6 "b\r\nc\r\nd\r\ne" 3 2 "Find file: /cwd/" () 17)
      ("left" 6 "c\r\nd" 2 2 "Find file: /cwd/" ("alpha.txt" "beta.txt") 17)
      ("up" 3 "d" 1 2 "Find file: /cwd/" ("alpha.txt" "beta.txt") 16)
      ("right" 8 "d\r\ne\r\n\r\n" 1 2 "Find file: /cwd/" ("alpha.txt" "beta.txt") 16)
      ("X" 8 "d\r\ne\r\n\r\n" 1 2 "Find file: /cwd/" ("alpha.txt" "beta.txt") 17)
      ("backspace" 8 "d\r\ne\r\n\r\n\r\n\r\n" 1 2 "Find file: /cwd/X" () 18)
      ("tab" 8 "d\r\ne\r\n\r\n\r\n\r\n" 1 2 "Find file: /cwd/" () 17)
      ("tab" 8 "d\r\ne\r\n\r\n\r\n\r\n" 1 2 "Find file: /cwd/b" () 18)
      ("escape" 8 "d\r\ne\r\n\r\n" 1 2 "Find file: /cwd/b" ("beta.txt" "bravo.txt") 18)
      ("ctrl-x" 8 "d\r\ne\r\n\r\n\r\n\r\n" 1 2 "" () #f)
      ("find" 8 "d\r\ne\r\n\r\n\r\n\r\n" 1 2 "" () #f)
      ("a" 8 "d\r\ne\r\n\r\n\r\n\r\n" 1 2 "Find file: /cwd/" () 17)
      ("tab" 8 "d\r\ne\r\n\r\n\r\n\r\n" 1 2 "Find file: /cwd/a" () 18)
      ("h" 8 "d\r\ne\r\n\r\n\r\n\r\n" 1 2 "Find file: /cwd/alp" () 20)
      ("tab" 8 "d\r\ne\r\n\r\n\r\n\r\n" 1 2 "Find file: /cwd/alph" () 21)
      ("return" 8 "d\r\ne\r\n\r\n\r\n\r\n" 1 2 "Find file: /cwd/alpha.txt" () 26)
      ("escape" 8 "disk contents\r\n\r\n\r\n\r\n\r\n" 1 1 "" () #f)))
  (define index (box 0))
  (define frames (box '()))
  (define events (box '()))
  (define snapshots (box '()))
  (define (record item) (set-box! events (append (unbox events) (list item))))
  (define term
    (make-host-receiver
      (make-host-interface 'ScriptedTerm
        (list
          (make-host-method 'columns '() 'Int (lambda (_) (record '(columns 30)) 30))
          (make-host-method 'rows '() 'Int (lambda (_)
            (define height (cadr (list-ref steps (unbox index))))
            (record (list 'rows height)) height))
          (make-host-method 'write '(String) 'String (lambda (_ text)
            (record 'write) (set-box! frames (append (unbox frames) (list text))) text))
          (make-host-method 'read-key '() 'String (lambda (_)
            (record 'read-key)
            (set-box! snapshots (append (unbox snapshots) (list (unbox calls))))
            (define i (unbox index))
            ;; Only another Tab observes these changes; redraw/resize cannot.
            (when (= i 19) (set-box! names '("beta.txt" "bravo.txt")))
            (when (= i 25) (set-box! names '("alpha.txt" "alpine.txt")))
            (set-box! index (add1 i))
            (car (list-ref steps i)))))) #f))
  (run-aloemacs-with-hosts term host)
  (define expected
    (for/list ([step (in-list steps)] [i (in-naturals)])
      (define height (list-ref step 1))
      (define text-row (list-ref step 3))
      (define text-col (list-ref step 4))
      (define prompt-col (list-ref step 7))
      (single (list-ref step 2) text-row text-col 30 height
              (if (= i 29) "/cwd/alpha.txt" "untitled") (list-ref step 5) (list-ref step 6)
              (if prompt-col height text-row) (or prompt-col text-col))))
  (check-equal? (unbox frames) expected)
  (check-equal? (unbox index) (length steps))
  (check-equal? (unbox events)
    (append-map (lambda (step) (list '(columns 30) (list 'rows (cadr step)) 'write 'read-key)) steps))
  (check-equal? (effects calls 'current) '((current) (current)))
  (check-equal? (effects calls 'names) (make-list 5 '(names "/cwd")))
  (check-equal? (effects calls 'read) '((read "/cwd/alpha.txt")))
  (check-equal? (effects calls 'write) '())
  (for ([snapshot (in-list (take (unbox snapshots) 29))])
    (check-equal? (filter (lambda (call) (memq (car call) '(read write))) snapshot) '()))
  ;; Every non-start/Tab/Return iteration, including size changes and list
  ;; clearing, keeps the complete lookup snapshot, not just its names count.
  (for ([i (in-range 1 (length steps))] #:unless (member i '(13 14 20 21 24 26 28 29)))
    (check-equal? (list-ref (unbox snapshots) i) (list-ref (unbox snapshots) (sub1 i))))
  (for ([i '(14 15 16 19 20 21 25 26 27 28 29)] [count '(1 1 1 1 2 3 3 4 4 5 5)])
    (check-equal? (length (filter (lambda (call) (eq? (car call) 'names))
                                (list-ref (unbox snapshots) i))) count)))
