#lang racket/base

(require racket/list racket/port racket/runtime-path racket/string rackunit
         "../../aloe/driver.rkt" "../../aloe/host.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/env.rkt" env-bound?)
         (only-in "../../aloe/type.rkt" exn:fail:aloe-type? type-of type->datum)
         "../../host/racket/fs.rkt" "../../host/racket/term.rkt"
         "../../host/racket/aloemacs-run.rkt")

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define-runtime-path main-path "../../examples/aloemacs/main.aloe")
(define no-mark '(if #t (Option None) (Option Some (Position new 0 0))))
(define no-path '(if #t (Option None) (Option Some (Path new "/typed-none"))))
(define no-pending '(if #t (Option None) (Option Some aloemacs-global-keymap)))
(define no-prompt '(if #t (Option None) (Option Some (AloemacsPrompt new "" "" 0 "" (List empty) (List empty) 0))))
(define no-submission '(if #t (Option None) (Option Some "")))
(define no-command '(if #t (Option None) (Option Some (AloemacsCommand FindFile))))
(define waiting '(Option Some (AloemacsCommand FindFile)))
(define (prompt text [column (string-length text)] [label "Find file: "])
  `(Option Some (AloemacsPrompt new ,label ,text ,column "" (List empty) (List empty) 0)))
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (type st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))

;; All observable calls, including the resolves inside thin Fs.inspect, count.
(define default-listing
  '(("alpha.txt" file) ("alpine.txt" file) ("docs" directory)
    ("link" symlink) ("pipe" "fifo") (".secret" file)))
;; The directory table is deliberately ordered by the caller, not by the host.
;; A box allows the next Tab to see changed names, with no live lookup.
(define (counted-fs #:host-name [host-name 'FsHost]
                    #:current [current "/cwd"] #:listing [listing default-listing]
                    #:fail [fail #f] #:root-path [root-path #f]
                    #:second-kind [second-kind #f])
  (define names (box (map car listing)))
  (define nodes (make-hash
    (append (list (cons "/" 'directory) (cons "/cwd" 'directory)
                  (cons "/cwd/src" 'directory))
      (for*/list ([dir '("/cwd" "/cwd/src" "")]
                  [entry listing])
        (cons (string-append dir "/" (car entry)) (cadr entry))))))
  (define disk (make-fs-double current nodes
    (for/hash ([entry listing] #:when (eq? (cadr entry) 'file))
      (values (string-append "/cwd/" (car entry)) "disk contents"))))
  (define calls (box '()))
  (define target-probes 0)
  (define (forward selector args)
    (set-box! calls (cons (cons selector args) (unbox calls)))
    (when (eq? selector fail) (error 'completion-test "host failure"))
    (when (and (eq? selector 'kind) (equal? args '("/cwd/pa")))
      (set! target-probes (add1 target-probes)))
    (cond
      [(and second-kind (eq? selector 'kind) (equal? args '("/cwd/pa"))
            (> target-probes 1)) second-kind]
      [(eq? selector 'names)
       ;; Keep the ordinary directory-only contract even in this order double.
       (host-receiver-send disk selector args)
       (if (member (car args) '("/cwd" "/cwd/src" "/")) (unbox names) '())]
      [(and root-path (eq? selector 'root?) (equal? args (list root-path))) #t]
      [else (host-receiver-send disk selector args)]))
  (define interface
    (make-host-interface host-name
      (for/list ([method (in-list (host-interface-methods fs-interface))])
        (define selector (host-method-selector method))
        (define params (host-method-parameter-types method))
        (make-host-method selector params (host-method-return-type method)
          (case (length params)
            [(0) (lambda (_) (forward selector '()))]
            [(1) (lambda (_ a) (forward selector (list a)))]
            [(2) (lambda (_ a b) (forward selector (list a b)))])))))
  (values (make-host-receiver interface #f) calls names))
(define (state #:host-name [host-name 'FsHost] #:current [current "/cwd"]
               #:listing [listing default-listing] #:fail [fail #f]
               #:root-path [root-path #f] #:second-kind [second-kind #f])
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  (define-values (host calls names)
    (counted-fs #:host-name host-name #:current current #:listing listing
                #:fail fail #:root-path root-path #:second-kind second-kind))
  (driver-inject-host! st 'fs-host host)
  (values st calls names))
(define (all-calls calls) (reverse (unbox calls)))
(define (effects calls selector)
  (filter (lambda (call) (eq? (car call) selector)) (all-calls calls)))
(define (read-calls typed resolved [read? #t] [second? #t])
  (append (list (list 'resolve typed) (list 'kind resolved) (list 'resolve resolved))
          (if second? (list (list 'kind resolved) (list 'resolve resolved)) '())
          (if read? (list (list 'read resolved)) '())))
(define (editor contents)
  `(AloemacsEditor new ((Text from-string ,contents) indexed-value)
     (Position new 0 0) #f 0 0 (List empty) ,no-mark 0))
(define (buffer contents [path no-path] [id 0])
  `(AloemacsBuffer new ,(editor contents) ,path ,id))
(define (bound contents name [id 0]) (buffer contents `(Option Some (Path new ,name)) id))
(define (zipper order focus)
  `(AloemacsBuffers new (List of ,@(reverse (take order focus)))
     ,(list-ref order focus) (List of ,@(drop order (add1 focus)))))
(define (session buffers)
  `(AloemacsSession new ,buffers (Fs new fs-host) "saved" #f "old query"
     (Position new 4 2) #t #t (List of "newest" "older")
     ,no-pending ,no-prompt ,no-submission ,no-command
     (let ((buffer (,buffers current-buffer)))
       (AloemacsWindows new
         (AloemacsWindowTree Leaf
           (AloemacsView new 0 (buffer id)
             ((buffer editor) scroll-row) ((buffer editor) scroll-col) #f (Option None)))
         0 0 0))))
;; Only constructors and reads appear in expected reconstructions.
(define (rebuild s #:buffers [buffers `(,s buffers)] #:echo [echo `(,s echo)]
                 #:searching [searching `(,s searching)] #:query [query `(,s query)]
                 #:origin [origin `(,s origin)] #:wrapped [wrapped `(,s wrapped)]
                 #:failing [failing `(,s failing)] #:ring [ring `(,s kill-ring)]
                 #:pending [pending `(,s pending)] #:prompt [line `(,s prompt)]
                 #:submission [submission `(,s last-submission)]
                 #:waiting [command `(,s waiting-command)]
                 #:columns [columns `((,s windows) columns)]
                 #:rows [rows `((,s windows) rows)] #:windows [ws `(,s windows)])
  `(AloemacsSession new ,buffers (,s fs) ,echo ,searching ,query ,origin
     ,wrapped ,failing ,ring ,pending ,line ,submission ,command
     ,(or ws `(let ((buffer (,buffers current-buffer)))
       (AloemacsWindows new
         (AloemacsWindowTree Leaf
           (AloemacsView new 0 (buffer id)
             ((buffer editor) scroll-row) ((buffer editor) scroll-col) #f (Option None)))
         0 ,columns ,rows)))))
(define (replace-current s new-editor [path `(,s path)])
  `(AloemacsBuffers new ((,s buffers) before)
     (AloemacsBuffer new ,new-editor ,path ((,s current-buffer) id)) ((,s buffers) after)))
(define (selected s buffers)
  (rebuild s #:buffers buffers #:echo "" #:searching #f #:query ""
    #:origin '(Position new 0 0) #:wrapped #f #:failing #f #:pending no-pending))
(define (rich! st)
  (def! st 'a (bound "neighbor a" "/cwd/old.txt" 0))
  (def! st 'rich-editor
    '(AloemacsEditor new
       (Text indexed (List of "second" "first") "third-long"
                     (List of "fourth" "fifth") 2)
       (Position new 2 4) #f 2 3
       (List of (UndoFrame new (Text from-string "old b") (Position new 0 2) 1 2))
       (Option Some (Position new 1 1)) 4))
  (def! st 'b '(AloemacsBuffer new rich-editor (Option Some (Path new "/cwd/b.txt")) 1))
  (def! st 'c (buffer "neighbor c" no-path 2))
  (def! st 'source (session (zipper '(a b c) 1))))

;; Intentionally unsorted, with classified entries and raw control characters.
(define raw-names
  '("pz" "pa" "pm" "pb\nLF" "py\rCR" "pc\tTab" "px" "pd\eESC"
    "pw\u007fDEL" "pe" "pv" "pf" "pu" "pg" "pt" "ph" "ps" "pi"))
(define display-names
  '("pz" "pa" "pm/" "pb\nLF" "py\rCR" "pc\tTab" "px" "pd\eESC"
    "pw\u007fDEL" "pe" "pv" "pf" "pu" "pg" "pt" "ph" "ps" "pi"))
(define first-page '("pz" "pa" "pm/" "pb\nLF" "py\rCR" "pc\tTab" "px" "...(+11)"))
(define middle-page '("pd\eESC" "pw\u007fDEL" "pe" "pv" "pf" "pu" "pg" "...(+11)"))
(define tail-page '("pt" "ph" "ps" "pi" "...(+14)"))
(define listing
  (append (for/list ([n raw-names] [i (in-naturals)])
            (list n (case i [(2) 'directory] [(6) 'symlink] [(11) "fifo"] [else 'file])))
          '((".private" file) ("other" file) ("Pupper" file))))
(define (page-state #:host-name [identity 'FsHost] #:fail [failure #f]
                    #:second-kind [second-kind #f])
  (define-values (st calls names)
    (state #:host-name identity #:fail failure #:second-kind second-kind
           #:listing (append listing '(("p" file) ("p-only" file)
                                       ("palpha" file) ("palpine" file)))))
  (set-box! names (map car listing))
  (values st calls names))
(define (q [text "/cwd/p"] [column 2] [matches display-names] [start 0]
           [lines first-page] [note ""])
  `(AloemacsPrompt new "Typed: " ,text ,column ,note
     (List of ,@lines) (List of ,@matches) ,start))
(define (active! st [command 'FindFile] [text "/cwd/p"] [column 2])
  (rich! st)
  (def! st 's (rebuild 'source #:prompt `(Option Some ,(q text column '() 0 '()))
    #:submission '(Option Some "previous")
    #:waiting `(Option Some (AloemacsCommand ,command)))))
(define (prompt-value s) `((,s prompt) case (Some (p) p) (None () ,(q))))
(define (expect-page st result source start lines [text "/cwd/p"] [column 2]
                     [matches display-names] [note ""])
  (same st result (rebuild source #:prompt `(Option Some ,(q text column matches start lines note)))))
(define (snapshot! st [command 'FindFile] [text "/cwd/p"] [column 2])
  (active! st command text column)
  (def! st 'listed '(s handle-key "tab")))

(test-case "seven prompt fields, scanner signatures, unchanged session and checked nominal hosts"
  (define datums (call-with-input-file file-path (lambda (in) (port->list read in))))
  (define (decl name) (findf (lambda (d) (equal? (cadr d) name)) datums))
  (check-equal? (take datums 2) '((load "editor.aloe") (load "../../lib/fs.aloe")))
  (check-equal? (map cadr (filter (lambda (d) (eq? (car d) 'define-class)) datums))
    '(AloemacsPrompt AloemacsCompletionScan AloemacsBuffer AloemacsBuffers AloemacsModeLine
      AloemacsLeafPicture AloemacsView AloemacsWindowTree AloemacsWindowRect AloemacsWindows AloemacsCommand
      (AloemacsKeymap B) AloemacsBinding AloemacsSearchScan (AloemacsSession H)))
  (check-equal? (caddr (decl 'AloemacsPrompt))
    '(fields (label String) (text String) (column Int) (completion-note String)
       (completion-lines (List String)) (completion-matches (List String)) (completion-start Int)))
  (check-equal? (caddr (decl '(AloemacsSession H)))
    '(fields (buffers AloemacsBuffers) (fs (Fs H)) (echo String) (searching Bool)
       (query String) (origin Position) (wrapped Bool) (failing Bool)
       (kill-ring (List String)) (pending (Option (AloemacsKeymap AloemacsBinding)))
       (prompt (Option AloemacsPrompt)) (last-submission (Option String))
       (waiting-command (Option AloemacsCommand)) (windows AloemacsWindows)))
  (check-equal? (caddr (decl 'AloemacsCompletionScan)) '(fields))
  (for ([class '(AloemacsPrompt AloemacsCompletionScan (AloemacsSession H))]
        [signatures '(((with-completion-page (matches (List String)) (start Int)
                            (lines (List String)) AloemacsPrompt))
                      ((drop-lines (lines (List String)) (count Int) (List String))
                       (window-lines (matches (List String)) (start Int) (List String)))
                      ((page-completion (key String) (AloemacsSession H))))])
    (define methods (cdr (cadddr (decl class))))
    (for ([sig signatures]) (check-equal? (drop-right (assoc (car sig) methods) 1) sig)))
  ;; Full command and map inventories remain independently sealed by completion-session.
  (check-equal? (length (cdr (caddr (decl 'AloemacsCommand)))) 31)
  (for ([identity '(FsHost PageOtherFsHost)])
    (define st (make-driver))
    (define out (open-output-string))
    (parameterize ([current-output-port out]) (ev st `(load ,(path->string file-path))))
    (check-equal? (get-output-string out) "")
    (for ([name '(term fs-host)]) (check-false (env-bound? (driver-runtime-environment st) name)))
    (define-values (host calls names) (counted-fs #:host-name identity))
    (driver-inject-host! st 'fs-host host)
    (ev st `(load ,(path->string main-path)))
    (def! st 'base 'aloemacs-editor)
    (def! st 'p (q))
    (def! st 'scan '(AloemacsCompletionScan new))
    (for ([expr '((p completion-matches) (p completion-start)
                  (p with-completion-page (List of "x") 0 (List of "x"))
                  (scan drop-lines (List of "x") 1) (scan window-lines (List of "x") 0)
                  (base page-completion "page-down") (base prompt-key "page-up")
                  (base handle-key "page-down"))]
          [expected (list '(List String) 'Int 'AloemacsPrompt '(List String) '(List String)
                          `(AloemacsSession ,identity) `(AloemacsSession ,identity)
                          `(AloemacsSession ,identity))])
      (check-equal? (type st expr) expected))
    (for ([bad '((AloemacsPrompt new "L" "x" 0 "" (List empty))
                 (AloemacsPrompt new "L" "x" 0 "" (List empty) (List of 1) 0)
                 (AloemacsPrompt new "L" "x" 0 "" (List empty) (List empty) "0")
                 (p completion-matches 1) (p completion-start 1)
                 (p with-completion-page) (p with-completion-page (List of "x") 0)
                 (p with-completion-page (List of "x") 0 (List empty) 1)
                 (p with-completion-page "x" 0 (List empty))
                 (p with-completion-page (List of "x") 0.0 (List empty))
                 (p with-completion-page (List of "x") 0 (List of 1))
                 (1 with-completion-page (List of "x") 0 (List empty))
                 (AloemacsPrompt with-completion-page (List of "x") 0 (List empty))
                 (scan drop-lines) (scan drop-lines (List of "x"))
                 (scan drop-lines (List of "x") 0 1) (scan drop-lines (List of 1) 0)
                 (scan drop-lines (List of "x") "0") (scan window-lines (List of "x"))
                 (scan window-lines (List of "x") 0 1) (scan window-lines "x" 0)
                 (scan window-lines (List of "x") 0.0)
                 (1 window-lines (List of "x") 0) ("x" drop-lines (List of "x") 0)
                 (AloemacsCompletionScan drop-lines (List of "x") 0)
                 (base page-completion) (base page-completion 1)
                 (base page-completion "page-up" "page-down")
                 (p page-completion "page-down") (AloemacsSession page-completion "page-up"))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
    (check-equal? (unbox calls) '())))

(test-case "pure checked scanner drop and literal windows include complete and partial tails"
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  (def! st 'scan '(AloemacsCompletionScan new))
  (for ([count '(-3 0 1 3 4 12)]
        [expected '(("a" "dir/" "c\n") ("a" "dir/" "c\n") ("dir/" "c\n") () () ())])
    (same st `(scan drop-lines (List of "a" "dir/" "c\n") ,count) `(List of ,@expected)))
  (for ([count '(-1 0 7)]) (same st `(scan drop-lines (List empty) ,count) '(List empty)))
  (for ([row (list (list 0 0 '()) (list 1 0 '("pz"))
                    (list 7 0 '("pz" "pa" "pm/" "pb\nLF" "py\rCR" "pc\tTab" "px"))
                    (list 8 0 '("pz" "pa" "pm/" "pb\nLF" "py\rCR" "pc\tTab" "px" "pd\eESC"))
                    (list 9 0 '("pz" "pa" "pm/" "pb\nLF" "py\rCR" "pc\tTab" "px" "...(+2)"))
                    (list 9 7 '("pd\eESC" "pw\u007fDEL" "...(+7)"))
                    (list 14 7 '("pd\eESC" "pw\u007fDEL" "pe" "pv" "pf" "pu" "pg" "...(+7)"))
                    (list 15 14 '("pt" "...(+14)"))
                    (list 18 0 first-page) (list 18 7 middle-page) (list 18 14 tail-page))])
    (same st `(scan window-lines (List of ,@(take display-names (car row))) ,(cadr row))
      `(List of ,@(caddr row))))
  ;; Summary-looking raw names are data, never recognized or filtered.
  (same st '(scan window-lines (List of "...(+9)" "dir/" "\n\r\t\e\u007f") 0)
    '(List of "...(+9)" "dir/" "\n\r\t\e\u007f")))

(test-case "actual FindFile and SaveAs Tab: every unsorted match, disjoint pages, exact stops"
  (for ([command '(FindFile SaveAs)])
    (define-values (st calls names) (page-state))
    (snapshot! st command)
    (expect-page st 'listed 's 0 first-page)
    (check-equal? (effects calls 'names) '((names "/cwd")))
    (check-equal? (effects calls 'read) '())
    (check-equal? (effects calls 'write) '())
    (define lookup-calls (all-calls calls))
    (def! st 'middle '(listed handle-key "page-down"))
    (expect-page st 'middle 'listed 7 middle-page)
    (def! st 'tail '(middle handle-key "page-down"))
    (expect-page st 'tail 'middle 14 tail-page)
    (same st '(tail handle-key "page-down") 'tail)
    (same st '(tail page-completion "page-down") 'tail)
    (same st '(tail handle-key "page-up") 'middle)
    (same st '(middle handle-key "page-up") 'listed)
    (same st '(listed handle-key "page-up") 'listed)
    (check-equal? (append (drop-right first-page 1) (drop-right middle-page 1)
                         (drop-right tail-page 1)) display-names)
    (check-equal? (all-calls calls) lookup-calls)
    (for ([count '(8 9 14)]
          [tail-lines '(("pz" "pa" "pm/" "pb\nLF" "py\rCR" "pc\tTab" "px" "pd\eESC")
                        ("pd\eESC" "pw\u007fDEL" "...(+7)")
                        ("pd\eESC" "pw\u007fDEL" "pe" "pv" "pf" "pu" "pg" "...(+7)"))])
      (set-box! names (take raw-names count))
      (snapshot! st command)
      (def! st 'next '(listed handle-key "page-down"))
      (expect-page st 'next 'listed (if (= count 8) 0 7) tail-lines "/cwd/p" 2
                   (take display-names count))
      (same st '(next handle-key "page-down") 'next)
      (same st '(next handle-key "page-up") 'listed)
      (when (= count 8) (same st 'next 'listed)))))

(test-case "cached snapshot survives redraw and motion; every fresh Tab replaces and resets it"
  (define-values (st calls names) (page-state))
  (snapshot! st)
  (def! st 'late '((listed handle-key "page-down") handle-key "page-down"))
  (set-box! names '("pi" "pa" "pt" "ph" "pg" "pu" "pf" "pv" "pe"))
  (define before (all-calls calls))
  (def! st 'moved '(late handle-key "left"))
  (expect-page st 'moved 'late 14 tail-page "/cwd/p" 1)
  (def! st 'fitted '(moved ensure-visible 9 5))
  (same st '(fitted prompt) '(moved prompt))
  (ev st '(fitted frame 9 5))
  (same st '(moved handle-key "page-up")
    (rebuild 'moved #:prompt `(Option Some ,(q "/cwd/p" 1 display-names 7 middle-page))))
  (check-equal? (all-calls calls) before)
  (def! st 'fresh '(moved handle-key "tab"))
  (expect-page st 'fresh 'moved 0 '("pi" "pa" "pt" "ph" "pg" "pu" "pf" "...(+2)")
    "/cwd/p" 1 '("pi" "pa" "pt" "ph" "pg" "pu" "pf" "pv" "pe"))
  (check-equal? (length (effects calls 'names)) 2)
  (for ([ns '(() ("p") ("p-only") ("palpha" "palpine"))]
        [text '("/cwd/p" "/cwd/p" "/cwd/p-only" "/cwd/palp")]
        [column '(2 2 11 9)] [note '(" [No match]" " [Sole completion]" "" "")])
    (set-box! names ns)
    (def! st 'fresh '(late complete-prompt))
    (expect-page st 'fresh 'late 0 '() text column '() note))
  (check-equal? (length (effects calls 'names)) 6)
  (check-equal? (effects calls 'read) '())
  (check-equal? (effects calls 'write) '()))

(test-case "prompt page helper and editing lifetimes preserve raw values and interior column"
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  (def! st 'p (q "/cwd/p" 2 display-names 14 tail-page))
  (define original (ev st 'p))
  (same st '(p with-completion-page (List of "raw\n" "dir/") 0 (List of "raw\n" "dir/"))
    (q "/cwd/p" 2 '("raw\n" "dir/") 0 '("raw\n" "dir/")))
  (same st '(p with-completion "/cwd/p" "note" (List of "display"))
    (q "/cwd/p" 2 '() 0 '("display") "note"))
  (same st '(p with-completion "changed" "" (List empty)) (q "changed" 7 '() 0 '()))
  (same st '(p clear-completion) (q "/cwd/p" 2 '() 0 '()))
  (check-equal? (ev st '(p row)) "Typed: /cwd/p")
  (for ([width '(40 8 1)] [column '(10 8 1)])
    (check-equal? (ev st `(p screen-column ,width)) column))
  (for ([method '(move-left move-right line-start line-end)] [column '(1 3 0 6)])
    (same st `(p ,method) (q "/cwd/p" column display-names 14 tail-page)))
  (same st '((p line-start) move-left) (q "/cwd/p" 0 display-names 14 tail-page))
  (same st '((p line-end) move-right) (q "/cwd/p" 6 display-names 14 tail-page))
  (for ([input '("" "long" "\n")]) (same st `(p insert ,input) 'p))
  (same st '(p insert "X") (q "/cXwd/p" 3 '() 0 '()))
  (same st '(p backward-delete) (q "/wd/p" 1 '() 0 '()))
  (same st '((p line-start) backward-delete) (q "/cwd/p" 0 '() 0 '()))
  (check-equal? (ev st 'p) original)
  (define-values (ss calls names) (page-state))
  (snapshot! ss)
  (def! ss 'late '(listed handle-key "page-down"))
  (set-box! calls '())
  (for ([key '("up" "down" "save" "ctrl-x" "unknown" "\n")])
    (same ss `(late handle-key ,key) 'late))
  (for ([key '("X" "backspace")])
    (def! ss 'edit `(late handle-key ,key))
    (same ss `(,(prompt-value 'edit) completion-matches) '(List empty))
    (same ss '(edit completion-lines) '(List empty))
    (check-equal? (ev ss `(,(prompt-value 'edit) completion-start)) 0))
  (def! ss 'zero '((late handle-key "line-start") handle-key "backspace"))
  (expect-page ss 'zero 'late 0 '() "/cwd/p" 0 '())
  (check-equal? (unbox calls) '()))

(test-case "direct gates and handle-key precedence never leak active prompt paging to idle"
  (define-values (st calls names) (page-state))
  (active! st)
  (def! st 's (rebuild 's #:prompt `(Option Some ,(q))))
  (set-box! calls '())
  (for ([line (list no-prompt `(Option Some ,(q "/cwd/p" 2 '() 0 '()))
                    `(Option Some ,(q "/cwd/p" 2 '() 0 first-page))
                    `(Option Some ,(q "/cwd/p" 2 display-names 0 '()))
                    `(Option Some ,(q "/cwd/p" 2 display-names 0 first-page "note")))])
    (def! st 'g (rebuild 's #:prompt line))
    (for ([key '("page-down" "page-up")])
      (same st `(g page-completion ,key) 'g)
      (unless (equal? line no-prompt) (same st `(g handle-key ,key) 'g))))
  (for ([command (list no-command '(Option Some (AloemacsCommand SelectBuffer))
                       '(Option Some (AloemacsCommand MoveLeft)))])
    (def! st 'g (rebuild 's #:waiting command))
    (for ([key '("page-down" "page-up")])
      (same st `(g page-completion ,key) 'g) (same st `(g handle-key ,key) 'g)))
  (same st '(s page-completion "down") 's)
  (def! st 'quit '(s request-quit))
  (for ([key '("page-up" "page-down")]) (same st `(quit handle-key ,key) 'quit))
  (def! st 'prefix (rebuild 's #:prompt no-prompt #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (for ([key '("page-up" "page-down")])
    (same st `(prefix handle-key ,key) (rebuild 'prefix #:pending no-pending #:echo "")))
  (def! st 'idle (rebuild 's #:prompt no-prompt))
  (for ([key '("page-up" "page-down")] [command '(PageUp PageDown)])
    (same st `(idle handle-key ,key) `(idle execute-command (AloemacsCommand ,command) ,key)))
  (def! st 'both (rebuild 's #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (expect-page st '(both handle-key "page-down") 'both 7 middle-page)
  (for ([pending (list no-pending '(Option Some aloemacs-ctrl-x-keymap))])
    (def! st 'search (rebuild 's #:searching #t #:pending pending))
    (for ([key '("page-up" "page-down")])
      (def! st 'done `(search handle-key ,key))
      (same st 'done `((search end-search) idle-key ,key))
      (same st '(done prompt) '(search prompt))))
  (check-equal? (unbox calls) '()))

(test-case "paging preserves complete rich shared-window state and direct operations keep the prompt"
  (define-values (st calls names) (page-state))
  (active! st 'SaveAs)
  (def! st 's (rebuild 's #:prompt `(Option Some ,(q))
    #:pending '(Option Some aloemacs-ctrl-x-keymap)
    #:windows '(AloemacsWindows new
       (AloemacsWindowTree Right
         (AloemacsWindowTree Leaf (AloemacsView new 7 1 2 3 #t (Option None)))
         (AloemacsWindowTree Below
           (AloemacsWindowTree Leaf (AloemacsView new 9 1 0 1 #f (Option None)))
           (AloemacsWindowTree Leaf (AloemacsView new 11 0 1 0 #t (Option None))))) 7 43 13)))
  (define original (ev st 's))
  (def! st 'middle '(s handle-key "page-down"))
  (expect-page st 'middle 's 7 middle-page)
  (def! st 'tail '(middle page-completion "page-down"))
  (expect-page st 'tail 'middle 14 tail-page)
  (same st '(tail handle-key "page-up") 'middle)
  (for ([expr '((tail with-echo "other") (tail with-editor (tail editor))
                (tail toggle-window-lock) (tail other-window) (tail switch-buffer)
                (tail move-down) (tail undo) (tail ensure-visible 43 13))])
    (def! st 'changed expr)
    (same st '(changed prompt) '(tail prompt)))
  (check-equal? (ev st 's) original)
  (check-equal? (unbox calls) '()))

(test-case "Return and Escape after paging use typed text and preserve all command outcomes"
  (define-values (st calls names) (page-state))
  (define (paged! command target)
    (active! st command target 0)
    (def! st 's (rebuild 's #:prompt `(Option Some ,(q target 0))))
    (def! st 'late '(s handle-key "page-down"))
    (set-box! calls '()))
  (define (ended! target)
    (def! st 'done '(late handle-key "return"))
    (same st '(done prompt) no-prompt)
    (same st '(done waiting-command) no-command)
    (same st '(done last-submission) `(Option Some ,target))
    (define before (all-calls calls))
    (same st '(done submit-prompt) 'done)
    (check-equal? (all-calls calls) before))
  ;; Typed path differs from every displayed name, including its directory.
  (paged! 'FindFile "./pa")
  (ended! "./pa")
  (check-equal? (ev st '((done text) to-string)) "disk contents")
  (same st '(done path) '(Option Some (Path new "/cwd/pa")))
  (check-equal? (all-calls calls) (read-calls "./pa" "/cwd/pa"))
  (paged! 'FindFile "/cwd/new")
  (ended! "/cwd/new")
  (check-equal? (ev st '((done text) to-string)) "")
  (same st '(done path) '(Option Some (Path new "/cwd/new")))
  (check-equal? (all-calls calls) (read-calls "/cwd/new" "/cwd/new" #f #f))
  (paged! 'FindFile "/cwd/old.txt")
  (ended! "/cwd/old.txt")
  (check-equal? (all-calls calls) '((resolve "/cwd/old.txt")))
  (check-equal? (ev st '((done text) to-string)) "neighbor a")
  (for* ([command '(FindFile SaveAs)] [target '("/cwd/pm" "/cwd/px" "/cwd/pf")])
    (paged! command target)
    (when (equal? target "/cwd/pm")
      (def! st 'late '(late handle-key "page-up")))
    (ended! target)
    (same st 'done (rebuild 'late #:prompt no-prompt #:waiting no-command
      #:submission `(Option Some ,target) #:echo "failed"))
    (check-equal? (effects calls 'read) '())
    (check-equal? (effects calls 'write) '()))
  (paged! 'SaveAs "./pa")
  (ended! "./pa")
  (same st '(done path) '(Option Some (Path new "/cwd/pa")))
  (same st '(done editor) '(late editor))
  (check-equal? (ev st '(done echo)) "saved")
  (check-equal? (effects calls 'write)
    '((write "/cwd/pa" "first\nsecond\nthird-long\nfourth\nfifth")))
  (paged! 'SaveAs "/cwd/new")
  (ended! "/cwd/new")
  (same st '(done path) '(Option Some (Path new "/cwd/new")))
  (check-equal? (length (effects calls 'write)) 1)
  (paged! 'SaveAs "/absent/new")
  (ended! "/absent/new")
  (same st 'done (rebuild 'late #:prompt no-prompt #:waiting no-command
    #:submission '(Option Some "/absent/new") #:echo "failed"))
  (check-equal? (effects calls 'write) '())
  ;; Select another current buffer while the page stays installed.
  (paged! 'SaveAs "/cwd/pa")
  (def! st 'before-select 'late)
  (def! st 'late '(late select-buffer-submitted "/cwd/old.txt"))
  (same st '(late prompt) '(before-select prompt))
  (set-box! calls '())
  (ended! "/cwd/pa")
  (check-equal? (effects calls 'write) '((write "/cwd/pa" "neighbor a")))
  (for ([command '(FindFile SaveAs)])
    (paged! command "")
    (ended! "")
    (same st 'done (rebuild 'late #:prompt no-prompt #:waiting no-command
      #:submission '(Option Some "") #:echo "failed"))
    (check-equal? (unbox calls) '()))
  (paged! 'FindFile "./pa")
  (same st '(late handle-key "escape") (rebuild 'late #:prompt no-prompt #:waiting no-command))
  (check-equal? (unbox calls) '())
  (def! st 'orphan (rebuild 'late #:prompt no-prompt))
  (same st '(orphan cancel-prompt) (rebuild 'orphan #:waiting no-command))
  (for ([command (list no-command '(Option Some (AloemacsCommand SelectBuffer)))])
    (def! st 'late (rebuild 's #:waiting command
      #:prompt `(Option Some ,(q "/cwd/old.txt" 0))))
    (set-box! calls '())
    (ended! "/cwd/old.txt")
    (check-equal? (unbox calls) '())
    (when (equal? command no-command) (same st '(done buffers) '(late buffers))))
  ;; Refused direct visit preserves the entire prompt; success discards it.
  (paged! 'FindFile "./pa")
  (same st '((late visit (Path new "/cwd/pm")) case (None () late) (Some (s) s)) 'late)
  (def! st 'visited '((late visit (Path new "/cwd/pa")) case (None () late) (Some (s) s)))
  (same st '(visited prompt) no-prompt)
  ;; The second thin Fs.read inspection can refuse after the first found a file.
  (for ([kind '("missing" "directory" "symlink" "fifo")])
    (define-values (fs refused-calls names) (page-state #:second-kind kind))
    (active! fs 'FindFile "/cwd/pa" 0)
    (def! fs 's `(s with-active-prompt ,(q "/cwd/pa" 0)))
    (def! fs 'late '(s handle-key "page-down"))
    (def! fs 'done '(late handle-key "return"))
    (same fs 'done (rebuild 'late #:prompt no-prompt #:waiting no-command
      #:submission '(Option Some "/cwd/pa") #:echo "failed"))
    (check-equal? (all-calls refused-calls) (read-calls "/cwd/pa" "/cwd/pa" #f))
    (check-equal? (effects refused-calls 'write) '()))
  (for ([failure '(read write)] [command '(FindFile SaveAs)])
    (define-values (fs calls names) (page-state #:fail failure))
    (active! fs command "/cwd/pa" 0)
    (def! fs 'late `(s with-active-prompt ,(q "/cwd/pa" 0 display-names 7 middle-page)))
    (define original (ev fs 'late))
    (check-exn #rx"host failure" (lambda () (ev fs '(late submit-prompt))))
    (check-equal? (ev fs 'late) original)))
