#lang racket/base

(require racket/list racket/port racket/runtime-path racket/string rackunit
         "../../aloe/driver.rkt" "../../aloe/host.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/env.rkt" env-bound?)
         (only-in "../../aloe/type.rkt" exn:fail:aloe-type? type-of type->datum)
         "../../host/racket/fs.rkt" "../../host/racket/term.rkt"
         "../../host/racket/aloemacs-run.rkt")

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define-runtime-path main-path "../../examples/aloemacs/main.aloe")
(define no-mark '(if #t (Option None) (Option Some (Position new 0 0))))
(define no-path '(if #t (Option None) (Option Some (Path new "/typed-none"))))
(define no-pending '(if #t (Option None) (Option Some aloemacs-global-keymap)))
(define no-prompt '(if #t (Option None) (Option Some (AloemacsPrompt new "" "" 0 "" (List empty)))))
(define no-submission '(if #t (Option None) (Option Some "")))
(define no-command '(if #t (Option None) (Option Some (AloemacsCommand FindFile))))
(define waiting '(Option Some (AloemacsCommand FindFile)))
(define (prompt text [column (string-length text)] [label "Find file: "])
  `(Option Some (AloemacsPrompt new ,label ,text ,column "" (List empty))))
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (type st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))

;; All observable calls, including the resolves inside thin Fs.inspect, count.
(define default-listing
  '(("alpha.txt" file) ("alpine.txt" file) ("docs" directory)
    ("link" symlink) ("pipe" "fifo") (".secret" file)))
;; The directory table is deliberately ordered by the caller, not by the host.
;; A box allows the next Tab to see changed names, with no live lookup.
(define (counted-fs #:host-name [host-name 'FsHost]
                    #:current [current "/cwd"] #:listing [listing default-listing]
                    #:fail [fail #f] #:root-path [root-path #f])
  (define names (box (map car listing)))
  (define nodes (make-hash
    (append (list (cons "/" 'directory) (cons "/cwd" 'directory)
                  (cons "/cwd/src" 'directory))
      (for*/list ([dir '("/cwd" "/cwd/src" "")]
                  [entry listing])
        (cons (string-append dir "/" (car entry)) (cadr entry))))))
  (define disk (make-fs-double current nodes
    (for/hash ([entry listing] #:when (eq? (cadr entry) 'file))
      (values (string-append "/cwd/" (car entry)) "disk contents"))))
  (define calls (box '()))
  (define (forward selector args)
    (set-box! calls (cons (cons selector args) (unbox calls)))
    (when (eq? selector fail) (error 'completion-test "host failure"))
    (cond
      [(eq? selector 'names)
       ;; Keep the ordinary directory-only contract even in this order double.
       (host-receiver-send disk selector args)
       (if (member (car args) '("/cwd" "/cwd/src" "/")) (unbox names) '())]
      [(and root-path (eq? selector 'root?) (equal? args (list root-path))) #t]
      [else (host-receiver-send disk selector args)]))
  (define interface
    (make-host-interface host-name
      (for/list ([method (in-list (host-interface-methods fs-interface))])
        (define selector (host-method-selector method))
        (define params (host-method-parameter-types method))
        (make-host-method selector params (host-method-return-type method)
          (case (length params)
            [(0) (lambda (_) (forward selector '()))]
            [(1) (lambda (_ a) (forward selector (list a)))]
            [(2) (lambda (_ a b) (forward selector (list a b)))])))))
  (values (make-host-receiver interface #f) calls names))
(define (state #:host-name [host-name 'FsHost] #:current [current "/cwd"]
               #:listing [listing default-listing] #:fail [fail #f]
               #:root-path [root-path #f])
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  (define-values (host calls names)
    (counted-fs #:host-name host-name #:current current #:listing listing
                #:fail fail #:root-path root-path))
  (driver-inject-host! st 'fs-host host)
  (values st calls names))
(define (all-calls calls) (reverse (unbox calls)))
(define (effects calls selector)
  (filter (lambda (call) (eq? (car call) selector)) (all-calls calls)))
(define (read-calls typed resolved [read? #t] [second? #t])
  (append (list (list 'resolve typed) (list 'kind resolved) (list 'resolve resolved))
          (if second? (list (list 'kind resolved) (list 'resolve resolved)) '())
          (if read? (list (list 'read resolved)) '())))
(define (editor contents)
  `(AloemacsEditor new ((Text from-string ,contents) indexed-value)
     (Position new 0 0) #f 0 0 (List empty) ,no-mark 0))
(define (buffer contents [path no-path] [id 0])
  `(AloemacsBuffer new ,(editor contents) ,path ,id))
(define (bound contents name [id 0]) (buffer contents `(Option Some (Path new ,name)) id))
(define (zipper order focus)
  `(AloemacsBuffers new (List of ,@(reverse (take order focus)))
     ,(list-ref order focus) (List of ,@(drop order (add1 focus)))))
(define (session buffers)
  `(AloemacsSession new ,buffers (Fs new fs-host) "saved" #f "old query"
     (Position new 4 2) #t #t (List of "newest" "older")
     ,no-pending ,no-prompt ,no-submission ,no-command
     (let ((buffer (,buffers current-buffer)))
       (AloemacsWindows new
         (AloemacsWindowTree Leaf
           (AloemacsView new 0 (buffer id)
             ((buffer editor) scroll-row) ((buffer editor) scroll-col) #f))
         0 0 0))))
;; Only constructors and reads appear in expected reconstructions.
(define (rebuild s #:buffers [buffers `(,s buffers)] #:echo [echo `(,s echo)]
                 #:searching [searching `(,s searching)] #:query [query `(,s query)]
                 #:origin [origin `(,s origin)] #:wrapped [wrapped `(,s wrapped)]
                 #:failing [failing `(,s failing)] #:ring [ring `(,s kill-ring)]
                 #:pending [pending `(,s pending)] #:prompt [line `(,s prompt)]
                 #:submission [submission `(,s last-submission)]
                 #:waiting [command `(,s waiting-command)]
                 #:columns [columns `((,s windows) columns)]
                 #:rows [rows `((,s windows) rows)] #:windows [ws #f])
  `(AloemacsSession new ,buffers (,s fs) ,echo ,searching ,query ,origin
     ,wrapped ,failing ,ring ,pending ,line ,submission ,command
     ,(or ws `(let ((buffer (,buffers current-buffer)))
       (AloemacsWindows new
         (AloemacsWindowTree Leaf
           (AloemacsView new 0 (buffer id)
             ((buffer editor) scroll-row) ((buffer editor) scroll-col) #f))
         0 ,columns ,rows)))))
(define (replace-current s new-editor [path `(,s path)])
  `(AloemacsBuffers new ((,s buffers) before)
     (AloemacsBuffer new ,new-editor ,path ((,s current-buffer) id)) ((,s buffers) after)))
(define (selected s buffers)
  (rebuild s #:buffers buffers #:echo "" #:searching #f #:query ""
    #:origin '(Position new 0 0) #:wrapped #f #:failing #f #:pending no-pending))
(define (rich! st)
  (def! st 'a (bound "neighbor a" "/cwd/old.txt" 0))
  (def! st 'rich-editor
    '(AloemacsEditor new
       (Text indexed (List of "second" "first") "third-long"
                     (List of "fourth" "fifth") 2)
       (Position new 2 4) #f 2 3
       (List of (UndoFrame new (Text from-string "old b") (Position new 0 2) 1 2))
       (Option Some (Position new 1 1)) 4))
  (def! st 'b '(AloemacsBuffer new rich-editor (Option Some (Path new "/cwd/b.txt")) 1))
  (def! st 'c (buffer "neighbor c" no-path 2))
  (def! st 'source (session (zipper '(a b c) 1))))
(define (draft! st [text "draft"])
  (rich! st)
  (def! st 'draft (rebuild 'source #:prompt (prompt text)
    #:submission '(Option Some "previous") #:waiting waiting)))
(define (editor-frame body row column)
  (string-append "\u001b[?25l\u001b[2J\u001b[H" body
    (format "\u001b[~a;~aH\u001b[?25h" row column)))
;; Independent name and text allocation from the supplied fixture and size.
(define (mode-row name width)
  (define label (substring (string-append name " ") 0
                          (min width (add1 (string-length name)))))
  (list->string
    (for/list ([c (in-string (string-append label
                              (make-string (- width (string-length label)) #\-)))])
      (if (or (< (char->integer c) 32) (= (char->integer c) 127)) #\space c))))
(define (text-body body rows)
  (define lines (string-split body "\r\n" #:trim? #f))
  (string-join (take lines (min (length lines) (if (>= rows 3) (- rows 2) 1))) "\r\n"))
(define (frame body row column rows shown cursor-row cursor-column #:name [name "untitled"] #:width [width 0])
  (string-append "\e[?25l\e[2J\e[H"
    (if rows (text-body body rows) body)
    (format "\e[~a;~aH\e[?25h" row column)
    (if (and rows (>= rows 2))
        (string-append "\e[?25l"
          (if (>= rows 3) (format "\e[~a;1H~a" (sub1 rows) (mode-row name width)) "")
          (format "\e[~a;1H~a\e[~a;~aH\e[?25h" rows shown cursor-row cursor-column)) "")))

(test-case "exact fourteen fields, helper signatures, command and production map inventories"
  (define datums (call-with-input-file file-path (lambda (in) (port->list read in))))
  (define (declaration name) (findf (lambda (d) (equal? (cadr d) name)) datums))
  (check-equal? (take datums 2) '((load "editor.aloe") (load "../../lib/fs.aloe")))
  (check-equal? (map cadr (filter (lambda (d) (eq? (car d) 'define-class)) datums))
    '(AloemacsPrompt AloemacsCompletionScan AloemacsBuffer AloemacsBuffers AloemacsModeLine AloemacsView AloemacsWindowTree
      AloemacsWindowRect AloemacsWindows AloemacsCommand
      (AloemacsKeymap B) AloemacsBinding AloemacsSearchScan (AloemacsSession H)))
  (check-equal? (caddr (declaration '(AloemacsSession H)))
    '(fields (buffers AloemacsBuffers) (fs (Fs H)) (echo String) (searching Bool)
       (query String) (origin Position) (wrapped Bool) (failing Bool)
       (kill-ring (List String)) (pending (Option (AloemacsKeymap AloemacsBinding)))
       (prompt (Option AloemacsPrompt)) (last-submission (Option String))
       (waiting-command (Option AloemacsCommand)) (windows AloemacsWindows)))
  (define signatures
    '((with-waiting-command (command AloemacsCommand) (AloemacsSession H))
      (clear-waiting-command () (AloemacsSession H))
      (start-command-prompt (command AloemacsCommand) (label String) (AloemacsSession H))
      (run-submitted-command () (AloemacsSession H))
      (selected-buffers (buffers AloemacsBuffers) (AloemacsSession H))
      (file-contents (path Path) (Option String))
      (find-file-submitted (submitted String) (AloemacsSession H))))
  (define methods (cdr (cadddr (declaration '(AloemacsSession H)))))
  (for ([signature signatures])
    (check-equal? (drop-right (assoc (car signature) methods) 1) signature))
  (define lookup-methods (cdr (cadddr (declaration 'AloemacsBuffers))))
  (for ([signature '((find-name (name String) (Option AloemacsBuffers))
                     (find-name-in (name String) (remaining Int) (Option AloemacsBuffers)))])
    (check-equal? (drop-right (assoc (car signature) lookup-methods) 1) signature))
  (define constructors (cdr (caddr (declaration 'AloemacsCommand))))
  (check-equal? (map car constructors)
    '(Newline BackwardDelete MoveLeft MoveRight MoveUp MoveDown LineStart LineEnd
      PageUp PageDown BufferStart BufferEnd RequestQuit Undo SetMark Kill KillLine
      Yank Find Save SelfInsert SwitchBuffer KillBuffer FindFile SaveAs SelectBuffer
      SplitBelow SplitRight DeleteWindow OtherWindow ToggleWindowLock))
  (check-equal? (take-right (drop-right constructors 5) 3)
    '((FindFile (fields)) (SaveAs (fields)) (SelectBuffer (fields))))
  (check-equal? (length (cdr (cadddr (declaration 'AloemacsCommand)))) 1)
  (define-values (st calls names) (state))
  (same st '(aloemacs-ctrl-x-keymap bindings)
    '(List of (AloemacsBinding Command "save" aloemacs-save-command)
              (AloemacsBinding Command "find" (AloemacsCommand FindFile))
              (AloemacsBinding Command "kill" (AloemacsCommand SaveAs))
              (AloemacsBinding Command "b" (AloemacsCommand SelectBuffer))
              (AloemacsBinding Command "2" (AloemacsCommand SplitBelow))
              (AloemacsBinding Command "3" (AloemacsCommand SplitRight))
              (AloemacsBinding Command "0" (AloemacsCommand DeleteWindow))
              (AloemacsBinding Command "o" (AloemacsCommand OtherWindow))
              (AloemacsBinding Command "l" (AloemacsCommand ToggleWindowLock))))
  (check-false (ev st '((aloemacs-ctrl-x-keymap default) present?)))
  (define global-rows
    '(("return" Newline) ("backspace" BackwardDelete) ("left" MoveLeft) ("right" MoveRight)
      ("up" MoveUp) ("down" MoveDown) ("line-start" LineStart) ("line-end" LineEnd)
      ("page-up" PageUp) ("page-down" PageDown) ("buffer-start" BufferStart)
      ("buffer-end" BufferEnd) ("escape" RequestQuit) ("undo" Undo) ("mark" SetMark)
      ("kill" Kill) ("kill-line" KillLine) ("yank" Yank) ("find" Find) ("save" Save)))
  (same st '(aloemacs-global-keymap bindings)
    `(List of ,@(for/list ([row global-rows])
                  `(AloemacsBinding Command ,(car row) (AloemacsCommand ,(cadr row))))
       (AloemacsBinding Prefix "ctrl-x" aloemacs-ctrl-x-keymap)))
  (same st '(aloemacs-global-keymap default) '(Option Some (AloemacsCommand SelfInsert)))
  (check-equal? (unbox calls) '()))


(define (p text column [note ""] [lines '()] [label "Find file: "])
  `(AloemacsPrompt new ,label ,text ,column ,note (List of ,@lines)))
(define (active! st text [column (string-length text)] [command 'FindFile]
                 [note "old note"] [lines '()])
  (def! st 'base (session (zipper (list (buffer "body")) 0)))
  (def! st 's (rebuild 'base #:prompt `(Option Some ,(p text column note lines))
    #:submission '(Option Some "previous")
    #:waiting `(Option Some (AloemacsCommand ,command)))))
(define (expect-completion st text column note lines [source 's])
  (same st 'done (rebuild source
    #:prompt `(Option Some ,(p text column note lines))
    #:windows `(,source windows)))
  (check-equal? (ev st '(done completion-note)) note)
  (same st '(done completion-lines) `(List of ,@lines)))
(define (no-file-effects calls)
  (check-equal? (effects calls 'read) '())
  (check-equal? (effects calls 'write) '()))

(test-case "exact prompt/scanner declarations and new session signatures"
  (define datums (call-with-input-file file-path (lambda (in) (port->list read in))))
  (define (decl name) (findf (lambda (d) (equal? (cadr d) name)) datums))
  (check-equal? (caddr (decl 'AloemacsPrompt))
    '(fields (label String) (text String) (column Int)
       (completion-note String) (completion-lines (List String))))
  (check-equal? (map (lambda (m) (drop-right m 1)) (cdr (cadddr (decl 'AloemacsPrompt))))
    '((row () String) (screen-column (columns Int) Int)
      (with-completion (text String) (note String) (lines (List String)) AloemacsPrompt)
      (clear-completion () AloemacsPrompt)
      (insert (character String) AloemacsPrompt) (backward-delete () AloemacsPrompt)
      (move-left () AloemacsPrompt) (move-right () AloemacsPrompt)
      (line-start () AloemacsPrompt) (line-end () AloemacsPrompt)))
  (check-equal? (caddr (decl 'AloemacsCompletionScan)) '(fields))
  (check-equal? (map (lambda (m) (drop-right m 1))
                    (cdr (cadddr (decl 'AloemacsCompletionScan))))
    '((split-offset (text String) Int)
      (scan-slashes (remaining String) (offset Int) (latest Int) Int)
      (common-prefix (names (List String)) String)
      (prefix-in (prefix String) (names (List String)) String)
      (shared-prefix (prefix String) (name String) String)))
  (define methods (cdr (cadddr (decl '(AloemacsSession H)))))
  (for ([sig '((completion-note () String) (completion-lines () (List String))
               (file-prompt-directory () String) (complete-prompt () (AloemacsSession H)))])
    (check-equal? (drop-right (assoc (car sig) methods) 1) sig)))

(test-case "prompt metadata algebra, reads, negatives, editing and immutable raw values"
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  (def! st 'q (p "ab" 1 " note" '("raw\n\t" "λ") "L: "))
  (define source (ev st 'q))
  (for ([expr '((q completion-note) (q completion-lines)
                (q with-completion "x" "" (List empty)) (q clear-completion))]
        [expected '(String (List String) AloemacsPrompt AloemacsPrompt)])
    (check-equal? (type st expr) expected))
  (check-equal? (ev st '(q row)) "L: ab note")
  (for ([w '(30 5 1)] [expected '(5 5 1)])
    (check-equal? (ev st `(q screen-column ,w)) expected))
  (same st '(q with-completion "ab" "new" (List of "n")) (p "ab" 1 "new" '("n") "L: "))
  (same st '(q with-completion "λ\n\r\t\e\u0001\u007f" "" (List empty))
    (p "λ\n\r\t\e\u0001\u007f" 7 "" '() "L: "))
  (same st '(q clear-completion) (p "ab" 1 "" '() "L: "))
  (same st '(q insert "x") (p "axb" 2 "" '() "L: "))
  (same st '(q insert "\t") (p "a\tb" 2 "" '() "L: "))
  (same st '(q backward-delete) (p "b" 0 "" '() "L: "))
  (same st '((q line-start) backward-delete) (p "ab" 0 "" '() "L: "))
  (for ([method '(move-left move-right line-start line-end)] [col '(0 2 0 2)])
    (same st `(q ,method) (p "ab" col " note" '("raw\n\t" "λ") "L: ")))
  (same st '((q line-start) move-left) (p "ab" 0 " note" '("raw\n\t" "λ") "L: "))
  (same st '((q line-end) move-right) (p "ab" 2 " note" '("raw\n\t" "λ") "L: "))
  (for ([key '("" "long" "\n")]) (same st `(q insert ,key) 'q))
  (for ([bad '((AloemacsPrompt new "a" "b" 0)
               (AloemacsPrompt new "a" "b" 0 1 (List empty))
               (AloemacsPrompt new "a" "b" 0 "" (List of 1))
               (q with-completion) (q with-completion "x" "")
               (q with-completion "x" "" (List empty) 1)
               (q with-completion 1 "" (List empty))
               (q with-completion "x" 1 (List empty))
               (q with-completion "x" "" (List of 1))
               (q completion-note 1) (q completion-lines 1) (q clear-completion 1)
               (1 clear-completion) (AloemacsPrompt clear-completion)
               ("x" with-completion "x" "" (List empty)))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
  (check-equal? (ev st 'q) source))

(test-case "checked nongeneric recursion needs no capability and has literal results"
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  (def! st 'scan '(AloemacsCompletionScan new))
  (check-equal? (type st 'scan) 'AloemacsCompletionScan)
  (for ([text '("" "abc" "/" "a/" "a//" "a/b/c" "./fi" "src/../src/fi" "λ\n/\t/\r")]
        [offset '(0 0 1 2 3 4 2 11 5)])
    (check-equal? (type st `(scan split-offset ,text)) 'Int)
    (check-equal? (ev st `(scan split-offset ,text)) offset))
  (check-equal? (ev st '(scan scan-slashes "a/b/" 3 1)) 7)
  (for ([names '(() ("alpha") ("same" "same") ("long" "")
                ("a" "b") ("alphabet" "alpine" "also" "ax")
                ("λ\n\tA" "λ\n\tB"))]
        [expected '("" "alpha" "same" "" "" "a" "λ\n\t")])
    (check-equal? (type st `(scan common-prefix (List of ,@names))) 'String)
    (check-equal? (ev st `(scan common-prefix (List of ,@names))) expected))
  (check-equal? (ev st '(scan prefix-in "abc" (List of "abd" "ax"))) "a")
  (check-equal? (ev st '(scan prefix-in "raw" (List empty))) "raw")
  (check-equal? (ev st '(scan shared-prefix "abcdef" "abz")) "ab")
  (check-equal? (ev st '(scan shared-prefix "" "z")) "")
  (for ([bad '((AloemacsCompletionScan new 1) (AloemacsCompletionScan split-offset "x")
               (scan split-offset) (scan split-offset "x" "y") (scan split-offset 1)
               (scan scan-slashes "" 0) (scan scan-slashes "" 0 0 1)
               (scan scan-slashes 1 0 0) (scan scan-slashes "x" 0.0 0)
               (scan scan-slashes "x" 0 "0")
               (scan common-prefix) (scan common-prefix (List of "x") 1)
               (scan common-prefix "x") (scan common-prefix (List of 1))
               (scan prefix-in "x") (scan prefix-in "x" (List empty) 1)
               (scan prefix-in 1 (List of "x")) (scan prefix-in "x" (List of 1))
               (scan shared-prefix "x") (scan shared-prefix "x" "y" "z")
               (scan shared-prefix 1 "x") (scan shared-prefix "x" 1))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
  (for ([method '(split-offset scan-slashes common-prefix prefix-in shared-prefix)]
        [args '(("x") ("x" 0 0) ((List of "x")) ("x" (List of "x")) ("x" "y"))])
    (for ([receiver '(1 "x" AloemacsCompletionScan)])
      (check-exn exn:fail:aloe-type? (lambda () (ev st `(,receiver ,method ,@args)))))))

(test-case "fresh loads, startup and two nominal host identities retain concrete types"
  (for ([host-name '(FsHost CompletionOtherHost)])
    (define out (open-output-string))
    (define st (make-driver))
    (parameterize ([current-output-port out]) (ev st `(load ,(path->string file-path))))
    (check-equal? (get-output-string out) "")
    (for ([name '(term fs-host)]) (check-false (env-bound? (driver-runtime-environment st) name)))
    (define-values (host calls names) (counted-fs #:host-name host-name))
    (driver-inject-host! st 'fs-host host)
    (ev st `(load ,(path->string main-path)))
    (def! st 'base 'aloemacs-editor)
    (same st 'base (rebuild 'base #:prompt no-prompt #:waiting no-command))
    (check-equal? (ev st '(base completion-note)) "")
    (same st '(base completion-lines) '(List empty))
    (for ([expr '((base complete-prompt)
                  (base start-command-prompt (AloemacsCommand FindFile) "custom")
                  (base file-prompt-directory))]
          [result (list `(AloemacsSession ,host-name) `(AloemacsSession ,host-name) 'String)])
      (check-equal? (type st expr) result))
    (check-equal? (unbox calls) '())
    (def! st 'started '(base start-command-prompt (AloemacsCommand FindFile) "Find file: "))
    (same st 'started (rebuild 'base #:prompt `(Option Some ,(p "/cwd/" 5)) #:waiting waiting))
    (def! st 's `(started with-active-prompt ,(p "/cwd/alph" 1)))
    (def! st 'done '(s complete-prompt))
    (expect-completion st "/cwd/alpha.txt" 14 "" '())
    (check-equal? (type st 'done) `(AloemacsSession ,host-name))
    (no-file-effects calls)
    (for ([bad '((base complete-prompt 1) (base completion-note 1) (base completion-lines 1)
                 (base file-prompt-directory 1) (1 complete-prompt) (AloemacsSession complete-prompt))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))))

(test-case "prefill uses command constructors, stored bindings, roots and exact query gates"
  (for ([binding '(#f "/cwd/old.txt" "/" "relative/file" "/raw//file")]
        [find-text '("/cwd/" "/cwd/" "/" "/cwd/relative/" "/raw/")])
    (define-values (st calls names) (state))
    (def! st 'base (session (zipper (list (if binding (bound "body" binding) (buffer "body"))) 0)))
    (for ([command '(FindFile SaveAs SelectBuffer MoveLeft)]
          [text (list find-text (or binding "/cwd/") "" "")])
      (set-box! calls '())
      (def! st 'done `(base start-command-prompt (AloemacsCommand ,command) "custom: "))
      (same st 'done (rebuild 'base #:prompt `(Option Some ,(p text (string-length text) "" '() "custom: "))
        #:waiting `(Option Some (AloemacsCommand ,command))))
      (check-equal? (all-calls calls)
        (cond [(or (eq? command 'SelectBuffer) (eq? command 'MoveLeft)
                   (and binding (eq? command 'SaveAs))) '()]
              [(not binding) '((current))]
              [(equal? binding "/") '((root? "/"))]
              [else (list (list 'root? binding) (list 'parent binding))]))
      (no-file-effects calls))
    (set-box! calls '())
    (def! st 'orphan (rebuild 'base #:waiting '(Option Some (AloemacsCommand SaveAs))))
    (same st '(orphan start-prompt "bare: ")
      (rebuild 'orphan #:prompt '(Option Some (AloemacsPrompt new "bare: " "" 0 "" (List empty)))))
    (check-equal? (unbox calls) '())
    (def! st 'done '(orphan start-command-prompt (AloemacsCommand FindFile) "X"))
    (same st '(done waiting-command) waiting))
  (for ([current '("/" "/cwd/")])
    (define-values (st calls names) (state #:current current))
    (def! st 'base (session (zipper (list (buffer "body")) 0)))
    (check-equal? (ev st '(base file-prompt-directory)) current)
    (check-equal? (all-calls calls) '((current))))
  (define-values (st calls names) (state #:root-path "/odd"))
  (def! st 'base (session (zipper (list (bound "body" "/odd")) 0)))
  (check-equal? (ev st '(base file-prompt-directory)) "/odd/")
  (check-equal? (all-calls calls) '((root? "/odd")))
  (rich! st)
  (for ([guard (list (rebuild 'source #:searching #t)
                     (rebuild 'source #:pending '(Option Some aloemacs-ctrl-x-keymap))
                     (rebuild 'source #:prompt `(Option Some ,(p "x" 0 "note" '("line"))))
                     '(source request-quit))])
    (def! st 'g guard)
    (set-box! calls '())
    (for ([command '(FindFile SaveAs SelectBuffer)])
      (same st `(g start-command-prompt (AloemacsCommand ,command) "ignored") 'g))
    (same st '(g start-prompt "ignored") 'g)
    (check-equal? (unbox calls) '()))
  (def! st 'done '(source execute-command (AloemacsCommand FindFile) "/wrong/input"))
  (check-equal? (ev st '((done prompt) case (None () "") (Some (p) (p text)))) "/cwd/"))

(test-case "all result arms, typed spelling, classification and exact underlying Fs calls"
  (for ([command '(FindFile SaveAs)])
    (define-values (st calls names) (state))
    (for ([row '(("/cwd/z" 2 "/cwd/z" 2 " [No match]" ())
                 ("/cwd/alph" 2 "/cwd/alpha.txt" 14 "" ())
                 ("/cwd/alpha.txt" 3 "/cwd/alpha.txt" 3 " [Sole completion]" ())
                 ("/cwd/a" 2 "/cwd/alp" 8 "" ())
                 ("/cwd/alp" 2 "/cwd/alp" 2 "" ("alpha.txt" "alpine.txt"))
                 ("./do" 1 "./docs/" 7 "" ())
                 ("li" 0 "link" 4 "" ()) ("pi" 0 "pipe" 4 "" ())
                 ("/cwd/.s" 1 "/cwd/.secret" 12 "" ())
                 ("/cwd/A" 1 "/cwd/A" 1 " [No match]" ())
                 ("/cwd//do" 1 "/cwd//docs/" 11 "" ())
                 ("src/../src/do" 1 "src/../src/docs/" 16 "" ())
                 ("/do" 0 "/docs/" 6 "" ())
                 ("" 0 "" 0 "" ("alpha.txt" "alpine.txt" "docs/" "link" "pipe"))
                 ("/cwd/" 1 "/cwd/" 1 "" ("alpha.txt" "alpine.txt" "docs/" "link" "pipe")))])
      (active! st (car row) (cadr row) command)
      (define source (ev st 's))
      (set-box! calls '())
      (def! st 'done '(s handle-key "tab"))
      (apply expect-completion st (cddr row))
      (check-equal? (ev st 's) source)
      (define dir (cond [(member (car row) '("li" "pi" "")) "/cwd"]
                       [(equal? (car row) "/do") "/"]
                       [(equal? (car row) "src/../src/do") "/cwd/src"]
                       [else "/cwd"]))
      (check-equal? (effects calls 'names) (list (list 'names dir)))
      (check-equal? (effects calls 'current)
        (if (member (car row) '("li" "pi" "")) '((current)) '()))
      (check-equal? (length (effects calls 'child)) 6)
      (check-equal? (length (effects calls 'kind)) 7)
      (check-equal? (length (effects calls 'resolve))
        (if (member (car row) '("li" "pi" "")) 7 8))
      (define matched
        (cond [(member (car row) '("/cwd/alph" "/cwd/alpha.txt")) '("alpha.txt")]
              [(member (car row) '("/cwd/a" "/cwd/alp")) '("alpha.txt" "alpine.txt")]
              [(member (car row) '("./do" "/cwd//do" "src/../src/do" "/do")) '("docs")]
              [(equal? (car row) "li") '("link")]
              [(equal? (car row) "pi") '("pipe")]
              [(equal? (car row) "/cwd/.s") '(".secret")]
              [(member (car row) '("" "/cwd/")) '("alpha.txt" "alpine.txt" "docs" "link" "pipe")]
              [else '()]))
      (check-equal? (effects calls 'name)
        (for/list ([n (append (map car default-listing) matched
                              (if (pair? (list-ref row 5)) matched '()))])
          (list 'name (string-append (if (equal? dir "/") "" dir) "/" n))))
      (no-file-effects calls)))
  ;; Inspect non-directories exactly once; none reaches host names.
  (define-values (st calls names) (state))
  (for ([text '("missing/a" "alpha.txt/a" "link/" "pipe/a")]
        [resolved '("/cwd/missing" "/cwd/alpha.txt" "/cwd/link" "/cwd/pipe")])
    (active! st text 0)
    (set-box! calls '())
    (def! st 'done '(s complete-prompt))
    (expect-completion st text 0 " [No match]" '())
    (check-equal? (effects calls 'kind) (list (list 'kind resolved)))
    (check-equal? (length (effects calls 'resolve)) 2)
    (for ([selector '(names child name read write)]) (check-equal? (effects calls selector) '())))
  (active! st "/cwd/do" 1)
  (def! st 'done '(s complete-prompt))
  (set-box! calls '())
  (def! st 's 'done)
  (def! st 'done '(s complete-prompt))
  (expect-completion st "/cwd/docs/" 10 " [No match]" '())
  (check-equal? (effects calls 'names) '((names "/cwd/docs")))
  (for ([failure '(names kind resolve)])
    (define-values (st calls names) (state #:fail failure))
    (active! st "/cwd/a" 1)
    (check-exn #rx"host failure" (lambda () (ev st '(s complete-prompt))))))

(test-case "raw names, no common-prefix slashes, hidden filtering and eight-line limit"
  (for ([listing (list '() '(("one" file))
                       '(("same" directory) ("same.txt" file))
                       '((".one" file) (".other" directory)))])
    (define-values (st calls names) (state #:listing listing))
    (active! st (if (and (pair? listing) (string-prefix? (caar listing) ".")) "." "") 0)
    (def! st 'done '(s complete-prompt))
    (cond [(null? listing) (expect-completion st "" 0 " [No match]" '())]
          [(= (length listing) 1) (expect-completion st "one" 3 "" '())]
          [(equal? (caar listing) "same") (expect-completion st "same" 4 "" '())]
          [else (expect-completion st ".o" 2 "" '())]))
  (define raw '("λ space" "B\e[31m" "c\nLF" "d\rCR" "e\tTab" "f\u0001Low" "g\u007fDEL" "h" "i" "j"))
  (for ([count '(8 9 10)])
    (define ns (take raw count))
    (define listing (for/list ([n ns] [i (in-naturals)])
                      (list n (if (= i 2) 'directory 'file))))
    (define-values (st calls names) (state #:listing listing))
    (active! st "" 0)
    (def! st 'done '(s complete-prompt))
    (define display (list "λ space" "B\e[31m" "c\nLF/" "d\rCR" "e\tTab" "f\u0001Low" "g\u007fDEL" "h"))
    (expect-completion st "" 0 ""
      (if (= count 8) display (append (take display 7) (list (format "...(+~a)" (- count 7))))))
    (no-file-effects calls))
  (define-values (st calls names)
    (state #:listing '(("λ\n\r\t\e\u0001\u007f" file))))
  (active! st "λ" 0)
  (def! st 'done '(s complete-prompt))
  (expect-completion st "λ\n\r\t\e\u0001\u007f" 7 "" '())
  (define before (ev st 'done))
  (set-box! calls '())
  (check-equal? (ev st '(done frame 30 2))
    (frame "body" 1 1 2 "Find file: λ      " 2 19 #:width 30))
  (check-equal? (ev st 'done) before)
  (check-equal? (unbox calls) '()))

(test-case "each Tab replaces display state; ordinary prompt keys never query Fs"
  (define-values (st calls names) (state))
  (active! st "/cwd/alp" 2)
  (def! st 'done '(s complete-prompt))
  (expect-completion st "/cwd/alp" 2 "" '("alpha.txt" "alpine.txt"))
  (def! st 's 'done)
  (set-box! names '("alpha.txt"))
  (def! st 'done '(s complete-prompt))
  (expect-completion st "/cwd/alpha.txt" 14 "" '())
  (def! st 's 'done)
  (def! st 'done '(s complete-prompt))
  (expect-completion st "/cwd/alpha.txt" 14 " [Sole completion]" '())
  (def! st 's 'done)
  (set-box! names '())
  (def! st 'done '(s complete-prompt))
  (expect-completion st "/cwd/alpha.txt" 14 " [No match]" '())
  (check-equal? (length (effects calls 'names)) 4)
  (def! st 's 'done)
  (set-box! calls '())
  (for ([key '("left" "right" "line-start" "line-end" "up" "down" "\n" "save")]
        [column '(13 14 0 14 14 14 14 14)])
    (def! st 'done `(s handle-key ,key))
    (expect-completion st "/cwd/alpha.txt" column " [No match]" '()))
  (def! st 'done '(s handle-key "x"))
  (expect-completion st "/cwd/alpha.txtx" 15 "" '())
  (def! st 'done '((s handle-key "line-start") handle-key "backspace"))
  (expect-completion st "/cwd/alpha.txt" 0 "" '())
  (check-equal? (unbox calls) '()))

(test-case "rich buffers and shared views preserve full payloads through start, completion and edits"
  (define-values (st calls names) (state))
  (rich! st)
  (def! st 'source (rebuild 'source #:windows
    '(AloemacsWindows new
       (AloemacsWindowTree Right
         (AloemacsWindowTree Leaf (AloemacsView new 7 1 2 3 #t))
         (AloemacsWindowTree Below
           (AloemacsWindowTree Leaf (AloemacsView new 9 1 0 1 #f))
           (AloemacsWindowTree Leaf (AloemacsView new 11 0 1 0 #t))))
       7 43 13)))
  (define original (ev st 'source))
  (def! st 'started '(source start-command-prompt (AloemacsCommand SaveAs) "Find file: "))
  (same st 'started (rebuild 'source #:windows '(source windows)
    #:prompt `(Option Some ,(p "/cwd/b.txt" 10))
    #:waiting '(Option Some (AloemacsCommand SaveAs))))
  (check-equal? (unbox calls) '())
  (def! st 's `(started with-active-prompt ,(p "/cwd/alp" 1)))
  (def! st 'done '(s handle-key "tab"))
  (expect-completion st "/cwd/alp" 1 "" '("alpha.txt" "alpine.txt"))
  (def! st 's 'done)
  (set-box! calls '())
  (for ([key '("left" "right" "line-start" "line-end")]
        [column '(0 2 0 8)])
    (def! st 'done `(s handle-key ,key))
    (expect-completion st "/cwd/alp" column "" '("alpha.txt" "alpine.txt")))
  (def! st 'done '(s handle-key "X"))
  (expect-completion st "/Xcwd/alp" 2 "" '())
  (def! st 'done '(s handle-key "backspace"))
  (expect-completion st "cwd/alp" 0 "" '())
  (def! st 'done '(s handle-key "escape"))
  (same st 'done (rebuild 's #:windows '(s windows) #:prompt no-prompt #:waiting no-command))
  (check-equal? (ev st 'source) original)
  (check-equal? (unbox calls) '()))

(test-case "Tab routing preserves quit, search, prompt, prefix, and idle precedence"
  (define-values (st calls names) (state))
  (active! st "/cwd/a" 1)
  (for ([command '(SelectBuffer MoveLeft)])
    (def! st 'g `(s with-waiting-command (AloemacsCommand ,command)))
    (same st '(g handle-key "tab") 'g)
    (same st '(g complete-prompt) 'g))
  (def! st 'g '(s clear-waiting-command))
  (same st '(g handle-key "tab") 'g)
  (def! st 'g '(s cancel-prompt))
  (same st '(g complete-prompt) 'g)
  (def! st 'q '(s request-quit))
  (same st '(q handle-key "tab") 'q)
  (check-equal? (unbox calls) '())
  (def! st 'g (rebuild 'base #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (same st '(g handle-key "tab") (rebuild 'g #:pending no-pending #:echo ""))
  (same st '(base handle-key "tab") (rebuild 'base #:echo ""))
  ;; A raw prompt and prefix coexist with search. Search ends, then idle
  ;; consumes the prefix miss, without retrying the retained prompt.
  (def! st 'g (rebuild 's #:searching #t #:query "raw"
    #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (same st '(g handle-key "tab") (rebuild 'g #:searching #f #:query ""
    #:origin '(Position new 0 0) #:wrapped #f #:failing #f
    #:pending no-pending #:echo ""))
  (check-equal? (unbox calls) '())
  (def! st 'g (rebuild 's #:searching #t #:query "raw"))
  (same st '(g handle-key "tab") (rebuild 'g #:searching #f #:query ""
    #:origin '(Position new 0 0) #:wrapped #f #:failing #f #:echo ""))
  (check-equal? (unbox calls) '())
  ;; Active prompt takes precedence over a raw prefix.
  (def! st 's (rebuild 's #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (def! st 'done '(s handle-key "tab"))
  (expect-completion st "/cwd/alp" 8 "" '())
  (check-equal? (effects calls 'names) '((names "/cwd"))))

(define (safe s)
  (list->string (for/list ([c (in-string s)])
    (if (or (< (char->integer c) 32) (= (char->integer c) 127)) #\space c))))
(define (clip s w) (substring s 0 (min w (string-length s))))
(test-case "notes keep single-row safe painting and prepared lists shorten fit and frames"
  (define-values (st calls names) (state))
  (active! st "/cwd/z" 2)
  (def! st 'noted '(s complete-prompt))
  (set-box! calls '())
  (for* ([width '(1 12 40)] [height '(1 2 3 7)])
    (def! st 'fitted `(noted ensure-visible ,width ,height))
    (def! st 'plain `(fitted with-active-prompt ,(p "/cwd/z" 2)))
    (same st '(fitted buffers) '(plain buffers))
    (same st '(fitted windows) '(plain windows))
    (check-equal? (ev st '((fitted editor) text-rows))
      (if (>= height 3) (- height 2) 1))
    (define body (if (>= height 3) (string-append (clip "body" width)
      (apply string-append (make-list (- height 3) "\r\n"))) (clip "body" width)))
    (define expected (frame body 1 1 height (safe (clip "Find file: /cwd/z [No match]" width))
      (if (= height 1) 1 height) (if (= height 1) 1 (min width 14))
      #:name "untitled" #:width width))
    (check-equal? (ev st `(fitted frame ,width ,height)) expected)
    (same st '(fitted prompt) '(noted prompt)))
  (def! st 'raw `(s with-active-prompt ,(p "T\n\r\t\e[31m\u0001\u007fZ" 99 " [No match]")))
  (check-equal? (ev st '(raw frame 30 2))
    (frame "body" 1 1 2 "Find file: T    [31m  Z [No ma" 2 30 #:width 30))
  ;; Independent list-aware expectations for this point-zero/body fixture.
  ;; Leave the no-list frame builder and the note goldens above unchanged.
  (define (listed-fit-gold source width height leaf-height)
    (define ed
      `(AloemacsEditor new ((,source editor) text) ((,source editor) point)
         ((,source editor) quit) 0 0 ((,source editor) history) ((,source editor) mark)
         ,(if (>= leaf-height 2) (sub1 leaf-height) leaf-height)))
    (rebuild source #:buffers (replace-current source ed)
      #:windows `(AloemacsWindows new ((,source windows) tree)
                    ((,source windows) selected) ,width ,height)))
  (define (listed-gold width height lines shown prompt-column split?)
    (define k (if (< height 2) 0 (min (length lines) (- height 2))))
    (define root (if (< height 2) height (- height 1 k)))
    (define text-height (if (>= root 2) (sub1 root) root))
    (define suffix
      (apply string-append
        (for/list ([line (in-list (take lines k))] [j (in-naturals 1)])
          (format "\e[~a;1H~a" (+ root j) (safe (clip line width))))))
    (define body (string-append (clip "body" (if split? 4 width))
                  (apply string-append (make-list (sub1 text-height) "\r\n"))))
    (define prefix
      (if split?
          (string-append "\e[?25l\e[2J\e[H"
            (string-join
              (append (list "body|body") (make-list (sub1 text-height) "    |    ")
                      (if (>= root 2) (list "unti|unti") '())) "\r\n"))
          (string-append (editor-frame body 1 1)
            (if (< height 2) ""
                (string-append "\e[?25l"
                  (if (>= root 2) (format "\e[~a;1H~a" root (mode-row "untitled" width)) ""))))))
    (string-append prefix suffix
      (if (< height 2)
          (if split? "\e[1;1H\e[?25h" "")
          (format "\e[~a;1H~a\e[~a;~aH\e[?25h" height (safe (clip shown width))
                  height (min width prompt-column)))))
  (for* ([width '(1 9 40)] [height '(1 2 3 7)])
    (def! st 'listed `(s with-active-prompt ,(p "/cwd/z" 2 "" '("raw\n\t" "dir/" "...(+2)"))))
    (def! st 'listed-fit `(listed ensure-visible ,width ,height))
    (define root (if (< height 2) height (- height 1 (min 3 (- height 2)))))
    (same st 'listed-fit (listed-fit-gold 'listed width height root))
    (check-equal? (ev st `(listed frame ,width ,height))
      (listed-gold width height '("raw\n\t" "dir/" "...(+2)") "Find file: /cwd/z" 14 #f)))
  ;; Split root: prepared lines shorten both leaves, retaining short text-only leaves.
  (def! st 'split (rebuild 's #:windows
    '(AloemacsWindows new
       (AloemacsWindowTree Right
         (AloemacsWindowTree Leaf (AloemacsView new 0 0 0 0 #f))
         (AloemacsWindowTree Leaf (AloemacsView new 1 0 0 0 #t))) 0 9 4)))
  (def! st 'split `(split with-active-prompt ,(p "x" 0 " [No match]")))
  (check-equal? (ev st '(split frame 9 4))
    "\e[?25l\e[2J\e[Hbody|body\r\n    |    \r\nunti|unti\e[4;1HFind file\e[4;9H\e[?25h")
  (def! st 'listed `(split with-active-prompt ,(p "x" 0 " [No match]" '("a" "b"))))
  (for* ([width '(1 9)] [height '(1 2 4 8)])
    (def! st 'listed-fit `(listed ensure-visible ,width ,height))
    (define root (if (< height 2) height (- height 1 (min 2 (- height 2)))))
    (same st 'listed-fit (listed-fit-gold 'listed width height root))
    (check-equal? (ev st `(listed frame ,width ,height))
      (listed-gold width height '("a" "b") "Find file: x [No match]" 11 (= width 9))))
  (check-equal? (unbox calls) '()))

(test-case "Return and cancellation discard display state and keep exact command outcomes"
  (define-values (st calls names) (state))
  (for ([command '(FindFile SaveAs)] [expected-echo '("" "saved")])
    (active! st "/cwd/alpha.txt" 2 command " [Sole completion]" '("ignored"))
    (set-box! calls '())
    (def! st 'done '(s handle-key "return"))
    (same st '(done last-submission) '(Option Some "/cwd/alpha.txt"))
    (same st '(done prompt) no-prompt)
    (same st '(done waiting-command) no-command)
    (check-equal? (ev st '(done completion-note)) "")
    (same st '(done completion-lines) '(List empty))
    (check-equal? (ev st '(done echo)) expected-echo)
    (check-equal? (effects calls (if (eq? command 'FindFile) 'read 'write))
      (if (eq? command 'FindFile) '((read "/cwd/alpha.txt")) '((write "/cwd/alpha.txt" "body"))))
    (same st '(done submit-prompt) 'done))
  (active! st "/cwd/alpha.txt" 2)
  (def! st 's (rebuild 's #:buffers (zipper (list (bound "keep" "/cwd/alpha.txt")) 0)))
  (set-box! calls '())
  (def! st 'done '(s submit-prompt))
  (check-equal? (effects calls 'read) '())
  (check-equal? (ev st '((done text) to-string)) "keep")
  (active! st "/cwd/new" 1)
  (set-box! calls '())
  (def! st 'done '(s submit-prompt))
  (check-equal? (ev st '((done text) to-string)) "")
  (same st '(done path) '(Option Some (Path new "/cwd/new")))
  (no-file-effects calls)
  (for* ([command '(FindFile SaveAs)] [target '("/cwd/docs" "/cwd/link" "/cwd/pipe")])
    (active! st target 0 command "note" '("ignored"))
    (set-box! calls '())
    (def! st 'done '(s submit-prompt))
    (same st 'done (rebuild 's #:prompt no-prompt #:waiting no-command
      #:submission `(Option Some ,target) #:echo "failed"))
    (no-file-effects calls))
  ;; Empty submission is reached by explicitly erasing the editable prefill.
  (def! st 'base (session (zipper (list (buffer "body")) 0)))
  (for ([command '(FindFile SaveAs)])
    (def! st 's `(base start-command-prompt (AloemacsCommand ,command) "Find file: "))
    (for ([i (in-range 5)]) (def! st 's '(s handle-key "backspace")))
    (set-box! calls '())
    (def! st 'done '(s submit-prompt))
    (same st 'done (rebuild 's #:prompt no-prompt #:waiting no-command
      #:submission '(Option Some "") #:echo "failed"))
    (check-equal? (unbox calls) '()))
  (active! st "/cwd/alp" 1)
  (def! st 'done '(s complete-prompt))
  (def! st 's 'done)
  (set-box! calls '())
  (same st '(s cancel-prompt) (rebuild 's #:prompt no-prompt #:waiting no-command))
  (def! st 'orphan (rebuild 'base #:waiting waiting))
  (same st '(orphan cancel-prompt) (rebuild 'orphan #:waiting no-command))
  (def! st 'other (bound "other" "/cwd/other" 1))
  (def! st 's (rebuild 's #:buffers (zipper (list '(s current-buffer) 'other) 0)))
  (def! st 'changed '(s select-buffer-submitted "/cwd/other"))
  (same st '(changed prompt) '(s prompt))
  (same st '(changed waiting-command) '(s waiting-command))
  (def! st 'selected `(changed with-active-prompt ,(p "/cwd/other" 0 "note" '("ignored"))))
  (def! st 'selected '(selected with-waiting-command (AloemacsCommand SelectBuffer)))
  (def! st 'done '(selected submit-prompt))
  (check-equal? (ev st '((done text) to-string)) "other")
  (same st '(done last-submission) '(Option Some "/cwd/other"))
  (check-equal? (unbox calls) '())
  (def! st 'refused '((s visit (Path new "/cwd/docs")) case (None () s) (Some (v) v)))
  (same st 'refused 's)
  (def! st 'visited '((s visit (Path new "/cwd/alpha.txt")) case (None () s) (Some (v) v)))
  (same st '(visited prompt) no-prompt)
  (check-equal? (ev st '(visited completion-note)) ""))

(test-case "production runner fits at full size and draws once through prefill, Tab, Return and cancel"
  (define-values (host calls names) (counted-fs))
  (define frames (box '()))
  (define events (box '()))
  (define snapshots (box '()))
  (define keys (box '("a" "return" "b" "return" "c" "up" "ctrl-x" "find" "a" "tab" "tab"
                     "h" "tab" "tab" "left" "right" "return" "ctrl-x" "find" "tab" "escape" "escape")))
  (define (record item) (set-box! events (append (unbox events) (list item))))
  (define term (make-host-receiver
    (make-host-interface 'Term
      (list (make-host-method 'columns '() 'Int (lambda (_) (record 'columns) 30))
            (make-host-method 'rows '() 'Int (lambda (_) (record 'rows) 3))
            (make-host-method 'write '(String) 'String (lambda (_ text)
              (record 'write) (set-box! frames (append (unbox frames) (list text))) text))
            (make-host-method 'read-key '() 'String (lambda (_)
              (record 'read-key)
              (set-box! snapshots (append (unbox snapshots) (list (reverse (unbox calls)))))
              (define key (car (unbox keys))) (set-box! keys (cdr (unbox keys))) key)))) #f))
  (run-aloemacs-with-hosts term host)
  (define (gold body row col shown prompt-col [name "untitled"])
    (frame body row col 3 shown (if prompt-col 3 row) (or prompt-col col)
      #:name name #:width 30))
  ;; Distinct a/b/c rows prove fitting before paint at one text row.
  (define blank (gold "" 1 1 "" #f))
  (define body (gold "b" 1 2 "" #f))
  (define started (gold "b" 1 2 "Find file: /cwd/" 17))
  (define typed (gold "b" 1 2 "Find file: /cwd/a" 18))
  (define grown (gold "b" 1 2 "Find file: /cwd/alp" 20))
  (define narrowed (gold "b" 1 2 "Find file: /cwd/alph" 21))
  (define unique (gold "b" 1 2 "Find file: /cwd/alpha.txt" 26))
  (define sole (gold "b" 1 2 (clip "Find file: /cwd/alpha.txt [Sole completion]" 30) 26))
  (define sole-left (gold "b" 1 2 (clip "Find file: /cwd/alpha.txt [Sole completion]" 30) 25))
  (define opened (gold "disk contents" 1 1 "" #f "/cwd/alpha.txt"))
  (define restarted (gold "disk contents" 1 1 "Find file: /cwd/" 17 "/cwd/alpha.txt"))
  (define listed-grown
    "\e[?25l\e[2J\e[Hb\e[1;2H\e[?25h\e[?25l\e[2;1Halpha.txt\e[3;1HFind file: /cwd/alp\e[3;20H\e[?25h")
  (define listed-restarted
    "\e[?25l\e[2J\e[Hdisk contents\e[1;1H\e[?25h\e[?25l\e[2;1Halpha.txt\e[3;1HFind file: /cwd/\e[3;17H\e[?25h")
  (check-equal? (unbox frames)
    (list blank (gold "a" 1 2 "" #f) blank (gold "b" 1 2 "" #f)
          blank (gold "c" 1 2 "" #f) body body started typed grown listed-grown
          narrowed unique sole sole-left sole opened opened restarted listed-restarted opened))
  (check-equal? (unbox events) (apply append (make-list 22 '(columns rows write read-key))))
  (check-equal? (effects calls 'current) '((current)))
  (check-equal? (effects calls 'parent) '((parent "/cwd/alpha.txt")))
  (check-equal? (effects calls 'names) (make-list 5 '(names "/cwd")))
  (check-equal? (effects calls 'read) '((read "/cwd/alpha.txt")))
  (check-equal? (effects calls 'write) '())
  ;; Only starts, Tabs and Return introduce calls between key snapshots.
  (for ([index '(1 2 3 4 5 6 7 9 12 15 16 18 21)])
    (check-equal? (list-ref (unbox snapshots) index) (list-ref (unbox snapshots) (sub1 index))))
  (check-equal? (unbox keys) '()))
