#lang racket/base

(require racket/string racket/list racket/port racket/runtime-path rackunit
         "../../aloe/driver.rkt" "../../aloe/host.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/type.rkt" exn:fail:aloe-type? type-of type->datum)
         "../../host/racket/fs.rkt")

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define no-mark '(if #t (Option None) (Option Some (Position new 0 0))))
(define no-path '(if #t (Option None) (Option Some (Path new "/typed-none"))))
(define no-pending '(if #t (Option None) (Option Some aloemacs-global-keymap)))
(define no-prompt '(if #t (Option None) (Option Some (AloemacsPrompt new "" "" 0 "" (List empty) (List empty) 0))))
(define no-submission '(if #t (Option None) (Option Some "")))
(define (prompt label text column)
  `(Option Some (AloemacsPrompt new ,label ,text ,column "" (List empty) (List empty) 0)))
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (type st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))

;; No real filesystem or TTY: every host send goes through this counted double.
(define (state #:host-name [host-name 'FsHost] #:fail [fail #f] #:vanish? [vanish? #f])
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  (define inner
    (make-fs-double "/cwd"
      (hash "/cwd" 'directory "/cwd/a.txt" 'file "/cwd/b.txt" 'file
            "/cwd/dir" 'directory "/cwd/link" 'symlink "/cwd/pipe" "fifo")
      (hash "/cwd/a.txt" "\uFEFFλ\r\nb\n" "/cwd/b.txt" "disk b")))
  (define calls (box '()))
  (define probes 0)
  (define (forward selector args)
    (set-box! calls (cons (cons selector args) (unbox calls)))
    (when (eq? selector fail) (error 'minibuffer-session "host failure"))
    (when (eq? selector 'kind) (set! probes (add1 probes)))
    (if (and vanish? (eq? selector 'kind) (> probes 1)) "missing"
        (host-receiver-send inner selector args)))
  (define interface
    (make-host-interface host-name
      (for/list ([method (in-list (host-interface-methods fs-interface))])
        (define selector (host-method-selector method))
        (define params (host-method-parameter-types method))
        (make-host-method selector params (host-method-return-type method)
          (case (length params)
            [(0) (lambda (state) (forward selector '()))]
            [(1) (lambda (state a) (forward selector (list a)))]
            [(2) (lambda (state a b) (forward selector (list a b)))])))))
  (driver-inject-host! st 'fs-host (make-host-receiver interface #f))
  (values st calls))
(define (effects calls selector)
  (reverse (filter (lambda (call) (eq? (car call) selector)) (unbox calls))))
(define (editor contents [point '(Position new 0 0)])
  `(AloemacsEditor new ((Text from-string ,contents) indexed-value)
     ,point #f 0 0 (List empty) ,no-mark 0))
(define (buffer contents [path no-path] [id 0])
  `(AloemacsBuffer new ,(editor contents) ,path ,id))
(define (zipper order focus)
  `(AloemacsBuffers new (List of ,@(reverse (take order focus)))
     ,(list-ref order focus) (List of ,@(drop order (add1 focus)))))
(define (session buffers)
  `(AloemacsSession new ,buffers (Fs new fs-host) "saved" #f "old query"
     (Position new 4 2) #t #t (List of "newest" "older")
     ,no-pending ,no-prompt ,no-submission
     (if #t (Option None) (Option Some (AloemacsCommand FindFile)))
     (let ((buffer (,buffers current-buffer)))
       (AloemacsWindows new
         (AloemacsWindowTree Leaf
           (AloemacsView new 0 (buffer id)
             ((buffer editor) scroll-row) ((buffer editor) scroll-col) #f))
         0 0 0))))

;; Expectations use only constructors and reads, never the transition under test.
(define (rebuild s #:buffers [buffers `(,s buffers)] #:echo [echo `(,s echo)]
                 #:searching [searching `(,s searching)] #:query [query `(,s query)]
                 #:origin [origin `(,s origin)] #:wrapped [wrapped `(,s wrapped)]
                 #:failing [failing `(,s failing)] #:ring [ring `(,s kill-ring)]
                 #:pending [pending `(,s pending)] #:prompt [line `(,s prompt)]
                 #:submission [submission `(,s last-submission)]
                 #:columns [columns `((,s windows) columns)]
                 #:rows [rows `((,s windows) rows)])
  `(AloemacsSession new ,buffers (,s fs) ,echo ,searching ,query ,origin
     ,wrapped ,failing ,ring ,pending ,line ,submission
     (,s waiting-command)
     (let ((buffer (,buffers current-buffer)))
       (AloemacsWindows new
         (AloemacsWindowTree Leaf
           (AloemacsView new 0 (buffer id)
             ((buffer editor) scroll-row) ((buffer editor) scroll-col) #f))
         0 ,columns ,rows))))
(define (replace-current s new-editor [path `(,s path)])
  `(AloemacsBuffers new ((,s buffers) before)
     (AloemacsBuffer new ,new-editor ,path ((,s current-buffer) id)) ((,s buffers) after)))
(define (reset s buffers #:visit? [visit? #f])
  (rebuild s #:buffers buffers #:echo "" #:searching #f #:query ""
    #:origin '(Position new 0 0) #:wrapped #f #:failing #f #:pending no-pending
    #:ring (if visit? '(List empty) `(,s kill-ring))
    #:prompt (if visit? no-prompt `(,s prompt))))
(define (rich! st)
  (def! st 'a
    `(AloemacsBuffer new
       (AloemacsEditor new
         (Text indexed (List of "a zero") "neighbor a" (List of "a last") 1)
         (Position new 1 2) #f 1 1
         (List of (UndoFrame new (Text from-string "old a") (Position new 0 1) 0 1))
         (Option Some (Position new 0 2)) 2)
       (Option Some (Path new "/cwd/a.txt")) 0))
  (def! st 'rich-editor
    '(AloemacsEditor new
       (Text indexed (List of "second" "first") "third-long"
                     (List of "fourth" "fifth") 2)
       (Position new 2 4) #f 2 3
       (List of (UndoFrame new (Text from-string "old b") (Position new 0 2) 1 2))
       (Option Some (Position new 1 1)) 4))
  (def! st 'b '(AloemacsBuffer new rich-editor (Option Some (Path new "/cwd/b.txt")) 1))
  (def! st 'c (buffer "neighbor c" no-path 2))
  (def! st 'source (session (zipper '(a b c) 1))))
(define session-fields
  '(buffers fs echo searching query origin wrapped failing kill-ring pending
            prompt last-submission waiting-command windows))
(define editor-fields '(text point quit scroll-row scroll-col history mark text-rows))
(define (same-session st actual expected)
  (def! st 'comparison-actual actual)
  (def! st 'comparison-expected expected)
  (same st 'comparison-actual 'comparison-expected)
  (for ([field (append session-fields '(current-buffer editor path text point quit))])
    (same st `(comparison-actual ,field) `(comparison-expected ,field))))
(define (snapshot st s)
  (append
    (for/list ([field (append (take session-fields 10) '(current-buffer editor path text point quit))])
      (ev st `(,s ,field)))
    (for/list ([field editor-fields]) (ev st `((,s editor) ,field)))
    (list (ev st `((,s current-buffer) name)))))

;; Snapshot before EVERY prompt transition. Entire zipper equality covers both
;; neighbors, their paths/names, every editor payload, and exact Text focus.
(define (transition! st calls s send expected)
  (define before (ev st s))
  (define old-prompt (ev st `(,s prompt)))
  (define preserved (snapshot st s))
  (define old-calls (unbox calls))
  (def! st 'actual send)
  (same-session st 'actual expected)
  (check-equal? (snapshot st 'actual) preserved)
  (check-equal? (ev st s) before)
  (check-equal? (ev st `(,s prompt)) old-prompt)
  (check-equal? (unbox calls) old-calls))
(define (line-is st s label text column)
  (same st `(,s prompt) (prompt label text column))
  (check-equal? (ev st `((,s prompt) case (None () "missing") (Some (p) (p text)))) text)
  (check-equal? (ev st `((,s prompt) case (None () -1) (Some (p) (p column)))) column))
(define (editor-frame body row column)
  (string-append "\u001b[?25l\u001b[2J\u001b[H" body
    (format "\u001b[~a;~aH\u001b[?25h" row column)))
;; Independent name and text allocation from the supplied fixture and size.
(define (mode-row name width)
  (define label (substring (string-append name " ") 0
                          (min width (add1 (string-length name)))))
  (list->string
    (for/list ([c (in-string (string-append label
                              (make-string (- width (string-length label)) #\-)))])
      (if (or (< (char->integer c) 32) (= (char->integer c) 127)) #\space c))))
(define (text-body body rows)
  (define lines (string-split body "\r\n" #:trim? #f))
  (string-join (take lines (min (length lines) (if (>= rows 3) (- rows 2) 1))) "\r\n"))
(define (frame body row column rows shown cursor-row cursor-column #:name [name "untitled"] #:width [width 0])
  (string-append "\e[?25l\e[2J\e[H"
    (if rows (text-body body rows) body)
    (format "\e[~a;~aH\e[?25h" row column)
    (if (and rows (>= rows 2))
        (string-append "\e[?25l"
          (if (>= rows 3) (format "\e[~a;1H~a" (sub1 rows) (mode-row name width)) "")
          (format "\e[~a;1H~a\e[~a;~aH\e[?25h" rows shown cursor-row cursor-column)) "")))

(test-case "five ordinary session methods have exact signatures and concrete checked results"
  (define datums (call-with-input-file file-path (lambda (in) (port->list read in))))
  (define declaration
    (findf (lambda (d) (equal? (cadr d) '(AloemacsSession H))) datums))
  (define additions '(start-prompt with-active-prompt submit-prompt cancel-prompt prompt-key))
  (check-equal?
    (for/list ([m (cdr (cadddr declaration))] #:when (memq (car m) additions))
      (drop-right m 1))
    '((start-prompt (label String) (AloemacsSession H))
      (with-active-prompt (prompt AloemacsPrompt) (AloemacsSession H))
      (submit-prompt () (AloemacsSession H))
      (cancel-prompt () (AloemacsSession H))
      (prompt-key (key String) (AloemacsSession H))))
  (for ([host-name '(FsHost AlternateFsHost)])
    (define-values (st calls) (state #:host-name host-name))
    (rich! st)
    (def! st 'p '(AloemacsPrompt new "Ask: " "abc" 1 "" (List empty) (List empty) 0))
    (for ([send '((source start-prompt "Ask: ") (source with-active-prompt p)
                  (source submit-prompt) (source cancel-prompt) (source prompt-key "x"))])
      (check-equal? (type st send) `(AloemacsSession ,host-name))
      (check-not-exn (lambda () (ev st send))))
    (def! st 'active (rebuild 'source #:prompt '(Option Some p)))
    (for ([send '((active submit-prompt) (active cancel-prompt) (active prompt-key "x"))])
      (check-equal? (type st send) `(AloemacsSession ,host-name))
      (check-not-exn (lambda () (ev st send))))
    (for ([bad '((source start-prompt) (source start-prompt "a" "b")
                 (source start-prompt 1) (source start-prompt #f)
                 (source with-active-prompt) (source with-active-prompt p p)
                 (source with-active-prompt "x") (source with-active-prompt 0)
                 (source with-active-prompt (Option Some p))
                 (source with-active-prompt (if #t (Option None) (Option Some p)))
                 (source prompt-key) (source prompt-key "x" "y")
                 (source prompt-key 0) (source prompt-key #f)
                 (source submit-prompt 0) (source cancel-prompt 0))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st bad)) (format "reject ~s" bad)))
    (for* ([receiver '(1 "s" p AloemacsSession)]
           [tail '((start-prompt "x") (with-active-prompt p)
                   (submit-prompt) (cancel-prompt) (prompt-key "x"))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st `(,receiver ,@tail)))))
    (check-equal? (unbox calls) '())))

(test-case "start accepts exact labels, refuses four states, and inactive helpers do nothing"
  (define-values (st calls) (state))
  (rich! st)
  (for ([label '("Ask: " "" "L\t\r\u001b\u0000\u007f\n")])
    (transition! st calls 'source `(source start-prompt ,label)
      (rebuild 'source #:prompt (prompt label "" 0)))
    (line-is st 'actual label "" 0))
  (for ([fixture (list
                   (rebuild 'source #:buffers (replace-current 'source '(rich-editor request-quit)))
                   (rebuild 'source #:searching #t)
                   (rebuild 'source #:pending '(Option Some aloemacs-ctrl-x-keymap))
                   (rebuild 'source #:prompt (prompt "Old: " "unchanged" 3)))])
    (def! st 'refused fixture)
    (transition! st calls 'refused '(refused start-prompt "replacement") 'refused))
  (for ([send '((source submit-prompt) (source cancel-prompt)
                (source prompt-key "x") (source prompt-key "save")
                (source prompt-key "find") (source prompt-key "ctrl-x")
                (source prompt-key "escape") (source prompt-key "return"))])
    (transition! st calls 'source send 'source))
  (def! st 'answered (rebuild 'source #:submission '(Option Some "previous\tanswer")))
  (transition! st calls 'answered '(answered start-prompt "Again: ")
    (rebuild 'answered #:prompt (prompt "Again: " "" 0)))
  (same st '(actual last-submission) '(Option Some "previous\tanswer"))
  (check-equal? (unbox calls) '()))

(test-case "every active editing key has literal independent results and preserves rich state"
  (define-values (st calls) (state))
  (rich! st)
  (for ([row '(("abc" 0 "X" "Xabc" 1) ("abc" 1 "X" "aXbc" 2)
               ("abc" 3 "X" "abcX" 4) ("" 0 "λ" "λ" 1)
               ("abc" 0 "backspace" "abc" 0) ("abc" 2 "backspace" "ac" 1)
               ("abc" 3 "backspace" "ab" 2) ("" 0 "backspace" "" 0)
               ("abc" 0 "left" "abc" 0) ("abc" 3 "left" "abc" 2)
               ("abc" 0 "right" "abc" 1) ("abc" 3 "right" "abc" 3)
               ("abc" 2 "line-start" "abc" 0) ("abc" 1 "line-end" "abc" 3)
               ("" 0 "left" "" 0) ("" 0 "right" "" 0)
               ("" 0 "line-start" "" 0) ("" 0 "line-end" "" 0))])
    (def! st 'active (rebuild 'source #:prompt (prompt "L\t: " (car row) (cadr row))))
    (for ([helper '(handle-key prompt-key)])
      (transition! st calls 'active `(active ,helper ,(list-ref row 2))
        (rebuild 'active #:prompt (prompt "L\t: " (list-ref row 3) (list-ref row 4))))
      (line-is st 'actual "L\t: " (list-ref row 3) (list-ref row 4))))
  (for ([key '(" " "\t" "\r" "\u001b" "\u0000" "\u007f" "\u0001" "λ")])
    (def! st 'active (rebuild 'source #:prompt (prompt "Ask: " "ab" 1)))
    (transition! st calls 'active `(active handle-key ,key)
      (rebuild 'active #:prompt (prompt "Ask: " (string-append "a" key "b") 2)))
    (check-false (ev st '((((actual prompt) case
      (None () "missing") (Some (p) (p text))) find "\n" 0) present?))))
  (check-equal? (unbox calls) '()))

(define ignored-keys
  '("" "unknown" "xy" "find" "save" "ctrl-x" "undo" "mark" "kill"
    "kill-line" "yank" "up" "down" "page-up" "page-down" "buffer-start"
    "buffer-end" "delete" "switch-buffer" "kill-buffer"))

(test-case "LF and every ignored key preserve the full active session with zero Fs calls"
  (define-values (st calls) (state))
  (rich! st)
  (def! st 'active (rebuild 'source #:prompt (prompt "Ask: " "abc" 1)))
  (for* ([key (cons "\n" ignored-keys)] [helper '(handle-key prompt-key)])
    (transition! st calls 'active `(active ,helper ,key) 'active))
  (check-equal? (unbox calls) '()))

(test-case "quit absorbs first, while direct prompt helpers retain their local transitions"
  (define-values (st calls) (state))
  (rich! st)
  (def! st 'raw
    (rebuild 'source #:buffers (replace-current 'source '(rich-editor request-quit))
      #:searching #t #:pending '(Option Some aloemacs-ctrl-x-keymap)
      #:prompt (prompt "Ask: " "abc" 1) #:submission '(Option Some "old")))
  (for ([key (append ignored-keys '("x" "\n" "backspace" "left" "right"
                                    "line-start" "line-end" "return" "escape"))])
    (transition! st calls 'raw `(raw handle-key ,key) 'raw))
  (transition! st calls 'raw '(raw prompt-key "x")
    (rebuild 'raw #:prompt (prompt "Ask: " "axbc" 2)))
  (transition! st calls 'raw '(raw prompt-key "return")
    (rebuild 'raw #:prompt no-prompt #:submission '(Option Some "abc")))
  (transition! st calls 'raw '(raw prompt-key "escape") (rebuild 'raw #:prompt no-prompt))
  (transition! st calls 'raw '(raw submit-prompt)
    (rebuild 'raw #:prompt no-prompt #:submission '(Option Some "abc")))
  (transition! st calls 'raw '(raw cancel-prompt) (rebuild 'raw #:prompt no-prompt))
  (transition! st calls 'raw '(raw with-active-prompt (AloemacsPrompt new "New" "xyz" 2 "" (List empty) (List empty) 0))
    (rebuild 'raw #:prompt (prompt "New" "xyz" 2)))
  (check-equal? (unbox calls) '()))

(test-case "search precedes prompt and retains its filter, point, exit, and idle forwarding"
  (define-values (st calls) (state))
  (rich! st)
  (def! st 'raw
    (rebuild 'source #:searching #t #:query "" #:origin '(source point)
      #:wrapped #f #:failing #f #:prompt (prompt "Ask: " "draft" 2)
      #:submission '(Option Some "old")))
  (define before (ev st 'raw))
  (def! st 'hit '(raw handle-key "l"))
  (same-session st 'hit
    (rebuild 'raw #:query "l" #:buffers
      (replace-current 'raw
        '(AloemacsEditor new (raw text) (Position new 2 6) #f 2 3
           (rich-editor history) (rich-editor mark) 4))))
  (check-equal? (ev st '(hit searching)) #t)
  (same st '(hit prompt) '(raw prompt))
  (check-equal? (ev st '(hit frame 12 3))
    (frame "rd-long\r\nrth" 1 4 3 "Ask: draft" 3 8 #:name "/cwd/b.txt" #:width 12))
  (def! st 'miss '(raw handle-key "z"))
  (same-session st 'miss (rebuild 'raw #:query "z" #:failing #t))
  (def! st 'deleted '(hit handle-key "backspace"))
  (same-session st 'deleted (rebuild 'raw #:buffers (replace-current 'raw
    '(AloemacsEditor new (raw text) (raw origin) #f 2 3
       (rich-editor history) (rich-editor mark) 4))))
  (for ([key '("return" "escape")])
    (same-session st `(hit handle-key ,key)
      (rebuild 'hit #:searching #f #:query "" #:origin '(Position new 0 0)
               #:wrapped #f #:failing #f)))
  ;; Existing unsafe-character and unknown-key paths end search and send to
  ;; idle directly, even in this combined fixture. They keep the draft line.
  (for ([key '("\t" "\n")])
    (def! st 'forwarded `(raw handle-key ,key))
    (check-false (ev st '(forwarded searching)))
    (same st '(forwarded prompt) '(raw prompt))
    (same st '(forwarded last-submission) '(Option Some "old"))
    (check-equal? (ev st '(forwarded echo)) "")
    (check-equal? (ev st '((forwarded text) to-string))
      (string-append "first\nsecond\nthir" key "d-long\nfourth\nfifth"))
    (check-equal? (ev st '(((forwarded editor) history) len)) 2))
  (same-session st '(raw handle-key "unknown")
    (rebuild 'raw #:searching #f #:query "" #:origin '(Position new 0 0)
             #:wrapped #f #:failing #f #:echo ""))
  (def! st 'again '(hit handle-key "find"))
  (check-true (ev st '(again searching)))
  (check-true (ev st '(again wrapped)))
  (same st '(again prompt) '(raw prompt))
  (check-equal? (ev st '(again query)) "l")
  (check-equal? (ev st 'raw) before)
  (check-equal? (unbox calls) '()))

(test-case "an active prompt owns keys without consulting or consuming a pending map"
  (define-values (st calls) (state))
  (rich! st)
  (def! st 'trap-map
    '(AloemacsKeymap new
       (List of (AloemacsBinding Command "x" (AloemacsCommand RequestQuit))
                (AloemacsBinding Command "escape" (AloemacsCommand Save))
                (AloemacsBinding Command "return" (AloemacsCommand KillBuffer)))
       (Option Some (AloemacsCommand Save))))
  (def! st 'raw (rebuild 'source #:prompt (prompt "Ask: " "ab" 1)
                                   #:pending '(Option Some trap-map)))
  (transition! st calls 'raw '(raw handle-key "x")
    (rebuild 'raw #:prompt (prompt "Ask: " "axb" 2)))
  (for ([key (cons "\n" ignored-keys)])
    (transition! st calls 'raw `(raw handle-key ,key) 'raw))
  (transition! st calls 'raw '(raw handle-key "return")
    (rebuild 'raw #:prompt no-prompt #:submission '(Option Some "ab")))
  (transition! st calls 'raw '(raw handle-key "escape") (rebuild 'raw #:prompt no-prompt))
  ;; Once canceled, the existing pending miss is consumed without global retry.
  (def! st 'canceled 'actual)
  (same-session st '(canceled handle-key "y")
    (rebuild 'canceled #:pending no-pending #:echo ""))
  (check-equal? (unbox calls) '()))

(test-case "Ask sequence paints complete exact frames, submits text only, and restores text cursor"
  (define-values (st calls) (state))
  (rich! st)
  (def! st 's (session (zipper (list (buffer "ab\nsecond")) 0)))
  (def! st 's (rebuild 's #:buffers (replace-current 's
    '(AloemacsEditor new ((Text from-string "ab\nsecond") indexed-value)
       (Position new 0 1) #f 0 0 (List empty) (Option Some (Position new 1 2)) 2))))
  (define inactive (frame "ab\r\nsecond" 1 2 3 "saved: untit" 1 2 #:name "untitled" #:width 12))
  (check-equal? (ev st '(s frame 12 3)) inactive)
  (transition! st calls 's '(s start-prompt "Ask: ") (rebuild 's #:prompt (prompt "Ask: " "" 0)))
  (def! st 's 'actual)
  (for ([row '(("a" "a" 1) ("c" "ac" 2) ("left" "ac" 1) ("b" "abc" 2))])
    (transition! st calls 's `(s handle-key ,(car row))
      (rebuild 's #:prompt (prompt "Ask: " (cadr row) (caddr row))))
    (line-is st 'actual "Ask: " (cadr row) (caddr row))
    (def! st 's 'actual))
  (define before (ev st 's))
  (for ([i (in-range 2)])
    (check-equal? (ev st '(s frame 12 3))
      (frame "ab\r\nsecond" 1 2 3 "Ask: abc" 3 8 #:name "untitled" #:width 12)))
  (check-equal? (ev st 's) before)
  (transition! st calls 's '(s handle-key "return")
    (rebuild 's #:prompt no-prompt #:submission '(Option Some "abc")))
  (check-false (ev st '((actual prompt) present?)))
  (for ([i (in-range 3)])
    (same st '(actual last-submission) '(Option Some "abc"))
    (check-equal? (ev st '(actual frame 12 3)) inactive))
  (check-equal? (ev st 's) before)
  (check-equal? (unbox calls) '()))

(test-case "empty and replaced submissions survive restart, Escape, reads, and redraws"
  (define-values (st calls) (state))
  (rich! st)
  (for ([echo '("saved" "failed")] [shown '("saved: /cw" "failed: /c")])
    (def! st 's (rebuild 'source #:echo echo))
    (define inactive (frame "rd-long\r\nrth" 1 2 3 shown 1 2 #:name "/cwd/b.txt" #:width 10))
    ;; Cancellation before a submit retains None.
    (transition! st calls 's '(s start-prompt "Ask: ") (rebuild 's #:prompt (prompt "Ask: " "" 0)))
    (def! st 's 'actual)
    (transition! st calls 's '(s handle-key "escape") (rebuild 's #:prompt no-prompt))
    (same st '(actual last-submission) no-submission)
    (check-false (ev st '(actual quit)))
    (check-equal? (ev st '(actual frame 10 3)) inactive)
    (def! st 's 'actual)
    (transition! st calls 's '(s start-prompt "") (rebuild 's #:prompt (prompt "" "" 0)))
    (def! st 's 'actual)
    (transition! st calls 's '(s handle-key "return")
      (rebuild 's #:prompt no-prompt #:submission '(Option Some "")))
    (check-true (ev st '((actual last-submission) present?)))
    (def! st 's 'actual)
    (transition! st calls 's '(s start-prompt "Next: ") (rebuild 's #:prompt (prompt "Next: " "" 0)))
    (def! st 's 'actual)
    (transition! st calls 's '(s handle-key "Z") (rebuild 's #:prompt (prompt "Next: " "Z" 1)))
    (def! st 's 'actual)
    (transition! st calls 's '(s handle-key "return")
      (rebuild 's #:prompt no-prompt #:submission '(Option Some "Z")))
    (def! st 's 'actual)
    (transition! st calls 's '(s start-prompt "Cancel: ") (rebuild 's #:prompt (prompt "Cancel: " "" 0)))
    (def! st 's 'actual)
    (transition! st calls 's '(s handle-key "x") (rebuild 's #:prompt (prompt "Cancel: " "x" 1)))
    (def! st 's 'actual)
    (transition! st calls 's '(s handle-key "escape") (rebuild 's #:prompt no-prompt))
    (def! st 's 'actual)
    (define canceled (ev st 's))
    (for ([i (in-range 3)])
      (same st '(s last-submission) '(Option Some "Z"))
      (check-equal? (ev st '(s frame 10 3)) inactive)
      (check-false (ev st '(s quit))))
    (check-equal? (ev st 's) canceled)
    ;; Another empty Return replaces even a nonempty previous submission.
    (transition! st calls 's '(s start-prompt "") (rebuild 's #:prompt (prompt "" "" 0)))
    (def! st 's 'actual)
    (transition! st calls 's '(s handle-key "return")
      (rebuild 's #:prompt no-prompt #:submission '(Option Some ""))))
  (check-equal? (unbox calls) '()))

;; Exercise the public transition seam before testing the retained operations.
(define (answered! st calls)
  (rich! st)
  (transition! st calls 'source '(source start-prompt "Answer: ")
    (rebuild 'source #:prompt (prompt "Answer: " "" 0)))
  (def! st 's 'actual)
  (transition! st calls 's '(s handle-key "Z") (rebuild 's #:prompt (prompt "Answer: " "Z" 1)))
  (def! st 's 'actual)
  (transition! st calls 's '(s handle-key "return")
    (rebuild 's #:prompt no-prompt #:submission '(Option Some "Z")))
  (def! st 'answered 'actual))

(test-case "after submit, ordinary input and search retain submission and their editor results"
  (define-values (st calls) (state))
  (answered! st calls)
  (define original (ev st 'answered))
  (def! st 'edited '(answered handle-key "!"))
  (check-equal? (ev st '((edited text) to-string)) "first\nsecond\nthir!d-long\nfourth\nfifth")
  (same st '(edited point) '(Position new 2 5))
  (check-equal? (ev st '(((edited editor) history) len)) 2)
  (check-equal? (ev st '(edited echo)) "")
  (same st '(edited last-submission) '(Option Some "Z"))
  (same st '((edited buffers) before) '((answered buffers) before))
  (same st '((edited buffers) after) '((answered buffers) after))
  ;; The direct LF string is still a length-one idle self-insert.
  (def! st 'lf '(answered handle-key "\n"))
  (check-equal? (ev st '((lf text) to-string)) "first\nsecond\nthir\nd-long\nfourth\nfifth")
  (same st '(lf point) '(Position new 3 0))
  (check-equal? (ev st '(((lf editor) history) len)) 2)
  (same st '(lf last-submission) '(Option Some "Z"))
  (def! st 'search '(answered handle-key "find"))
  (same-session st 'search (rebuild 'answered #:searching #t #:query ""
                                  #:origin '(answered point) #:wrapped #f #:failing #f))
  (def! st 'hit '(search handle-key "l"))
  (check-equal? (ev st '(hit query)) "l")
  (same st '(hit point) '(Position new 2 6))
  (same st '(hit last-submission) '(Option Some "Z"))
  (check-equal? (ev st '(hit frame 12 3))
    (frame "rd-long\r\nrth" 1 4 3 "search: l" 1 4 #:name "/cwd/b.txt" #:width 12))
  (for ([key '("escape" "return")])
    (def! st 'exited `(hit handle-key ,key))
    (check-false (ev st '(exited searching)))
    (check-false (ev st '(exited quit)))
    (same st '(exited last-submission) '(Option Some "Z"))
    (same st '(exited point) '(Position new 2 6)))
  (check-equal? (ev st 'answered) original)
  (check-equal? (unbox calls) '()))

(test-case "plain and prefix saves, consumed prefix cancellation, and selection retain submission"
  (define-values (st calls) (state))
  (answered! st calls)
  (define original (ev st 'answered))
  (def! st 'plain '(answered handle-key "save"))
  (same-session st 'plain (rebuild 'answered #:echo "saved"))
  (check-equal? (effects calls 'write)
    '((write "/cwd/b.txt" "first\nsecond\nthird-long\nfourth\nfifth")))
  (set-box! calls '())
  (def! st 'armed '(answered handle-key "ctrl-x"))
  (same-session st 'armed (rebuild 'answered #:echo "" #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (check-equal? (unbox calls) '())
  (def! st 'saved '(armed handle-key "save"))
  (same-session st 'saved (rebuild 'answered #:echo "saved"))
  (check-equal? (effects calls 'write)
    '((write "/cwd/b.txt" "first\nsecond\nthird-long\nfourth\nfifth")))
  (set-box! calls '())
  (for ([key '("escape" "x" "ctrl-x" "unknown")])
    (same-session st `(armed handle-key ,key) (rebuild 'answered #:echo "")))
  (same-session st '(answered switch-buffer) (reset 'answered (zipper '(a b c) 2)))
  (same-session st '(answered kill-buffer) (reset 'answered (zipper '(a c) 1)))
  (same-session st '(answered add-buffer "new")
    (reset 'answered (zipper (list 'a 'b (buffer "new" no-path 3) 'c) 2)))
  (same-session st '(answered add-buffer "new" (Path new "./new.txt"))
    (reset 'answered (zipper (list 'a 'b (buffer "new" '(Option Some (Path new "./new.txt")) 3) 'c) 2)))
  (check-equal? (unbox calls) '())
  (check-equal? (ev st 'answered) original))

(test-case "direct save, both additions, switch, kill, fit, and frame preserve an unfinished line"
  (define-values (st calls) (state))
  (answered! st calls)
  (transition! st calls 'answered '(answered start-prompt "Draft: ")
    (rebuild 'answered #:prompt (prompt "Draft: " "" 0)))
  (def! st 's 'actual)
  (transition! st calls 's '(s handle-key "d") (rebuild 's #:prompt (prompt "Draft: " "d" 1)))
  (def! st 'draft 'actual)
  (define original (ev st 'draft))
  (def! st 'option '(draft save))
  (check-true (ev st '(option present?)))
  (same-session st '(option case (None () draft) (Some (s) s)) 'draft)
  (check-equal? (effects calls 'write)
    '((write "/cwd/b.txt" "first\nsecond\nthird-long\nfourth\nfifth")))
  (set-box! calls '())
  (for ([row (list
              (list '(draft switch-buffer) (reset 'draft (zipper '(a b c) 2)))
              (list '(draft kill-buffer) (reset 'draft (zipper '(a c) 1)))
              (list '(draft add-buffer "new")
                    (reset 'draft (zipper (list 'a 'b (buffer "new" no-path 3) 'c) 2)))
              (list '(draft add-buffer "new" (Path new "new.txt"))
                    (reset 'draft (zipper (list 'a 'b (buffer "new" '(Option Some (Path new "new.txt")) 3) 'c) 2)))
              (list '(draft ensure-visible 2 2)
                    (rebuild 'draft #:columns 2 #:rows 2 #:buffers (replace-current 'draft
                      '(AloemacsEditor new (draft text) (draft point) #f 2 3
                         (rich-editor history) (rich-editor mark) 1)))))])
    (def! st 'result (car row))
    (same-session st 'result (cadr row))
    (line-is st 'result "Draft: " "d" 1)
    (same st '(result last-submission) '(Option Some "Z")))
  (for ([i (in-range 2)])
    (check-equal? (ev st '(draft frame 12 3))
      (frame "rd-long\r\nrth" 1 2 3 "Draft: d" 3 9 #:name "/cwd/b.txt" #:width 12)))
  (check-equal? (ev st 'draft) original)
  (check-equal? (unbox calls) '()))

(test-case "regular and missing visits drop only the draft among prompt state and reset only current"
  (define-values (st calls) (state))
  (answered! st calls)
  (transition! st calls 'answered '(answered start-prompt "Draft: ")
    (rebuild 'answered #:prompt (prompt "Draft: " "" 0)))
  (def! st 's 'actual)
  (transition! st calls 's '(s handle-key "d") (rebuild 's #:prompt (prompt "Draft: " "d" 1)))
  (def! st 'draft 'actual)
  (for ([source '(answered draft)])
    (define original (ev st source))
    (for ([path '("./dir/../a.txt" "missing.txt")]
          [resolved '("/cwd/a.txt" "/cwd/missing.txt")]
          [contents '("\uFEFFλ\r\nb\n" "")])
      (set-box! calls '())
      (def! st 'option `(,source visit (Path new ,path)))
      (check-true (ev st '(option present?)))
      (def! st 'visited `(option case (None () ,source) (Some (s) s)))
      (same-session st 'visited
        (reset source (replace-current source (editor contents)
                        `(Option Some (Path new ,resolved))) #:visit? #t))
      (check-false (ev st '((visited prompt) present?)))
      (same st '(visited last-submission) '(Option Some "Z"))
      (same st '((visited buffers) before) `((,source buffers) before))
      (same st '((visited buffers) after) `((,source buffers) after))
      (check-equal? (ev st '((visited text) to-string)) contents)
      (check-equal? (effects calls 'kind)
        (if (equal? contents "") '((kind "/cwd/missing.txt"))
            '((kind "/cwd/a.txt") (kind "/cwd/a.txt"))))
      (check-equal? (effects calls 'read)
        (if (equal? contents "") '() '((read "/cwd/a.txt"))))
      (check-equal? (effects calls 'write) '())
      (check-equal? (ev st source) original))))

(test-case "refused visits and host failures keep the whole answered or draft source"
  (define-values (st calls) (state))
  (answered! st calls)
  (transition! st calls 'answered '(answered start-prompt "Draft: ")
    (rebuild 'answered #:prompt (prompt "Draft: " "" 0)))
  (def! st 'draft 'actual)
  (for* ([source '(answered draft)] [path '("dir" "link" "pipe")])
    (define original (ev st source))
    (set-box! calls '())
    (check-false (ev st `((,source visit (Path new ,path)) present?)))
    (check-equal? (effects calls 'kind) `((kind ,(string-append "/cwd/" path))))
    (check-equal? (effects calls 'read) '())
    (check-equal? (effects calls 'write) '())
    (same st `(,source last-submission) '(Option Some "Z"))
    (check-equal? (ev st source) original))
  (define-values (vanished probes) (state #:vanish? #t))
  (answered! vanished probes)
  (transition! vanished probes 'answered '(answered start-prompt "Draft: ")
    (rebuild 'answered #:prompt (prompt "Draft: " "" 0)))
  (def! vanished 'draft 'actual)
  (define original (ev vanished 'draft))
  (check-false (ev vanished '((draft visit (Path new "a.txt")) present?)))
  (check-equal? (effects probes 'kind) '((kind "/cwd/a.txt") (kind "/cwd/a.txt")))
  (check-equal? (effects probes 'read) '())
  (check-equal? (ev vanished 'draft) original)
  (for ([selector '(resolve kind read)])
    (define-values (failing failures) (state #:fail selector))
    (answered! failing failures)
    (transition! failing failures 'answered '(answered start-prompt "Draft: ")
      (rebuild 'answered #:prompt (prompt "Draft: " "" 0)))
    (def! failing 'draft 'actual)
    (define before (ev failing 'draft))
    (check-exn exn:fail:aloe-host? (lambda () (ev failing '(draft visit (Path new "a.txt")))))
    (check-equal? (ev failing 'draft) before)
    (check-equal? (effects failures 'write) '())))

(test-case "stored controls and offscreen text are exact, unsanitized, and exclude the label"
  (define-values (st calls) (state))
  (rich! st)
  (define label "L\t\u001b: ")
  (define text "\t\r\u001b\u0000\u007f λabcdef")
  (def! st 's 'source)
  (transition! st calls 's `(s start-prompt ,label) (rebuild 's #:prompt (prompt label "" 0)))
  (def! st 's 'actual)
  (for ([c (in-string text)] [column (in-naturals 1)])
    (transition! st calls 's `(s handle-key ,(string c))
      (rebuild 's #:prompt (prompt label (substring text 0 column) column)))
    (def! st 's 'actual))
  ;; Width four clips the label before safe cells; neither edit nor submit
  ;; depends on these displayed spaces or the clipped prompt cursor.
  (check-equal? (ev st '(s frame 4 3)) (frame "rd-l\r\nrth" 1 2 3 "L  :" 3 4 #:name "/cwd/b.txt" #:width 4))
  (transition! st calls 's '(s handle-key "return")
    (rebuild 's #:prompt no-prompt #:submission `(Option Some ,text)))
  (for ([i (in-range 3)]) (same st '(actual last-submission) `(Option Some ,text)))
  (check-equal? (unbox calls) '()))

(test-case "one-row typing, Return, and cancellation work without an echo suffix"
  (define-values (st calls) (state))
  (rich! st)
  (def! st 's '(source ensure-visible 12 1))
  (define only-text (editor-frame "rd-long" 1 2))
  (transition! st calls 's '(s start-prompt "Ask: ") (rebuild 's #:prompt (prompt "Ask: " "" 0)))
  (def! st 's 'actual)
  (transition! st calls 's '(s handle-key "x") (rebuild 's #:prompt (prompt "Ask: " "x" 1)))
  (def! st 's 'actual)
  (check-equal? (ev st '(s frame 12 1)) only-text)
  (check-equal? (ev st '(s frame 12 1)) (ev st '((s editor) frame 12 1)))
  (check-equal? (ev st '(s frame 12 3)) (frame "rd-long\r\nrth" 1 2 3 "Ask: x" 3 7 #:name "/cwd/b.txt" #:width 12))
  (transition! st calls 's '(s handle-key "return")
    (rebuild 's #:prompt no-prompt #:submission '(Option Some "x")))
  (def! st 's 'actual)
  (check-equal? (ev st '(s frame 12 1)) only-text)
  (transition! st calls 's '(s start-prompt "Again: ") (rebuild 's #:prompt (prompt "Again: " "" 0)))
  (def! st 's 'actual)
  (transition! st calls 's '(s handle-key "y") (rebuild 's #:prompt (prompt "Again: " "y" 1)))
  (def! st 's 'actual)
  (transition! st calls 's '(s handle-key "escape") (rebuild 's #:prompt no-prompt))
  (check-equal? (ev st '(actual frame 12 1)) only-text)
  (same st '(actual last-submission) '(Option Some "x"))
  (check-false (ev st '(actual quit)))
  (check-equal? (unbox calls) '()))
