#lang racket/base

(require racket/list racket/port racket/runtime-path rackunit
         "../../aloe/driver.rkt" "../../aloe/env.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/type.rkt" type-of type->datum
                  exn:fail:aloe-type? type-environment-bound?))

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define-runtime-path editor-path "../../examples/aloemacs/editor.aloe")
(define (ev st expr) (driver-eval! st expr))
(define (loaded)
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  st)
(define (dtype st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))

(test-case "fieldless helper placement, unchanged payloads and capability-free load"
  (define datums (call-with-input-file file-path (lambda (in) (port->list read in))))
  (define classes (filter (lambda (d) (eq? (car d) 'define-class)) datums))
  (check-equal? (take datums 2) '((load "editor.aloe") (load "../../lib/fs.aloe")))
  (check-equal? (map cadr classes)
    '(AloemacsPrompt AloemacsCompletionScan AloemacsBuffer AloemacsBuffers AloemacsModeLine AloemacsView
      AloemacsWindowTree AloemacsWindowRect AloemacsWindows AloemacsCommand
      (AloemacsKeymap B) AloemacsBinding AloemacsSearchScan (AloemacsSession H)))
  (define (payload name) (caddr (findf (lambda (d) (equal? (cadr d) name)) classes)))
  (check-equal? (payload 'AloemacsModeLine) '(fields))
  (check-equal? (payload 'AloemacsBuffer)
                '(fields (editor AloemacsEditor) (path (Option Path)) (id Int)))
  (check-equal? (payload 'AloemacsView)
                '(fields (id Int) (buffer-id Int) (scroll-row Int) (scroll-col Int) (locked Bool)))
  (check-equal? (payload 'AloemacsWindowRect)
                '(fields (x Int) (y Int) (columns Int) (rows Int)))
  (check-equal? (payload 'AloemacsWindows)
                '(fields (tree AloemacsWindowTree) (selected Int) (columns Int) (rows Int)))
  (check-equal? (map car (cdr (payload '(AloemacsSession H))))
                '(buffers fs echo searching query origin wrapped failing kill-ring pending
                          prompt last-submission waiting-command windows))
  (define editor-datums (call-with-input-file editor-path (lambda (in) (port->list read in))))
  (check-equal? (caddr (findf (lambda (d) (equal? (take d 2) '(define-class AloemacsEditor)))
                            editor-datums))
    '(fields (text Text) (point Position) (quit Bool) (scroll-row Int) (scroll-col Int)
             (history (List UndoFrame)) (mark (Option Position)) (text-rows Int)))
  (define out (open-output-string))
  (define err (open-output-string))
  (define st (parameterize ([current-output-port out] [current-error-port err]) (loaded)))
  (for ([name '(fs-host term)])
    (check-false (env-bound? (driver-runtime-environment st) name))
    (check-false (type-environment-bound? (driver-type-environment st) name)))
  (check-equal? (get-output-string out) "")
  (check-equal? (get-output-string err) "")
  (check-equal? (dtype st '(AloemacsModeLine new)) 'AloemacsModeLine)
  (check-equal? (dtype st '((AloemacsModeLine new) row "x" 4)) 'String)
  (check-equal? (dtype st '((AloemacsWindowRect new 0 0 3 4) text-rows)) 'Int)
  (for ([expr '((AloemacsModeLine new 0)
                ((AloemacsModeLine new) row) ((AloemacsModeLine new) row "x")
                ((AloemacsModeLine new) row "x" 1 2)
                ((AloemacsModeLine new) row 1 2) ((AloemacsModeLine new) row "x" "2")
                ((AloemacsModeLine new) row "x" 2.0) ("x" row "x" 2)
                ((AloemacsWindowRect new 0 0 3 4) text-rows 1)
                ((AloemacsModeLine new) text-rows)
                (AloemacsWindowRect new 0 0 3) (AloemacsWindowRect new 0 0 3 4 5))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st expr)) (format "reject ~s" expr))))

(test-case "independent exact row examples, lengths, clipping and raw controls"
  (define st (loaded))
  (for ([entry '(("untitled" 0 "") ("untitled" -8 "") ("untitled" 1 "u")
                ("untitled" 8 "untitled") ("untitled" 9 "untitled ")
                ("untitled" 12 "untitled ---") ("/cwd/a.txt" 8 "/cwd/a.t")
                ("/a" 4 "/a -") ("" 4 " ---") ("abc" 3 "abc")
                ("abc" 4 "abc ") ("abc" 6 "abc --")
                ("/a/very/long/name" 5 "/a/ve")
                ("a\u001bb" 6 "a\u001bb --")
                ("a\u001b[31m\t\r\n\u0001\u007fZ" 15 "a\u001b[31m\t\r\n\u0001\u007fZ --")
                ("abc\u001b\t\r\n\u0001\u007f" 3 "abc"))])
    (define actual (ev st `((AloemacsModeLine new) row ,(car entry) ,(cadr entry))))
    (check-equal? actual (caddr entry))
    (check-equal? (string-length actual) (max 0 (cadr entry)))))

(test-case "derived height leaves nominal geometry unchanged"
  (define st (loaded))
  (for ([height '(-1 0 1 2 3 5 10)] [text-height '(-1 0 1 1 2 4 9)])
    (ev st `(define rect (AloemacsWindowRect new 2 3 7 ,height)))
    (define before (ev st 'rect))
    (check-equal? (ev st '(rect text-rows)) text-height)
    (check-equal? (ev st '(rect rows)) height)
    (check-equal? (ev st 'rect) before)))
