#lang racket/base

(require racket/list racket/runtime-path racket/string rackunit
         "../../aloe/driver.rkt" "../../aloe/host.rkt"
         "../../host/racket/fs.rkt" "../../host/racket/term.rkt"
         "../../host/racket/aloemacs-run.rkt")

(define-runtime-path main-path "../../examples/aloemacs/main.aloe")
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))
(define no-path '(if #t (Option None) (Option Some (Path new ""))))
(define no-mark '(if #t (Option None) (Option Some (Position new 0 0))))
(define history '(List of (UndoFrame new (Text from-string "old") (Position new 0 1) 2 3)))
(define (indexed lines [focus 0])
  `(Text indexed (List of ,@(reverse (take lines focus))) ,(list-ref lines focus)
     (List of ,@(drop lines (add1 focus))) ,focus))
(define (editor text [line 0] [col 0] [top 0] [left 0] [height 17] [quit #f])
  `(AloemacsEditor new ,text (Position new ,line ,col) ,quit ,top ,left
     ,history (Option Some (Position new 0 1)) ,height))
(define (buffer id ed [name #f])
  `(AloemacsBuffer new ,ed ,(if name `(Option Some (Path new ,name)) no-path) ,id))
(define (zipper bs [focus 0])
  `(AloemacsBuffers new (List of ,@(reverse (take bs focus))) ,(list-ref bs focus)
     (List of ,@(drop bs (add1 focus)))))
(define (leaf id [bid 41] [top 0] [left 0] [lock #f])
  `(AloemacsWindowTree Leaf (AloemacsView new ,id ,bid ,top ,left ,lock (Option None))))
(define (right a b) `(AloemacsWindowTree Right ,a ,b))
(define (below a b) `(AloemacsWindowTree Below ,a ,b))
(define (windows tree selected [w 9] [h 6]) `(AloemacsWindows new ,tree ,selected ,w ,h))
(define (session bs tree [selected 7])
  `(AloemacsSession new ,bs (s fs) "" #f "query" (Position new 1 2) #t #t
     (List of "ring" "older") (s pending) (s prompt) (Option Some "prior")
     (Option Some (AloemacsCommand SaveAs)) ,(windows tree selected)))
(define (rebuild s #:buffers [bs `(,s buffers)] #:windows [ws `(,s windows)]
                 #:pending [pending `(,s pending)])
  `(AloemacsSession new ,bs (,s fs) (,s echo) (,s searching) (,s query) (,s origin)
     (,s wrapped) (,s failing) (,s kill-ring) ,pending (,s prompt)
     (,s last-submission) (,s waiting-command) ,ws))
(define (counted-fs)
  (define calls (box '()))
  (define disk (make-fs-double "/cwd"
    (hash "/cwd" 'directory "/cwd/a" 'file "/cwd/b" 'file "/cwd/dir" 'directory)
    (hash "/cwd/a" "abc\ndef" "/cwd/b" "bee")))
  (define (forward selector args)
    (set-box! calls (append (unbox calls) (list (cons selector args))))
    (host-receiver-send disk selector args))
  (define interface
    (make-host-interface 'FsHost
      (for/list ([m (in-list (host-interface-methods fs-interface))])
        (define selector (host-method-selector m))
        (define params (host-method-parameter-types m))
        (make-host-method selector params (host-method-return-type m)
          (case (length params)
            [(0) (lambda (_) (forward selector '()))]
            [(1) (lambda (_ a) (forward selector (list a)))]
            [(2) (lambda (_ a b) (forward selector (list a b)))])))))
  (values (make-host-receiver interface #f) calls))
(define (state)
  (define st (make-driver))
  (define-values (host calls) (counted-fs))
  (driver-inject-host! st 'fs-host host)
  (ev st `(load ,(path->string main-path)))
  (def! st 's 'aloemacs-editor)
  (values st calls))

;; Expected cells and chrome use only Racket and explicit fixture data.
;; Each leaf's name is supplied separately from the echo, including prompts.
(define (clip s w) (substring s 0 (min w (string-length s))))
(define (safe s)
  (list->string (for/list ([c (in-string s)])
    (if (or (< (char->integer c) 32) (= (char->integer c) 127)) #\space c))))
(define (mode name w)
  (define label (clip (string-append name " ") w))
  (safe (string-append label (make-string (- w (string-length label)) #\-))))
;; Name rows are bars: LIGHT on the selected view and the one-view frame,
;; DARK on every other split view. An empty row stays empty.
(define LIGHT "\e[38;5;16;48;5;250m")
(define DARK "\e[38;5;252;48;5;239m")
(define PLAIN "\e[0m")
(define (painted row selected?)
  (if (string=? row "") "" (string-append (if selected? LIGHT DARK) row PLAIN)))
(define (light row) (painted row #t))
(define (dark row) (painted row #f))
(define (visible row)
  (for/fold ([row row]) ([sequence (list LIGHT DARK PLAIN)]) (string-replace row sequence "")))
(define (cells lines w h top left name selected?)
  (append
    (for/list ([i (in-range top (+ top (if (>= h 2) (sub1 h) h)))])
      (define line (if (< i (length lines)) (list-ref lines i) ""))
      (define shown (safe (clip (substring line (min left (string-length line))) w)))
      (string-append shown (make-string (- w (string-length shown)) #\space)))
    (if (>= h 2) (list (painted (mode name w) selected?)) '())))
(define (side a b) (map (lambda (l r) (string-append l "|" r)) a b))
(define (cursor row col) (format "\e[~a;~aH" row col))
(define (multi lines row col w h echo)
  (string-append "\e[?25l\e[2J\e[H" (string-join lines "\r\n")
    (if (>= h 2) (string-append (cursor h 1) (safe (clip echo w))) "")
    (cursor row col) "\e[?25h"))
(define (single body row col w h name echo)
  (string-append "\e[?25l\e[2J\e[H" body (cursor row col) "\e[?25h"
    (if (< h 2) ""
        (string-append "\e[?25l"
          (if (>= h 3) (string-append (cursor (sub1 h) 1) (light (mode name w))) "")
          (cursor h 1) (safe (clip echo w)) (cursor row col) "\e[?25h"))))
(define (snapshot st s)
  (for/list ([expr (list s `(,s buffers) `((,s buffers) before)
      `((,s buffers) current-buffer) `((,s buffers) after)
      `((,s editor) text) `(,s windows))]) (ev st expr)))
(define (paint st s w h expected calls)
  (define before (snapshot st s))
  (define effects (unbox calls))
  (for ([i '(1 2)]) (check-equal? (ev st `(,s frame ,w ,h)) expected))
  (check-equal? (snapshot st s) before)
  (check-equal? (unbox calls) effects))
(define (rows! st s w h expected)
  (def! st 'painted `(((,s windows) tree) frame-rows (,s buffers)
                     (AloemacsWindowRect new 0 0 ,w ,h) ((,s windows) selected)))
  (same st 'painted `(List of ,@expected))
  (check-equal? (ev st '(painted len)) h)
  ;; Bars add only LIGHT/DARK/PLAIN, so every row's visible width is w.
  (same st '(painted map (fn (row) (row len))) `(List of ,@(map string-length expected)))
  (check-equal? (map (lambda (row) (string-length (visible row))) expected) (make-list h w)))

(test-case "distinct IDs/names, shared origins, clipped safe cells and dangling blank leaf"
  (define-values (st calls) (state))
  (define a-lines '("a\tbcdef" "ghijkl" "mnopqr"))
  (define b-lines '("ABCDE" "FGHIJ" "KLMNO"))
  (for ([w '(1 2 4 8)] [name '("/long-name" "a\eafter-clip" "a\u007fb\tfar" "-|+\u0000name")])
    (def! st 'a (buffer 41 (editor (indexed a-lines 1)) name))
    (def! st 'b (buffer 9 (editor (indexed b-lines 2) 2 4 99 99) name))
    (define t (right (leaf 7) (leaf 3 9 1 2 #t)))
    (def! st 'v (session (zipper '(b a) 1) t))
    (define expected (side (cells a-lines w 3 0 0 name #t) (cells b-lines w 3 1 2 name #f)))
    (rows! st 'v (+ (* 2 w) 1) 3 expected)
    (paint st 'v (+ (* 2 w) 1) 4 (multi expected 1 1 (+ (* 2 w) 1) 4 "") calls)
    (define far (right (leaf 7) (leaf 3 41 99 101 #t)))
    (def! st 'shared (rebuild 'v #:windows (windows far 7)))
    (define shared (side (cells a-lines w 3 0 0 name #t) (cells a-lines w 3 99 101 name #f)))
    (rows! st 'shared (+ (* 2 w) 1) 3 shared)
    (paint st 'shared (+ (* 2 w) 1) 4 (multi shared 1 1 (+ (* 2 w) 1) 4 "") calls)
    (def! st 'missing (rebuild 'v #:windows (windows (right (leaf 7) (leaf 3 999)) 7)))
    (define blanks (side (cells a-lines w 3 0 0 name #t) (make-list 3 (make-string w #\space))))
    (rows! st 'missing (+ (* 2 w) 1) 3 blanks)
    (paint st 'missing (+ (* 2 w) 1) 4 (multi blanks 1 1 (+ (* 2 w) 1) 4 "") calls))
  (check-equal? (unbox calls) '()))

(define a-lines '("abcdef" "ghijkl" "mnopqr" "stuvwx" "yz0123"))
(define b-lines '("ABCDE" "FGHIJ" "KLMNO" "PQRST" "UVWXY"))
(define mixed-tree (right (below (leaf 7) (leaf 3 41 3 1 #t)) (leaf 55 9 1 2)))
;; Below over five rows: view 7 takes three, view 3 the last two.
(define (mixed-rows selected)
  (define (bar id row) (painted row (= id selected)))
  (list "abcd|HIJ " "ghij|MNO " (string-append (bar 7 "/a -") "|RST ") "tuvw|WXY "
        (string-append (bar 3 "/a -") "|" (bar 55 "/b -"))))
(define (mixed! st)
  (def! st 'a (buffer 41 (editor (indexed a-lines 2) 3 2 3 1) "/a"))
  (def! st 'b (buffer 9 (editor (indexed b-lines 3) 3 4 1 2) "/b"))
  (def! st 'v (session (zipper '(a b)) mixed-tree 3)))

(test-case "exact mixed example, translated selection, T/cross and punctuation geometry"
  (define-values (st calls) (state))
  (mixed! st)
  (rows! st 'v 9 5 (mixed-rows 3))
  (paint st 'v 9 6 (multi (mixed-rows 3) 4 2 9 6 "") calls)
  (def! st 'r (session (zipper '(a b) 1) mixed-tree 55))
  (paint st 'r 9 6 (multi (mixed-rows 55) 3 8 9 6 "") calls)
  (def! st 'top-a (buffer 41 (editor (indexed a-lines 2) 0 2) "/a"))
  (def! st 'top (session (zipper '(top-a b)) mixed-tree 7))
  (paint st 'top 9 6 (multi (mixed-rows 7) 1 3 9 6 "") calls)
  (def! st 'a (buffer 41 (editor (indexed '("---" "|||" "+++"))) "-|+"))
  (define l (leaf 7)) (define r (leaf 3)) (define n (leaf 55)) (define m (leaf 8))
  (for ([t (list (right (below l r) n) (below (right l r) n)
                 (right (below l r) (below n m)) (below (right l r) (right n m)))]
        [expected (list (list "---|---" "|||||||" (string-append (light "-|+") "|+++") "---|   "
                              (string-append (dark "-|+") "|" (dark "-|+")))
                        (list "---|---" "|||||||" (string-append (light "-|+") "|" (dark "-|+"))
                              "---    " (dark "-|+ ---"))
                        (list "---|---" "|||||||" (string-append (light "-|+") "|" (dark "-|+"))
                              "---|---" (string-append (dark "-|+") "|" (dark "-|+")))
                        (list "---|---" "|||||||" (string-append (light "-|+") "|" (dark "-|+"))
                              "---|---" (string-append (dark "-|+") "|" (dark "-|+"))))])
    (def! st 'v (session (zipper '(a)) t))
    (rows! st 'v 7 5 expected)
    (paint st 'v 7 6 (multi expected 1 1 7 6 "") calls))
  (check-equal? (unbox calls) '()))

(test-case "both directions: odd/even, height two/one, tall-short and all-short frames"
  (define-values (st calls) (state))
  (def! st 'a (buffer 41 (editor (indexed '("abc" "def" "ghi"))) "/a"))
  (for ([extent '(3 4 5 6 7 8)] [early '(1 2 2 3 3 4)] [late '(1 1 2 2 3 3)]
        [upper '(2 2 3 3 4 4)] [lower '(1 2 2 3 3 4)])
    (def! st 'v (session (zipper '(a)) (right (leaf 7) (leaf 3))))
    (define side-rows (side (cells '("abc" "def" "ghi") early 2 0 0 "/a" #t)
                            (cells '("abc" "def" "ghi") late 2 0 0 "/a" #f)))
    (rows! st 'v extent 2 side-rows)
    (paint st 'v extent 3 (multi side-rows 1 1 extent 3 "") calls)
    ;; Below spends no row; its top takes the odd row.
    (def! st 'v (session (zipper '(a)) (below (leaf 7) (leaf 3))))
    (define stacked (append (cells '("abc" "def" "ghi") 7 upper 0 0 "/a" #t)
                            (cells '("abc" "def" "ghi") 7 lower 0 0 "/a" #f)))
    (rows! st 'v 7 extent stacked)
    (paint st 'v 7 (add1 extent) (multi stacked 1 1 7 (add1 extent) (if (>= upper 2) "" "/a")) calls))
  ;; A positive Below is all-short only at extent two: one text row each, no bars.
  (def! st 'v (session (zipper '(a)) (below (leaf 7) (leaf 3))))
  (define short-rows (append (cells '("abc" "def" "ghi") 7 1 0 0 "/a" #t)
                             (cells '("abc" "def" "ghi") 7 1 0 0 "/a" #f)))
  (rows! st 'v 7 2 short-rows)
  (paint st 'v 7 3 (multi short-rows 1 1 7 3 "/a") calls)
  (def! st 'v (session (zipper '(a)) (right (leaf 7) (leaf 3))))
  (def! st 'p '(v with-active-prompt (AloemacsPrompt new "P:" "x" 1 "" (List empty) (List empty) 0)))
  (for ([h '(1 2)])
    (def! st 'fit `(p ensure-visible 7 ,h))
    (check-equal? (ev st '((fit editor) text-rows)) 1)
    (paint st 'fit 7 h (multi '("abc|abc") (if (= h 1) 1 2)
                              (if (= h 1) 1 4) 7 h "P:x") calls))
  (check-equal? (unbox calls) '()))

(test-case "rich locked shared fit changes only selected origin/height and full size"
  (define-values (st calls) (state))
  (define text (indexed a-lines 2))
  (def! st 'a (buffer 41 (editor text 3 5 0 0 17 #t) "/a"))
  (def! st 'b (buffer 9 (editor (indexed b-lines 3) 3 4 99 101 13) "/b"))
  (define t (right (below (leaf 7 41 7 11 #t) (leaf 3 41 0 0 #t)) (leaf 55 9 99 101)))
  (def! st 'v (session (zipper '(b a) 1) t 3))
  (def! st 'v '(v with-search (v editor) #t "q\t" (v origin) #t #t))
  (def! st 'v (rebuild 'v #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (def! st 'v '(v with-active-prompt (AloemacsPrompt new "Ask:" "abc" 2 "" (List empty) (List empty) 0)))
  (define before (snapshot st 'v))
  (def! st 'fit '(v ensure-visible 9 6))
  (define fitted-tree (right (below (leaf 7 41 7 11 #t) (leaf 3 41 3 2 #t)) (leaf 55 9 99 101)))
  (same st 'fit (rebuild 'v #:buffers (zipper (list 'b (buffer 41 (editor text 3 5 3 2 1 #t) "/a")) 1)
                        #:windows (windows fitted-tree 3)))
  (same st '(fit ensure-visible 9 6) 'fit)
  (check-equal? (snapshot st 'v) before)
  (define fitted (snapshot st 'fit))
  (ev st '(fit frame 19 10))
  (check-equal? (snapshot st 'fit) fitted)
  (def! st 'far (rebuild 'v #:buffers (zipper (list 'b (buffer 41 (editor text 3 5 99 101 17 #t) "/a")) 1)))
  (def! st 'minimal '(far ensure-visible 9 6))
  (check-equal? (ev st '((minimal editor) scroll-row)) 3)
  (check-equal? (ev st '((minimal editor) scroll-col)) 5)
  (check-equal? (unbox calls) '()))

(test-case "page travel and subsequent fit at selected text heights one, two and three"
  (define-values (st calls) (state))
  (define lines (for/list ([i (in-range 12)]) (format "abcdef~a" i)))
  (define text (indexed lines 4))
  (for ([h '(4 8 10)] [height '(1 2 3)] [origin '(4 3 2)] [distance '(1 1 2)]
        [top-height '(2 4 5)] [leaf-height '(1 3 4)] [bottom-y '(2 4 5)])
    (def! st 'a (buffer 41 (editor text 4 5 0 0)))
    (define t (below (leaf 7 41 8 2 #t) (leaf 3)))
    (def! st 'v (session (zipper '(a)) t 3))
    (def! st 'fit `(v ensure-visible 4 ,h))
    (check-equal? (ev st '((fit editor) text-rows)) height)
    (check-equal? (ev st '((fit editor) page-distance)) distance)
    (check-equal? (ev st '((fit editor) scroll-row)) origin)
    (check-equal? (ev st '((fit editor) scroll-col)) 2)
    (check-equal? (ev st '((fit windows) columns)) 4)
    (check-equal? (ev st '((fit windows) rows)) h)
    (same st '(((fit windows) tree) find-view 7) '(Option Some (AloemacsView new 7 41 8 2 #t (Option None))))
    (define expected (append (cells lines 4 top-height 8 2 "untitled" #f)
                             (cells lines 4 leaf-height origin 2 "untitled" #t)))
    (rows! st 'fit 4 (sub1 h) expected)
    (paint st 'fit 4 h (multi expected (+ bottom-y (- 4 origin) 1) 4 4 h (if (>= leaf-height 2) "" "untitled")) calls)
    (for ([send '(page-up page-down)] [line (list (- 4 distance) (+ 4 distance))]
          [top (list (min origin (- 4 distance)) (+ origin distance))])
      (def! st 'moved `((fit ,send) ensure-visible 4 ,h))
      (check-equal? (ev st '((moved point) line)) line)
      (check-equal? (ev st '((moved editor) scroll-row)) top)
      (same st '((moved editor) history) history)
      (same st '((moved editor) mark) '(Option Some (Position new 0 1)))))
  (check-equal? (unbox calls) '()))

(test-case "per-view names during every echo token, search and visible prompt"
  (define-values (st calls) (state))
  (mixed! st)
  (for ([token '("" "saved" "failed")] [echo '("" "saved: /a" "failed: /a")])
    (def! st 'status `(v with-echo ,token))
    (paint st 'status 9 6 (multi (mixed-rows 3) 4 2 9 6 echo) calls)
    (for ([wrapped '(#f #t #t)] [failing '(#f #f #t)]
          [shown '("search: q " "wrapped: q " "failing: q ")])
      (def! st 'search `(status with-search (status editor) #t "q\t" (v origin) ,wrapped ,failing))
      (paint st 'search 9 6 (multi (mixed-rows 3) 4 2 9 6 shown) calls)
      (def! st 'p '(search with-active-prompt (AloemacsPrompt new "P\t" "x\ry" 2 "" (List empty) (List empty) 0)))
      (paint st 'p 9 6 (multi (mixed-rows 3) 6 5 9 6 "P x y") calls)
      (check-equal? (ev st '(p echo)) token)))
  (check-equal? (unbox calls) '()))

(test-case "global fallback with positive selected geometry; growth preserves locks/inactive origins"
  (define-values (st calls) (state))
  (def! st 'a (buffer 41 (editor (indexed a-lines 2) 3 2) "/a"))
  (define t (right (leaf 7 41 0 0 #t) (below (leaf 3 41 99 101 #t) (leaf 55 41 2 1 #t))))
  (def! st 'v (session (zipper '(a)) t))
  (for ([h '(1 4)] [top '(3 2)] [body '("stuvwx" "mnopqr\r\nstuvwx")])
    (def! st 'small `(v ensure-visible 2 ,h))
    (check-equal? (ev st '((small editor) scroll-row)) top)
    (same st '(((small windows) tree) find-view 3) '(Option Some (AloemacsView new 3 41 99 101 #t (Option None))))
    (same st '(((small windows) tree) find-view 55) '(Option Some (AloemacsView new 55 41 2 1 #t (Option None))))
    (define clipped-body (string-join (map (lambda (s) (substring s 1 3)) (string-split body "\r\n")) "\r\n"))
    (paint st 'small 2 h (single clipped-body (- 4 top) 2 2 h "/a" (if (>= h 3) "" "/a")) calls)
    (same st `(small frame 2 ,h) `(small single-frame 2 ,h)))
  ;; Left stays positive, but right's bottom leaf has zero height at root h=1.
  ;; A Below at root h=2 now gives one row to each child.
  (def! st 'small '(v ensure-visible 9 2))
  (paint st 'small 9 2 (single "stuvwx" 1 3 9 2 "/a" "/a") calls)
  (same st '(small frame 9 2) '(small single-frame 9 2))
  (def! st 'grown '(small ensure-visible 9 6))
  (define grown-rows (list "stuv|    " "yz01|    " (string-append "    |" (dark "/a -"))
                           "    |nopq" (string-append (light "/a -") "|" (dark "/a -"))))
  (paint st 'grown 9 6 (multi grown-rows 1 3 9 6 "") calls)
  (same st '((grown windows) tree)
    (right (leaf 7 41 3 0 #t) (below (leaf 3 41 99 101 #t) (leaf 55 41 2 1 #t))))
  (check-equal? (unbox calls) '()))

(test-case "real window/buffer operations derive next names with no redraw effects"
  (define-values (st calls) (state))
  ;; A real Below split fits the original once and captures its child's old
  ;; origin first. A below split needs four rows: it refuses at extent three,
  ;; and at extent four leaves two-row children that cannot split again.
  (define text (indexed a-lines 2))
  (def! st 'raw (session (zipper (list (buffer 41 (editor text 3 2 1 1) "/a")))
                        (leaf 7 41 1 1)))
  (def! st 'stacked '(raw split-below))
  (same st 'stacked (rebuild 'raw
    #:buffers (zipper (list (buffer 41 (editor text 3 2 2 1 2) "/a")))
    #:windows (windows (below (leaf 7 41 2 1) (leaf 8 41 1 1)) 7)))
  (paint st 'stacked 9 6
    (multi (list "nopqr    " "tuvwx    " (light "/a ------") "hijkl    " (dark "/a ------"))
           2 2 9 6 "") calls)
  (def! st 'three '(raw ensure-visible 9 4))
  (same st '(three split-below) '(three with-echo "failed"))
  (def! st 'short '(raw ensure-visible 9 5))
  (def! st 'minimum '(short split-below))
  (check-equal? (ev st '((minimum windows) selected)) 7)
  (check-equal? (ev st '((minimum editor) text-rows)) 1)
  (same st '(((minimum windows) tree) find-view 8) '(Option Some (AloemacsView new 8 41 1 1 #f (Option None))))
  (same st '(minimum split-below) '(minimum with-echo "failed"))
  (def! st 's '(s add-buffer "abc\ndef" (Path new "/a")))
  (def! st 's '(s ensure-visible 9 6))
  (def! st 'split '(s split-right))
  ;; The left view is selected until other-window; then the right one is.
  (define (ab left?) (side (cells '("abc" "def") 4 5 0 0 "/a" left?)
                           (cells '("abc" "def") 4 5 0 0 "/a" (not left?))))
  (paint st 'split 9 6 (multi (ab #t) 1 1 9 6 "") calls)
  (def! st 'locked '(split toggle-window-lock))
  (paint st 'locked 9 6 (multi (ab #t) 1 1 9 6 "") calls)
  (same st '(locked split-right) '(locked with-echo "failed"))
  (def! st 'other '(locked other-window))
  (check-equal? (ev st '((other editor) text-rows)) 4)
  (paint st 'other 9 6 (multi (ab #f) 1 6 9 6 "") calls)
  (def! st 'edited '(other insert "X"))
  (define changed (side (cells '("Xabc" "def") 4 5 0 0 "/a" #f) (cells '("Xabc" "def") 4 5 0 0 "/a" #t)))
  (paint st 'edited 9 6 (multi changed 1 7 9 6 "") calls)
  (same st '(edited undo) 'other)
  (def! st 'saved '(other save-as-submitted "a"))
  (define saved-rows (side (cells '("abc" "def") 4 5 0 0 "/cwd/a" #f) (cells '("abc" "def") 4 5 0 0 "/cwd/a" #t)))
  (paint st 'saved 9 6 (multi saved-rows 1 6 9 6 "saved: /cwd/a") calls)
  (def! st 'visited '((saved visit (Path new "b")) case (None () saved) (Some (v) v)))
  (define visited-rows (side (cells '("bee") 4 5 0 0 "/cwd/b" #f) (cells '("bee") 4 5 0 0 "/cwd/b" #t)))
  (paint st 'visited 9 6 (multi visited-rows 1 6 9 6 "") calls)
  (def! st 'found '(saved find-file-submitted "b"))
  (define found-rows (side (cells '("abc" "def") 4 5 0 0 "/cwd/a" #f) (cells '("bee") 4 5 0 0 "/cwd/b" #t)))
  (paint st 'found 9 6 (multi found-rows 1 6 9 6 "") calls)
  (def! st 'selected '(found select-buffer-submitted "/cwd/a"))
  (paint st 'selected 9 6 (multi saved-rows 1 6 9 6 "") calls)
  (def! st 'killed '(selected kill-buffer))
  (paint st 'killed 9 6 (multi visited-rows 1 6 9 6 "") calls)
  (def! st 'unlocked '((killed other-window) toggle-window-lock))
  (def! st 'deleted '(unlocked delete-window))
  (paint st 'deleted 9 6 (single "bee\r\n\r\n\r\n" 1 1 9 6 "/cwd/b" "") calls)
  (check-equal? (filter (lambda (c) (memq (car c) '(read write))) (unbox calls))
                '((write "/cwd/a" "abc\ndef") (read "/cwd/b") (read "/cwd/b")))
  (check-equal? (unbox calls)
    '((resolve "a") (kind "/cwd/a") (resolve "/cwd/a") (write "/cwd/a" "abc\ndef")
      (resolve "b") (kind "/cwd/b") (resolve "/cwd/b")
      (kind "/cwd/b") (resolve "/cwd/b") (read "/cwd/b")
      (resolve "b") (kind "/cwd/b") (resolve "/cwd/b")
      (kind "/cwd/b") (resolve "/cwd/b") (read "/cwd/b"))))

(test-case "production runner splits/selects/edits/saves/prompts/deletes/resizes and quits"
  (define keys '("ctrl-x" "3" "ctrl-x" "o" "X" "save" "ctrl-x" "find" "b" "return" "ctrl-x" "0" "escape"))
  (define sizes (for/list ([i (in-range (length keys))]) (if (= i 6) '(2 4) '(9 6))))
  (define initial (single "abc\r\ndef\r\n\r\n" 1 1 9 6 "/cwd/a" ""))
  ;; The left view is selected until other-window; then the right one is.
  (define (ab left?) (side (cells '("abc" "def") 4 5 0 0 "/cwd/a" left?)
                           (cells '("abc" "def") 4 5 0 0 "/cwd/a" (not left?))))
  (define changed (side (cells '("Xabc" "def") 4 5 0 0 "/cwd/a" #f) (cells '("Xabc" "def") 4 5 0 0 "/cwd/a" #t)))
  (define found (side (cells '("Xabc" "def") 4 5 0 0 "/cwd/a" #f) (cells '("bee") 4 5 0 0 "/cwd/b" #t)))
  (define frames
    (list initial initial (multi (ab #t) 1 1 9 6 "") (multi (ab #t) 1 1 9 6 "")
          (multi (ab #f) 1 6 9 6 "") (multi changed 1 7 9 6 "")
          (single "Xa\r\nde" 1 2 2 4 "/cwd/a" "saved: /cwd/a")
          (multi changed 1 7 9 6 "")
          (multi changed 6 9 9 6 "Find file: /cwd/") (multi changed 6 9 9 6 "Find file: /cwd/b")
          (multi found 1 6 9 6 "") (multi found 1 6 9 6 "")
          (single "Xabc\r\ndef\r\n\r\n" 1 2 9 6 "/cwd/a" "")))
  (define events '())
  (define remaining keys)
  (define n 0)
  (define (record! x) (set! events (append events (list x))))
  (define out (make-output-port 'mode-line-splits always-evt
    (lambda (bytes start end _non-block? _breakable?)
      (record! (if (= start end) 'flush (list 'write (bytes->string/utf-8 (subbytes bytes start end)))))
      (- end start)) void))
  (define term (make-term-receiver out
    (lambda () (define key (car remaining)) (set! remaining (cdr remaining))
      (record! (list 'key key)) key)
    (lambda ()
      (define size (list-ref sizes (quotient n 2)))
      (record! (list (if (even? n) 'columns 'rows) (if (even? n) (car size) (cadr size))))
      (set! n (add1 n)) (values (car size) (cadr size)))))
  (define-values (host calls) (counted-fs))
  (run-aloemacs-with-hosts term host "a")
  (check-equal? remaining '())
  (check-equal? n (* 2 (length keys)))
  (check-equal? events (append-map (lambda (size key frame)
    (list (list 'columns (car size)) (list 'rows (cadr size)) (list 'write frame) 'flush (list 'key key)))
    sizes keys frames))
  (check-equal? (filter (lambda (c) (memq (car c) '(read write))) (unbox calls))
                '((read "/cwd/a") (write "/cwd/a" "Xabc\ndef") (read "/cwd/b")))
  (check-equal? (unbox calls)
    '((resolve "a") (resolve "/cwd/a") (kind "/cwd/a") (resolve "/cwd/a")
      (kind "/cwd/a") (resolve "/cwd/a") (read "/cwd/a")
      (kind "/cwd/a") (resolve "/cwd/a") (write "/cwd/a" "Xabc\ndef")
      (root? "/cwd/a") (parent "/cwd/a")
      (resolve "/cwd/b") (kind "/cwd/b") (resolve "/cwd/b")
      (kind "/cwd/b") (resolve "/cwd/b") (read "/cwd/b"))))
