#lang racket/base

(require racket/string racket/list racket/port racket/runtime-path rackunit
         "../../aloe/driver.rkt" "../../aloe/host.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/type.rkt" exn:fail:aloe-type? type-of type->datum)
         "../../host/racket/fs.rkt" "../../host/racket/aloemacs-run.rkt")

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define-runtime-path editor-path "../../examples/aloemacs/editor.aloe")
(define no-mark '(if #t (Option None) (Option Some (Position new 0 0))))
(define no-path '(if #t (Option None) (Option Some (Path new "/typed-none"))))
(define no-pending '(if #t (Option None) (Option Some aloemacs-global-keymap)))
(define no-prompt '(if #t (Option None) (Option Some (AloemacsPrompt new "" "" 0 "" (List empty) (List empty) 0))))
(define no-submission '(if #t (Option None) (Option Some "")))
(define no-command '(if #t (Option None) (Option Some (AloemacsCommand FindFile))))
(define waiting '(Option Some (AloemacsCommand SaveAs)))
(define (prompt text [column (string-length text)] [label "Save as: "])
  `(Option Some (AloemacsPrompt new ,label ,text ,column "" (List empty) (List empty) 0)))
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (type st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))

;; Count every crossing, including thin Fs's preflight resolves. Disk probes
;; made by the proof itself bypass this receiver and never enter the log.
(define (counted-fs #:host-name [host-name 'FsHost] #:fail [fail #f])
  (define disk
    (make-fs-double "/cwd"
      (hash "/cwd" 'directory "/cwd/a.txt" 'file "/cwd/b.txt" 'file
            "/cwd/dir" 'directory "/cwd/link" 'symlink "/cwd/pipe" "fifo")
      (hash "/cwd/a.txt" "disk a" "/cwd/b.txt" "disk b")))
  (define calls (box '()))
  (define (forward selector args)
    (set-box! calls (cons (cons selector args) (unbox calls)))
    (when (eq? selector fail) (error 'save-as-test "host failure"))
    (host-receiver-send disk selector args))
  (define interface
    (make-host-interface host-name
      (for/list ([method (in-list (host-interface-methods fs-interface))])
        (define selector (host-method-selector method))
        (define params (host-method-parameter-types method))
        (make-host-method selector params (host-method-return-type method)
          (case (length params)
            [(0) (lambda (state) (forward selector '()))]
            [(1) (lambda (state a) (forward selector (list a)))]
            [(2) (lambda (state a b) (forward selector (list a b)))])))))
  (values (make-host-receiver interface #f) calls disk))
(define (state #:host-name [host-name 'FsHost] #:fail [fail #f])
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  (define-values (host calls disk) (counted-fs #:host-name host-name #:fail fail))
  (driver-inject-host! st 'fs-host host)
  (values st calls disk))
(define (all-calls calls) (reverse (unbox calls)))
(define (effects calls selector)
  (filter (lambda (call) (eq? (car call) selector)) (all-calls calls)))
(define (write-calls typed resolved contents #:parent [parent #f] #:write? [write? #t])
  (append (list (list 'resolve typed) (list 'kind resolved) (list 'resolve resolved))
    (if parent
        (list (list 'root? resolved) (list 'parent resolved)
              (list 'kind parent) (list 'resolve parent)) '())
    (if write? (list (list 'write resolved contents)) '())))
(define (editor contents)
  `(AloemacsEditor new ((Text from-string ,contents) indexed-value)
     (Position new 0 0) #f 0 0 (List empty) ,no-mark 0))
(define (buffer contents [path no-path] [id 0]) `(AloemacsBuffer new ,(editor contents) ,path ,id))
(define (bound contents name [id 0]) (buffer contents `(Option Some (Path new ,name)) id))
(define (zipper order focus)
  `(AloemacsBuffers new (List of ,@(reverse (take order focus)))
     ,(list-ref order focus) (List of ,@(drop order (add1 focus)))))
(define (session buffers)
  `(AloemacsSession new ,buffers (Fs new fs-host) "saved" #f "old query"
     (Position new 4 2) #t #t (List of "newest" "older")
     ,no-pending ,no-prompt ,no-submission ,no-command
     (let ((buffer (,buffers current-buffer)))
       (AloemacsWindows new
         (AloemacsWindowTree Leaf
           (AloemacsView new 0 (buffer id)
             ((buffer editor) scroll-row) ((buffer editor) scroll-col) #f))
         0 0 0))))
;; Independent expected values use only constructors and reads. In particular,
;; they never send with-path, with-current-path, or save-as-submitted.
(define (rebuild s #:buffers [buffers `(,s buffers)] #:echo [echo `(,s echo)]
                 #:searching [searching `(,s searching)] #:query [query `(,s query)]
                 #:origin [origin `(,s origin)] #:wrapped [wrapped `(,s wrapped)]
                 #:failing [failing `(,s failing)] #:ring [ring `(,s kill-ring)]
                 #:pending [pending `(,s pending)] #:prompt [line `(,s prompt)]
                 #:submission [submission `(,s last-submission)]
                 #:waiting [command `(,s waiting-command)]
                 #:columns [columns `((,s windows) columns)]
                 #:rows [rows `((,s windows) rows)])
  `(AloemacsSession new ,buffers (,s fs) ,echo ,searching ,query ,origin
     ,wrapped ,failing ,ring ,pending ,line ,submission ,command
     (let ((buffer (,buffers current-buffer)))
       (AloemacsWindows new
         (AloemacsWindowTree Leaf
           (AloemacsView new 0 (buffer id)
             ((buffer editor) scroll-row) ((buffer editor) scroll-col) #f))
         0 ,columns ,rows))))
(define (replace-current s new-editor [path `(,s path)])
  `(AloemacsBuffers new ((,s buffers) before)
     (AloemacsBuffer new ,new-editor ,path ((,s current-buffer) id)) ((,s buffers) after)))
(define (rebound s resolved)
  (replace-current s `(,s editor) `(Option Some (Path new ,resolved))))
(define (completed s submitted #:echo [echo "saved"] #:buffers [buffers `(,s buffers)])
  (rebuild s #:buffers buffers #:echo echo #:prompt no-prompt
    #:submission `(Option Some ,submitted) #:waiting no-command))
(define (selected s buffers)
  (rebuild s #:buffers buffers #:echo "" #:searching #f #:query ""
    #:origin '(Position new 0 0) #:wrapped #f #:failing #f #:pending no-pending))
(define (rich! st [path '(Option Some (Path new "/cwd/b.txt"))])
  (def! st 'rich-editor
    '(AloemacsEditor new
       (Text indexed (List of "second" "first") "third-long" (List of "fourth" "fifth") 2)
       (Position new 2 4) #f 2 3
       (List of (UndoFrame new (Text from-string "old b") (Position new 0 2) 1 2))
       (Option Some (Position new 1 1)) 4))
  (def! st 'a
    `(AloemacsBuffer new
       (AloemacsEditor new (Text from-string "unsaved neighbor a") (Position new 0 3)
         #f 1 2 (rich-editor history) (Option Some (Position new 0 1)) 5)
       (Option Some (Path new "/cwd/a.txt")) 0))
  (def! st 'b `(AloemacsBuffer new rich-editor ,path 1))
  (def! st 'c
    '(AloemacsBuffer new
       (AloemacsEditor new (Text indexed (List of "c first") "c second" (List empty) 1)
         (Position new 1 2) #f 1 1 (rich-editor history)
         (Option Some (Position new 0 1)) 3)
       (if #t (Option None) (Option Some (Path new "/typed-none"))) 2))
  (def! st 'source (session (zipper '(a b c) 1))))
(define (draft! st [text "new.txt"])
  (def! st 'draft (rebuild 'source #:prompt (prompt text)
    #:submission '(Option Some "previous") #:waiting waiting)))
(define rich-text "first\nsecond\nthird-long\nfourth\nfifth")
(define (datums path) (call-with-input-file path (lambda (in) (port->list read in))))
(define (declaration ds name) (findf (lambda (d) (equal? (cadr d) name)) ds))

(define (editor-frame body row column)
  (string-append "\u001b[?25l\u001b[2J\u001b[H" body
    (format "\u001b[~a;~aH\u001b[?25h" row column)))
;; Independent name and text allocation from the supplied fixture and size.
(define (mode-row name width)
  (define label (substring (string-append name " ") 0
                          (min width (add1 (string-length name)))))
  (list->string
    (for/list ([c (in-string (string-append label
                              (make-string (- width (string-length label)) #\-)))])
      (if (or (< (char->integer c) 32) (= (char->integer c) 127)) #\space c))))
(define (text-body body rows)
  (define lines (string-split body "\r\n" #:trim? #f))
  (string-join (take lines (min (length lines) (if (>= rows 3) (- rows 2) 1))) "\r\n"))
(define (frame body row column rows shown cursor-row cursor-column #:name [name "untitled"] #:width [width 0])
  (string-append "\e[?25l\e[2J\e[H"
    (if rows (text-body body rows) body)
    (format "\e[~a;~aH\e[?25h" row column)
    (if (and rows (>= rows 2))
        (string-append "\e[?25l"
          (if (>= rows 3) (format "\e[~a;1H~a" (sub1 rows) (mode-row name width)) "")
          (format "\e[~a;1H~a\e[~a;~aH\e[?25h" rows shown cursor-row cursor-column)) "")))
(define (runner-frame text column label [prompt-column #f] [columns 20] [rows 3]
                      #:name [name "untitled"])
  (define shown
    (if (and (>= rows 3) (not prompt-column) (equal? label name)) ""
        (substring label 0 (min columns (string-length label)))))
  (if (= rows 1) (editor-frame text 1 column)
      (frame (string-append text "\r\n") 1 column rows shown
        (if prompt-column rows 1) (or prompt-column column) #:name name #:width columns)))

(test-case "SaveAs, pure helper signatures, unchanged shapes and exact production maps"
  (define ds (datums file-path))
  (define methods (cdr (cadddr (declaration ds '(AloemacsSession H)))))
  (for ([signature '((with-current-path (path Path) (AloemacsSession H))
                     (save-as-submitted (submitted String) (AloemacsSession H)))])
    (check-equal? (drop-right (assoc (car signature) methods) 1) signature))
  (check-equal? (drop-right (assoc 'with-path
    (cdr (cadddr (declaration ds 'AloemacsBuffer)))) 1)
    '(with-path (path Path) AloemacsBuffer))
  (check-equal? (caddr (declaration ds '(AloemacsSession H)))
    '(fields (buffers AloemacsBuffers) (fs (Fs H)) (echo String) (searching Bool)
       (query String) (origin Position) (wrapped Bool) (failing Bool)
       (kill-ring (List String)) (pending (Option (AloemacsKeymap AloemacsBinding)))
       (prompt (Option AloemacsPrompt)) (last-submission (Option String))
       (waiting-command (Option AloemacsCommand)) (windows AloemacsWindows)))
  (define es (datums editor-path))
  (check-equal? (caddr (declaration es 'AloemacsEditor))
    '(fields (text Text) (point Position) (quit Bool) (scroll-row Int) (scroll-col Int)
       (history (List UndoFrame)) (mark (Option Position)) (text-rows Int)))
  (check-equal? (caddr (declaration es 'UndoFrame))
    '(fields (text Text) (point Position) (scroll-row Int) (scroll-col Int)))
  (check-equal? (caddr (declaration ds 'AloemacsCommand))
    '(constructors (Newline (fields)) (BackwardDelete (fields)) (MoveLeft (fields))
       (MoveRight (fields)) (MoveUp (fields)) (MoveDown (fields)) (LineStart (fields))
       (LineEnd (fields)) (PageUp (fields)) (PageDown (fields)) (BufferStart (fields))
       (BufferEnd (fields)) (RequestQuit (fields)) (Undo (fields)) (SetMark (fields))
       (Kill (fields)) (KillLine (fields)) (Yank (fields)) (Find (fields)) (Save (fields))
       (SelfInsert (fields)) (SwitchBuffer (fields)) (KillBuffer (fields))
       (FindFile (fields)) (SaveAs (fields)) (SelectBuffer (fields))
       (SplitBelow (fields)) (SplitRight (fields))
       (DeleteWindow (fields)) (OtherWindow (fields)) (ToggleWindowLock (fields))))
  (check-equal? (map (lambda (m) (drop-right m 1))
    (cdr (cadddr (declaration ds 'AloemacsCommand)))) '((name () String)))
  (define-values (st calls disk) (state))
  (same st '(aloemacs-ctrl-x-keymap bindings)
    '(List of (AloemacsBinding Command "save" aloemacs-save-command)
              (AloemacsBinding Command "find" (AloemacsCommand FindFile))
              (AloemacsBinding Command "kill" (AloemacsCommand SaveAs))
              (AloemacsBinding Command "b" (AloemacsCommand SelectBuffer))
              (AloemacsBinding Command "2" (AloemacsCommand SplitBelow))
              (AloemacsBinding Command "3" (AloemacsCommand SplitRight))
              (AloemacsBinding Command "0" (AloemacsCommand DeleteWindow))
              (AloemacsBinding Command "o" (AloemacsCommand OtherWindow))
              (AloemacsBinding Command "l" (AloemacsCommand ToggleWindowLock))))
  (check-false (ev st '((aloemacs-ctrl-x-keymap default) present?)))
  (define global-rows
    '(("return" Newline) ("backspace" BackwardDelete) ("left" MoveLeft) ("right" MoveRight)
      ("up" MoveUp) ("down" MoveDown) ("line-start" LineStart) ("line-end" LineEnd)
      ("page-up" PageUp) ("page-down" PageDown) ("buffer-start" BufferStart)
      ("buffer-end" BufferEnd) ("escape" RequestQuit) ("undo" Undo) ("mark" SetMark)
      ("kill" Kill) ("kill-line" KillLine) ("yank" Yank) ("find" Find) ("save" Save)))
  (same st '(aloemacs-global-keymap bindings)
    `(List of ,@(for/list ([row global-rows])
      `(AloemacsBinding Command ,(car row) (AloemacsCommand ,(cadr row))))
      (AloemacsBinding Prefix "ctrl-x" aloemacs-ctrl-x-keymap)))
  (same st '(aloemacs-global-keymap default) '(Option Some (AloemacsCommand SelfInsert)))
  (check-equal? (ev st '((AloemacsCommand Kill) name)) "kill")
  (check-equal? (unbox calls) '()))

(test-case "checked construction and helpers retain both concrete hosts and reject wrong sends"
  (for ([host-name '(FsHost AlternateFsHost)])
    (define-values (st calls disk) (state #:host-name host-name))
    (rich! st)
    (def! st 'command '(AloemacsCommand SaveAs))
    (check-equal? (type st 'command) 'AloemacsCommand)
    (check-equal? (ev st '(command name)) "save-as")
    (check-equal? (type st '((source current-buffer) with-path (Path new "relative"))) 'AloemacsBuffer)
    (for ([send '((source with-current-path (Path new "relative"))
                  (source save-as-submitted "") (source execute-command command "ignored")
                  (source start-command-prompt command "Save as: ")
                  (source run-submitted-command) (source submit-prompt))])
      (check-equal? (type st send) `(AloemacsSession ,host-name)))
    (for ([bad '((AloemacsCommand SaveAs 0) (AloemacsCommand SaveAs "x") (command name 0)
                 (command execute-command "x")
                 ((source current-buffer) with-path) ((source current-buffer) with-path "x")
                 ((source current-buffer) with-path (Option Some (Path new "x")))
                 ((source current-buffer) with-path (if #t (Option None) (Option Some (Path new "x"))))
                 ((source current-buffer) with-path (Path new "x") 0)
                 (source with-current-path) (source with-current-path "x")
                 (source with-current-path (Option Some (Path new "x")))
                 (source with-current-path (if #t (Option None) (Option Some (Path new "x"))))
                 (source with-current-path (Path new "x") 0)
                 (source save-as-submitted) (source save-as-submitted (Path new "x"))
                 (source save-as-submitted "x" "y"))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st bad)) (format "reject ~s" bad)))
    (for* ([receiver '(1 "x" command AloemacsSession AloemacsBuffer)]
           [tail '((with-path (Path new "x")) (with-current-path (Path new "x"))
                   (save-as-submitted "x"))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st `(,receiver ,@tail)))))
    (check-exn exn:fail:aloe-type? (lambda () (ev st '((source editor) with-path (Path new "x")))))
    (define valid (session '(source buffers)))
    (for ([bad (list (drop-right valid 1) (append valid '(0)))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
    (check-equal? (unbox calls) '())))

(test-case "direct and chord starts, four whole-session guards, orphan replacement and plain keys"
  (define-values (st calls disk) (state))
  (rich! st)
  (define before (ev st 'source))
  (same st '(source execute-command (AloemacsCommand SaveAs) "/ignored/path")
    (rebuild 'source #:prompt (prompt "/cwd/b.txt") #:waiting waiting))
  (def! st 'armed '(source handle-key "ctrl-x"))
  (same st '(armed handle-key "kill")
    (rebuild 'source #:echo "" #:prompt (prompt "/cwd/b.txt") #:waiting waiting))
  (for ([fixture (list
                   (rebuild 'source #:buffers (replace-current 'source '(rich-editor request-quit)))
                   (rebuild 'source #:searching #t)
                   (rebuild 'source #:pending '(Option Some aloemacs-ctrl-x-keymap))
                   (rebuild 'source #:prompt (prompt "old" 2 "Old: ")))])
    (def! st 'guarded fixture)
    (def! st 'guarded (rebuild 'guarded #:waiting '(Option Some (AloemacsCommand FindFile))
                                        #:submission '(Option Some "old answer")))
    (same st '(guarded execute-command (AloemacsCommand SaveAs) "ignored") 'guarded)
    (same st '(guarded start-command-prompt (AloemacsCommand SaveAs) "Save as: ") 'guarded))
  (def! st 'orphan (rebuild 'source #:waiting '(Option Some (AloemacsCommand FindFile))))
  (same st '(orphan execute-command (AloemacsCommand SaveAs) "ignored")
    (rebuild 'orphan #:prompt (prompt "/cwd/b.txt") #:waiting waiting))
  (same st '(armed handle-key "b")
    (rebuild 'source #:echo "" #:prompt (prompt "" 0 "Buffer: ")
      #:waiting '(Option Some (AloemacsCommand SelectBuffer))))
  (for ([key '("escape" "x" "s" "left" "undo" "return" "mark" "unknown" "" "ctrl-x" "kill-line" "yank")])
    (same st `(armed handle-key ,key) (rebuild 'source #:echo "")))
  (def! st 'killed '(source handle-key "kill"))
  (check-equal? (ev st '((killed text) to-string)) "first\nsd-long\nfourth\nfifth")
  (same st '(killed kill-ring) '(List of "econd\nthir" "newest" "older"))
  (same st '(source handle-key "b")
    (rebuild 'source #:echo "" #:buffers (replace-current 'source '(rich-editor insert "b"))))
  (check-equal? (ev st 'source) before)
  (check-equal? (unbox calls) '()))

(test-case "prompt editing, ignored keys, fit and repeated frame retain SaveAs without I/O"
  (define-values (st calls disk) (state))
  (rich! st)
  (draft! st "abc")
  (define before (ev st 'draft))
  (for ([row '(("X" "abcX" 4) ("backspace" "ab" 2) ("left" "abc" 2)
               ("right" "abc" 3) ("line-start" "abc" 0) ("line-end" "abc" 3))])
    (same st `(draft handle-key ,(car row)) (rebuild 'draft #:prompt (prompt (cadr row) (caddr row)))))
  (for ([key '("\n" "save" "find" "ctrl-x" "kill" "kill-line" "yank" "up" "down" "unknown")])
    (same st `(draft handle-key ,key) 'draft))
  (same st '(draft ensure-visible 2 2)
    (rebuild 'draft #:columns 2 #:rows 2 #:buffers (replace-current 'draft
      '(AloemacsEditor new (draft text) (draft point) #f 2 3
         (rich-editor history) (rich-editor mark) 1))))
  (for ([i (in-range 2)]) (check-equal? (ev st '(draft frame 12 3))
    (frame "rd-long\r\nrth" 1 2 3 "Save as: abc" 3 12 #:name "/cwd/b.txt" #:width 12)))
  (check-equal? (ev st 'draft) before)
  (check-equal? (unbox calls) '()))

(test-case "path helpers independently retain exact editors and all raw protocol/search/prefix fields"
  (define-values (st calls disk) (state))
  (rich! st)
  (draft! st)
  (def! st 'raw (rebuild 'draft #:searching #t
    #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (define before (ev st 'raw))
  (for ([s '(source raw (raw request-quit))])
    (def! st 's s)
    (def! st 'changed-buffer '((s current-buffer) with-path (Path new "./relative/../new")))
    (same st 'changed-buffer '(AloemacsBuffer new (s editor) (Option Some (Path new "./relative/../new")) ((s current-buffer) id)))
    (same st '(changed-buffer editor) '(s editor))
    (check-equal? (ev st '(changed-buffer name)) "./relative/../new")
    (same st '(s with-current-path (Path new "./relative/../new"))
      (rebuild 's #:buffers (rebound 's "./relative/../new"))))
  (check-equal? (ev st 'raw) before)
  (check-equal? (unbox calls) '()))

(test-case "submitted helper changes only binding/echo even with raw active search, prompt and prefix"
  (define-values (st calls disk) (state))
  (rich! st)
  (draft! st)
  (def! st 'raw (rebuild 'draft #:searching #t #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (define before (ev st 'raw))
  (same st '(raw save-as-submitted "") (rebuild 'raw #:echo "failed"))
  (check-equal? (unbox calls) '())
  (same st '(raw save-as-submitted "a.txt")
    (rebuild 'raw #:buffers (rebound 'raw "/cwd/a.txt") #:echo "saved"))
  (check-equal? (all-calls calls) (write-calls "a.txt" "/cwd/a.txt" rich-text))
  (set-box! calls '())
  (same st '(raw save-as-submitted "dir") (rebuild 'raw #:echo "failed"))
  (check-equal? (all-calls calls) (write-calls "dir" "/cwd/dir" rich-text #:write? #f))
  (check-equal? (ev st 'raw) before))

(test-case "untitled/bound rich buffers write missing/existing relative destinations without editor replacement"
  (for* ([path (list no-path '(Option Some (Path new "/cwd/b.txt")))]
         [input '("./dir/../a.txt" "new.txt")])
    (define-values (st calls disk) (state))
    (rich! st path)
    (draft! st input)
    (define old-session (ev st 'draft))
    (define old-editor (ev st '(draft editor)))
    (define resolved (if (equal? input "new.txt") "/cwd/new.txt" "/cwd/a.txt"))
    (def! st 'done '(draft handle-key "return"))
    (same st 'done (completed 'draft input #:buffers (rebound 'draft resolved)))
    (check-equal? (ev st '(done editor)) old-editor)
    (check-equal? (ev st '((done current-buffer) name)) resolved)
    (check-equal? (all-calls calls) (write-calls input resolved rich-text
      #:parent (and (equal? input "new.txt") "/cwd")))
    (check-equal? (host-receiver-send disk 'read (list resolved)) rich-text)
    (check-equal? (ev st 'draft) old-session)))

(test-case "exact CRLF, BOM, Unicode, final newline and edited text survive writes"
  (for ([contents '("one\ntwo\n" "one\ntwo" "one\r\ntwo\r\n" "lone\rCR" "\uFEFFλ\n" "")])
    (define-values (st calls disk) (state))
    (rich! st no-path)
    (def! st 'source (rebuild 'source #:buffers (replace-current 'source (editor contents))))
    (draft! st "  ")
    (def! st 'done '(draft submit-prompt))
    (same st 'done (completed 'draft "  " #:buffers (rebound 'draft "/cwd/  ")))
    (check-equal? (all-calls calls) (write-calls "  " "/cwd/  " contents #:parent "/cwd"))
    (check-equal? (host-receiver-send disk 'read '("/cwd/  ")) contents))
  (define-values (st calls disk) (state))
  (rich! st)
  (def! st 'source (session (zipper (list (buffer "ab")) 0)))
  (def! st 'source '(((source handle-key "x") handle-key "return") handle-key "λ"))
  (check-equal? (ev st '((source text) to-string)) "x\nλab")
  (draft! st "new.txt")
  (def! st 'done '(draft submit-prompt))
  (same st 'done (completed 'draft "new.txt" #:buffers (rebound 'draft "/cwd/new.txt")))
  (check-equal? (all-calls calls) (write-calls "new.txt" "/cwd/new.txt" "x\nλab" #:parent "/cwd")))

(test-case "same-path writes repeat only on new submissions; inactive Return keeps its editing meaning"
  (define-values (st calls disk) (state))
  (rich! st)
  (draft! st "b.txt")
  (def! st 'done '(draft submit-prompt))
  (same st 'done (completed 'draft "b.txt" #:buffers (rebound 'draft "/cwd/b.txt")))
  (same st '(done submit-prompt) 'done)
  (check-equal? (all-calls calls) (write-calls "b.txt" "/cwd/b.txt" rich-text))
  (set-box! calls '())
  (same st '(done handle-key "return")
    (rebuild 'done #:echo "" #:buffers (replace-current 'done '((done editor) newline))))
  (check-equal? (unbox calls) '())
  (def! st 'next '(done execute-command (AloemacsCommand SaveAs) "ignored"))
  (def! st 'next (rebuild 'next #:prompt (prompt "b.txt")))
  (def! st 'again '(next submit-prompt))
  (same st 'again (completed 'next "b.txt" #:buffers (rebound 'next "/cwd/b.txt")))
  (check-equal? (all-calls calls) (write-calls "b.txt" "/cwd/b.txt" rich-text)))

(test-case "neighbor path overwrite allows duplicates, retains unsaved neighbor, then ordinary saves use new path"
  (define-values (st calls disk) (state))
  (rich! st)
  (draft! st "a.txt")
  (define neighbor (ev st 'a))
  (define source (ev st 'draft))
  (def! st 'done '(draft submit-prompt))
  (same st 'done (completed 'draft "a.txt" #:buffers (rebound 'draft "/cwd/a.txt")))
  (check-equal? (ev st '(((done buffers) before) first)) neighbor)
  (check-equal? (host-receiver-send disk 'read '("/cwd/a.txt")) rich-text)
  (check-equal? (host-receiver-send disk 'read '("/cwd/b.txt")) "disk b")
  (same st '(done editor) 'rich-editor)
  (def! st 'edited '(done handle-key "!"))
  (set-box! calls '())
  (same st '(edited handle-key "save") (rebuild 'edited #:echo "saved"))
  (same st '((edited handle-key "ctrl-x") handle-key "save") (rebuild 'edited #:echo "saved"))
  (define edited-text "first\nsecond\nthir!d-long\nfourth\nfifth")
  (check-equal? (all-calls calls)
    (append-map (lambda (i) (list '(kind "/cwd/a.txt") '(resolve "/cwd/a.txt")
                                 (list 'write "/cwd/a.txt" edited-text))) '(1 2)))
  (check-equal? (ev st 'a) neighbor)
  (check-equal? (ev st 'draft) source))

(test-case "completion writes the buffer current at Return after direct selection"
  (define-values (st calls disk) (state))
  (rich! st)
  (draft! st "new.txt")
  (def! st 'switched '(draft switch-buffer))
  (same st 'switched (selected 'draft (zipper '(a b c) 2)))
  (check-equal? (unbox calls) '())
  (def! st 'done '(switched submit-prompt))
  (same st 'done (completed 'switched "new.txt" #:buffers (rebound 'switched "/cwd/new.txt")))
  (same st '((done buffers) before) '(List of b a))
  (check-equal? (all-calls calls) (write-calls "new.txt" "/cwd/new.txt" "c first\nc second" #:parent "/cwd")))

(test-case "empty input, all thin refusals and cancellation preserve exact buffers and prior tokens"
  (for ([input '("" "absent/new" "a.txt/new" "link/new" "pipe/new" "dir" "link" "pipe" "/")])
    (define-values (st calls disk) (state))
    (rich! st)
    (draft! st input)
    (define before (ev st 'draft))
    (def! st 'done '(draft submit-prompt))
    (same st 'done (completed 'draft input #:echo "failed"))
    (check-equal? (effects calls 'write) '())
    (check-equal? (effects calls 'read) '())
    (cond
      [(equal? input "") (check-equal? (unbox calls) '())]
      [(equal? input "/")
       (check-equal? (all-calls calls) '((resolve "/") (kind "/") (resolve "/") (root? "/")))]
      [else
       (define resolved (string-append "/cwd/" input))
       (define parent (cond [(equal? input "absent/new") "/cwd/absent"]
                            [(equal? input "a.txt/new") "/cwd/a.txt"]
                            [(equal? input "link/new") "/cwd/link"]
                            [(equal? input "pipe/new") "/cwd/pipe"] [else #f]))
       (check-equal? (all-calls calls) (write-calls input resolved rich-text #:parent parent #:write? #f))])
    (check-equal? (ev st 'draft) before)
    (set-box! calls '())
    ;; Cancel a later prompt after a failed submission; echo and answer survive.
    (def! st 'later '(done execute-command (AloemacsCommand SaveAs) "ignored"))
    (same st '(later handle-key "escape") (rebuild 'later #:prompt no-prompt #:waiting no-command))
    (check-equal? (unbox calls) '()))
  (define-values (st calls disk) (state))
  (rich! st)
  (for* ([token '("" "saved" "failed")]
         [answer (list no-submission '(Option Some "previous"))])
    (def! st 'source (rebuild 'source #:echo token #:submission answer))
    (def! st 'active '(source execute-command (AloemacsCommand SaveAs) "ignored"))
    (for ([cancel '((active handle-key "escape") (active cancel-prompt))])
      (same st cancel 'source))
    (def! st 'orphan (rebuild 'source #:waiting waiting))
    (same st '(orphan submit-prompt) 'orphan)
    (same st '(orphan cancel-prompt) 'source))
  (check-equal? (unbox calls) '()))

(test-case "raised host write failures still raise and the immutable source retains its old path"
  (define-values (st calls disk) (state #:fail 'write))
  (rich! st)
  (draft! st "a.txt")
  (define before (ev st 'draft))
  (check-exn exn:fail:aloe-host? (lambda () (ev st '(draft submit-prompt))))
  (check-equal? (all-calls calls) (write-calls "a.txt" "/cwd/a.txt" rich-text))
  (check-equal? (ev st 'draft) before))

(test-case "absent/non-prompt/missing-answer protocol, direct save/visit and selections stay intact"
  (define-values (st calls disk) (state))
  (rich! st)
  (draft! st "a.txt")
  (def! st 'direct (rebuild 'draft #:waiting no-command))
  (same st '(direct submit-prompt) (rebuild 'direct #:prompt no-prompt #:submission '(Option Some "a.txt")))
  (same st '(source start-prompt "Direct: ") (rebuild 'source #:prompt (prompt "" 0 "Direct: ")))
  (for ([command '(Save Kill RequestQuit SwitchBuffer KillBuffer Undo)])
    (def! st 'raw (rebuild 'draft #:waiting `(Option Some (AloemacsCommand ,command))))
    (same st '(raw submit-prompt)
      (rebuild 'raw #:prompt no-prompt #:submission '(Option Some "a.txt") #:waiting no-command)))
  (def! st 'no-answer (rebuild 'draft #:prompt no-prompt #:submission no-submission))
  (same st '(no-answer run-submitted-command) (rebuild 'no-answer #:waiting no-command))
  (same st '(draft kill-buffer) (selected 'draft (zipper '(a c) 1)))
  (same st '(draft switch-buffer) (selected 'draft (zipper '(a b c) 2)))
  (def! st 'mixed (rebuild 'draft #:searching #t))
  (same st '(mixed handle-key "return")
    (rebuild 'mixed #:searching #f #:query "" #:origin '(Position new 0 0) #:wrapped #f #:failing #f))
  (def! st 'quit '(draft request-quit))
  (same st '(quit handle-key "return") 'quit)
  (check-equal? (unbox calls) '())
  (same st '((draft save) case (None () source) (Some (s) s)) 'draft)
  (check-equal? (effects calls 'write) (list (list 'write "/cwd/b.txt" rich-text)))
  (set-box! calls '())
  (check-false (ev st '((draft visit (Path new "dir")) present?)))
  (same st '(draft waiting-command) waiting)
  (def! st 'visited '((draft visit (Path new "missing")) case (None () source) (Some (s) s)))
  (same st 'visited
    (rebuild 'draft #:buffers (replace-current 'draft (editor "") '(Option Some (Path new "/cwd/missing")))
      #:echo "" #:searching #f #:query "" #:origin '(Position new 0 0) #:wrapped #f #:failing #f
      #:ring '(List empty) #:pending no-pending #:prompt no-prompt #:waiting no-command))
  (check-equal? (effects calls 'write) '()))

(test-case "full active/saved/failed/canceled frames, safe clipping, submission and one row"
  (define-values (st calls disk) (state))
  (def! st 'source (session (zipper (list (buffer "ab\nsecond")) 0)))
  (draft! st "a.txt")
  (check-equal? (ev st '(draft frame 20 3)) (frame "ab\r\nsecond" 1 1 3 "Save as: a.txt" 3 15 #:name "untitled" #:width 20))
  (def! st 'done '(draft submit-prompt))
  (check-equal? (ev st '(done frame 20 3)) (frame "ab\r\nsecond" 1 1 3 "saved: /cwd/a.txt" 1 1 #:name "/cwd/a.txt" #:width 20))
  (def! st 'failed (rebuild 'draft #:prompt (prompt "dir")))
  (def! st 'failed '(failed submit-prompt))
  (check-equal? (ev st '(failed frame 20 3)) (frame "ab\r\nsecond" 1 1 3 "failed: untitled" 1 1 #:name "untitled" #:width 20))
  (def! st 'later '(done execute-command (AloemacsCommand SaveAs) "ignored"))
  (def! st 'cancel '(later handle-key "escape"))
  (check-equal? (ev st '(cancel frame 20 3)) (frame "ab\r\nsecond" 1 1 3 "saved: /cwd/a.txt" 1 1 #:name "/cwd/a.txt" #:width 20))
  (define unsafe "\t\r\u001b\u0000\u007f λabcdef")
  (def! st 'safe (rebuild 'draft #:prompt (prompt unsafe)))
  (set-box! calls '())
  (check-equal? (ev st '(safe frame 12 3)) (frame "ab\r\nsecond" 1 1 3 "Save as:    " 3 12 #:name "untitled" #:width 12))
  (check-equal? (unbox calls) '())
  (def! st 'safe-done '(safe submit-prompt))
  (same st '(safe-done last-submission) `(Option Some ,unsafe))
  (check-equal? (car (all-calls calls)) (list 'resolve unsafe))
  (for ([s '(draft done failed cancel safe)])
    (check-equal? (ev st `(,s frame 20 1)) (ev st `((,s editor) frame 20 1)))))

;; Exact Term call shapes, full frames and event order exercise the unchanged
;; runner's fit-before-frame step; narrow views require fitting to show bc/cd.
(define (scripted-run keys columns rows expected)
  (define-values (fs calls disk) (counted-fs))
  (define events (box '()))
  (define remaining keys)
  (define disk-kinds (box '()))
  (define (record x) (set-box! events (cons x (unbox events))))
  (define term
    (make-host-receiver
      (make-host-interface 'Term
        (list
          (make-host-method 'read-key '() 'String (lambda (state)
            (when (null? remaining) (error 'scripted-run "exhausted"))
            (define key (car remaining))
            (set! remaining (cdr remaining))
            (record (list 'key key))
            (set-box! disk-kinds (cons (host-receiver-send disk 'kind '("/cwd/new")) (unbox disk-kinds)))
            key))
          (make-host-method 'write-line '(String) 'String (lambda (state s) (error 'scripted-run "unexpected write-line")))
          (make-host-method 'write '(String) 'String (lambda (state s) (record (list 'write s)) s))
          (make-host-method 'columns '() 'Int (lambda (state) (record 'columns) columns))
          (make-host-method 'rows '() 'Int (lambda (state) (record 'rows) rows)))) #f))
  (run-aloemacs-with-hosts term fs)
  (check-equal? remaining '())
  (check-equal? (reverse (unbox events))
    (append-map (lambda (key painted) (list 'columns 'rows (list 'write painted) (list 'key key))) keys expected))
  (values calls disk (reverse (unbox disk-kinds))))

(test-case "scripted runner saves as, redraws through typing, edits/saves, cancels and quits at one or three rows"
  (for ([rows '(3 1)])
    (define keys '("x" "ctrl-x" "kill" "n" "e" "w" "left" "right" "return"
                  "y" "save" "ctrl-x" "kill" "z" "escape" "escape"))
    (define (paint text column label [prompt-column #f] #:name [name "untitled"])
      (runner-frame text column label prompt-column 20 rows #:name name))
    (define frames
      (append (list (paint "" 1 "untitled") (paint "x" 2 "untitled") (paint "x" 2 "untitled"))
        (for/list ([text '("/cwd/" "/cwd/n" "/cwd/ne" "/cwd/new" "/cwd/new" "/cwd/new")] [col '(15 16 17 18 17 18)])
          (paint "x" 2 (string-append "Save as: " text) col))
        (list (paint "x" 2 "saved: /cwd/new" #:name "/cwd/new") (paint "xy" 3 "/cwd/new" #:name "/cwd/new")
              (paint "xy" 3 "saved: /cwd/new" #:name "/cwd/new") (paint "xy" 3 "/cwd/new" #:name "/cwd/new")
              (paint "xy" 3 "Save as: /cwd/new" 18 #:name "/cwd/new") (paint "xy" 3 "Save as: /cwd/newz" 19 #:name "/cwd/new")
              (paint "xy" 3 "/cwd/new" #:name "/cwd/new"))))
    (define-values (calls disk kinds) (scripted-run keys 20 rows frames))
    (check-equal? (all-calls calls)
      (append '((current)) (write-calls "/cwd/new" "/cwd/new" "x" #:parent "/cwd")
        '((kind "/cwd/new") (resolve "/cwd/new") (write "/cwd/new" "xy"))))
    (check-equal? (take kinds 9) (make-list 9 "missing"))
    (check-equal? (drop kinds 9) (make-list 7 "file"))
    (check-equal? (host-receiver-send disk 'read '("/cwd/new")) "xy")))

(test-case "scripted narrow runner fits before every frame through save-as without changing contents"
  (for ([rows '(3 1)])
    (define keys '("a" "b" "c" "d" "ctrl-x" "kill" "a" "." "t" "x" "t" "return" "escape"))
    (define (paint text column label [prompt-column #f] #:name [name "untitled"])
      (runner-frame text column label prompt-column 2 rows #:name name))
    (define frames
      (append (list (paint "" 1 "untitled") (paint "a" 2 "untitled") (paint "b" 2 "untitled")
                    (paint "c" 2 "untitled") (paint "d" 2 "untitled") (paint "d" 2 "untitled"))
        (for/list ([text '("/cwd/" "/cwd/a" "/cwd/a." "/cwd/a.t" "/cwd/a.tx" "/cwd/a.txt")])
          (paint "d" 2 (string-append "Save as: " text) 2))
        (list (paint "d" 2 "saved: /cwd/a.txt" #:name "/cwd/a.txt"))))
    (define-values (calls disk kinds) (scripted-run keys 2 rows frames))
    (check-equal? (all-calls calls) (cons '(current) (write-calls "/cwd/a.txt" "/cwd/a.txt" "abcd")))))
