#lang racket/base

(require racket/list racket/port racket/runtime-path racket/string rackunit
         "../../aloe/driver.rkt" "../../aloe/host.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/env.rkt" env-bound?)
         (only-in "../../aloe/type.rkt" exn:fail:aloe-type? type-of type->datum)
         "../../host/racket/fs.rkt" "../../host/racket/term.rkt"
         "../../host/racket/aloemacs-run.rkt")

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define-runtime-path main-path "../../examples/aloemacs/main.aloe")
(define no-mark '(if #t (Option None) (Option Some (Position new 0 0))))
(define no-path '(if #t (Option None) (Option Some (Path new "/typed-none"))))
(define no-pending '(if #t (Option None) (Option Some aloemacs-global-keymap)))
(define no-prompt '(if #t (Option None) (Option Some (AloemacsPrompt new "" "" 0 "" (List empty) (List empty) 0))))
(define no-submission '(if #t (Option None) (Option Some "")))
(define no-command '(if #t (Option None) (Option Some (AloemacsCommand FindFile))))
(define waiting '(Option Some (AloemacsCommand FindFile)))
(define (prompt text [column (string-length text)] [label "Find file: "])
  `(Option Some (AloemacsPrompt new ,label ,text ,column "" (List empty) (List empty) 0)))
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (type st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))

;; All observable calls, including the resolves inside thin Fs.inspect, count.
(define (counted-fs #:host-name [host-name 'FsHost] #:fail [fail #f]
                    #:second-kind [second-kind #f] #:contents [contents "\uFEFFλ\r\nb\n"])
  (define disk (make-fs-double "/cwd"
    (hash "/cwd" 'directory "/cwd/a.txt" 'file "/cwd/b.txt" 'file
          "/cwd/dir" 'directory "/cwd/link" 'symlink "/cwd/pipe" "fifo")
    (hash "/cwd/a.txt" contents "/cwd/b.txt" "disk b")))
  (define calls (box '()))
  (define probes 0)
  (define (forward selector args)
    (set-box! calls (cons (cons selector args) (unbox calls)))
    (when (eq? selector fail) (error 'find-file-test "host failure"))
    (when (eq? selector 'kind) (set! probes (add1 probes)))
    (if (and second-kind (eq? selector 'kind) (> probes 1)) second-kind
        (host-receiver-send disk selector args)))
  (define interface
    (make-host-interface host-name
      (for/list ([method (in-list (host-interface-methods fs-interface))])
        (define selector (host-method-selector method))
        (define params (host-method-parameter-types method))
        (make-host-method selector params (host-method-return-type method)
          (case (length params)
            [(0) (lambda (state) (forward selector '()))]
            [(1) (lambda (state a) (forward selector (list a)))]
            [(2) (lambda (state a b) (forward selector (list a b)))])))))
  (values (make-host-receiver interface #f) calls disk))
(define (state #:host-name [host-name 'FsHost] #:fail [fail #f]
               #:second-kind [second-kind #f] #:contents [contents "\uFEFFλ\r\nb\n"])
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  (define-values (host calls disk)
    (counted-fs #:host-name host-name #:fail fail #:second-kind second-kind #:contents contents))
  (driver-inject-host! st 'fs-host host)
  (values st calls))
(define (all-calls calls) (reverse (unbox calls)))
(define (effects calls selector)
  (filter (lambda (call) (eq? (car call) selector)) (all-calls calls)))
(define (read-calls typed resolved [read? #t] [second? #t])
  (append (list (list 'resolve typed) (list 'kind resolved) (list 'resolve resolved))
          (if second? (list (list 'kind resolved) (list 'resolve resolved)) '())
          (if read? (list (list 'read resolved)) '())))
(define (editor contents)
  `(AloemacsEditor new ((Text from-string ,contents) indexed-value)
     (Position new 0 0) #f 0 0 (List empty) ,no-mark 0))
(define (buffer contents [path no-path] [id 0])
  `(AloemacsBuffer new ,(editor contents) ,path ,id))
(define (bound contents name [id 0]) (buffer contents `(Option Some (Path new ,name)) id))
(define (zipper order focus)
  `(AloemacsBuffers new (List of ,@(reverse (take order focus)))
     ,(list-ref order focus) (List of ,@(drop order (add1 focus)))))
(define (session buffers)
  `(AloemacsSession new ,buffers (Fs new fs-host) "saved" #f "old query"
     (Position new 4 2) #t #t (List of "newest" "older")
     ,no-pending ,no-prompt ,no-submission ,no-command
     (let ((buffer (,buffers current-buffer)))
       (AloemacsWindows new
         (AloemacsWindowTree Leaf
           (AloemacsView new 0 (buffer id)
             ((buffer editor) scroll-row) ((buffer editor) scroll-col) #f))
         0 0 0))))
;; Only constructors and reads appear in expected reconstructions.
(define (rebuild s #:buffers [buffers `(,s buffers)] #:echo [echo `(,s echo)]
                 #:searching [searching `(,s searching)] #:query [query `(,s query)]
                 #:origin [origin `(,s origin)] #:wrapped [wrapped `(,s wrapped)]
                 #:failing [failing `(,s failing)] #:ring [ring `(,s kill-ring)]
                 #:pending [pending `(,s pending)] #:prompt [line `(,s prompt)]
                 #:submission [submission `(,s last-submission)]
                 #:waiting [command `(,s waiting-command)]
                 #:columns [columns `((,s windows) columns)]
                 #:rows [rows `((,s windows) rows)])
  `(AloemacsSession new ,buffers (,s fs) ,echo ,searching ,query ,origin
     ,wrapped ,failing ,ring ,pending ,line ,submission ,command
     (let ((buffer (,buffers current-buffer)))
       (AloemacsWindows new
         (AloemacsWindowTree Leaf
           (AloemacsView new 0 (buffer id)
             ((buffer editor) scroll-row) ((buffer editor) scroll-col) #f))
         0 ,columns ,rows))))
(define (replace-current s new-editor [path `(,s path)])
  `(AloemacsBuffers new ((,s buffers) before)
     (AloemacsBuffer new ,new-editor ,path ((,s current-buffer) id)) ((,s buffers) after)))
(define (selected s buffers)
  (rebuild s #:buffers buffers #:echo "" #:searching #f #:query ""
    #:origin '(Position new 0 0) #:wrapped #f #:failing #f #:pending no-pending))
(define (rich! st)
  (def! st 'a (bound "neighbor a" "/cwd/old.txt" 0))
  (def! st 'rich-editor
    '(AloemacsEditor new
       (Text indexed (List of "second" "first") "third-long"
                     (List of "fourth" "fifth") 2)
       (Position new 2 4) #f 2 3
       (List of (UndoFrame new (Text from-string "old b") (Position new 0 2) 1 2))
       (Option Some (Position new 1 1)) 4))
  (def! st 'b '(AloemacsBuffer new rich-editor (Option Some (Path new "/cwd/b.txt")) 1))
  (def! st 'c (buffer "neighbor c" no-path 2))
  (def! st 'source (session (zipper '(a b c) 1))))
(define (draft! st [text "draft"])
  (rich! st)
  (def! st 'draft (rebuild 'source #:prompt (prompt text)
    #:submission '(Option Some "previous") #:waiting waiting)))
(define (editor-frame body row column)
  (string-append "\u001b[?25l\u001b[2J\u001b[H" body
    (format "\u001b[~a;~aH\u001b[?25h" row column)))
;; Independent name and text allocation from the supplied fixture and size.
(define (mode-row name width)
  (define label (substring (string-append name " ") 0
                          (min width (add1 (string-length name)))))
  (list->string
    (for/list ([c (in-string (string-append label
                              (make-string (- width (string-length label)) #\-)))])
      (if (or (< (char->integer c) 32) (= (char->integer c) 127)) #\space c))))
(define (text-body body rows)
  (define lines (string-split body "\r\n" #:trim? #f))
  (string-join (take lines (min (length lines) (if (>= rows 3) (- rows 2) 1))) "\r\n"))
(define (frame body row column rows shown cursor-row cursor-column #:name [name "untitled"] #:width [width 0])
  (string-append "\e[?25l\e[2J\e[H"
    (if rows (text-body body rows) body)
    (format "\e[~a;~aH\e[?25h" row column)
    (if (and rows (>= rows 2))
        (string-append "\e[?25l"
          (if (>= rows 3) (format "\e[~a;1H~a" (sub1 rows) (mode-row name width)) "")
          (format "\e[~a;1H~a\e[~a;~aH\e[?25h" rows shown cursor-row cursor-column)) "")))

(test-case "exact fourteen fields, helper signatures, command and production map inventories"
  (define datums (call-with-input-file file-path (lambda (in) (port->list read in))))
  (define (declaration name) (findf (lambda (d) (equal? (cadr d) name)) datums))
  (check-equal? (take datums 2) '((load "editor.aloe") (load "../../lib/fs.aloe")))
  (check-equal? (map cadr (filter (lambda (d) (eq? (car d) 'define-class)) datums))
    '(AloemacsPrompt AloemacsCompletionScan AloemacsBuffer AloemacsBuffers AloemacsModeLine AloemacsView AloemacsWindowTree
      AloemacsWindowRect AloemacsWindows AloemacsCommand
      (AloemacsKeymap B) AloemacsBinding AloemacsSearchScan (AloemacsSession H)))
  (check-equal? (caddr (declaration '(AloemacsSession H)))
    '(fields (buffers AloemacsBuffers) (fs (Fs H)) (echo String) (searching Bool)
       (query String) (origin Position) (wrapped Bool) (failing Bool)
       (kill-ring (List String)) (pending (Option (AloemacsKeymap AloemacsBinding)))
       (prompt (Option AloemacsPrompt)) (last-submission (Option String))
       (waiting-command (Option AloemacsCommand)) (windows AloemacsWindows)))
  (define signatures
    '((with-waiting-command (command AloemacsCommand) (AloemacsSession H))
      (clear-waiting-command () (AloemacsSession H))
      (start-command-prompt (command AloemacsCommand) (label String) (AloemacsSession H))
      (run-submitted-command () (AloemacsSession H))
      (selected-buffers (buffers AloemacsBuffers) (AloemacsSession H))
      (file-contents (path Path) (Option String))
      (find-file-submitted (submitted String) (AloemacsSession H))))
  (define methods (cdr (cadddr (declaration '(AloemacsSession H)))))
  (for ([signature signatures])
    (check-equal? (drop-right (assoc (car signature) methods) 1) signature))
  (define lookup-methods (cdr (cadddr (declaration 'AloemacsBuffers))))
  (for ([signature '((find-name (name String) (Option AloemacsBuffers))
                     (find-name-in (name String) (remaining Int) (Option AloemacsBuffers)))])
    (check-equal? (drop-right (assoc (car signature) lookup-methods) 1) signature))
  (define constructors (cdr (caddr (declaration 'AloemacsCommand))))
  (check-equal? (map car constructors)
    '(Newline BackwardDelete MoveLeft MoveRight MoveUp MoveDown LineStart LineEnd
      PageUp PageDown BufferStart BufferEnd RequestQuit Undo SetMark Kill KillLine
      Yank Find Save SelfInsert SwitchBuffer KillBuffer FindFile SaveAs SelectBuffer
      SplitBelow SplitRight DeleteWindow OtherWindow ToggleWindowLock))
  (check-equal? (take-right (drop-right constructors 5) 3)
    '((FindFile (fields)) (SaveAs (fields)) (SelectBuffer (fields))))
  (check-equal? (length (cdr (cadddr (declaration 'AloemacsCommand)))) 1)
  (define-values (st calls) (state))
  (same st '(aloemacs-ctrl-x-keymap bindings)
    '(List of (AloemacsBinding Command "save" aloemacs-save-command)
              (AloemacsBinding Command "find" (AloemacsCommand FindFile))
              (AloemacsBinding Command "kill" (AloemacsCommand SaveAs))
              (AloemacsBinding Command "b" (AloemacsCommand SelectBuffer))
              (AloemacsBinding Command "2" (AloemacsCommand SplitBelow))
              (AloemacsBinding Command "3" (AloemacsCommand SplitRight))
              (AloemacsBinding Command "0" (AloemacsCommand DeleteWindow))
              (AloemacsBinding Command "o" (AloemacsCommand OtherWindow))
              (AloemacsBinding Command "l" (AloemacsCommand ToggleWindowLock))))
  (check-false (ev st '((aloemacs-ctrl-x-keymap default) present?)))
  (define global-rows
    '(("return" Newline) ("backspace" BackwardDelete) ("left" MoveLeft) ("right" MoveRight)
      ("up" MoveUp) ("down" MoveDown) ("line-start" LineStart) ("line-end" LineEnd)
      ("page-up" PageUp) ("page-down" PageDown) ("buffer-start" BufferStart)
      ("buffer-end" BufferEnd) ("escape" RequestQuit) ("undo" Undo) ("mark" SetMark)
      ("kill" Kill) ("kill-line" KillLine) ("yank" Yank) ("find" Find) ("save" Save)))
  (same st '(aloemacs-global-keymap bindings)
    `(List of ,@(for/list ([row global-rows])
                  `(AloemacsBinding Command ,(car row) (AloemacsCommand ,(cadr row))))
       (AloemacsBinding Prefix "ctrl-x" aloemacs-ctrl-x-keymap)))
  (same st '(aloemacs-global-keymap default) '(Option Some (AloemacsCommand SelfInsert)))
  (check-equal? (unbox calls) '()))

(test-case "fresh checked loads, lawful startup, concrete hosts and argument/receiver negatives"
  (for ([i (in-range 2)])
    (define st (make-driver))
    (define out (open-output-string))
    (parameterize ([current-output-port out]) (ev st `(load ,(path->string file-path))))
    (for ([name '(term fs-host)]) (check-false (env-bound? (driver-runtime-environment st) name)))
    (check-equal? (get-output-string out) ""))
  (for ([host-name '(FsHost AlternateFsHost)])
    (define-values (st calls) (state #:host-name host-name))
    (ev st `(load ,(path->string main-path)))
    (check-false (ev st '((aloemacs-editor waiting-command) present?)))
    (check-false (ev st '((aloemacs-editor prompt) present?)))
    (check-false (ev st '((aloemacs-editor last-submission) present?)))
    (check-equal? (ev st '((aloemacs-editor text) to-string)) "")
    (check-equal? (ev st '((aloemacs-editor current-buffer) name)) "untitled")
    (check-equal? (unbox calls) '())
    (rich! st)
    (def! st 'command '(AloemacsCommand FindFile))
    (check-equal? (ev st '(command name)) "find-file")
    (check-equal? (type st '(source waiting-command)) '(Option AloemacsCommand))
    (for ([send '((source with-waiting-command command) (source clear-waiting-command)
                  (source start-command-prompt command "Find file: ")
                  (source run-submitted-command) (source selected-buffers (source buffers))
                  (source find-file-submitted "") (source execute-command command "./ignored"))])
      (check-equal? (type st send) `(AloemacsSession ,host-name)))
    (check-equal? (type st '(source file-contents (Path new "/cwd/a.txt"))) '(Option String))
    (for ([send '(((source buffers) find-name "x") ((source buffers) find-name-in "x" 3))])
      (check-equal? (type st send) '(Option AloemacsBuffers)))
    (for ([bad '((AloemacsCommand FindFile 0) (source waiting-command 0)
                 (source with-waiting-command) (source with-waiting-command "find-file")
                 (source with-waiting-command command command) (source clear-waiting-command 0)
                 (source start-command-prompt command) (source start-command-prompt 0 "x")
                 (source start-command-prompt command 0) (source start-command-prompt command "x" 0)
                 (source run-submitted-command 0) (source selected-buffers)
                 (source selected-buffers (source current-buffer))
                 (source selected-buffers (source buffers) (source buffers))
                 (source file-contents) (source file-contents "x") (source file-contents (Path new "x") 0)
                 (source find-file-submitted) (source find-file-submitted (Path new "x"))
                 (source find-file-submitted "x" "y") ((source buffers) find-name 0)
                 ((source buffers) find-name) ((source buffers) find-name "x" 0)
                 ((source buffers) find-name-in "x") ((source buffers) find-name-in "x" "3")
                 ((source buffers) find-name-in "x" 3 0))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st bad)) (format "reject ~s" bad)))
    (for* ([receiver '(1 "x" command AloemacsSession)]
           [tail '((waiting-command) (with-waiting-command command) (clear-waiting-command)
                   (start-command-prompt command "x") (run-submitted-command)
                   (selected-buffers (source buffers)) (file-contents (Path new "x"))
                   (find-file-submitted "x") (find-name "x") (find-name-in "x" 1))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st `(,receiver ,@tail)))))
    (define valid (session '(source buffers)))
    (for ([bad (list (drop-right valid 1) (append valid '(0))
                    (append (drop-right valid 1) '("bad-slot")))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
    (check-equal? (unbox calls) '())))

(test-case "direct and prefix start, four whole-session guards, and orphan replacement"
  (define-values (st calls) (state))
  (rich! st)
  (define before (ev st 'source))
  (same st '(source execute-command (AloemacsCommand FindFile) "/ignored/path")
    (rebuild 'source #:prompt (prompt "/cwd/") #:waiting waiting))
  (def! st 'armed '(source handle-key "ctrl-x"))
  (same st 'armed (rebuild 'source #:echo "" #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (same st '(armed handle-key "find")
    (rebuild 'source #:echo "" #:prompt (prompt "/cwd/") #:waiting waiting))
  (for ([fixture (list
                   (rebuild 'source #:buffers (replace-current 'source '(rich-editor request-quit)))
                   (rebuild 'source #:searching #t)
                   (rebuild 'source #:pending '(Option Some aloemacs-ctrl-x-keymap))
                   (rebuild 'source #:prompt (prompt "old" 2 "Old: ")))])
    (def! st 'guarded fixture)
    (def! st 'guarded (rebuild 'guarded #:waiting '(Option Some (AloemacsCommand Save))
                                        #:submission '(Option Some "old answer")))
    (same st '(guarded execute-command (AloemacsCommand FindFile) "ignored") 'guarded)
    (same st '(guarded start-command-prompt (AloemacsCommand FindFile) "Find file: ") 'guarded))
  (def! st 'orphan (rebuild 'source #:waiting '(Option Some (AloemacsCommand Undo))))
  (same st '(orphan start-command-prompt (AloemacsCommand FindFile) "Find file: ")
    (rebuild 'orphan #:prompt (prompt "/cwd/") #:waiting waiting))
  (same st '(orphan start-prompt "Direct: ")
    (rebuild 'orphan #:prompt (prompt "" 0 "Direct: ")))
  (check-equal? (ev st 'source) before)
  (check-equal? (all-calls calls)
    '((root? "/cwd/b.txt") (parent "/cwd/b.txt")
      (root? "/cwd/b.txt") (parent "/cwd/b.txt")
      (root? "/cwd/b.txt") (parent "/cwd/b.txt"))))

(test-case "prompt editing, ignored input, storage-only Return and cancellation preserve protocol state"
  (define-values (st calls) (state))
  (draft! st "abc")
  (define before (ev st 'draft))
  (same st '(draft with-waiting-command (AloemacsCommand Undo))
    (rebuild 'draft #:waiting '(Option Some (AloemacsCommand Undo))))
  (same st '(draft clear-waiting-command) (rebuild 'draft #:waiting no-command))
  (for ([row '(("X" "abcX" 4) ("backspace" "ab" 2) ("left" "abc" 2)
               ("right" "abc" 3) ("line-start" "abc" 0) ("line-end" "abc" 3))])
    (same st `(draft handle-key ,(car row)) (rebuild 'draft #:prompt (prompt (cadr row) (caddr row)))))
  (for ([key '("\n" "save" "find" "ctrl-x" "kill" "kill-line" "yank" "up" "down" "unknown")])
    (same st `(draft handle-key ,key) 'draft))
  (for ([submission (list no-submission '(Option Some "previous"))])
    (def! st 'active (rebuild 'draft #:submission submission))
    (same st '(active handle-key "escape")
      (rebuild 'active #:prompt no-prompt #:waiting no-command)))
  (def! st 'orphan (rebuild 'draft #:prompt no-prompt))
  (same st '(orphan submit-prompt) 'orphan)
  (same st '(orphan cancel-prompt) (rebuild 'orphan #:waiting no-command))
  (same st '(source cancel-prompt) 'source)
  (for ([text '("" "exact\tλ")])
    (def! st 'direct (rebuild 'source #:prompt (prompt text) #:waiting no-command))
    (same st '(direct handle-key "return")
      (rebuild 'direct #:prompt no-prompt #:submission `(Option Some ,text))))
  (for ([command '(Save RequestQuit SwitchBuffer KillBuffer Undo)])
    (def! st 'raw (rebuild 'draft #:waiting `(Option Some (AloemacsCommand ,command))))
    (same st '(raw submit-prompt)
      (rebuild 'raw #:prompt no-prompt #:submission '(Option Some "abc") #:waiting no-command)))
  (def! st 'no-answer (rebuild 'orphan #:submission no-submission))
  (same st '(no-answer run-submitted-command) (rebuild 'no-answer #:waiting no-command))
  (same st '(source run-submitted-command) 'source)
  ;; Search still precedes prompt; Return ends search without submitting.
  (def! st 'mixed (rebuild 'draft #:searching #t #:query "abc"))
  (same st '(mixed handle-key "return")
    (rebuild 'mixed #:searching #f #:query "" #:origin '(Position new 0 0) #:wrapped #f #:failing #f))
  (same st '((draft request-quit) handle-key "return") '(draft request-quit))
  (check-equal? (ev st 'draft) before)
  (check-equal? (unbox calls) '()))

(test-case "every preserving reconstruction retains active prompt, nontrivial slot and prior submission"
  (define-values (st calls) (state))
  (draft! st)
  (define before (ev st 'draft))
  (define rows
    (list
      (list '(draft with-active-prompt (AloemacsPrompt new "Other: " "x" 1 "" (List empty) (List empty) 0))
            (rebuild 'draft #:prompt (prompt "x" 1 "Other: ")))
      (list '(draft with-editor rich-editor) 'draft)
      (list '(draft with-kill-state rich-editor (List of "ring")) (rebuild 'draft #:echo "" #:ring '(List of "ring")))
      (list '(draft with-search rich-editor #t "q" (Position new 1 2) #f #t)
            (rebuild 'draft #:searching #t #:query "q" #:origin '(Position new 1 2) #:wrapped #f #:failing #t))
      (list '(draft with-echo "failed") (rebuild 'draft #:echo "failed"))
      (list '(draft with-prefix aloemacs-ctrl-x-keymap)
            (rebuild 'draft #:echo "" #:pending '(Option Some aloemacs-ctrl-x-keymap)))
      (list '(draft clear-prefix) 'draft)
      (list '(draft switch-buffer) (selected 'draft (zipper '(a b c) 2)))
      (list '(draft kill-buffer) (selected 'draft (zipper '(a c) 1)))
      (list '(draft add-buffer "new") (selected 'draft (zipper (list 'a 'b (buffer "new" no-path 3) 'c) 2)))
      (list '(draft add-buffer "new" (Path new "relative"))
            (selected 'draft (zipper (list 'a 'b (bound "new" "relative" 3) 'c) 2)))
      (list '(draft selected-buffers (draft buffers)) (selected 'draft '(draft buffers)))
      (list '(draft ensure-visible 2 2)
            (rebuild 'draft #:columns 2 #:rows 2 #:buffers (replace-current 'draft
              '(AloemacsEditor new (draft text) (draft point) #f 2 3
                 (rich-editor history) (rich-editor mark) 1))))))
  (for ([row rows])
    (def! st 'result (car row))
    (same st 'result (cadr row))
    ;; with-active-prompt intentionally replaces the line.
    (unless (eq? (cadar row) 'with-active-prompt)
      (same st '(result prompt) '(draft prompt)))
    (same st '(result waiting-command) waiting)
    (same st '(result last-submission) '(Option Some "previous")))
  (check-equal? (unbox calls) '())
  (def! st 'option '(draft save))
  (same st '(option case (None () source) (Some (s) s)) 'draft)
  (check-equal? (effects calls 'write) '((write "/cwd/b.txt" "first\nsecond\nthird-long\nfourth\nfifth")))
  (set-box! calls '())
  (for ([i (in-range 2)])
    (check-equal? (ev st '(draft frame 12 3)) (frame "rd-long\r\nrth" 1 2 3 "Find file: d" 3 12 #:name "/cwd/b.txt" #:width 12)))
  (check-equal? (unbox calls) '())
  (check-equal? (ev st 'draft) before)
  ;; Completion uses the current buffer at Return, after a direct switch.
  (def! st 'changed '(draft switch-buffer))
  (def! st 'changed (rebuild 'changed #:prompt (prompt "b.txt")))
  (def! st 'done '(changed submit-prompt))
  (same st '(done buffers) (zipper '(a b c) 1))
  (check-equal? (all-calls calls) '((resolve "b.txt")))
  (check-false (ev st '((done prompt) present?)))
  (check-false (ev st '((done waiting-command) present?))))

(test-case "bounded pure lookup: singleton, forward/wrapped duplicates and equal-valued positions"
  (define-values (st calls) (state))
  (def! st 'a (bound "a" "same" 0))
  (def! st 'b (bound "b" "same" 1))
  (def! st 'c (bound "c" "target" 2))
  (def! st 'd (bound "d" "same" 3))
  (def! st 'equal-a (bound "a" "same" 4))
  (for ([row (list (list '(a) 0 "same" 0) (list '(a b c d) 1 "same" 1)
                   (list '(a b c d) 0 "target" 2) (list '(a b c d) 3 "target" 2)
                   (list '(a c b d) 1 "same" 2) (list '(a b c d) 2 "same" 3)
                   (list '(a b c) 2 "same" 0) (list '(a equal-a c) 0 "target" 2))])
    (define order (car row))
    (def! st 'collection (zipper order (cadr row)))
    (define before (ev st 'collection))
    (same st `(collection find-name ,(caddr row)) `(Option Some ,(zipper order (cadddr row))))
    (for ([name '("" "miss" "Target" " same" "a")])
      (check-false (ev st `((collection find-name ,name) present?))))
    (for ([budget '(0 -1 -100)])
      (check-false (ev st `((collection find-name-in "same" ,budget) present?))))
    (check-equal? (ev st 'collection) before))
  (def! st 'empty-name (zipper (list (bound "empty" "")) 0))
  (check-false (ev st '((empty-name find-name "") present?)))
  (def! st 'collection (zipper '(a equal-a c) 0))
  (check-false (ev st '((collection find-name-in "target" 2) present?)))
  (same st '(collection find-name-in "target" 3) `(Option Some ,(zipper '(a equal-a c) 2)))
  (check-equal? (unbox calls) '()))

(test-case "Return opens exact regular contents or missing paths after current, preserving complete buffers"
  (for* ([focus '(1 2)] [input '("./dir/../a.txt" "missing.txt")])
    (define-values (st calls) (state))
    (rich! st)
    (def! st 'source (rebuild 'source #:buffers (zipper '(a b c) focus)))
    (define old-session (ev st 'source))
    (define old-buffer (ev st '(source current-buffer)))
    (def! st 'active (rebuild 'source #:prompt (prompt input) #:waiting waiting))
    (def! st 'done '(active handle-key "return"))
    (define missing? (equal? input "missing.txt"))
    (define resolved (if missing? "/cwd/missing.txt" "/cwd/a.txt"))
    (define contents (if missing? "" "\uFEFFλ\r\nb\n"))
    (define new (bound contents resolved 3))
    (define order (append (take '(a b c) (add1 focus)) (list new) (drop '(a b c) (add1 focus))))
    (same st 'done (rebuild 'active #:buffers (zipper order (add1 focus)) #:echo ""
      #:searching #f #:query "" #:origin '(Position new 0 0) #:wrapped #f #:failing #f
      #:pending no-pending #:prompt no-prompt #:submission `(Option Some ,input) #:waiting no-command))
    (check-equal? (ev st '((done text) to-string)) contents)
    (check-equal? (all-calls calls) (read-calls input resolved (not missing?) (not missing?)))
    (define observed (all-calls calls))
    (same st '(done submit-prompt) 'done)
    (same st '(done handle-key "return")
      (rebuild 'done #:buffers (replace-current 'done '((done editor) newline)) #:echo ""))
    (check-equal? (all-calls calls) observed)
    ;; Cycle without fitting/editing and compare the entire original buffer.
    (def! st 'back 'done)
    (for ([i (in-range 3)]) (def! st 'back '(back switch-buffer)))
    (check-equal? (ev st '(back current-buffer)) old-buffer)
    (check-equal? (ev st 'source) old-session)
    (check-equal? (effects calls 'write) '()))
  ;; Empty untitled is retained as a complete buffer, even for a missing path.
  (define-values (st calls) (state))
  (def! st 'empty (buffer ""))
  (def! st 's (session (zipper '(empty) 0)))
  (same st '(s find-file-submitted "new")
    (selected 's (zipper (list 'empty (bound "" "/cwd/new" 1)) 1)))
  (check-equal? (all-calls calls) (read-calls "new" "/cwd/new" #f #f)))

(test-case "reuse precedes all disk inspection and resets selection even on current hits"
  (for ([input '("b.txt" "dir" "missing.txt" "link" "pipe")])
    (define-values (st calls) (state))
    (rich! st)
    (define resolved (string-append "/cwd/" input))
    (def! st 'first `(AloemacsBuffer new rich-editor (Option Some (Path new ,resolved)) 1))
    (def! st 'duplicate (bound "different unsaved" resolved 3))
    (for ([focus '(0 1 2 3)] [hit '(1 1 2 1)])
      (def! st 's (session (zipper '(a first duplicate c) focus)))
      (def! st 's (rebuild 's #:pending '(Option Some aloemacs-ctrl-x-keymap)
                             #:prompt (prompt "kept") #:waiting waiting))
      (define before (ev st 's))
      (set-box! calls '())
      (same st `(s find-file-submitted ,input) (selected 's (zipper '(a first duplicate c) hit)))
      (check-equal? (all-calls calls) (list (list 'resolve input)))
      (check-equal? (ev st 's) before)))
  ;; Stored relative names are not resolved, basename identity is not used.
  (define-values (st calls) (state))
  (def! st 's (session (zipper (list (bound "unsaved" "a.txt")) 0)))
  (def! st 'opened '(s find-file-submitted "a.txt"))
  (check-equal? (ev st '(((opened buffers) before) len)) 1)
  (check-equal? (all-calls calls) (read-calls "a.txt" "/cwd/a.txt"))
  (set-box! calls '())
  (def! st 'spaced '(s find-file-submitted "  "))
  (check-equal? (ev st '((spaced current-buffer) name)) "/cwd/  ")
  (check-equal? (all-calls calls) (read-calls "  " "/cwd/  " #f #f)))

(test-case "empty/cancel, shared read refusals, live second inspection and raised read failures"
  (define-values (st calls) (state))
  (draft! st "")
  (same st '(draft submit-prompt)
    (rebuild 'draft #:echo "failed" #:prompt no-prompt #:submission '(Option Some "") #:waiting no-command))
  (same st '(draft cancel-prompt) (rebuild 'draft #:prompt no-prompt #:waiting no-command))
  (check-equal? (unbox calls) '())
  (for ([input '("dir" "link" "pipe")])
    (def! st 'active (rebuild 'draft #:prompt (prompt input)))
    (define before (ev st 'active))
    (set-box! calls '())
    (same st '(active submit-prompt)
      (rebuild 'active #:echo "failed" #:prompt no-prompt #:submission `(Option Some ,input) #:waiting no-command))
    (check-equal? (all-calls calls) (read-calls input (string-append "/cwd/" input) #f #f))
    (check-equal? (ev st 'active) before)
    (set-box! calls '())
    (check-false (ev st `((active visit (Path new ,input)) present?)))
    (check-equal? (all-calls calls) (read-calls input (string-append "/cwd/" input) #f #f))
    (check-equal? (ev st 'active) before))
  (for ([kind '("missing" "directory" "symlink" "fifo")])
    (define-values (live probes) (state #:second-kind kind))
    (draft! live "a.txt")
    (same live '(draft submit-prompt)
      (rebuild 'draft #:echo "failed" #:prompt no-prompt #:submission '(Option Some "a.txt") #:waiting no-command))
    (check-equal? (all-calls probes) (read-calls "a.txt" "/cwd/a.txt" #f))
    (check-equal? (effects probes 'write) '()))
  (define-values (failing failures) (state #:fail 'read))
  (draft! failing "a.txt")
  (define original (ev failing 'draft))
  (check-exn exn:fail:aloe-host? (lambda () (ev failing '(draft submit-prompt))))
  (check-equal? (ev failing 'draft) original)
  (check-equal? (all-calls failures) (read-calls "a.txt" "/cwd/a.txt")))

(test-case "shared policy has no resolution at its boundary; visit clears only current prompt/slot and ring"
  (define-values (st calls) (state))
  (draft! st)
  (for ([input '("a.txt" "missing" "dir" "link" "pipe")]
        [contents '("\uFEFFλ\r\nb\n" "" #f #f #f)])
    (define resolved (string-append "/cwd/" input))
    (define before (ev st 'draft))
    (set-box! calls '())
    (same st `(draft file-contents (Path new ,resolved))
      (if contents `(Option Some ,contents) '(if #t (Option None) (Option Some ""))))
    (check-equal? (all-calls calls)
      (cdr (read-calls input resolved (equal? input "a.txt") (equal? input "a.txt"))))
    (check-equal? (ev st 'draft) before)
    (set-box! calls '())
    (def! st 'option `(draft visit (Path new ,input)))
    (if contents
        (same st 'option `(Option Some ,(rebuild 'draft
          #:buffers (replace-current 'draft (editor contents) `(Option Some (Path new ,resolved)))
          #:echo "" #:searching #f #:query "" #:origin '(Position new 0 0) #:wrapped #f #:failing #f
          #:ring '(List empty) #:pending no-pending #:prompt no-prompt #:waiting no-command)))
        (check-false (ev st '(option present?))))
    (check-equal? (ev st 'draft) before)
    (check-equal? (all-calls calls) (read-calls input resolved (equal? input "a.txt") (equal? input "a.txt")))))

(test-case "full ANSI active, completed, failed, canceled, safe clipped and one-row frames"
  (define-values (st calls) (state #:contents "λ\r\nb\n"))
  (def! st 's (session (zipper (list (buffer "ab\nsecond")) 0)))
  (def! st 'active '((s handle-key "ctrl-x") handle-key "find"))
  (same st '(active waiting-command) waiting)
  (check-equal? (ev st '(active frame 20 3)) (frame "ab\r\nsecond" 1 1 3 "Find file: /cwd/" 3 17 #:name "untitled" #:width 20))
  (def! st 'typed (rebuild 'active #:prompt (prompt "a.txt")))
  (check-equal? (ev st '(typed frame 20 3)) (frame "ab\r\nsecond" 1 1 3 "Find file: a.txt" 3 17 #:name "untitled" #:width 20))
  (def! st 'done '(typed handle-key "return"))
  (check-equal? (ev st '(done frame 20 3)) (frame "λ \r\nb" 1 1 3 "" 1 1 #:name "/cwd/a.txt" #:width 20))
  (def! st 'refused (rebuild 'active #:prompt (prompt "dir")))
  (def! st 'failed '(refused handle-key "return"))
  (check-equal? (ev st '(failed frame 20 3)) (frame "ab\r\nsecond" 1 1 3 "failed: untitled" 1 1 #:name "untitled" #:width 20))
  (def! st 'cancel '(typed handle-key "escape"))
  (check-equal? (ev st '(cancel frame 20 3)) (frame "ab\r\nsecond" 1 1 3 "" 1 1 #:name "untitled" #:width 20))
  (define unsafe "\t\r\u001b\u0000\u007f λabcdef")
  (def! st 'safe (rebuild 'active #:prompt (prompt unsafe (string-length unsafe) "L\t\u001b: ")))
  (define before (ev st 'safe))
  (set-box! calls '())
  (for ([i (in-range 2)])
    (check-equal? (ev st '(safe frame 4 3)) (frame "ab\r\nseco" 1 1 3 "L  :" 3 4 #:name "untitled" #:width 4)))
  (check-equal? (ev st 'safe) before)
  (check-equal? (unbox calls) '())
  (def! st 'done '(safe submit-prompt))
  (same st '(done last-submission) `(Option Some ,unsafe))
  (check-equal? (car (all-calls calls)) (list 'resolve unsafe))
  (for ([s '(active typed done cancel failed)])
    (check-equal? (ev st `(,s frame 20 1)) (ev st `((,s editor) frame 20 1))))
  (set-box! calls '())
  (def! st 'one '(active ensure-visible 20 1))
  (same st '(one waiting-command) waiting)
  (def! st 'one (rebuild 'one #:prompt (prompt "missing")))
  (def! st 'one '(one submit-prompt))
  (check-equal? (ev st '(one frame 20 1)) (editor-frame "" 1 1))
  (same st '(one last-submission) '(Option Some "missing"))
  (check-false (ev st '((one waiting-command) present?))))

(test-case "exact newline/BOM/Unicode strings survive all fresh opens"
  (for ([contents '("one\ntwo\n" "one\ntwo" "one\r\ntwo\r\n" "lone\rCR" "\uFEFFλ\n" "")])
    (define-values (st calls) (state #:contents contents))
    (rich! st)
    (def! st 'done '(source find-file-submitted "a.txt"))
    (same st '(done current-buffer) (bound contents "/cwd/a.txt" 3))
    (check-equal? (all-calls calls) (read-calls "a.txt" "/cwd/a.txt"))))

;; Real runner, descriptor-compatible Term with exact fixed host call shapes.
;; Record the complete event sequence and the Fs state at every key boundary.
(define (scripted-run keys columns rows expected #:contents [contents "x"])
  (define-values (fs calls disk) (counted-fs #:contents contents))
  (define events (box '()))
  (define remaining keys)
  (define missing-at-key (box '()))
  (define (record x) (set-box! events (cons x (unbox events))))
  (define term
    (make-host-receiver
      (make-host-interface 'Term
        (list
          (make-host-method 'read-key '() 'String (lambda (state)
            (when (null? remaining) (error 'scripted-run "exhausted"))
            (define key (car remaining))
            (set! remaining (cdr remaining))
            (record (list 'key key))
            (set-box! missing-at-key (cons (host-receiver-send disk 'kind '("/cwd/new")) (unbox missing-at-key)))
            key))
          (make-host-method 'write-line '(String) 'String (lambda (state s) (error 'scripted-run "unexpected write-line")))
          (make-host-method 'write '(String) 'String (lambda (state s) (record (list 'write s)) s))
          (make-host-method 'columns '() 'Int (lambda (state) (record 'columns) columns))
          (make-host-method 'rows '() 'Int (lambda (state) (record 'rows) rows)))) #f))
  (run-aloemacs-with-hosts term fs)
  (check-equal? remaining '())
  (check-equal? (reverse (unbox events))
    (append-map (lambda (key painted) (list 'columns 'rows (list 'write painted) (list 'key key))) keys expected))
  (values calls disk (reverse (unbox missing-at-key))))
(define (runner-frame text column label [prompt-column #f] [columns 20] [rows 3]
                      #:name [name "untitled"])
  (define shown
    (if (and (>= rows 3) (not prompt-column) (equal? label name)) ""
        (substring label 0 (min columns (string-length label)))))
  (if (= rows 1)
      (editor-frame text 1 column)
      (frame (string-append text "\r\n") 1 column rows shown
        (if prompt-column rows 1) (or prompt-column column) #:name name #:width columns)))

(test-case "scripted runner prefix, redraw, typing, completion, edit/save, cancel and quit"
  (define keys '("ctrl-x" "unknown" "ctrl-x" "find" "n" "e" "w" "left" "right" "return"
                "x" "save" "ctrl-x" "save" "ctrl-x" "find" "z" "escape" "escape"))
  (define frames
    (append
      (make-list 4 (runner-frame "" 1 "untitled"))
      (for/list ([text '("/cwd/" "/cwd/n" "/cwd/ne" "/cwd/new" "/cwd/new" "/cwd/new")]
                 [col '(17 18 19 20 19 20)])
        (runner-frame "" 1 (string-append "Find file: " text) col))
      (list (runner-frame "" 1 "/cwd/new" #:name "/cwd/new") (runner-frame "x" 2 "/cwd/new" #:name "/cwd/new")
            (runner-frame "x" 2 "saved: /cwd/new" #:name "/cwd/new") (runner-frame "x" 2 "/cwd/new" #:name "/cwd/new")
            (runner-frame "x" 2 "saved: /cwd/new" #:name "/cwd/new") (runner-frame "x" 2 "/cwd/new" #:name "/cwd/new")
            (runner-frame "x" 2 "Find file: /cwd/" 17 #:name "/cwd/new") (runner-frame "x" 2 "Find file: /cwd/z" 18 #:name "/cwd/new")
            (runner-frame "x" 2 "/cwd/new" #:name "/cwd/new"))))
  (define-values (calls disk missing) (scripted-run keys 20 3 frames))
  (check-equal? (all-calls calls)
    '((current) (resolve "/cwd/new") (kind "/cwd/new") (resolve "/cwd/new")
      (kind "/cwd/new") (resolve "/cwd/new") (root? "/cwd/new")
      (parent "/cwd/new") (kind "/cwd") (resolve "/cwd") (write "/cwd/new" "x")
      (kind "/cwd/new") (resolve "/cwd/new") (write "/cwd/new" "x")
      (root? "/cwd/new") (parent "/cwd/new")))
  (check-equal? (effects calls 'read) '())
  (check-equal? (effects calls 'write) '((write "/cwd/new" "x") (write "/cwd/new" "x")))
  (check-equal? (take missing 12) (make-list 12 "missing"))
  (check-equal? (drop missing 12) (make-list 7 "file"))
  (check-equal? (host-receiver-send disk 'read '("/cwd/new")) "x"))

(test-case "runner opens regular contents and fits before frames, including one-row operation"
  (for ([rows '(3 1)])
    (define keys '("ctrl-x" "find" "a" "." "t" "x" "t" "return" "right" "right" "right" "escape"))
    (define frames
      (append (make-list 2 (runner-frame "" 1 "untitled" #f 2 rows))
        (for/list ([text '("/cwd/" "/cwd/a" "/cwd/a." "/cwd/a.t" "/cwd/a.tx" "/cwd/a.txt")])
          (runner-frame "" 1 (string-append "Find file: " text) (if (= rows 1) #f 2) 2 rows))
        (list (runner-frame "ab" 1 "/cwd/a.txt" #f 2 rows #:name "/cwd/a.txt")
              (runner-frame "ab" 2 "/cwd/a.txt" #f 2 rows #:name "/cwd/a.txt")
              (runner-frame "bc" 2 "/cwd/a.txt" #f 2 rows #:name "/cwd/a.txt")
              (runner-frame "cd" 2 "/cwd/a.txt" #f 2 rows #:name "/cwd/a.txt"))))
    (define-values (calls disk missing) (scripted-run keys 2 rows frames #:contents "abcd"))
    (check-equal? (all-calls calls) (cons '(current) (read-calls "/cwd/a.txt" "/cwd/a.txt")))
    (check-equal? (effects calls 'write) '())))

(test-case "remaining prefix misses, plain search/region/insertion/save, and quit keep their meanings"
  (define-values (st calls) (state))
  (rich! st)
  (def! st 'armed '(source handle-key "ctrl-x"))
  (same st '(armed handle-key "kill")
    (rebuild 'source #:echo "" #:prompt (prompt "/cwd/b.txt" 10 "Save as: ")
      #:waiting '(Option Some (AloemacsCommand SaveAs))))
  (same st '(armed handle-key "b")
    (rebuild 'source #:echo "" #:prompt (prompt "" 0 "Buffer: ")
      #:waiting '(Option Some (AloemacsCommand SelectBuffer))))
  (for ([key '("escape" "x" "s" "left" "undo" "return" "mark" "unknown" "" "ctrl-x" "kill-line" "yank")])
    (same st `(armed handle-key ,key) (rebuild 'source #:echo "")))
  (same st '(source handle-key "b")
    (rebuild 'source #:echo "" #:buffers (replace-current 'source '(rich-editor insert "b"))))
  (same st '(source handle-key "find")
    (rebuild 'source #:searching #t #:query "" #:origin '(source point) #:wrapped #f #:failing #f))
  ;; Mark (1,1) to point (2,4) removes econd\nthir, independently of dispatch.
  (def! st 'killed '(source handle-key "kill"))
  (check-equal? (ev st '((killed text) to-string)) "first\nsd-long\nfourth\nfifth")
  (check-equal? (ev st '((killed kill-ring) first)) "econd\nthir")
  (check-equal? (unbox calls) '())
  (def! st 'saved '(source handle-key "save"))
  (same st 'saved (rebuild 'source #:echo "saved"))
  (set-box! calls '())
  (same st '(armed handle-key "save") (rebuild 'source #:echo "saved"))
  (check-equal? (effects calls 'write) '((write "/cwd/b.txt" "first\nsecond\nthird-long\nfourth\nfifth")))
  (set-box! calls '())
  (def! st 'quit '(source request-quit))
  (for ([key '("ctrl-x" "find" "return" "save" "kill" "b" "escape")])
    (same st `(quit handle-key ,key) 'quit))
  (check-equal? (unbox calls) '()))
