#lang racket/base

(require racket/list racket/port racket/runtime-path rackunit
         "../../aloe/driver.rkt" "../../aloe/host.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/type.rkt" exn:fail:aloe-type? type-of type->datum)
         "../../host/racket/fs.rkt" "../../host/racket/aloemacs-run.rkt")

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define-runtime-path editor-path "../../examples/aloemacs/editor.aloe")
(define no-mark '(if #t (Option None) (Option Some (Position new 0 0))))
(define no-path '(if #t (Option None) (Option Some (Path new "/typed-none"))))
(define no-pending '(if #t (Option None) (Option Some aloemacs-global-keymap)))
(define no-prompt '(if #t (Option None) (Option Some (AloemacsPrompt new "" "" 0))))
(define no-submission '(if #t (Option None) (Option Some "")))
(define no-command '(if #t (Option None) (Option Some (AloemacsCommand FindFile))))
(define waiting '(Option Some (AloemacsCommand SelectBuffer)))
(define (prompt text [column (string-length text)] [label "Buffer: "])
  `(Option Some (AloemacsPrompt new ,label ,text ,column)))
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (type st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))

;; Every observable crossing is recorded, including current/resolve/inspection.
;; Disk probes in the proof bypass this receiver and are not application calls.
(define (counted-fs #:host-name [host-name 'FsHost])
  (define disk
    (make-fs-double "/cwd"
      (hash "/cwd" 'directory "/cwd/a.txt" 'file "/cwd/b.txt" 'file)
      (hash "/cwd/a.txt" "disk a" "/cwd/b.txt" "disk b")))
  (define calls (box '()))
  (define (forward selector args)
    (set-box! calls (cons (cons selector args) (unbox calls)))
    (host-receiver-send disk selector args))
  (define interface
    (make-host-interface host-name
      (for/list ([method (in-list (host-interface-methods fs-interface))])
        (define selector (host-method-selector method))
        (define params (host-method-parameter-types method))
        (make-host-method selector params (host-method-return-type method)
          (case (length params)
            [(0) (lambda (state) (forward selector '()))]
            [(1) (lambda (state a) (forward selector (list a)))]
            [(2) (lambda (state a b) (forward selector (list a b)))])))))
  (values (make-host-receiver interface #f) calls disk))
(define (state #:host-name [host-name 'FsHost])
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  (define-values (host calls disk) (counted-fs #:host-name host-name))
  (driver-inject-host! st 'fs-host host)
  (values st calls disk))
(define (all-calls calls) (reverse (unbox calls)))
(define (effects calls selector)
  (filter (lambda (call) (eq? (car call) selector)) (all-calls calls)))
(define (editor contents)
  `(AloemacsEditor new ((Text from-string ,contents) indexed-value)
     (Position new 0 0) #f 0 0 (List empty) ,no-mark 0))
(define (buffer contents [path no-path]) `(AloemacsBuffer new ,(editor contents) ,path))
(define (bound contents name) (buffer contents `(Option Some (Path new ,name))))
(define (zipper order focus)
  `(AloemacsBuffers new (List of ,@(reverse (take order focus)))
     ,(list-ref order focus) (List of ,@(drop order (add1 focus)))))
(define (session buffers)
  `(AloemacsSession new ,buffers (Fs new fs-host) "saved" #f "old query"
     (Position new 4 2) #t #t (List of "newest" "older")
     ,no-pending ,no-prompt ,no-submission ,no-command))
;; Expectations only construct and read values; they do not invoke lookup,
;; selected-buffers, or select-buffer-submitted to obtain an expected focus.
(define (rebuild s #:buffers [buffers `(,s buffers)] #:echo [echo `(,s echo)]
                 #:searching [searching `(,s searching)] #:query [query `(,s query)]
                 #:origin [origin `(,s origin)] #:wrapped [wrapped `(,s wrapped)]
                 #:failing [failing `(,s failing)] #:ring [ring `(,s kill-ring)]
                 #:pending [pending `(,s pending)] #:prompt [line `(,s prompt)]
                 #:submission [submission `(,s last-submission)]
                 #:waiting [command `(,s waiting-command)])
  `(AloemacsSession new ,buffers (,s fs) ,echo ,searching ,query ,origin
     ,wrapped ,failing ,ring ,pending ,line ,submission ,command))
(define (replace-current s new-editor)
  `(AloemacsBuffers new ((,s buffers) before)
     (AloemacsBuffer new ,new-editor (,s path)) ((,s buffers) after)))
(define (selected s buffers)
  (rebuild s #:buffers buffers #:echo "" #:searching #f #:query ""
    #:origin '(Position new 0 0) #:wrapped #f #:failing #f #:pending no-pending))
(define (completed s submitted buffers)
  (rebuild s #:buffers buffers #:echo "" #:searching #f #:query ""
    #:origin '(Position new 0 0) #:wrapped #f #:failing #f #:pending no-pending
    #:prompt no-prompt #:submission `(Option Some ,submitted) #:waiting no-command))
(define (missed s submitted)
  (rebuild s #:echo "failed" #:prompt no-prompt
    #:submission `(Option Some ,submitted) #:waiting no-command))
(define (rich! st)
  (def! st 'rich-editor
    '(AloemacsEditor new
       (Text indexed (List of "second" "first") "third-long" (List of "fourth" "fifth") 2)
       (Position new 2 4) #f 2 3
       (List of (UndoFrame new (Text from-string "old b") (Position new 0 2) 1 2))
       (Option Some (Position new 1 1)) 4))
  (def! st 'a
    '(AloemacsBuffer new
       (AloemacsEditor new (Text from-string "unsaved neighbor a") (Position new 0 3)
         #f 1 2 (rich-editor history) (Option Some (Position new 0 1)) 5)
       (Option Some (Path new "/cwd/a.txt"))))
  (def! st 'b '(AloemacsBuffer new rich-editor (Option Some (Path new "/cwd/b.txt"))))
  (def! st 'c
    `(AloemacsBuffer new
       (AloemacsEditor new (Text indexed (List of "c first") "c second" (List empty) 1)
         (Position new 1 2) #f 1 1 (rich-editor history)
         (Option Some (Position new 0 1)) 3)
       ,no-path))
  (def! st 'source (session (zipper '(a b c) 1))))
(define (draft! st [text "/cwd/a.txt"])
  (def! st 'draft (rebuild 'source #:prompt (prompt text)
    #:submission '(Option Some "previous") #:waiting waiting)))
(define (datums path) (call-with-input-file path (lambda (in) (port->list read in))))
(define (declaration ds name) (findf (lambda (d) (equal? (cadr d) name)) ds))
(define (editor-frame body row column)
  (string-append "\u001b[?25l\u001b[2J\u001b[H" body
    (format "\u001b[~a;~aH\u001b[?25h" row column)))
(define (frame body text-row text-column rows shown cursor-row cursor-column)
  (string-append (editor-frame body text-row text-column)
    (format "\u001b[?25l\u001b[~a;1H~a\u001b[~a;~aH\u001b[?25h"
      rows shown cursor-row cursor-column)))
(define (runner-frame text column label [prompt-column #f] [columns 20] [rows 3])
  (define shown (substring label 0 (min columns (string-length label))))
  (if (= rows 1) (editor-frame text 1 column)
      (frame (string-append text "\r\n") 1 column rows shown
        (if prompt-column rows 1) (or prompt-column column))))

(test-case "SelectBuffer signature, thirteen fields, unchanged editor shapes and final maps"
  (define ds (datums file-path))
  (define methods (cdr (cadddr (declaration ds '(AloemacsSession H)))))
  (check-equal? (drop-right (assoc 'select-buffer-submitted methods) 1)
    '(select-buffer-submitted (submitted String) (AloemacsSession H)))
  (check-equal? (caddr (declaration ds '(AloemacsSession H)))
    '(fields (buffers AloemacsBuffers) (fs (Fs H)) (echo String) (searching Bool)
       (query String) (origin Position) (wrapped Bool) (failing Bool)
       (kill-ring (List String)) (pending (Option (AloemacsKeymap AloemacsBinding)))
       (prompt (Option AloemacsPrompt)) (last-submission (Option String))
       (waiting-command (Option AloemacsCommand))))
  (define es (datums editor-path))
  (check-equal? (caddr (declaration es 'AloemacsEditor))
    '(fields (text Text) (point Position) (quit Bool) (scroll-row Int) (scroll-col Int)
       (history (List UndoFrame)) (mark (Option Position)) (text-rows Int)))
  (check-equal? (caddr (declaration es 'UndoFrame))
    '(fields (text Text) (point Position) (scroll-row Int) (scroll-col Int)))
  (check-equal? (caddr (declaration ds 'AloemacsCommand))
    '(constructors (Newline (fields)) (BackwardDelete (fields)) (MoveLeft (fields))
       (MoveRight (fields)) (MoveUp (fields)) (MoveDown (fields)) (LineStart (fields))
       (LineEnd (fields)) (PageUp (fields)) (PageDown (fields)) (BufferStart (fields))
       (BufferEnd (fields)) (RequestQuit (fields)) (Undo (fields)) (SetMark (fields))
       (Kill (fields)) (KillLine (fields)) (Yank (fields)) (Find (fields)) (Save (fields))
       (SelfInsert (fields)) (SwitchBuffer (fields)) (KillBuffer (fields))
       (FindFile (fields)) (SaveAs (fields)) (SelectBuffer (fields))))
  (check-equal? (map (lambda (m) (drop-right m 1))
    (cdr (cadddr (declaration ds 'AloemacsCommand)))) '((name () String)))
  (define-values (st calls disk) (state))
  (same st '(aloemacs-ctrl-x-keymap bindings)
    '(List of (AloemacsBinding Command "save" aloemacs-save-command)
              (AloemacsBinding Command "find" (AloemacsCommand FindFile))
              (AloemacsBinding Command "kill" (AloemacsCommand SaveAs))
              (AloemacsBinding Command "b" (AloemacsCommand SelectBuffer))))
  (check-false (ev st '((aloemacs-ctrl-x-keymap default) present?)))
  (define global-rows
    '(("return" Newline) ("backspace" BackwardDelete) ("left" MoveLeft) ("right" MoveRight)
      ("up" MoveUp) ("down" MoveDown) ("line-start" LineStart) ("line-end" LineEnd)
      ("page-up" PageUp) ("page-down" PageDown) ("buffer-start" BufferStart)
      ("buffer-end" BufferEnd) ("escape" RequestQuit) ("undo" Undo) ("mark" SetMark)
      ("kill" Kill) ("kill-line" KillLine) ("yank" Yank) ("find" Find) ("save" Save)))
  (same st '(aloemacs-global-keymap bindings)
    `(List of ,@(for/list ([row global-rows])
      `(AloemacsBinding Command ,(car row) (AloemacsCommand ,(cadr row))))
      (AloemacsBinding Prefix "ctrl-x" aloemacs-ctrl-x-keymap)))
  (same st '(aloemacs-global-keymap default) '(Option Some (AloemacsCommand SelfInsert)))
  (check-equal? (unbox calls) '()))

(test-case "checked command and submitted sends retain two concrete hosts and reject invalid sends"
  (for ([host-name '(FsHost AlternateFsHost)])
    (define-values (st calls disk) (state #:host-name host-name))
    (rich! st)
    (def! st 'command '(AloemacsCommand SelectBuffer))
    (check-equal? (type st 'command) 'AloemacsCommand)
    (check-equal? (ev st '(command name)) "select-buffer")
    (for ([send '((source select-buffer-submitted "")
                  (source select-buffer-submitted "/cwd/a.txt")
                  (source execute-command command "ignored")
                  (source start-command-prompt command "Buffer: ")
                  (source run-submitted-command) (source submit-prompt)
                  (source switch-buffer))])
      (check-equal? (type st send) `(AloemacsSession ,host-name)))
    (for ([bad '((AloemacsCommand SelectBuffer 0) (AloemacsCommand SelectBuffer "x")
                 (command name 0) (command execute-command "x")
                 (source select-buffer-submitted) (source select-buffer-submitted 0)
                 (source select-buffer-submitted (Path new "x"))
                 (source select-buffer-submitted (Option Some "x"))
                 (source select-buffer-submitted "x" "y")
                 (source switch-buffer "x"))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st bad)) (format "reject ~s" bad)))
    (for ([receiver '(1 "x" command AloemacsSession AloemacsBuffer (source editor)
                       (source current-buffer) (source buffers))])
      (check-exn exn:fail:aloe-type?
        (lambda () (ev st `(,receiver select-buffer-submitted "x")))))
    (define valid (session '(source buffers)))
    (for ([bad (list (drop-right valid 1) (append valid '(0)))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
    (same st '(source select-buffer-submitted "/cwd/a.txt")
      (selected 'source (zipper '(a b c) 0)))
    (check-equal? (unbox calls) '())))

(test-case "direct and C-x b starts, whole-session guards, orphan replacement and plain b"
  (define-values (st calls disk) (state))
  (rich! st)
  (define before (ev st 'source))
  (same st '(source execute-command (AloemacsCommand SelectBuffer) "/cwd/a.txt")
    (rebuild 'source #:prompt (prompt "") #:waiting waiting))
  (def! st 'armed '(source handle-key "ctrl-x"))
  (same st 'armed (rebuild 'source #:echo "" #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (same st '(armed handle-key "b")
    (rebuild 'source #:echo "" #:prompt (prompt "") #:waiting waiting))
  (for ([fixture (list
                   (rebuild 'source #:buffers (replace-current 'source '(rich-editor request-quit)))
                   (rebuild 'source #:searching #t)
                   (rebuild 'source #:pending '(Option Some aloemacs-ctrl-x-keymap))
                   (rebuild 'source #:prompt (prompt "old" 2 "Old: ")))])
    (def! st 'guarded fixture)
    (def! st 'guarded (rebuild 'guarded #:waiting '(Option Some (AloemacsCommand SaveAs))
                                        #:submission '(Option Some "old answer")))
    (same st '(guarded execute-command (AloemacsCommand SelectBuffer) "ignored") 'guarded)
    (same st '(guarded start-command-prompt (AloemacsCommand SelectBuffer) "Buffer: ") 'guarded))
  (def! st 'orphan (rebuild 'source #:waiting '(Option Some (AloemacsCommand FindFile))))
  (same st '(orphan execute-command (AloemacsCommand SelectBuffer) "ignored")
    (rebuild 'orphan #:prompt (prompt "") #:waiting waiting))
  (same st '(source handle-key "b")
    (rebuild 'source #:echo "" #:buffers (replace-current 'source '(rich-editor insert "b"))))
  (check-equal? (ev st 'source) before)
  (check-equal? (unbox calls) '()))

(test-case "prompt edits, ignored keys, LF, fit and redraw retain the selection slot and buffers"
  (define-values (st calls disk) (state))
  (rich! st)
  (draft! st "abc")
  (define before (ev st 'draft))
  (for ([row '(("b" "abcb" 4) ("backspace" "ab" 2) ("left" "abc" 2)
               ("right" "abc" 3) ("line-start" "abc" 0) ("line-end" "abc" 3))])
    (same st `(draft handle-key ,(car row))
      (rebuild 'draft #:prompt (prompt (cadr row) (caddr row)))))
  (def! st 'middle (rebuild 'draft #:prompt (prompt "abc" 1)))
  (same st '(middle handle-key "b") (rebuild 'middle #:prompt (prompt "abbc" 2)))
  (for ([key '("\n" "save" "find" "ctrl-x" "kill" "kill-line" "yank" "undo" "mark"
              "up" "down" "page-up" "buffer-end" "unknown" "select-buffer" "")])
    (same st `(draft handle-key ,key) 'draft))
  (same st '(draft ensure-visible 2 2)
    (rebuild 'draft #:buffers (replace-current 'draft
      '(AloemacsEditor new (draft text) (draft point) #f 2 3
         (rich-editor history) (rich-editor mark) 1))))
  (for ([i (in-range 2)])
    (check-equal? (ev st '(draft frame 12 3))
      (frame "rd-long\r\nrth" 1 2 3 "Buffer: abc" 3 12)))
  (check-equal? (ev st 'draft) before)
  (check-equal? (unbox calls) '()))

(test-case "full-path and untitled completions retain rich editors, paths, order and source snapshots"
  (define-values (st calls disk) (state))
  (rich! st)
  (define old (for/list ([x '(source a b c rich-editor)]) (ev st x)))
  (for ([name '("/cwd/a.txt" "untitled" "/cwd/b.txt")] [focus '(0 2 1)])
    (draft! st name)
    (define before (ev st 'draft))
    (def! st 'done '(draft handle-key "return"))
    (same st 'done (completed 'draft name (zipper '(a b c) focus)))
    (same st '(done current-buffer) (list-ref '(a b c) focus))
    (same st '(done last-submission) `(Option Some ,name))
    (same st '(done submit-prompt) 'done)
    (check-equal? (ev st 'draft) before))
  ;; No fit or edit between either direction of this round trip.
  (draft! st "/cwd/a.txt")
  (def! st 'away '(draft submit-prompt))
  (def! st 'back '(away execute-command (AloemacsCommand SelectBuffer) "ignored"))
  (def! st 'back (rebuild 'back #:prompt (prompt "/cwd/b.txt")))
  (def! st 'back '(back submit-prompt))
  (same st 'back (completed 'draft "/cwd/b.txt" (zipper '(a b c) 1)))
  (check-equal? (for/list ([x '(source a b c rich-editor)]) (ev st x)) old)
  (check-equal? (unbox calls) '()))

(test-case "direct hits accept the departing search point and reset only selection fields"
  (define-values (st calls disk) (state))
  (rich! st)
  (draft! st)
  (def! st 'raw (rebuild 'draft #:searching #t #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (define before (ev st 'raw))
  (for ([s '(source raw)])
    (for ([name '("/cwd/b.txt" "/cwd/a.txt" "untitled")] [focus '(1 0 2)])
      (same st `(,s select-buffer-submitted ,name) (selected s (zipper '(a b c) focus)))))
  (check-equal? (ev st 'raw) before)
  (same st '((raw select-buffer-submitted "/cwd/a.txt") buffers) (zipper '(a b c) 0))
  (same st 'b '(AloemacsBuffer new rich-editor (Option Some (Path new "/cwd/b.txt"))))
  (check-equal? (unbox calls) '()))

(test-case "current-first and first-forward duplicate selection before and across wrap"
  (define-values (st calls disk) (state))
  (def! st 'a (bound "first duplicate" "same"))
  (def! st 'b (bound "second duplicate" "same"))
  (def! st 'c (bound "other current" "other"))
  (def! st 'd (bound "third duplicate" "same"))
  (for ([row '(((a b c d) 0 0) ((a b c d) 1 1) ((a c b d) 1 2)
               ((a b d c) 3 0) ((c a b d) 0 1))])
    (define order (car row))
    (def! st 'source (session (zipper order (cadr row))))
    (draft! st "same")
    (define before (ev st 'draft))
    (same st '(draft submit-prompt) (completed 'draft "same" (zipper order (caddr row))))
    (check-equal? (ev st 'draft) before))
  (check-equal? (unbox calls) '()))

(test-case "multiple untitled buffers and literal untitled collisions have no kind preference"
  (define-values (st calls disk) (state))
  (def! st 'a (buffer "pathless first"))
  (def! st 'b (buffer "pathless second"))
  (def! st 'c (bound "bound literal" "untitled"))
  (def! st 'd (bound "nonmatching" "/cwd/d"))
  (for ([row '(((a b d) 0 0) ((a b d) 2 0) ((d a b) 0 1)
               ((d a c) 0 1) ((d c a) 0 1) ((a c d) 2 0) ((c a d) 2 0)
               ((a c d) 1 1) ((c a d) 1 1))])
    (define order (car row))
    (def! st 'source (session (zipper order (cadr row))))
    (draft! st "untitled")
    (same st '(draft submit-prompt) (completed 'draft "untitled" (zipper order (caddr row)))))
  (check-equal? (unbox calls) '()))

(test-case "equal-valued distinct positions do not terminate the bounded scan early"
  (define-values (st calls disk) (state))
  (def! st 'a (bound "equal payload" "same"))
  (def! st 'b (bound "equal payload" "same"))
  (def! st 'c (bound "target after equal positions" "target"))
  (same st 'a 'b)
  (for ([row '(((a b c) 0 2) ((a b c) 1 2) ((c a b) 1 0))])
    (define order (car row))
    (def! st 'source (session (zipper order (cadr row))))
    (define before (ev st 'source))
    (same st '(source select-buffer-submitted "target")
      (selected 'source (zipper order (caddr row))))
    (same st '(source select-buffer-submitted "missing") (rebuild 'source #:echo "failed"))
    (check-false (ev st '(((source buffers) find-name "missing") present?)))
    (check-equal? (ev st 'source) before))
  (def! st 'source (session (zipper '(a b c) 0)))
  (same st '(source select-buffer-submitted "same") (selected 'source (zipper '(a b c) 0)))
  (for ([budget '(-1 0 1 2)])
    (check-false (ev st `(((source buffers) find-name-in "target" ,budget) present?))))
  (same st '((source buffers) find-name-in "target" 3) `(Option Some ,(zipper '(a b c) 2)))
  (check-equal? (unbox calls) '()))

(test-case "direct misses retain all buffers, search, pending and protocol fields exactly"
  (define-values (st calls disk) (state))
  (rich! st)
  (draft! st)
  (def! st 'raw (rebuild 'draft #:searching #t #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (define before (ev st 'raw))
  (for ([name '("" "a.txt" "./a.txt" "/cwd/./a.txt" "/CWD/a.txt" "/cwd/A.txt"
               " /cwd/a.txt" "/cwd/a.txt " "  " "unknown")])
    (same st `(raw select-buffer-submitted ,name) (rebuild 'raw #:echo "failed")))
  (check-equal? (ev st 'raw) before)
  (def! st 'empty-path (bound "raw empty stored path" ""))
  (def! st 'raw (rebuild 'raw #:buffers (zipper '(a empty-path c) 1)))
  (same st '(raw select-buffer-submitted "") (rebuild 'raw #:echo "failed"))
  (same st '((raw buffers) current-buffer) 'empty-path)
  (check-equal? (unbox calls) '()))

(test-case "completed misses end prompt, retain exact submission, and do not apply selection resets"
  (define-values (st calls disk) (state))
  (rich! st)
  (for ([name '("" "a.txt" "./a.txt" "/cwd/./a.txt" "/CWD/a.txt" "/cwd/A.txt"
               " /cwd/a.txt" "/cwd/a.txt " "  " "unknown")])
    (draft! st name)
    (def! st 'draft (rebuild 'draft #:searching #t #:pending '(Option Some aloemacs-ctrl-x-keymap)))
    (define before (ev st 'draft))
    ;; A direct submit completes even this mixed raw search/prefix fixture.
    (def! st 'done '(draft submit-prompt))
    (same st 'done (missed 'draft name))
    (same st '(done submit-prompt) 'done)
    (check-equal? (ev st 'draft) before))
  (def! st 'source (rebuild 'source #:buffers (zipper (list (bound "empty name" "") 'a 'c) 0)))
  (draft! st "")
  (same st '(draft submit-prompt) (missed 'draft ""))
  (check-equal? (unbox calls) '()))

(test-case "relative, space and case names match only their exact stored string"
  (define-values (st calls disk) (state))
  (define order (list (bound "relative" "./a.txt") (bound "spaces" "  ")
                      (bound "case" "/CWD/A.txt")))
  (def! st 'source (session (zipper order 1)))
  (for ([name '("./a.txt" "  " "/CWD/A.txt")] [focus '(0 1 2)])
    (draft! st name)
    (same st '(draft submit-prompt) (completed 'draft name (zipper order focus))))
  (for ([name '("a.txt" "/cwd/a.txt" " " "/cwd/A.txt")])
    (same st `(source select-buffer-submitted ,name) (rebuild 'source #:echo "failed")))
  (check-equal? (unbox calls) '()))

(test-case "Escape and direct cancellation preserve saved/failed echo and old submissions"
  (define-values (st calls disk) (state))
  (rich! st)
  (for* ([echo '("" "saved" "failed")]
         [submission (list no-submission '(Option Some "previous"))])
    (def! st 'source (rebuild 'source #:echo echo #:submission submission))
    (def! st 'active '(source execute-command (AloemacsCommand SelectBuffer) "ignored"))
    (def! st 'active (rebuild 'active #:prompt (prompt "/cwd/a.txt")))
    (define before (ev st 'active))
    (for ([send '((active handle-key "escape") (active cancel-prompt))])
      (same st send (rebuild 'active #:prompt no-prompt #:waiting no-command)))
    (check-equal? (ev st 'active) before)
    (check-false (ev st '((active handle-key "escape") quit))))
  (draft! st "/cwd/a.txt")
  (def! st 'done '(draft submit-prompt))
  (def! st 'later '(done execute-command (AloemacsCommand SelectBuffer) "ignored"))
  (def! st 'later '(later handle-key "b"))
  (same st '(later handle-key "escape") (rebuild 'done))
  (draft! st "unknown")
  (def! st 'failed '(draft submit-prompt))
  (def! st 'later '(failed execute-command (AloemacsCommand SelectBuffer) "ignored"))
  (same st '(later handle-key "escape") 'failed)
  (def! st 'mixed (rebuild 'later #:searching #t #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (same st '(mixed cancel-prompt) (rebuild 'mixed #:prompt no-prompt #:waiting no-command))
  (check-equal? (unbox calls) '()))

(test-case "inactive submit, orphan cancel, absent slot and unsupported completion retain the protocol"
  (define-values (st calls disk) (state))
  (rich! st)
  (def! st 'orphan (rebuild 'source #:submission '(Option Some "/cwd/a.txt") #:waiting waiting))
  (same st '(orphan submit-prompt) 'orphan)
  (same st '(orphan cancel-prompt) (rebuild 'orphan #:waiting no-command))
  (same st '(source cancel-prompt) 'source)
  (for ([name '("" "/cwd/a.txt")])
    (def! st 'direct '(source start-prompt "Direct: "))
    (def! st 'direct (rebuild 'direct #:prompt (prompt name (string-length name) "Direct: ")))
    (same st '(direct submit-prompt)
      (rebuild 'direct #:prompt no-prompt #:submission `(Option Some ,name))))
  (draft! st)
  (for ([command '(SelfInsert SwitchBuffer KillBuffer Save Find)])
    (def! st 'unsupported (rebuild 'draft #:waiting `(Option Some (AloemacsCommand ,command))))
    (same st '(unsupported submit-prompt)
      (rebuild 'unsupported #:prompt no-prompt #:submission '(Option Some "/cwd/a.txt") #:waiting no-command)))
  (for ([command '(SelectBuffer FindFile SaveAs SwitchBuffer)])
    (def! st 'missing (rebuild 'source #:waiting `(Option Some (AloemacsCommand ,command))))
    (same st '(missing run-submitted-command) (rebuild 'missing #:waiting no-command)))
  ;; An inactive Return keeps its ordinary editor meaning.
  (same st '(source handle-key "return")
    (rebuild 'source #:echo "" #:buffers (replace-current 'source '(rich-editor newline))))
  (check-equal? (unbox calls) '()))

(test-case "direct cycling preserves prompt/slot and inactive submit cannot select again"
  (define-values (st calls disk) (state))
  (rich! st)
  (draft! st)
  (same st '(draft switch-buffer) (selected 'draft (zipper '(a b c) 2)))
  (same st '(draft execute-command (AloemacsCommand SwitchBuffer) "ignored")
    (selected 'draft (zipper '(a b c) 2)))
  (def! st 'done '(draft submit-prompt))
  (def! st 'cycled '(done switch-buffer))
  (same st 'cycled (completed 'draft "/cwd/a.txt" (zipper '(a b c) 1)))
  (same st '(cycled submit-prompt) 'cycled)
  ;; A direct selection during a prompt does not store or replace a target.
  (def! st 'changed '(draft select-buffer-submitted "untitled"))
  (same st '(changed submit-prompt) (completed 'draft "/cwd/a.txt" (zipper '(a b c) 0)))
  (check-equal? (unbox calls) '()))

(test-case "full frames restore selected text cursors, safe display keeps exact names, and one row works"
  (define-values (st calls disk) (state))
  (def! st 'a (buffer "ab\nsecond"))
  (def! st 'b
    `(AloemacsBuffer new
       (AloemacsEditor new ((Text from-string "other") indexed-value) (Position new 0 2)
         #f 0 0 (List empty) ,no-mark 2)
       (Option Some (Path new "/cwd/b.txt"))))
  (def! st 'source (session (zipper '(a b) 0)))
  (def! st 'active '(source execute-command (AloemacsCommand SelectBuffer) "ignored"))
  (check-equal? (ev st '(active frame 20 3)) (frame "ab\r\nsecond" 1 1 3 "Buffer: " 3 9))
  (def! st 'typed (rebuild 'active #:prompt (prompt "/cwd/b.txt")))
  (check-equal? (ev st '(typed frame 12 3)) (frame "ab\r\nsecond" 1 1 3 "Buffer: /cwd" 3 12))
  (def! st 'done '(typed submit-prompt))
  (check-equal? (ev st '(done frame 20 3)) (frame "other\r\n" 1 3 3 "/cwd/b.txt" 1 3))
  (def! st 'failed (rebuild 'active #:prompt (prompt "missing")))
  (def! st 'failed '(failed submit-prompt))
  (check-equal? (ev st '(failed frame 20 3)) (frame "ab\r\nsecond" 1 1 3 "failed: untitled" 1 1))
  (def! st 'cancel '(typed handle-key "escape"))
  (check-equal? (ev st '(cancel frame 20 3)) (frame "ab\r\nsecond" 1 1 3 "saved: untitled" 1 1))
  (define unsafe "\t\r\u001b\u0000\u007f λabcdef")
  (def! st 'unsafe-buffer (bound "unsafe target" unsafe))
  (def! st 'safe (rebuild 'active #:buffers (zipper '(a unsafe-buffer) 0) #:prompt (prompt unsafe)))
  (define before (ev st 'safe))
  (for ([i (in-range 2)])
    (check-equal? (ev st '(safe frame 12 3)) (frame "ab\r\nsecond" 1 1 3 "Buffer:     " 3 12)))
  (def! st 'safe-done '(safe submit-prompt))
  (same st 'safe-done (completed 'safe unsafe (zipper '(a unsafe-buffer) 1)))
  (same st '(safe-done last-submission) `(Option Some ,unsafe))
  (check-equal? (ev st 'safe) before)
  (for ([s '(active typed done failed cancel safe safe-done)])
    (check-equal? (ev st `(,s frame 20 1)) (ev st `((,s editor) frame 20 1))))
  (def! st 'one '(typed ensure-visible 20 1))
  (def! st 'one-a '(one current-buffer))
  (def! st 'one '(one submit-prompt))
  (same st 'one (completed 'one "/cwd/b.txt" (zipper '(one-a b) 1)))
  (check-equal? (ev st '(one frame 20 1)) (editor-frame "other" 1 3))
  (check-equal? (unbox calls) '()))

(test-case "search precedes mixed prompt/prefix input and quit absorbs selection keys"
  (define-values (st calls disk) (state))
  (rich! st)
  (draft! st)
  (def! st 'mixed (rebuild 'draft #:searching #t #:query "" #:origin '(draft point)
    #:wrapped #f #:failing #f #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (same st '(mixed handle-key "b") '(mixed search-key "b"))
  (same st '((mixed handle-key "b") prompt) '(mixed prompt))
  (same st '((mixed handle-key "b") waiting-command) waiting)
  (check-equal? (ev st '((mixed handle-key "b") query)) "b")
  (def! st 'quit '(mixed request-quit))
  (for ([key '("ctrl-x" "find" "return" "save" "kill" "b" "escape" "unknown")])
    (same st `(quit handle-key ,key) 'quit))
  (check-equal? (unbox calls) '()))

(test-case "idle command-name misses, remaining consumed prefix misses and old plain keys"
  (define-values (st calls disk) (state))
  (rich! st)
  (for ([key '("select-buffer" "switch-buffer" "kill-buffer" "find-file" "save-as")])
    (same st `(source handle-key ,key) (rebuild 'source #:echo "")))
  (def! st 'armed '(source handle-key "ctrl-x"))
  (for ([key '("escape" "x" "s" "left" "undo" "return" "mark" "unknown" ""
              "ctrl-x" "kill-line" "yank" "select-buffer" "switch-buffer")])
    (same st `(armed handle-key ,key) (rebuild 'source #:echo "")))
  (same st '(source handle-key "find")
    (rebuild 'source #:searching #t #:query "" #:origin '(source point) #:wrapped #f #:failing #f))
  (def! st 'killed '(source handle-key "kill"))
  (check-equal? (ev st '((killed text) to-string)) "first\nsd-long\nfourth\nfifth")
  (same st '(killed kill-ring) '(List of "econd\nthir" "newest" "older"))
  (check-equal? (unbox calls) '())
  (for ([send '((source handle-key "save") (armed handle-key "save"))])
    (set-box! calls '())
    (same st send (rebuild 'source #:echo "saved"))
    (check-equal? (all-calls calls)
      '((kind "/cwd/b.txt") (resolve "/cwd/b.txt")
        (write "/cwd/b.txt" "first\nsecond\nthird-long\nfourth\nfifth")))))

;; Production runner, fixed host call shapes, exact full event order. Capture
;; all Fs calls at every key boundary to isolate both selection segments.
(define (scripted-run keys columns rows expected)
  (define-values (fs calls disk) (counted-fs))
  (define events (box '()))
  (define snapshots (box '()))
  (define remaining keys)
  (define (record x) (set-box! events (cons x (unbox events))))
  (define term
    (make-host-receiver
      (make-host-interface 'Term
        (list
          (make-host-method 'read-key '() 'String (lambda (state)
            (when (null? remaining) (error 'scripted-run "exhausted"))
            (define key (car remaining))
            (set! remaining (cdr remaining))
            (record (list 'key key))
            (set-box! snapshots (cons (all-calls calls) (unbox snapshots)))
            key))
          (make-host-method 'write-line '(String) 'String (lambda (state s) (error 'scripted-run "unexpected write-line")))
          (make-host-method 'write '(String) 'String (lambda (state s) (record (list 'write s)) s))
          (make-host-method 'columns '() 'Int (lambda (state) (record 'columns) columns))
          (make-host-method 'rows '() 'Int (lambda (state) (record 'rows) rows)))) #f))
  (run-aloemacs-with-hosts term fs "/cwd/a.txt")
  (check-equal? remaining '())
  (check-equal? (reverse (unbox events))
    (append-map (lambda (key painted) (list 'columns 'rows (list 'write painted) (list 'key key))) keys expected))
  (values calls disk (reverse (unbox snapshots))))

(test-case "runner opens neighbor, selects original, edits/saves there and retains neighbor at one or three rows"
  (for* ([rows '(3 1)] [columns '(20 2)])
    (define keys
      (append '("right" "right" "ctrl-x" "find" "b" "." "t" "x" "t" "return" "ctrl-x" "b")
        (map string (string->list "/cwd/a.txt"))
        '("return" "!" "save" "ctrl-x" "b")
        (map string (string->list "/cwd/b.txt")) '("return" "escape")))
    (define narrow? (= columns 2))
    (define (paint text column label [prompt-column #f])
      (runner-frame text column label
        (and prompt-column (min columns prompt-column)) columns rows))
    (define old-visible (if narrow? "is" "disk a"))
    (define old-column (if narrow? 2 3))
    (define neighbor-visible (if narrow? "di" "disk b"))
    (define edited-visible (if narrow? "!s" "di!sk a"))
    (define edited-column (if narrow? 2 4))
    (define (typing-frames text column label input)
      (for/list ([n (in-range (add1 (string-length input)))])
        (paint text column (string-append label (substring input 0 n))
          (+ (string-length label) n 1))))
    (define frames
      (append
        (list (paint (if narrow? "di" "disk a") 1 "/cwd/a.txt")
              (paint (if narrow? "di" "disk a") 2 "/cwd/a.txt")
              (paint old-visible old-column "/cwd/a.txt")
              (paint old-visible old-column "/cwd/a.txt"))
        (typing-frames old-visible old-column "Find file: " "b.txt")
        (make-list 2 (paint neighbor-visible 1 "/cwd/b.txt"))
        (typing-frames neighbor-visible 1 "Buffer: " "/cwd/a.txt")
        (list (paint old-visible old-column "/cwd/a.txt")
              (paint edited-visible edited-column "/cwd/a.txt")
              (paint edited-visible edited-column "saved: /cwd/a.txt")
              (paint edited-visible edited-column "/cwd/a.txt"))
        (typing-frames edited-visible edited-column "Buffer: " "/cwd/b.txt")
        (list (paint neighbor-visible 1 "/cwd/b.txt"))))
    (define-values (calls disk snapshots) (scripted-run keys columns rows frames))
    (define startup
      '((resolve "/cwd/a.txt") (resolve "/cwd/a.txt")
        (kind "/cwd/a.txt") (resolve "/cwd/a.txt")
        (kind "/cwd/a.txt") (resolve "/cwd/a.txt") (read "/cwd/a.txt")))
    (define opening
      '((resolve "b.txt") (kind "/cwd/b.txt") (resolve "/cwd/b.txt")
        (kind "/cwd/b.txt") (resolve "/cwd/b.txt") (read "/cwd/b.txt")))
    (define saving '((kind "/cwd/a.txt") (resolve "/cwd/a.txt") (write "/cwd/a.txt" "di!sk a")))
    (check-equal? (all-calls calls) (append startup opening saving))
    (check-equal? (take snapshots 10) (make-list 10 startup))
    ;; Includes both prefix keys, every typed name key, Return and following edit/save.
    (check-equal? (take (drop snapshots 10) 15) (make-list 15 (append startup opening)))
    (check-equal? (drop snapshots 25) (make-list 14 (append startup opening saving)))
    (check-equal? (map (lambda (op) (length (effects calls op))) '(resolve kind read write)) '(8 5 2 1))
    (check-equal? (host-receiver-send disk 'read '("/cwd/a.txt")) "di!sk a")
    (check-equal? (host-receiver-send disk 'read '("/cwd/b.txt")) "disk b")))
