#lang racket/base

(require racket/list racket/port racket/runtime-path racket/string rackunit
         "../../aloe/driver.rkt" "../../aloe/host.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/env.rkt" env-bound?)
         (only-in "../../aloe/type.rkt" exn:fail:aloe-type? type-of type->datum)
         "../../host/racket/fs.rkt" "../../host/racket/term.rkt")

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define-runtime-path editor-path "../../examples/aloemacs/editor.aloe")
(define no-mark '(if #t (Option None) (Option Some (Position new 0 0))))
(define no-path '(if #t (Option None) (Option Some (Path new ""))))
(define no-pending '(if #t (Option None) (Option Some aloemacs-global-keymap)))
(define no-prompt '(if #t (Option None) (Option Some (AloemacsPrompt new "" "" 0))))
(define no-submission '(if #t (Option None) (Option Some "")))
(define no-command '(if #t (Option None) (Option Some (AloemacsCommand SaveAs))))
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))
(define (dtype st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))
(define (loaded)
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  st)
(define (state)
  (define st (loaded))
  (define disk (make-fs-double "/cwd" (hash "/cwd" 'directory "/cwd/a.txt" 'file)
                               (hash "/cwd/a.txt" "disk")))
  (define calls (box '()))
  (define (forward selector args)
    (set-box! calls (append (unbox calls) (list (cons selector args))))
    (host-receiver-send disk selector args))
  (define interface
    (make-host-interface 'FsHost
      (for/list ([method (in-list (host-interface-methods fs-interface))])
        (define selector (host-method-selector method))
        (define params (host-method-parameter-types method))
        (make-host-method selector params (host-method-return-type method)
          (case (length params)
            [(0) (lambda (_) (forward selector '()))]
            [(1) (lambda (_ a) (forward selector (list a)))]
            [(2) (lambda (_ a b) (forward selector (list a b)))])))))
  (driver-inject-host! st 'fs-host (make-host-receiver interface #f))
  (values st calls))

;; All expected payloads, rectangles and ANSI bytes are constructed here,
;; without using a product layout, fit, composition or selection helper.
(define (indexed lines focus)
  `(Text indexed (List of ,@(reverse (take lines focus))) ,(list-ref lines focus)
     (List of ,@(drop lines (add1 focus))) ,focus))
(define history '(List of (UndoFrame new (Text from-string "old") (Position new 0 2) 1 2)))
(define (editor text [line 0] [column 0] [row 0] [left 0] [rows 0] [quit #f])
  `(AloemacsEditor new ,text (Position new ,line ,column) ,quit ,row ,left
     ,history (Option Some (Position new 0 1)) ,rows))
(define (buffer id ed [path no-path]) `(AloemacsBuffer new ,ed ,path ,id))
(define (zipper buffers focus)
  `(AloemacsBuffers new (List of ,@(reverse (take buffers focus))) ,(list-ref buffers focus)
     (List of ,@(drop buffers (add1 focus)))))
(define (leaf id [buffer-id 41] [row 0] [left 0] [lock #f])
  `(AloemacsWindowTree Leaf (AloemacsView new ,id ,buffer-id ,row ,left ,lock)))
(define (below a b) `(AloemacsWindowTree Below ,a ,b))
(define (right a b) `(AloemacsWindowTree Right ,a ,b))
(define (rect x y w h) `(AloemacsWindowRect new ,x ,y ,w ,h))
(define (config tree selected [columns 0] [rows 0])
  `(AloemacsWindows new ,tree ,selected ,columns ,rows))
(define (session buffers tree selected #:columns [columns 80] #:rows [rows 24]
                 #:echo [echo "saved"] #:searching [searching #f] #:query [query "old"]
                 #:wrapped [wrapped #t] #:failing [failing #t]
                 #:pending [pending no-pending] #:prompt [prompt no-prompt]
                 #:waiting [waiting no-command])
  `(AloemacsSession new ,buffers (Fs new fs-host) ,echo ,searching ,query
     (Position new 4 2) ,wrapped ,failing (List of "newest" "older") ,pending ,prompt
     (Option Some "previous") ,waiting ,(config tree selected columns rows)))
(define (rebuild s #:buffers [buffers `(,s buffers)] #:windows [windows `(,s windows)]
                 #:echo [echo `(,s echo)] #:searching [searching `(,s searching)]
                 #:query [query `(,s query)] #:wrapped [wrapped `(,s wrapped)]
                 #:failing [failing `(,s failing)] #:prompt [prompt `(,s prompt)]
                 #:pending [pending `(,s pending)] #:waiting [waiting `(,s waiting-command)])
  `(AloemacsSession new ,buffers (,s fs) ,echo ,searching ,query (,s origin)
     ,wrapped ,failing (,s kill-ring) ,pending ,prompt (,s last-submission) ,waiting ,windows))
(define session-fields '(buffers fs echo searching query origin wrapped failing kill-ring
                                pending prompt last-submission waiting-command windows))
(define (same-session st actual expected)
  (def! st 'actual actual)
  (def! st 'expected expected)
  (same st 'actual 'expected)
  (for ([field session-fields]) (same st `(actual ,field) `(expected ,field)))
  (for ([field '(before current-buffer after)])
    (same st `((actual buffers) ,field) `((expected buffers) ,field))))
(define (cursor row column) (format "\e[~a;~aH" row column))
(define (multi rows row col [echo-row #f] [echo ""])
  (string-append "\e[?25l\e[2J\e[H" (string-join rows "\r\n")
                 (if echo-row (string-append (cursor echo-row 1) echo) "")
                 (cursor row col) "\e[?25h"))
;; Independent name and text allocation from the supplied fixture and size.
(define (mode-row name width)
  (define label (substring (string-append name " ") 0
                          (min width (add1 (string-length name)))))
  (list->string
    (for/list ([c (in-string (string-append label
                              (make-string (- width (string-length label)) #\-)))])
      (if (or (< (char->integer c) 32) (= (char->integer c) 127)) #\space c))))
(define (text-body body rows)
  (define lines (string-split body "\r\n" #:trim? #f))
  (string-join (take lines (min (length lines) (if (>= rows 3) (- rows 2) 1))) "\r\n"))
(define (single lines row col [echo-row #f] [echo ""] [final-row row] [final-col col]
                #:name [name "untitled"] #:width [width 0])
  (string-append "\e[?25l\e[2J\e[H"
    (if echo-row (text-body (string-join lines "\r\n") echo-row) (string-join lines "\r\n"))
    (format "\e[~a;~aH\e[?25h" row col)
    (if echo-row
        (string-append "\e[?25l"
          (if (>= echo-row 3) (format "\e[~a;1H~a" (sub1 echo-row) (mode-row name width)) "")
          (format "\e[~a;1H~a\e[~a;~aH\e[?25h" echo-row echo final-row final-col)) "")))
(define (snapshot st s)
  (for/list ([expr (list s `(,s buffers) `((,s buffers) before)
                          `((,s buffers) current-buffer) `((,s buffers) after)
                          `((,s windows) tree) `(,s windows) `((,s editor) text))])
    (ev st expr)))
(define (paint st s columns rows expected)
  (define before (snapshot st s))
  (check-equal? (ev st `(,s frame ,columns ,rows)) expected)
  (check-equal? (snapshot st s) before))

(test-case "nominal rectangles: minimum, odd/even, zero axes and exact tree nesting"
  (define st (loaded))
  (def! st 'a (leaf 71))
  (def! st 'b (leaf 3))
  (for ([extent '(0 1 2 3 4 5 6 7 8 9)]
        [earlier '(0 0 1 1 2 2 3 3 4 4)]
        [later '(0 0 0 1 1 2 2 3 3 4)]
        [offset '(0 1 2 2 3 3 4 4 5 5)])
    (def! st 't '(AloemacsWindowTree Right a b))
    (same st `(t rect-for 71 ,(rect 2 4 extent 5)) `(Option Some ,(rect 2 4 earlier 5)))
    (same st `(t rect-for 3 ,(rect 2 4 extent 5)) `(Option Some ,(rect (+ 2 offset) 4 later 5)))
    (check-equal? (ev st `(t positive-layout? ,(rect 2 4 extent 5))) (>= extent 3))
    (def! st 't '(AloemacsWindowTree Below a b))
    (same st `(t rect-for 71 ,(rect 2 4 5 extent)) `(Option Some ,(rect 2 4 5 earlier)))
    (same st `(t rect-for 3 ,(rect 2 4 5 extent)) `(Option Some ,(rect 2 (+ 4 offset) 5 later)))
    (check-equal? (ev st `(t positive-layout? ,(rect 2 4 5 extent))) (>= extent 3)))
  (define t (right (below (leaf 71) (leaf 3)) (leaf 55)))
  (def! st 't t)
  (for ([id '(71 3 55)] [r '((0 0 4 2) (0 3 4 2) (5 0 4 5))])
    (same st `(t rect-for ,id ,(rect 0 0 9 5)) `(Option Some ,(apply rect r))))
  (same st `(t rect-for 999 ,(rect 0 0 9 5))
    `(if #t (Option None) (Option Some ,(rect 0 0 9 5))))
  (same st '((t leaves) map (fn (v) (v id))) '(List of 71 3 55))
  ;; Same-direction nesting remains binary; a 13-cell axis is 6 | 3 | 2.
  (def! st 'deep (right (leaf 71) (right (leaf 3) (right (leaf 55) (leaf 8)))))
  (for ([id '(71 3 55 8)] [r '((0 0 6 2) (7 0 3 2) (11 0 1 2) (13 0 0 2))])
    (same st `(deep rect-for ,id ,(rect 0 0 13 2)) `(Option Some ,(apply rect r))))
  (check-false (ev st `(deep positive-layout? ,(rect 0 0 13 2))))
  (def! st 'w (config t 3))
  (same st '(w fit-rect 9 6) (rect 0 3 4 2))
  (same st '(w fit-rect 9 2) (rect 0 0 9 1))
  (same st '(w fit-rect 1 6) (rect 0 0 1 5))
  (same st '(w fit-rect 9 1) (rect 0 0 9 1))
  (for ([entry `(((t rect-for 3 ,(rect 0 0 9 5)) (Option AloemacsWindowRect))
                ((t positive-layout? ,(rect 0 0 9 5)) Bool)
                ((w fit-rect 9 6) AloemacsWindowRect))])
    (check-equal? (dtype st (car entry)) (cadr entry)))
  (for ([bad `((t rect-for) (t rect-for 3) (t rect-for "3" ,(rect 0 0 9 5))
               (t rect-for 3 a) (t rect-for 3 ,(rect 0 0 9 5) 0)
               (a positive-layout?) (t positive-layout? 9 5)
               (w fit-rect "9" 6) (w fit-rect 9) (w fit-rect 9 6 1))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st bad)))))

(test-case "explicit-origin rows: checked signature, bounded clipping, controls and blank tails"
  (define st (loaded))
  (define ls '("abcdef" "x\t\e\r\u0000\u007fλ" "" "last" ""))
  (for ([text (list `(Text from-string ,(string-join ls "\n")) (indexed ls 3))])
    ;; Point and stored origin are deliberately irrelevant to this row send.
    (def! st 'ed (editor text 99 20 77 42 6 #t))
    (define before (ev st 'ed))
    (same st '(ed frame-rows 4 4 0 2) '(List of "cdef" "    " "" "st"))
    (same st '(ed frame-rows 7 6 1 0) '(List of "x     λ" "" "last" "" "" ""))
    (same st '(ed frame-rows 1 3 3 99) '(List of "" "" ""))
    (same st '(ed frame-rows 4 3 5 0) '(List of "" "" ""))
    (same st '(ed frame-rows 4 2 999 2) '(List of "" ""))
    (check-equal? (dtype st '(ed frame-rows 4 2 0 0)) '(List String))
    (check-equal? (ev st 'ed) before))
  (for ([bad '((ed frame-rows) (ed frame-rows 4 2 0) (ed frame-rows 4 2 0 0 0)
               (ed frame-rows "4" 2 0 0) (ed frame-rows 4 #f 0 0)
               (ed frame-rows 4 2 "0" 0) (ed frame-rows 4 2 0 #t)
               ((Text from-string "x") frame-rows 4 2 0 0))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st bad)))))

(define a-lines '("abcdef" "ghijkl" "mnopqr" "stuvwx" "yz0123" ""))
(define b-lines '("ABCDE" "FGHIJ" "KLMNO" "PQRST" "UVWXY"))
(define example-tree (right (below (leaf 71 41) (leaf 3 41 3 1 #t)) (leaf 55 9 1 2)))
(define example-rows '("abcd|HIJ " "/cwd|MNO " "----+RST " "tuvw|WXY " "/cwd|unti"))
(define (example! st)
  (def! st 'a (buffer 41 (editor (indexed a-lines 2) 3 2 3 1 2)
                     '(Option Some (Path new "/cwd/a.txt"))))
  (def! st 'b (buffer 9 (editor (indexed b-lines 3) 3 4 2 3 5)))
  (def! st 's (session (zipper '(a b) 0) example-tree 3 #:echo "")))

(test-case "complete mixed frame, selected offsets, full-width echo and exactly one ANSI envelope"
  (define-values (st calls) (state))
  (example! st)
  (paint st 's 9 6 (multi example-rows 4 2 6 "/cwd/a.tx"))
  (define output (ev st '(s frame 9 6)))
  (for ([piece '("\e[?25l" "\e[2J" "\e[H" "\e[?25h")])
    (check-equal? (length (regexp-match* (regexp (regexp-quote piece)) output)) 1))
  ;; Construct a different selected leaf/current origin without any entry API.
  (def! st 'b-selected (buffer 9 (editor (indexed b-lines 3) 3 4 1 2 5)))
  (def! st 'r (session (zipper '(a b-selected) 1) example-tree 55 #:echo ""))
  (paint st 'r 9 6 (multi example-rows 3 8 6 "untitled"))
  (def! st 'a-top (buffer 41 (editor (indexed a-lines 2) 1 2)))
  (def! st 'top (session (zipper '(a-top b) 0) example-tree 71 #:echo ""))
  (paint st 'top 9 6 (multi '("abcd|HIJ " "unti|MNO " "----+RST " "tuvw|WXY " "unti|unti")
                            2 3 6 "untitled"))
  (for ([token '("" "saved" "failed")]
        [shown '("/cwd/a.tx" "saved: /c" "failed: /")])
    (def! st 'idle (rebuild 's #:echo token))
    (paint st 'idle 9 6 (multi example-rows 4 2 6 shown))
    (check-equal? (ev st '(idle echo)) token))
  (for ([wrapped '(#f #t #t)] [failing '(#f #f #t)]
        [shown '("search: λ" "wrapped: " "failing: ")])
    (def! st 'search (rebuild 's #:searching #t #:query "λ\txy"
                             #:wrapped wrapped #:failing failing))
    (paint st 'search 9 6 (multi example-rows 4 2 6 shown)))
  (def! st 'safe-path (rebuild 's #:buffers
    (zipper (list (buffer 41 '(a editor) '(Option Some (Path new "/a\tbcdefghij"))) 'b) 0)))
  (paint st 'safe-path 9 6 (multi '("abcd|HIJ " "/a b|MNO " "----+RST " "tuvw|WXY " "/a b|unti")
                                  4 2 6 "/a bcdefg"))
  (def! st 'prompted (rebuild 'search #:prompt '(Option Some (AloemacsPrompt new "L\t" "A\rB" 2))))
  (paint st 'prompted 9 6 (multi example-rows 6 5 6 "L A B"))
  (def! st 'ended '(prompted cancel-prompt))
  (paint st 'ended 9 6 (multi example-rows 4 2 6 "failing: "))
  (check-equal? (unbox calls) '()))

(test-case "junctions in both orientations, aligned cross, nested edges and punctuation independence"
  (define-values (st calls) (state))
  (def! st 'a (buffer 41 (editor '(Text from-string "a"))))
  (define l (leaf 71))
  (define r (leaf 3))
  (define n (leaf 55))
  (define m (leaf 8))
  (for ([t (list (right (below l r) n) (right l (below r n))
                 (below (right l r) n) (below l (right r n))
                 (right (below l r) (below n m))
                 (below (right l r) (right n m)))]
        [rows (list '("a  |a  " "unt|   " "---+   " "a  |   " "unt|unt")
                    '("a  |a  " "   |unt" "   +---" "   |a  " "unt|unt")
                    '("a  |a  " "unt|unt" "---+---" "a      " "untitle")
                    '("a      " "untitle" "---+---" "a  |a  " "unt|unt")
                    '("a  |a  " "unt|unt" "---+---" "a  |a  " "unt|unt")
                    '("a  |a  " "unt|unt" "---+---" "a  |a  " "unt|unt"))])
    (def! st 's (session (zipper '(a) 0) t 71 #:echo ""))
    (paint st 's 7 6 (multi rows 1 1 6 "untitle")))
  ;; A grandchild divider reaches the ancestor, through its subtree edge.
  (def! st 's (session (zipper '(a) 0)
    (right (right l (below r n)) m) 71 #:echo ""))
  (paint st 's 11 6 (multi '("a |a |a    " "  |un|     " "  +--+     " "  |a |     " "un|un|untit")
                            1 1 6 "untitled"))
  ;; Identical punctuation next to a divider does not affect its orientation.
  (def! st 'punct (buffer 41 (editor '(Text from-string "---\n|||\n+++\n---\n|||"))))
  (def! st 's (session (zipper '(punct) 0) (right l r) 71 #:echo ""))
  (paint st 's 7 6 (multi '("---|---" "|||||||" "+++|+++" "---|---" "unt|unt") 1 1 6 "untitle"))
  (check-equal? (unbox calls) '()))

(test-case "shared edit and visit preserve inactive origins beyond EOF and exact zipper focus during paint"
  (define-values (st calls) (state))
  (example! st)
  (define t (right (leaf 71 41 99 101 #t) (leaf 3 41 3 1)))
  (def! st 'far (rebuild 's #:windows (config t 3 80 24)))
  ;; Shared edit replaces one owned editor; the far view remains blank.
  (def! st 'edited '(far insert "λ"))
  (paint st 'edited 9 3 (multi '("    |tλuv" "/cwd|/cwd") 1 8 3 "/cwd/a.tx"))
  (def! st 'short '(far visited "x\n" (Path new "/short")))
  (paint st 'short 9 3 (multi '("    |x   " "/sho|/sho") 1 6 3 "/short"))
  (same st '(((short windows) tree) find-view 71)
    '(Option Some (AloemacsView new 71 41 99 101 #t)))
  (check-equal? (unbox calls) '()))

(test-case "selected-only minimal fit preserves every rich payload, lock, inactive origin and full size"
  (define-values (st calls) (state))
  (define ls (for/list ([i (in-range 20)]) (format "line~a-abcdefghijk" i)))
  (define text (indexed ls 12))
  (define tree (right (below (leaf 71 41 7 11 #t) (leaf 3 41 2 3 #t)) (leaf 55 9 99 101)))
  (define fitted-tree (right (below (leaf 71 41 7 11 #t) (leaf 3 41 10 6 #t)) (leaf 55 9 99 101)))
  (def! st 'a (buffer 41 (editor text 10 9 2 3 17 #t) '(Option Some (Path new "/cwd/a.txt"))))
  (def! st 'b (buffer 9 (editor '(Text from-string "inactive") 0 4 2 3 13)))
  (def! st 's (session (zipper '(b a) 1) tree 3 #:columns 0 #:rows 0
    #:searching #t #:pending '(Option Some aloemacs-ctrl-x-keymap)
    #:prompt '(Option Some (AloemacsPrompt new "draft: " "input" 2))
    #:waiting '(Option Some (AloemacsCommand SaveAs))))
  (define source (snapshot st 's))
  (define fitted-buffer (buffer 41 (editor text 10 9 10 6 1 #t) '(a path)))
  (same-session st '(s ensure-visible 9 6)
    (rebuild 's #:buffers (zipper (list 'b fitted-buffer) 1)
      #:windows (config fitted-tree 3 9 6)))
  (def! st 'fit '(s ensure-visible 9 6))
  (same-session st '(fit ensure-visible 9 6) 'fit)
  ;; Point before the old origin: move back exactly to point on both axes.
  (def! st 'far-a (buffer 41 (editor text 10 9 99 101 17 #t) '(a path)))
  (define far-tree (right (below (leaf 71 41 7 11 #t) (leaf 3 41 99 101 #t)) (leaf 55 9 99 101)))
  (def! st 'far (rebuild 's #:buffers (zipper '(b far-a) 1) #:windows (config far-tree 3)))
  (same-session st '(far ensure-visible 9 6)
    (rebuild 'far #:buffers (zipper (list 'b (buffer 41 (editor text 10 9 10 9 1 #t) '(a path))) 1)
      #:windows (config (right (below (leaf 71 41 7 11 #t) (leaf 3 41 10 9 #t))
                              (leaf 55 9 99 101)) 3 9 6)))
  (define before (snapshot st 'fit))
  (ev st '(fit frame 19 10)) ; a supplied size different from remembered size
  (check-equal? (snapshot st 'fit) before)
  (check-equal? (snapshot st 's) source)
  (for ([send '((with-echo "failed") (page-up) (switch-buffer) (add-buffer "x"))])
    (same st `(((fit ,@send) windows) columns) 9)
    (same st `(((fit ,@send) windows) rows) 6))
  (check-equal? (unbox calls) '()))

(test-case "selected rectangle height drives page motion; fallback and growth fit only selected"
  (define-values (st calls) (state))
  (define ls (for/list ([i (in-range 15)]) (format "abcdef~a" i)))
  (define text (indexed ls 8))
  (define tree (below (leaf 71 41 2 1 #t) (leaf 3 41 8 1 #t)))
  (def! st 'a (buffer 41 (editor text 8 2 8 1 0)))
  (def! st 's (session (zipper '(a) 0) tree 3 #:echo ""))
  (def! st 'fit '(s ensure-visible 7 8)) ; full leaves 3, text heights 2
  (same st '((fit editor) text-rows) 2)
  (same st '((fit page-down) point) '(Position new 9 2))
  (same st '((fit page-up) point) '(Position new 7 2))
  (same st '((fit editor) text) text)
  (def! st 'tiny '(fit ensure-visible 7 2))
  (same-session st 'tiny (rebuild 'fit #:buffers
    (zipper (list (buffer 41 (editor text 8 2 8 1 1) '(a path))) 0)
    #:windows (config tree 3 7 2)))
  (same st '((tiny page-down) point) '(Position new 9 2))
  (paint st 'tiny 7 2 (single '("bcdef8") 1 2 2 "untitle" #:name "untitled" #:width 7))
  (def! st 'grown '(tiny ensure-visible 7 8))
  (same-session st 'grown (rebuild 'tiny #:buffers
    (zipper (list (buffer 41 (editor text 8 2 8 1 2) '(a path))) 0)
    #:windows (config tree 3 7 8)))
  (paint st 'grown 7 8 (multi '("bcdef2 " "bcdef3 " "untitle" "-------" "bcdef8 " "bcdef9 " "untitle")
                              5 2 8 "untitle"))
  (check-equal? (unbox calls) '()))

(test-case "global fallback despite positive selected rectangle; one-row split and prompt rules"
  (define-values (st calls) (state))
  (def! st 'a (buffer 41 (editor '(Text from-string "abc\ndef"))))
  (define tree (right (leaf 71) (below (leaf 3) (leaf 55))))
  (def! st 's (session (zipper '(a) 0) tree 71 #:echo ""
    #:prompt '(Option Some (AloemacsPrompt new "P: " "long" 4))))
  ;; Selected left is positive; only the nested right fails.
  (def! st 'fit '(s ensure-visible 7 3))
  (same st '((fit editor) text-rows) 1)
  (same st '((fit windows) tree) tree)
  (paint st 'fit 7 3 (single '("abc" "def") 1 1 3 "P: long" 3 7 #:name "untitled" #:width 7))
  (paint st 'fit 7 1 (single '("abc") 1 1 #:name "untitled" #:width 7))
  (def! st 'horizontal (session (zipper '(a) 0) (right (leaf 71) (leaf 3)) 71
    #:echo "" #:prompt '(Option Some (AloemacsPrompt new "P: " "long" 4))))
  (paint st 'horizontal 7 1 (multi '("abc|abc") 1 1))
  (def! st 'one (rebuild 'horizontal #:windows (config (leaf 71) 71)))
  (paint st 'one 7 3 (single '("abc" "def") 1 1 3 "P: long" 3 7 #:name "untitled" #:width 7))
  (check-equal? (unbox calls) '()))

(test-case "checked scripted Term loop fits, paints, writes once, then reads/handles; shrink and growth"
  (define-values (st calls) (state))
  (def! st 'a (buffer 41 (editor '(Text from-string "abcdef\nghijkl"))))
  (define t (right (leaf 71) (leaf 3 41 1 2 #t)))
  (def! st 's (session (zipper '(a) 0) t 71 #:echo "failed"
    #:pending '(Option Some aloemacs-ctrl-x-keymap)
    #:prompt '(Option Some (AloemacsPrompt new "P: " "xy" 1))
    #:waiting '(Option Some (AloemacsCommand SaveAs))))
  (define sizes (box '((7 3) (1 2) (7 3))))
  (define keys (box '("ctrl-x" "left" "ctrl-x")))
  (define events (box '()))
  (define (record v) (set-box! events (append (unbox events) (list v))))
  (define output
    (make-output-port 'windows-script always-evt
      (lambda (bytes start end _non-block? _breakable?)
        (unless (= start end) (record (list 'write (bytes->string/utf-8 (subbytes bytes start end)))))
        (- end start)) void))
  (driver-inject-host! st 'term
    (make-term-receiver output
      (lambda () (record 'read) (begin0 (car (unbox keys)) (set-box! keys (cdr (unbox keys)))))
      (lambda () (record 'size) (apply values (car (unbox sizes))))))
  (define expected
    (list (multi '("abc|ijk" "unt|unt") 3 5 3 "P: xy")
          (single '("a") 1 1 2 "P" 2 1 #:name "untitled" #:width 1)
          (multi '("abc|ijk" "unt|unt") 3 4 3 "P: xy")))
  (for ([frame expected] [size '((7 3) (1 2) (7 3))])
    (define before (ev st 's))
    (def! st 'columns '(term columns))
    (def! st 'rows '(term rows))
    (def! st 's '(s ensure-visible columns rows))
    (def! st 'frame '(s frame columns rows))
    (check-equal? (ev st 'frame) frame)
    (ev st '(term write frame))
    (same st '((s windows) tree) t)
    (same st '(s pending) '(Option Some aloemacs-ctrl-x-keymap))
    (same st '(s waiting-command) '(Option Some (AloemacsCommand SaveAs)))
    (check-equal? (ev st '(s echo)) "failed")
    (def! st 's '(s handle-key (term read-key)))
    (set-box! sizes (cdr (unbox sizes))))
  (check-equal? (unbox events)
    (append-map (lambda (frame) (list 'size 'size (list 'write frame) 'read)) expected))
  (check-equal? (unbox keys) '())
  (same st '(s prompt) '(Option Some (AloemacsPrompt new "P: " "xy" 0)))
  (same st '((s editor) text) '(Text from-string "abcdef\nghijkl"))
  (check-equal? (unbox calls) '()))

(test-case "checked effect-free load, retained inventories/current keys and absent future commands"
  (define st0 (loaded))
  (for ([name '(fs-host term aloemacs-editor)])
    (check-false (env-bound? (driver-runtime-environment st0) name)))
  (define (datums path) (call-with-input-file path (lambda (in) (port->list read in))))
  (define source (datums file-path))
  (define classes (filter (lambda (d) (eq? (car d) 'define-class)) source))
  (define (decl name) (findf (lambda (d) (equal? (cadr d) name)) classes))
  (check-equal? (take source 2) '((load "editor.aloe") (load "../../lib/fs.aloe")))
  (check-equal? (map cadr classes)
    '(AloemacsPrompt AloemacsBuffer AloemacsBuffers AloemacsModeLine AloemacsView AloemacsWindowTree
      AloemacsWindowRect AloemacsWindows AloemacsCommand (AloemacsKeymap B)
      AloemacsBinding AloemacsSearchScan (AloemacsSession H)))
  (for ([entry '((AloemacsView (fields (id Int) (buffer-id Int) (scroll-row Int) (scroll-col Int) (locked Bool)))
                (AloemacsWindowRect (fields (x Int) (y Int) (columns Int) (rows Int)))
                (AloemacsWindows (fields (tree AloemacsWindowTree) (selected Int) (columns Int) (rows Int)))
                (AloemacsBuffer (fields (editor AloemacsEditor) (path (Option Path)) (id Int)))
                ((AloemacsSession H) (fields (buffers AloemacsBuffers) (fs (Fs H)) (echo String)
                  (searching Bool) (query String) (origin Position) (wrapped Bool) (failing Bool)
                  (kill-ring (List String)) (pending (Option (AloemacsKeymap AloemacsBinding)))
                  (prompt (Option AloemacsPrompt)) (last-submission (Option String))
                  (waiting-command (Option AloemacsCommand)) (windows AloemacsWindows))))])
    (check-equal? (caddr (decl (car entry))) (cadr entry)))
  (check-equal? (map car (cdr (caddr (decl 'AloemacsCommand))))
    '(Newline BackwardDelete MoveLeft MoveRight MoveUp MoveDown LineStart LineEnd
      PageUp PageDown BufferStart BufferEnd RequestQuit Undo SetMark Kill KillLine
      Yank Find Save SelfInsert SwitchBuffer KillBuffer FindFile SaveAs SelectBuffer
      SplitBelow SplitRight DeleteWindow OtherWindow ToggleWindowLock))
  (define ed-classes (filter (lambda (d) (eq? (car d) 'define-class)) (datums editor-path)))
  (check-equal? (map caddr ed-classes)
    '((fields (text Text) (point Position) (scroll-row Int) (scroll-col Int))
      (fields (text Text) (point Position) (quit Bool) (scroll-row Int) (scroll-col Int)
              (history (List UndoFrame)) (mark (Option Position)) (text-rows Int))))
  (define-values (st calls) (state))
  (def! st 'a (buffer 41 (editor '(Text from-string "a"))))
  (def! st 's (session (zipper '(a) 0) (leaf 71) 71 #:echo ""))
  (same st '((aloemacs-ctrl-x-keymap bindings) map (fn (b) (b key)))
    '(List of "save" "find" "kill" "b" "2" "3" "0" "o" "l"))
  (same st '((aloemacs-global-keymap bindings) map (fn (b) (b key)))
    '(List of "return" "backspace" "left" "right" "up" "down" "line-start" "line-end"
       "page-up" "page-down" "buffer-start" "buffer-end" "escape" "undo" "mark" "kill"
       "kill-line" "yank" "find" "save" "ctrl-x"))
  (for ([bad '((s select-view 3))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
  (for ([key '("2" "3" "0" "o" "l")])
    (def! st 'next `(s handle-key ,key))
    (same st '(next windows) '(s windows))
    (same st '(next text) (indexed (list (string-append key "a")) 0)))
  (for ([key '("x")])
    (def! st 'prefix '(s handle-key "ctrl-x"))
    (same st `((prefix handle-key ,key) text) '(s text))
    (same st `((prefix handle-key ,key) windows) '(s windows)))
  (check-equal? (unbox calls) '()))
