#lang racket/base

(require racket/string racket/list racket/port racket/runtime-path rackunit
         "../../aloe/driver.rkt" "../../aloe/host.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/env.rkt" env-bound?)
         (only-in "../../aloe/type.rkt" exn:fail:aloe-type? type-of type->datum)
         "../../host/racket/fs.rkt")

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define-runtime-path editor-path "../../examples/aloemacs/editor.aloe")
(define-runtime-path main-path "../../examples/aloemacs/main.aloe")
(define no-mark '(if #t (Option None) (Option Some (Position new 0 0))))
(define no-path '(if #t (Option None) (Option Some (Path new "/typed-none"))))
(define no-pending '(if #t (Option None) (Option Some aloemacs-global-keymap)))
(define no-prompt '(if #t (Option None) (Option Some (AloemacsPrompt new "" "" 0 "" (List empty) (List empty) 0))))
(define no-submission '(if #t (Option None) (Option Some "")))
(define no-command '(if #t (Option None) (Option Some (AloemacsCommand FindFile))))
(define session-fields
  '(buffers fs echo searching query origin wrapped failing kill-ring pending
            prompt last-submission waiting-command windows))
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))
(define (type st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))
(define (loaded)
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  st)
(define (state #:fail [fail #f])
  (define st (loaded))
  (define disk (make-fs-double "/cwd"
    (hash "/cwd" 'directory "/cwd/a.txt" 'file "/cwd/b.txt" 'file
          "/cwd/dir" 'directory "/cwd/link" 'symlink)
    (hash "/cwd/a.txt" "λ\r\nb\n" "/cwd/b.txt" "disk b")))
  (define calls (box '()))
  (define (forward selector args)
    (set-box! calls (append (unbox calls) (list (cons selector args))))
    (when (eq? selector fail) (error 'windows-test "host failure"))
    (host-receiver-send disk selector args))
  (define interface
    (make-host-interface 'FsHost
      (for/list ([method (in-list (host-interface-methods fs-interface))])
        (define selector (host-method-selector method))
        (define params (host-method-parameter-types method))
        (make-host-method selector params (host-method-return-type method)
          (case (length params)
            [(0) (lambda (state) (forward selector '()))]
            [(1) (lambda (state a) (forward selector (list a)))]
            [(2) (lambda (state a b) (forward selector (list a b)))])))))
  (driver-inject-host! st 'fs-host (make-host-receiver interface #f))
  (values st calls))
(define (fresh contents [cold? #f])
  `(AloemacsEditor new
     ,(if cold? `(Text from-string ,contents) `((Text from-string ,contents) indexed-value))
     (Position new 0 0) #f 0 0 (List empty) ,no-mark 0))
(define (buffer id contents [path no-path])
  `(AloemacsBuffer new ,(fresh contents) ,path ,id))
(define (zipper order focus)
  `(AloemacsBuffers new (List of ,@(reverse (take order focus)))
     ,(list-ref order focus) (List of ,@(drop order (add1 focus)))))
(define (windows id row col [columns 80] [rows 24] [view 17] [locked #t])
  `(AloemacsWindows new
     (AloemacsWindowTree Leaf (AloemacsView new ,view ,id ,row ,col ,locked))
     ,view ,columns ,rows))
;; Independent raw constructors: these expectations never call a window helper
;; or the session transition being tested.
(define (for-buffers buffers [columns 80] [rows 24])
  (windows `((,buffers current-buffer) id)
           `(((,buffers current-buffer) editor) scroll-row)
           `(((,buffers current-buffer) editor) scroll-col) columns rows))
(define (session buffers)
  `(AloemacsSession new ,buffers (Fs new fs-host) "saved" #t "old query"
     (Position new 4 2) #t #t (List of "newest" "older")
     (Option Some aloemacs-ctrl-x-keymap)
     (Option Some (AloemacsPrompt new "draft: " "input" 2 "" (List empty) (List empty) 0))
     (Option Some "previous") (Option Some (AloemacsCommand SaveAs))
     ,(for-buffers buffers)))
(define (rebuild s #:buffers [buffers `(,s buffers)] #:echo [echo `(,s echo)]
                 #:searching [searching `(,s searching)] #:query [query `(,s query)]
                 #:origin [origin `(,s origin)] #:wrapped [wrapped `(,s wrapped)]
                 #:failing [failing `(,s failing)] #:ring [ring `(,s kill-ring)]
                 #:pending [pending `(,s pending)] #:prompt [prompt `(,s prompt)]
                 #:submission [submission `(,s last-submission)]
                 #:waiting [waiting `(,s waiting-command)]
                 #:windows [config `(,s windows)])
  `(AloemacsSession new ,buffers (,s fs) ,echo ,searching ,query ,origin
     ,wrapped ,failing ,ring ,pending ,prompt ,submission ,waiting ,config))
(define (replace s ed [path `(,s path)])
  `(AloemacsBuffers new ((,s buffers) before)
     (AloemacsBuffer new ,ed ,path ((,s current-buffer) id)) ((,s buffers) after)))
(define (selected s buffers)
  (rebuild s #:buffers buffers #:echo "" #:searching #f #:query ""
    #:origin '(Position new 0 0) #:wrapped #f #:failing #f #:pending no-pending
    #:windows (for-buffers buffers)))
(define (with-editor s ed)
  (rebuild s #:buffers (replace s ed)
    #:windows (windows `((,s current-buffer) id) `(,ed scroll-row) `(,ed scroll-col))))
(define rich-editor
  '(AloemacsEditor new
     (Text indexed (List of "second" "first") "third-long" (List of "fourth" "fifth") 2)
     (Position new 2 4) #f 2 3
     (List of (UndoFrame new (Text from-string "old") (Position new 0 2) 1 2))
     (Option Some (Position new 1 1)) 4))
(define (rich! st)
  (def! st 'rich-editor rich-editor)
  (def! st 'a (buffer 41 "neighbor" '(Option Some (Path new "/cwd/a.txt"))))
  (def! st 'b '(AloemacsBuffer new rich-editor (Option Some (Path new "/cwd/b.txt")) 9))
  (def! st 'c
    `(AloemacsBuffer new
       (AloemacsEditor new (Text indexed (List of "one") "three" (List of "last") 1)
         (Position new 1 3) #f 1 2
         (List of (UndoFrame new (Text from-string "old c") (Position new 0 4) 0 2))
         (Option Some (Position new 1 1)) 5)
       ,no-path 27))
  (def! st 'source (session (zipper '(a b c) 1))))
(define (same-session st actual expected)
  (def! st 'actual actual)
  (def! st 'expected expected)
  (same st 'actual 'expected)
  (for ([field session-fields]) (same st `(actual ,field) `(expected ,field))))
(define (datums path)
  (call-with-input-file path (lambda (in) (port->list read in))))

(test-case "exact class order, inventories and preserved ownership"
  (define source (datums file-path))
  (define classes (filter (lambda (d) (eq? (car d) 'define-class)) source))
  (define (decl name) (findf (lambda (d) (equal? (cadr d) name)) classes))
  (check-equal? (take source 2) '((load "editor.aloe") (load "../../lib/fs.aloe")))
  (check-equal? (map cadr classes)
    '(AloemacsPrompt AloemacsCompletionScan AloemacsBuffer AloemacsBuffers AloemacsModeLine AloemacsView AloemacsWindowTree
      AloemacsWindowRect AloemacsWindows AloemacsCommand (AloemacsKeymap B)
      AloemacsBinding AloemacsSearchScan (AloemacsSession H)))
  (for ([entry
         '((AloemacsView (fields (id Int) (buffer-id Int) (scroll-row Int) (scroll-col Int) (locked Bool)))
           (AloemacsWindowTree (constructors
             (Leaf (fields (view AloemacsView)))
             (Below (fields (top AloemacsWindowTree) (bottom AloemacsWindowTree)))
             (Right (fields (left AloemacsWindowTree) (right AloemacsWindowTree)))))
           (AloemacsWindowRect (fields (x Int) (y Int) (columns Int) (rows Int)))
           (AloemacsWindows (fields (tree AloemacsWindowTree) (selected Int) (columns Int) (rows Int)))
           (AloemacsBuffer (fields (editor AloemacsEditor) (path (Option Path)) (id Int)))
           (AloemacsBuffers (fields (before (List AloemacsBuffer)) (current-buffer AloemacsBuffer)
                                   (after (List AloemacsBuffer)))))])
    (check-equal? (caddr (decl (car entry))) (cadr entry)))
  (check-equal? (caddr (decl '(AloemacsSession H)))
    '(fields (buffers AloemacsBuffers) (fs (Fs H)) (echo String) (searching Bool)
       (query String) (origin Position) (wrapped Bool) (failing Bool) (kill-ring (List String))
       (pending (Option (AloemacsKeymap AloemacsBinding))) (prompt (Option AloemacsPrompt))
       (last-submission (Option String)) (waiting-command (Option AloemacsCommand))
       (windows AloemacsWindows)))
  (define editor-classes
    (filter (lambda (d) (eq? (car d) 'define-class)) (datums editor-path)))
  (check-equal? (map caddr editor-classes)
    '((fields (text Text) (point Position) (scroll-row Int) (scroll-col Int))
      (fields (text Text) (point Position) (quit Bool) (scroll-row Int) (scroll-col Int)
              (history (List UndoFrame)) (mark (Option Position)) (text-rows Int))))
  (define command-constructors (map car (cdr (caddr (decl 'AloemacsCommand)))))
  (check-equal? command-constructors
    '(Newline BackwardDelete MoveLeft MoveRight MoveUp MoveDown LineStart LineEnd
      PageUp PageDown BufferStart BufferEnd RequestQuit Undo SetMark Kill KillLine
      Yank Find Save SelfInsert SwitchBuffer KillBuffer FindFile SaveAs SelectBuffer
      SplitBelow SplitRight DeleteWindow OtherWindow ToggleWindowLock)))

(test-case "pure mixed recursive tree traversal, lookup and concrete types"
  (define st (loaded))
  (for ([name '(v31 v4 v19 v2)] [id '(31 4 19 2)])
    (def! st name `(AloemacsView new ,id 9 3 5 #t)))
  (def! st 'tree '(AloemacsWindowTree Below
    (AloemacsWindowTree Right (AloemacsWindowTree Leaf v31) (AloemacsWindowTree Leaf v4))
    (AloemacsWindowTree Below (AloemacsWindowTree Leaf v19) (AloemacsWindowTree Leaf v2))))
  (define original (ev st 'tree))
  (same st '(tree leaves) '(List of v31 v4 v19 v2))
  (same st '((AloemacsWindowTree Leaf v4) leaves) '(List of v4))
  (for ([name '(v31 v4 v19 v2)] [id '(31 4 19 2)])
    (same st `(tree find-view ,id) `(Option Some ,name)))
  (same st '(tree find-view 0) '(if #t (Option None) (Option Some v4)))
  (same st '(tree find-view -1) '(if #t (Option None) (Option Some v4)))
  (for ([entry '(((tree leaves) (List AloemacsView))
                ((tree find-view 4) (Option AloemacsView)) ((v4 id) Int)
                ((v4 buffer-id) Int) ((v4 scroll-row) Int) ((v4 scroll-col) Int)
                ((v4 locked) Bool) ((AloemacsWindowRect new 1 2 3 4) AloemacsWindowRect)
                (((AloemacsWindows new tree 19 80 24) tree) AloemacsWindowTree)
                (((AloemacsWindows new tree 19 80 24) selected) Int))])
    (check-equal? (type st (car entry)) (cadr entry)))
  (for ([bad '((AloemacsView new 0 0 0 0) (AloemacsView new 0 0 0 0 #f 0)
               (AloemacsView new "0" 0 0 0 #f) (AloemacsView new 0 #f 0 0 #f)
               (AloemacsView new 0 0 "0" 0 #f) (AloemacsView new 0 0 0 #f #f)
               (AloemacsView new 0 0 0 0 0) (AloemacsWindowTree Leaf 0)
               (AloemacsWindowTree Below tree v4) (AloemacsWindowTree Right v4 tree)
               (AloemacsWindowTree Leaf v4 v4) (AloemacsWindowTree Below tree)
               (AloemacsWindowTree Right tree tree tree) (AloemacsWindowTree new v4)
               (AloemacsWindowRect new 1 2 3) (AloemacsWindowRect new 1 2 3 4 5)
               (AloemacsWindowRect new #f 2 3 4) (AloemacsWindowRect new 1 "2" 3 4)
               (AloemacsWindowRect new 1 2 #f 4) (AloemacsWindowRect new 1 2 3 "4")
               (AloemacsWindows new tree 19 80) (AloemacsWindows new tree 19 80 24 0)
               (AloemacsWindows new v4 19 80 24) (AloemacsWindows new tree #t 80 24)
               (AloemacsWindows new tree 19 #f 24) (AloemacsWindows new tree 19 80 "24")
               (tree leaves 0) (tree find-view) (tree find-view "4") (tree find-view 4 5)
               (v4 leaves) (v4 find-view 4) (tree selected) (v4 editor))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
  (check-equal? (ev st 'tree) original))

(test-case "fourteen-field constructor negatives and lawful cold startup"
  (define st0 (loaded))
  (for ([name '(fs-host term aloemacs-editor)])
    (check-false (env-bound? (driver-runtime-environment st0) name)))
  (define-values (st calls) (state))
  (rich! st)
  (define valid (session (zipper '(a b c) 1)))
  (for ([bad (list (drop-right valid 1) (append valid '(0))
                  (append (drop-right valid 1) '(0)))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
  (check-equal? (type st '(source windows)) 'AloemacsWindows)
  (ev st `(load ,(path->string main-path)))
  (same st '(aloemacs-editor windows) (windows 0 0 0 0 0 0 #f))
  (same st '(aloemacs-editor editor) (fresh "" #t))
  (same st '(aloemacs-editor buffers) (zipper (list `(AloemacsBuffer new ,(fresh "" #t) ,no-path 0)) 0))
  (for ([field '(echo query)]) (check-equal? (ev st `(aloemacs-editor ,field)) ""))
  (for ([field '(searching wrapped failing quit)]) (check-false (ev st `(aloemacs-editor ,field))))
  (for ([field '(pending prompt last-submission waiting-command)])
    (check-false (ev st `((aloemacs-editor ,field) present?))))
  (for ([bad '((source lock-window) (source select-view 17)
               (AloemacsCommand LockWindow))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
  (for ([key '("x")])
    (def! st 'next `(aloemacs-editor handle-key "ctrl-x"))
    (same st `((next handle-key ,key) windows) (windows 0 0 0 0 0 0 #f))
    (same st `((next handle-key ,key) text) '(aloemacs-editor text)))
  (for ([key '("return" "backspace" "left" "right" "up" "down" "line-start"
               "line-end" "page-up" "page-down" "buffer-start" "buffer-end"
               "escape" "undo" "mark" "kill" "kill-line" "yank" "find"
               "save" "ctrl-x" "λ" "unknown")])
    (def! st 'next `(aloemacs-editor handle-key ,key))
    (same st '(next windows) (windows 0 0 0 0 0 0 #f)))
  (check-equal? (unbox calls) '()))

(test-case "with-origin preserves exact cold and focused indexed rich payloads beyond EOF"
  (define st (loaded))
  (for ([text '((Text from-string "a\nb")
                (Text indexed (List of "second" "first") "third" (List of "fourth") 2))])
    (def! st 'ed `(AloemacsEditor new ,text (Position new 2 4) #t 2 3
                  (List of (UndoFrame new (Text from-string "undo") (Position new 0 1) 1 2))
                  (Option Some (Position new 1 1)) 7))
    (define original (ev st 'ed))
    (same st '(ed with-origin 99 101)
      `(AloemacsEditor new ,text (Position new 2 4) #t 99 101
         (List of (UndoFrame new (Text from-string "undo") (Position new 0 1) 1 2))
         (Option Some (Position new 1 1)) 7))
    (for ([field '(text point quit history mark text-rows)])
      (same st `((ed with-origin 0 0) ,field) `(ed ,field)))
    (check-equal? (ev st 'ed) original))
  (for ([bad '((ed with-origin) (ed with-origin 1) (ed with-origin 1 2 3)
               (ed with-origin #f 2) (ed with-origin 1 "2")
               ((Text from-string "a") with-origin 0 0))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st bad)))))

(test-case "every reconstruction and editor wrapper preserves or mirrors the locked sole view"
  (define-values (st calls) (state))
  (rich! st)
  (define original (ev st 'source))
  (for ([send '((insert "λ") (newline) (backward-delete) (move-left) (move-right)
                (move-up) (move-down) (line-start) (line-end) (page-up) (page-down)
                (buffer-start) (buffer-end) (undo) (request-quit))])
    (same-session st `(source ,@send) (with-editor 'source `(rich-editor ,@send))))
  (same-session st '(source with-editor (a editor)) (with-editor 'source '(a editor)))
  (same-session st '(source with-kill-state (a editor) (List of "cut"))
    (rebuild 'source #:buffers (replace 'source '(a editor)) #:echo "" #:ring '(List of "cut")
      #:windows (windows 9 0 0)))
  (same-session st '(source with-search (a editor) #f "new" (Position new 3 1) #f #t)
    (rebuild 'source #:buffers (replace 'source '(a editor)) #:searching #f #:query "new"
      #:origin '(Position new 3 1) #:wrapped #f #:failing #t #:windows (windows 9 0 0)))
  (for ([entry (list
    (list '(source unchanged) (rebuild 'source))
    (list '(source with-echo "failed") (rebuild 'source #:echo "failed"))
    (list '(source clear-prefix) (rebuild 'source #:pending no-pending))
    (list '(source with-prefix aloemacs-global-keymap)
          (rebuild 'source #:echo "" #:pending '(Option Some aloemacs-global-keymap)))
    (list '(source with-active-prompt (AloemacsPrompt new "new: " "x" 1 "" (List empty) (List empty) 0))
          (rebuild 'source #:prompt '(Option Some (AloemacsPrompt new "new: " "x" 1 "" (List empty) (List empty) 0))))
    (list '(source with-waiting-command (AloemacsCommand SelectBuffer))
          (rebuild 'source #:waiting '(Option Some (AloemacsCommand SelectBuffer))))
    (list '(source clear-waiting-command) (rebuild 'source #:waiting no-command))
    (list '(source cancel-prompt) (rebuild 'source #:prompt no-prompt #:waiting no-command))
    (list '(source find) (rebuild 'source #:searching #t #:query "" #:origin '(source point)
                                #:wrapped #f #:failing #f))
    (list '(source end-search) (rebuild 'source #:searching #f #:query ""
                                      #:origin '(Position new 0 0) #:wrapped #f #:failing #f)))])
    (same-session st (car entry) (cadr entry)))
  (def! st 'searching (rebuild 'source #:query "" #:origin '(source point)
                              #:wrapped #f #:failing #f))
  (define hit-ed
    '(AloemacsEditor new (Text indexed (List of "third-long" "second" "first") "fourth"
                                     (List of "fifth") 3)
       (Position new 3 0) #f 2 3 (rich-editor history) (rich-editor mark) 4))
  (same-session st '(searching search-key "f")
    (rebuild 'searching #:buffers (replace 'searching hit-ed) #:query "f"))
  (same-session st '(searching search-key "z") (rebuild 'searching #:query "z" #:failing #t))
  (def! st 'draft (rebuild 'source #:searching #f #:pending no-pending #:waiting no-command))
  (same-session st '(draft prompt-key "x")
    (rebuild 'draft #:prompt '(Option Some (AloemacsPrompt new "draft: " "inxput" 3 "" (List empty) (List empty) 0))))
  (same-session st '(draft submit-prompt)
    (rebuild 'draft #:prompt no-prompt #:submission '(Option Some "input")))
  (def! st 'idle (rebuild 'draft #:prompt no-prompt))
  (same-session st '(idle start-prompt "Ask: ")
    (rebuild 'idle #:prompt '(Option Some (AloemacsPrompt new "Ask: " "" 0 "" (List empty) (List empty) 0))))
  (same-session st '(idle start-command-prompt (AloemacsCommand FindFile) "Find file: ")
    (rebuild 'idle #:prompt '(Option Some (AloemacsPrompt new "Find file: " "/cwd/" 5 "" (List empty) (List empty) 0))
      #:waiting '(Option Some (AloemacsCommand FindFile))))
  (same-session st '(source with-current-path (Path new "new"))
    (rebuild 'source #:buffers (replace 'source 'rich-editor '(Option Some (Path new "new")))))
  (check-equal? (ev st 'source) original)
  (check-equal? (unbox calls) '((root? "/cwd/b.txt") (parent "/cwd/b.txt"))))

(test-case "one leaf retargets every existing buffer operation with sparse IDs and rich zippers"
  (define-values (st calls) (state))
  (rich! st)
  (for ([order '((a b c) (b))] [focus '(1 0)])
    (def! st 's (session (zipper order focus)))
    (define original (ev st 's))
    (define fresh-id (if (= (length order) 1) 10 42))
    (for ([path (list #f '(Path new "/new"))])
      (define added (buffer fresh-id "added" (if path `(Option Some ,path) no-path)))
      (same-session st `(s add-buffer "added" ,@(if path (list path) '()))
        (selected 's (zipper (append (take order (add1 focus)) (list added)
                                    (drop order (add1 focus))) (add1 focus)))))
    (same-session st '(s switch-buffer)
      (selected 's (zipper order (modulo (add1 focus) (length order)))))
    (same-session st '(s selected-buffers (s buffers)) (selected 's (zipper order focus)))
    (same-session st '(s select-buffer-submitted "/cwd/b.txt") (selected 's (zipper order focus)))
    (same-session st '(s select-buffer-submitted "missing") (rebuild 's #:echo "failed"))
    (define survivors (append (take order focus) (drop order (add1 focus))))
    (same-session st '(s kill-buffer)
      (selected 's (if (null? survivors) (zipper (list (buffer 9 "")) 0)
                      (zipper survivors (min focus (sub1 (length survivors)))))))
    (same-session st '(s visited "visit" (Path new "/visit"))
      (rebuild 's #:buffers (replace 's (fresh "visit") '(Option Some (Path new "/visit")))
        #:echo "" #:searching #f #:query "" #:origin '(Position new 0 0) #:wrapped #f #:failing #f
        #:ring '(List empty) #:pending no-pending #:prompt no-prompt #:waiting no-command
        #:windows (windows 9 0 0)))
    (check-equal? (ev st 's) original))
  ;; Last-buffer removal uses the predecessor, with its stored origin intact.
  (def! st 'last (session (zipper '(a b) 1)))
  (same-session st '(last kill-buffer) (selected 'last (zipper '(a) 0)))
  ;; Name reuse is current-first, even with equal paths and distinct IDs.
  (def! st 'duplicate '(AloemacsBuffer new (a editor) (b path) 73))
  (def! st 'dups (session (zipper '(duplicate b c) 1)))
  (same-session st '(dups select-buffer-submitted "/cwd/b.txt")
    (selected 'dups (zipper '(duplicate b c) 1)))
  (same-session st '(dups find-file-submitted "b.txt")
    (selected 'dups (zipper '(duplicate b c) 1)))
  (check-equal? (unbox calls) '((resolve "b.txt")))
  (set-box! calls '())
  (check-equal? (unbox calls) '()))

(define (read-calls typed resolved)
  (list (list 'resolve typed) (list 'kind resolved) (list 'resolve resolved)
        (list 'kind resolved) (list 'resolve resolved) (list 'read resolved)))
(define (write-calls typed resolved contents)
  (list (list 'resolve typed) (list 'kind resolved) (list 'resolve resolved)
        (list 'write resolved contents)))
(test-case "file effects, refusals, same-name reuse and waiting Return target remain exact"
  (define-values (st calls) (state))
  (rich! st)
  (same-session st '(source find-file-submitted "b.txt")
    (selected 'source (zipper '(a b c) 1)))
  (check-equal? (unbox calls) '((resolve "b.txt")))
  (set-box! calls '())
  (same-session st '(source find-file-submitted "a.txt")
    (selected 'source (zipper '(a b c) 0)))
  (check-equal? (unbox calls) '((resolve "a.txt")))
  (set-box! calls '())
  (same-session st '(source find-file-submitted "") (rebuild 'source #:echo "failed"))
  (check-equal? (unbox calls) '())
  (same-session st '(source find-file-submitted "dir") (rebuild 'source #:echo "failed"))
  (check-equal? (unbox calls) '((resolve "dir") (kind "/cwd/dir") (resolve "/cwd/dir")))
  (set-box! calls '())
  (def! st 'only (session (zipper '(b) 0)))
  (same-session st '(only find-file-submitted "a.txt")
    (selected 'only (zipper (list 'b (buffer 10 "λ\r\nb\n" '(Option Some (Path new "/cwd/a.txt")))) 1)))
  (check-equal? (unbox calls) (read-calls "a.txt" "/cwd/a.txt"))
  (set-box! calls '())
  (same-session st '(only find-file-submitted "missing")
    (selected 'only (zipper (list 'b (buffer 10 "" '(Option Some (Path new "/cwd/missing")))) 1)))
  (check-equal? (unbox calls) '((resolve "missing") (kind "/cwd/missing") (resolve "/cwd/missing")))
  (set-box! calls '())
  (same st '(source visit (Path new "dir"))
    '(if #t (Option None) (Option Some source)))
  (check-equal? (unbox calls) '((resolve "dir") (kind "/cwd/dir") (resolve "/cwd/dir")))
  (set-box! calls '())
  (define visited
    (rebuild 'source #:buffers (replace 'source (fresh "λ\r\nb\n") '(Option Some (Path new "/cwd/a.txt")))
      #:echo "" #:searching #f #:query "" #:origin '(Position new 0 0) #:wrapped #f #:failing #f
      #:ring '(List empty) #:pending no-pending #:prompt no-prompt #:waiting no-command
      #:windows (windows 9 0 0)))
  (same st '(source visit (Path new "a.txt")) `(Option Some ,visited))
  (check-equal? (unbox calls) (read-calls "a.txt" "/cwd/a.txt"))
  (set-box! calls '())
  (same st '(source save) '(Option Some source))
  (check-equal? (unbox calls) (cdr (write-calls "/cwd/b.txt" "/cwd/b.txt" "first\nsecond\nthird-long\nfourth\nfifth")))
  (set-box! calls '())
  (same-session st '(source save-as-submitted "a.txt")
    (rebuild 'source #:buffers (replace 'source 'rich-editor '(Option Some (Path new "/cwd/a.txt")))
      #:echo "saved"))
  (check-equal? (unbox calls) (write-calls "a.txt" "/cwd/a.txt" "first\nsecond\nthird-long\nfourth\nfifth"))
  (set-box! calls '())
  ;; The active prompt and slot survive selection; Return saves the new current.
  (def! st 'waiting (rebuild 'source #:searching #f #:pending no-pending
    #:prompt '(Option Some (AloemacsPrompt new "Save as: " "a.txt" 5 "" (List empty) (List empty) 0))))
  (def! st 'switched '(waiting select-buffer-submitted "untitled"))
  (same-session st 'switched (selected 'waiting (zipper '(a b c) 2)))
  (same-session st '(switched handle-key "return")
    (rebuild 'switched #:buffers (replace 'switched '(c editor) '(Option Some (Path new "/cwd/a.txt")))
      #:echo "saved" #:prompt no-prompt #:submission '(Option Some "a.txt") #:waiting no-command))
  (check-equal? (unbox calls) (write-calls "a.txt" "/cwd/a.txt" "one\nthree\nlast"))
  (set-box! calls '())
  (same-session st '(source save-as-submitted "dir") (rebuild 'source #:echo "failed"))
  (check-equal? (unbox calls) '((resolve "dir") (kind "/cwd/dir") (resolve "/cwd/dir")))
  (define-values (failed fcalls) (state #:fail 'write))
  (rich! failed)
  (define before (ev failed 'source))
  (check-exn exn:fail? (lambda () (ev failed '(source save-as-submitted "a.txt"))))
  (check-equal? (ev failed 'source) before)
  (check-equal? (unbox fcalls)
    (write-calls "a.txt" "/cwd/a.txt" "first\nsecond\nthird-long\nfourth\nfifth")))

;; Independent name and text allocation from the supplied fixture and size.
(define (mode-row name width)
  (define label (substring (string-append name " ") 0
                          (min width (add1 (string-length name)))))
  (list->string
    (for/list ([c (in-string (string-append label
                              (make-string (- width (string-length label)) #\-)))])
      (if (or (< (char->integer c) 32) (= (char->integer c) 127)) #\space c))))
(define (text-body body rows)
  (define lines (string-split body "\r\n" #:trim? #f))
  (string-join (take lines (min (length lines) (if (>= rows 3) (- rows 2) 1))) "\r\n"))
(define (ansi body row column [echo-row #f] [echo ""] [prompt-row row] [prompt-column column] #:name [name "untitled"] #:width [width 0])
  (string-append "\e[?25l\e[2J\e[H"
    (if echo-row (text-body body echo-row) body)
    (format "\e[~a;~aH\e[?25h" row column)
    (if (and echo-row (>= echo-row 2))
        (string-append "\e[?25l"
          (if (>= echo-row 3) (format "\e[~a;1H~a" (sub1 echo-row) (mode-row name width)) "")
          (format "\e[~a;1H~a\e[~a;~aH\e[?25h" echo-row echo prompt-row prompt-column)) "")))
(test-case "positive fit remembers full size, mirrors minimal origins and preserves complete frames"
  (define-values (st calls) (state))
  (rich! st)
  (define fitted-editor
    '(AloemacsEditor new (rich-editor text) (rich-editor point) #f 2 4
                         (rich-editor history) (rich-editor mark) 1))
  (same-session st '(source ensure-visible 1 2)
    (rebuild 'source #:buffers (replace 'source fitted-editor) #:windows (windows 9 2 4 1 2)))
  (def! st 'fitted '(source ensure-visible 1 2))
  (same st '(fitted ensure-visible 1 2) 'fitted)
  (for ([send '((with-echo "failed") (move-left) (switch-buffer) (kill-buffer)
                (add-buffer "new") (visited "new" (Path new "new")))])
    (same st `(((fitted ,@send) windows) columns) 1)
    (same st `(((fitted ,@send) windows) rows) 2))
  (def! st 'single '(fitted ensure-visible 2 1))
  (same st '(single windows) (windows 9 2 4 2 1))
  (same st '((single editor) text-rows) 1)
  (def! st 'grown '(single ensure-visible 12 4))
  (same st '(grown windows) (windows 9 2 4 12 4))
  (same st '((grown editor) text-rows) 2)
  ;; Fitting brings an origin beyond point back only as far as required.
  (def! st 'far-editor
    '(AloemacsEditor new (rich-editor text) (rich-editor point) #f 99 101
                         (rich-editor history) (rich-editor mark) 4))
  (def! st 'far (with-editor 'source 'far-editor))
  (same-session st '(far ensure-visible 8 4)
    (rebuild 'far #:buffers (replace 'far
      '(AloemacsEditor new (rich-editor text) (rich-editor point) #f 2 4
                           (rich-editor history) (rich-editor mark) 2))
      #:windows (windows 9 2 4 8 4)))
  (define snapshot (ev st 'source))
  ;; Stored origin, active prompt and the intermediate editor cursor are exact.
  (check-equal? (ev st '(source frame 8 3))
    (ansi "rd-long\r\nrth" 1 2 3 "draft: i" 3 8 #:name "/cwd/b.txt" #:width 8))
  (for ([echo '("" "saved" "failed")] [label '("" "saved: /" "failed: ")])
    (def! st 'idle (rebuild 'source #:searching #f #:prompt no-prompt #:echo echo))
    (check-equal? (ev st '(idle frame 8 3)) (ansi "rd-long\r\nrth" 1 2 3 label #:name "/cwd/b.txt" #:width 8)))
  (for ([wrapped '(#f #t #t)] [failing '(#f #f #t)]
        [label '("search: " "wrapped:" "failing:")])
    (def! st 'search (rebuild 'source #:prompt no-prompt #:query "abc"
                             #:wrapped wrapped #:failing failing))
    (check-equal? (ev st '(search frame 8 3)) (ansi "rd-long\r\nrth" 1 2 3 label #:name "/cwd/b.txt" #:width 8)))
  (check-equal? (ev st '(source frame 8 1)) (ansi "rd-long" 1 2 #:name "/cwd/b.txt" #:width 8))
  (check-equal? (ev st 'source) snapshot)
  (check-equal? (unbox calls) '()))

(test-case "blank, narrow and control-cell frames are complete and leave unknown size exact"
  (define-values (st calls) (state))
  (def! st 'empty (session (zipper (list (buffer 33 "")) 0)))
  (def! st 'blank (rebuild 'empty #:searching #f #:echo "" #:pending no-pending
                          #:prompt no-prompt #:windows (windows 33 0 0 0 0)))
  (define blank-before (ev st 'blank))
  (check-equal? (ev st '(blank frame 8 3)) (ansi "\r\n" 1 1 3 "" #:name "untitled" #:width 8))
  (check-equal? (ev st '(blank frame 1 1)) (ansi "" 1 1 #:name "untitled" #:width 8))
  (check-equal? (ev st 'blank) blank-before)
  (def! st 'controls (session (zipper (list (buffer 44 "a\u001bb\tc\u007f")) 0)))
  (def! st 'safe (rebuild 'controls #:searching #f
    #:prompt '(Option Some (AloemacsPrompt new "L\t" "A\rB" 2 "" (List empty) (List empty) 0))
    #:windows (windows 44 0 0 0 0)))
  (define safe-before (ev st 'safe))
  (check-equal? (ev st '(safe frame 4 2)) (ansi "a b " 1 1 2 "L A " 2 4 #:name "untitled" #:width 4))
  (check-equal? (ev st '(safe frame 1 2)) (ansi "a" 1 1 2 "L" 2 1 #:name "untitled" #:width 1))
  (check-equal? (ev st '(safe frame 4 1)) (ansi "a b " 1 1 #:name "untitled" #:width 4))
  (check-equal? (ev st 'safe) safe-before)
  (check-equal? (unbox calls) '()))
