#lang racket/base

(require racket/list racket/port racket/runtime-path rackunit
         "../../aloe/driver.rkt" "../../aloe/host.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/env.rkt" env-bound?)
         (only-in "../../aloe/type.rkt" exn:fail:aloe-type? type-of type->datum
                  type-environment-bound?)
         "../../host/racket/fs.rkt")

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define-runtime-path main-path "../../examples/aloemacs/main.aloe")
(define no-mark '(if #t (Option None) (Option Some (Position new 0 0))))
(define no-path '(if #t (Option None) (Option Some (Path new "/typed-none"))))
(define no-pending '(if #t (Option None) (Option Some aloemacs-global-keymap)))
(define no-prompt '(if #t (Option None) (Option Some (AloemacsPrompt new "" "" 0))))
(define no-submission '(if #t (Option None) (Option Some "")))
(define no-command '(if #t (Option None) (Option Some (AloemacsCommand FindFile))))
(define fields '(buffers fs echo searching query origin wrapped failing kill-ring
                         pending prompt last-submission waiting-command windows))
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (type st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))
(define (loaded)
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  st)

;; Count the complete thin-Fs call sequence, including nested resolves.
(define (state #:fail [fail #f] #:vanish? [vanish? #f]
               #:literal-untitled? [literal-untitled? #f])
  (define st (loaded))
  (define disk (make-fs-double "/cwd"
    (hash "/cwd" 'directory "/cwd/a.txt" 'file "/cwd/b.txt" 'file
          "/cwd/dir" 'directory "/cwd/link" 'symlink)
    (hash "/cwd/a.txt" "λ\r\nb\n" "/cwd/b.txt" "disk b")))
  (define calls (box '()))
  (define probes 0)
  (define (forward selector args)
    (set-box! calls (append (unbox calls) (list (cons selector args))))
    (when (eq? selector fail) (error 'identity-test "host failure"))
    (when (eq? selector 'kind) (set! probes (add1 probes)))
    (cond
      [(and vanish? (eq? selector 'kind) (> probes 1)) "missing"]
      [(and literal-untitled? (eq? selector 'resolve) (equal? args '("untitled"))) "untitled"]
      [else (host-receiver-send disk selector args)]))
  (define interface
    (make-host-interface 'FsHost
      (for/list ([method (in-list (host-interface-methods fs-interface))])
        (define selector (host-method-selector method))
        (define params (host-method-parameter-types method))
        (make-host-method selector params (host-method-return-type method)
          (case (length params)
            [(0) (lambda (state) (forward selector '()))]
            [(1) (lambda (state a) (forward selector (list a)))]
            [(2) (lambda (state a b) (forward selector (list a b)))])))))
  (driver-inject-host! st 'fs-host (make-host-receiver interface #f))
  (values st calls))
(define (editor contents [cold? #f])
  `(AloemacsEditor new
     ,(if cold? `(Text from-string ,contents) `((Text from-string ,contents) indexed-value))
     (Position new 0 0) #f 0 0 (List empty) ,no-mark 0))
(define (buffer id [contents "same"] [path no-path])
  `(AloemacsBuffer new ,(editor contents) ,path ,id))
;; Expectations use logical positions, never production lookup or allocation.
(define (zipper order focus)
  `(AloemacsBuffers new (List of ,@(reverse (take order focus)))
     ,(list-ref order focus) (List of ,@(drop order (add1 focus)))))
(define (session buffers)
  `(AloemacsSession new ,buffers (Fs new fs-host) "saved" #t "old query"
     (Position new 4 2) #t #t (List of "newest" "older")
     (Option Some aloemacs-ctrl-x-keymap)
     (Option Some (AloemacsPrompt new "draft: " "input" 2))
     (Option Some "previous") (Option Some (AloemacsCommand SaveAs))
     (let ((buffer (,buffers current-buffer)))
       (AloemacsWindows new
         (AloemacsWindowTree Leaf
           (AloemacsView new 0 (buffer id)
             ((buffer editor) scroll-row) ((buffer editor) scroll-col) #f))
         0 0 0))))
(define (rebuild s #:buffers [buffers `(,s buffers)] #:echo [echo `(,s echo)]
                 #:searching [searching `(,s searching)] #:query [query `(,s query)]
                 #:origin [origin `(,s origin)] #:wrapped [wrapped `(,s wrapped)]
                 #:failing [failing `(,s failing)] #:ring [ring `(,s kill-ring)]
                 #:pending [pending `(,s pending)] #:prompt [prompt `(,s prompt)]
                 #:submission [submission `(,s last-submission)]
                 #:waiting [waiting `(,s waiting-command)]
                 #:columns [columns `((,s windows) columns)]
                 #:rows [rows `((,s windows) rows)])
  `(AloemacsSession new ,buffers (,s fs) ,echo ,searching ,query ,origin
     ,wrapped ,failing ,ring ,pending ,prompt ,submission ,waiting
     (let ((buffer (,buffers current-buffer)))
       (AloemacsWindows new
         (AloemacsWindowTree Leaf
           (AloemacsView new 0 (buffer id)
             ((buffer editor) scroll-row) ((buffer editor) scroll-col) #f))
         0 ,columns ,rows))))
(define (replace s ed [path `(,s path)])
  `(AloemacsBuffers new ((,s buffers) before)
     (AloemacsBuffer new ,ed ,path ((,s current-buffer) id)) ((,s buffers) after)))
(define (selected s buffers)
  (rebuild s #:buffers buffers #:echo "" #:searching #f #:query ""
    #:origin '(Position new 0 0) #:wrapped #f #:failing #f #:pending no-pending))
(define (visited s contents path)
  (rebuild s #:buffers (replace s (editor contents) `(Option Some ,path))
    #:echo "" #:searching #f #:query "" #:origin '(Position new 0 0)
    #:wrapped #f #:failing #f #:ring '(List empty) #:pending no-pending
    #:prompt no-prompt #:waiting no-command))
(define (rich! st)
  (def! st 'rich-editor
    '(AloemacsEditor new
       (Text indexed (List of "second" "first") "third-long"
                     (List of "fourth" "fifth") 2)
       (Position new 2 4) #f 2 3
       (List of (UndoFrame new (Text from-string "old") (Position new 0 2) 1 2))
       (Option Some (Position new 1 1)) 4))
  (def! st 'a (buffer 41 "neighbor" '(Option Some (Path new "/cwd/a.txt"))))
  (def! st 'b '(AloemacsBuffer new rich-editor (Option Some (Path new "/cwd/b.txt")) 9))
  (def! st 'c (buffer 27))
  (def! st 'source (session (zipper '(a b c) 1))))
(define (same-session st actual expected)
  (def! st 'actual actual)
  (def! st 'expected expected)
  (same st 'actual 'expected)
  (for ([field fields]) (same st `(actual ,field) `(expected ,field)))
  (for ([field '(before current-buffer after)])
    (same st `((actual buffers) ,field) `((expected buffers) ,field))))

(test-case "exact identity shape, class order, collection and session inventories"
  (define datums (call-with-input-file file-path (lambda (in) (port->list read in))))
  (define classes (filter (lambda (d) (eq? (car d) 'define-class)) datums))
  (define (decl name) (findf (lambda (d) (equal? (cadr d) name)) classes))
  (check-equal? (take datums 2) '((load "editor.aloe") (load "../../lib/fs.aloe")))
  (check-equal? (map cadr classes)
    '(AloemacsPrompt AloemacsBuffer AloemacsBuffers AloemacsModeLine AloemacsView AloemacsWindowTree
      AloemacsWindowRect AloemacsWindows AloemacsCommand
      (AloemacsKeymap B) AloemacsBinding AloemacsSearchScan (AloemacsSession H)))
  (check-equal? (caddr (decl 'AloemacsBuffer))
    '(fields (editor AloemacsEditor) (path (Option Path)) (id Int)))
  (check-equal? (caddr (decl 'AloemacsBuffers))
    '(fields (before (List AloemacsBuffer)) (current-buffer AloemacsBuffer)
             (after (List AloemacsBuffer))))
  (check-equal? (map (lambda (m) (drop-right m 1)) (cdr (cadddr (decl 'AloemacsBuffers))))
    '((with-current-buffer (buffer AloemacsBuffer) AloemacsBuffers)
      (fresh-id () Int)
      (find-id (id Int) (Option AloemacsBuffers))
      (find-id-in (id Int) (remaining Int) (Option AloemacsBuffers))
      (find-name (name String) (Option AloemacsBuffers))
      (find-name-in (name String) (remaining Int) (Option AloemacsBuffers))
      (focus-next () AloemacsBuffers) (focus-previous () AloemacsBuffers)
      (insert-after (buffer AloemacsBuffer) AloemacsBuffers)
      (remove-current () AloemacsBuffers)))
  (check-equal? (caddr (decl '(AloemacsSession H)))
    '(fields (buffers AloemacsBuffers) (fs (Fs H)) (echo String) (searching Bool)
       (query String) (origin Position) (wrapped Bool) (failing Bool)
       (kill-ring (List String)) (pending (Option (AloemacsKeymap AloemacsBinding)))
       (prompt (Option AloemacsPrompt)) (last-submission (Option String))
       (waiting-command (Option AloemacsCommand)) (windows AloemacsWindows))))

(test-case "checked identity sends and constructor negatives retain exact types"
  (define-values (st calls) (state))
  (rich! st)
  (for ([entry (list (list (buffer 18) 'AloemacsBuffer)
                    '((b id) Int) '(((source buffers) fresh-id) Int)
                    '(((source buffers) find-id 9) (Option AloemacsBuffers)))])
    (check-equal? (type st (car entry)) (cadr entry)))
  (for ([bad (append
              '((AloemacsBuffer new rich-editor (Option Some (Path new "x")))
                (AloemacsBuffer new rich-editor (Option Some (Path new "x")) 0 1)
                (AloemacsBuffer new "bad" (Option Some (Path new "x")) 0)
                (AloemacsBuffer new rich-editor (Option Some "bad") 0)
                (AloemacsBuffer new rich-editor (Path new "x") 0)
                (b id 0) ((source buffers) fresh-id 0)
                ((source buffers) find-id) ((source buffers) find-id 9 27))
              (for/list ([id '(1.0 "9" #t (Path new "9") (Option Some 9))])
                `(AloemacsBuffer new rich-editor (Option Some (Path new "x")) ,id))
              (for/list ([id '(1.0 "9" #t b (Option Some 9))])
                `((source buffers) find-id ,id))
              (for*/list ([r '(1 "x" rich-editor b AloemacsBuffers AloemacsBuffer
                              (List of b) source)] [send '((fresh-id) (find-id 9))])
                `(,r ,@send))
              (for/list ([r '(1 "x" rich-editor (source buffers) AloemacsBuffer source)])
                `(,r id)))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st bad)) (format "reject ~s" bad)))
  ;; Raw constructors remain storage, including invalid IDs/point/path.
  (def! st 'raw '(AloemacsBuffer new
                  (AloemacsEditor new (Text from-string "") (Position new 99 -2)
                    #f 0 0 (List empty) (Option Some (Position new -1 4)) 0)
                  (Option Some (Path new "../directory")) -1))
  (check-equal? (ev st '(raw id)) -1)
  (check-equal? (ev st '(((raw editor) point) line)) 99)
  (check-equal? (unbox calls) '()))

(test-case "fold allocation on either side/current and both additions preserves full source"
  (define-values (st calls) (state))
  (rich! st)
  (for ([order '((a) (b) (a b c) (c a b) (b c a))])
    (for ([focus (in-range (length order))])
      (def! st 'source (session (zipper order focus)))
      (define original (ev st 'source))
      (define expected-id (add1 (apply max (map (lambda (b) (ev st `(,b id))) order))))
      (check-equal? (ev st '((source buffers) fresh-id)) expected-id)
      (for ([path (list #f '(Path new "./relative/../new"))])
        (define new (buffer expected-id "added" (if path `(Option Some ,path) no-path)))
        (define new-order (append (take order (add1 focus)) (list new) (drop order (add1 focus))))
        (same-session st `(source add-buffer "added" ,@(if path (list path) '()))
          (selected 'source (zipper new-order (add1 focus)))))
      (check-equal? (ev st 'source) original)))
  (check-equal? (unbox calls) '()))

(test-case "bounded integer lookup uses current then forward/wrap, preserves equal payloads"
  (define-values (st calls) (state))
  (define order (map buffer '(40 2 91 17)))
  (for ([focus (in-range 4)])
    (def! st 'source-buffers (zipper order focus))
    (define original (ev st 'source-buffers))
    (for ([id '(40 2 91 17)] [target (in-naturals)])
      (same st `(source-buffers find-id ,id) `(Option Some ,(zipper order target))))
    (for ([id '(-1 0 18 100)])
      (check-false (ev st `((source-buffers find-id ,id) present?))))
    (same st '(source-buffers find-id-in 17 0) '(if #t (Option None) (Option Some source-buffers)))
    ;; A countdown too short cannot reach the last possible forward hit.
    (define last-id (list-ref '(40 2 91 17) (modulo (sub1 focus) 4)))
    (check-false (ev st `((source-buffers find-id-in ,last-id 3) present?)))
    (same st `(source-buffers find-id-in ,last-id 4)
      `(Option Some ,(zipper order (modulo (sub1 focus) 4))))
    (check-equal? (ev st 'source-buffers) original))
  (def! st 'single (zipper (list (buffer 13)) 0))
  (same st '(single find-id 13) '(Option Some single))
  (check-false (ev st '((single find-id 0) present?)))
  ;; Current-first policy is also defined for raw duplicate-ID collections.
  (def! st 'raw (zipper (list (buffer 5 "first") (buffer 5 "current")) 1))
  (same st '(raw find-id 5) '(Option Some raw))
  (check-equal? (unbox calls) '()))

(test-case "removal preserves survivors, singleton identity and legal reuse"
  (define-values (st calls) (state))
  (rich! st)
  (for ([order '((a) (b) (c) (a b) (a b c))])
    (for ([focus (in-range (length order))])
      (def! st 'source (session (zipper order focus)))
      (define original (ev st 'source))
      (define survivors (append (take order focus) (drop order (add1 focus))))
      (define expected (if (null? survivors)
                          (zipper (list (buffer (ev st `(,(list-ref order focus) id)) "")) 0)
                          (zipper survivors (min focus (sub1 (length survivors))))))
      (same st '((source buffers) remove-current) expected)
      (same-session st '(source kill-buffer) (selected 'source expected))
      (check-equal? (ev st 'source) original)))
  (def! st 'pair (session (zipper (list (buffer 0) (buffer 1)) 1)))
  (def! st 'removed '(pair kill-buffer))
  (same-session st '(removed add-buffer "again")
    (selected 'removed (zipper (list (buffer 0) (buffer 1 "again")) 1)))
  (def! st 'quit-buffer '(AloemacsBuffer new (rich-editor request-quit) (b path) 9))
  (def! st 'single (session (zipper '(quit-buffer) 0)))
  (same-session st '(single kill-buffer) (selected 'single (zipper (list (buffer 9 "")) 0)))
  (check-equal? (unbox calls) '()))

(test-case "rich replacements, editor transitions, search and prompts preserve nonzero ID"
  (define-values (st calls) (state))
  (rich! st)
  (define original (ev st 'source))
  (same st '(b with-editor (a editor)) '(AloemacsBuffer new (a editor) (b path) 9))
  (same st '(b with-path (Path new "relative"))
    '(AloemacsBuffer new rich-editor (Option Some (Path new "relative")) 9))
  (same-session st '(source with-current-path (Path new "new"))
    (rebuild 'source #:buffers (replace 'source 'rich-editor '(Option Some (Path new "new")))))
  (for ([send '((insert "λ") (newline) (backward-delete) (move-left) (move-right)
                (move-up) (move-down) (line-start) (line-end) (page-up) (page-down)
                (buffer-start) (buffer-end) (undo) (request-quit))])
    (same-session st `(source ,@send)
      (rebuild 'source #:buffers (replace 'source `(rich-editor ,@send)))))
  (same-session st '(source with-editor (a editor))
    (rebuild 'source #:buffers (replace 'source '(a editor))))
  (same-session st '(source with-search (a editor) #f "new query" (Position new 3 1) #f #t)
    (rebuild 'source #:buffers (replace 'source '(a editor)) #:searching #f
      #:query "new query" #:origin '(Position new 3 1) #:wrapped #f #:failing #t))
  (same-session st '(source with-kill-state (a editor) (List of "cut"))
    (rebuild 'source #:buffers (replace 'source '(a editor)) #:echo "" #:ring '(List of "cut")))
  (same-session st '(source find)
    (rebuild 'source #:searching #t #:query "" #:origin '(source point) #:wrapped #f #:failing #f))
  (same-session st '(source ensure-visible 1 2)
    (rebuild 'source #:columns 1 #:rows 2 #:buffers (replace 'source
      '(AloemacsEditor new (source text) (source point) #f 2 4
         (rich-editor history) (rich-editor mark) 1))))
  (def! st 'searching (rebuild 'source #:searching #t #:query "" #:origin '(source point)
                       #:wrapped #f #:failing #f))
  ;; A real search hit refocuses Text while retaining editor metadata.
  (same-session st '(searching search-key "f")
    (rebuild 'searching #:buffers (replace 'searching
      '(AloemacsEditor new
         (Text indexed (List of "third-long" "second" "first") "fourth"
                       (List of "fifth") 3)
         (Position new 3 0) #f 2 3 (rich-editor history) (rich-editor mark) 4))
      #:query "f" #:wrapped #f #:failing #f))
  (same-session st '(searching search-key "z")
    (rebuild 'searching #:query "z" #:failing #t))
  (same-session st '(source with-echo "failed") (rebuild 'source #:echo "failed"))
  (same-session st '(source clear-prefix) (rebuild 'source #:pending no-pending))
  (same-session st '(source with-prefix aloemacs-global-keymap)
    (rebuild 'source #:echo "" #:pending '(Option Some aloemacs-global-keymap)))
  (same-session st '(source with-active-prompt (AloemacsPrompt new "new: " "x" 1))
    (rebuild 'source #:prompt '(Option Some (AloemacsPrompt new "new: " "x" 1))))
  (same-session st '(source cancel-prompt) (rebuild 'source #:prompt no-prompt #:waiting no-command))
  (same-session st '(source prompt-key "x")
    (rebuild 'source #:prompt '(Option Some (AloemacsPrompt new "draft: " "inxput" 3))))
  (same-session st '(source switch-buffer) (selected 'source (zipper '(a b c) 2)))
  (same st '((source buffers) focus-previous) (zipper '(a b c) 0))
  (same-session st '(source select-buffer-submitted "/cwd/a.txt")
    (selected 'source (zipper '(a b c) 0)))
  (same-session st '(source select-buffer-submitted "missing") (rebuild 'source #:echo "failed"))
  (check-equal? (ev st 'source) original)
  (check-equal? (unbox calls) '()))

(define (read-calls typed resolved)
  (list (list 'resolve typed) (list 'kind resolved) (list 'resolve resolved)
        (list 'kind resolved) (list 'resolve resolved) (list 'read resolved)))
(define (write-calls typed resolved contents [new? #f])
  (append (list (list 'resolve typed) (list 'kind resolved) (list 'resolve resolved))
          (if new? (list (list 'root? resolved) (list 'parent resolved)
                        '(kind "/cwd") '(resolve "/cwd")) '())
          (list (list 'write resolved contents))))

(test-case "visited/direct visit replace under existing ID, exact effects and refusal state"
  (define-values (st calls) (state))
  (rich! st)
  (define original (ev st 'source))
  (same-session st '(source visited "replacement" (Path new "raw"))
    (visited 'source "replacement" '(Path new "raw")))
  (check-equal? (unbox calls) '())
  (same st '(source visit (Path new "a.txt"))
    `(Option Some ,(visited 'source "λ\r\nb\n" '(Path new "/cwd/a.txt"))))
  (check-equal? (unbox calls) (read-calls "a.txt" "/cwd/a.txt"))
  (set-box! calls '())
  (same st '(source visit (Path new "missing"))
    `(Option Some ,(visited 'source "" '(Path new "/cwd/missing"))))
  (check-equal? (unbox calls) '((resolve "missing") (kind "/cwd/missing") (resolve "/cwd/missing")))
  (for ([name '("dir" "link")])
    (set-box! calls '())
    (check-false (ev st `((source visit (Path new ,name)) present?)))
    (check-equal? (unbox calls) (list (list 'resolve name) (list 'kind (string-append "/cwd/" name))
                                    (list 'resolve (string-append "/cwd/" name)))))
  (check-equal? (ev st 'source) original)
  (define-values (gone gone-calls) (state #:vanish? #t))
  (rich! gone)
  (check-false (ev gone '((source visit (Path new "a.txt")) present?)))
  (check-equal? (unbox gone-calls) (take (read-calls "a.txt" "/cwd/a.txt") 5))
  (same gone 'source (session (zipper '(a b c) 1))))

(test-case "duplicate names reuse current/first-forward IDs, new files allocate once"
  (define-values (st calls) (state))
  ;; Equal editor/path values with distinct identities must still all be scanned.
  (define order (list (buffer 40 "same" '(Option Some (Path new "/cwd/a.txt")))
                      (buffer 2 "same" '(Option Some (Path new "/cwd/a.txt")))
                      (buffer 91) (buffer 17)))
  (for ([focus '(0 1 2 3)] [target '(0 1 0 0)])
    (def! st 'source (session (zipper order focus)))
    (define original (ev st 'source))
    (same st '((source buffers) find-name "/cwd/a.txt") `(Option Some ,(zipper order target)))
    (same-session st '(source find-file-submitted "a.txt")
      (selected 'source (zipper order target)))
    (check-equal? (unbox calls) '((resolve "a.txt")))
    (set-box! calls '())
    (same-session st '(source select-buffer-submitted "/cwd/a.txt")
      (selected 'source (zipper order target)))
    (check-equal? (unbox calls) '())
    (check-equal? (ev st 'source) original))
  (def! st 'source (session (zipper order 3)))
  (same st '((source buffers) find-name "untitled") `(Option Some ,(zipper order 3)))
  (def! st 'forward-source (session (zipper order 1)))
  (same st '((forward-source buffers) find-name "untitled") `(Option Some ,(zipper order 2)))
  (same-session st '(source find-file-submitted "b.txt")
    (selected 'source (zipper (append order (list (buffer 92 "disk b" '(Option Some (Path new "/cwd/b.txt"))))) 4)))
  (check-equal? (unbox calls) (read-calls "b.txt" "/cwd/b.txt"))
  (set-box! calls '())
  (same-session st '(source find-file-submitted "missing")
    (selected 'source (zipper (append order (list (buffer 92 "" '(Option Some (Path new "/cwd/missing"))))) 4)))
  (check-equal? (unbox calls) '((resolve "missing") (kind "/cwd/missing") (resolve "/cwd/missing")))
  (set-box! calls '())
  (same-session st '(source find-file-submitted "") (rebuild 'source #:echo "failed"))
  (check-equal? (unbox calls) '())
  ;; A nominal host may return this exact text. Name reuse still gives neither
  ;; pathless buffers nor a stored literal "untitled" name special priority.
  (define-values (literal literal-calls) (state #:literal-untitled? #t))
  (define untitled-order (list (buffer 5) (buffer 13 "same" '(Option Some (Path new "untitled")))
                               (buffer 19 "other" '(Option Some (Path new "other")))))
  (for ([focus '(0 1 2)] [target '(0 1 0)])
    (def! literal 'source (session (zipper untitled-order focus)))
    (define original (ev literal 'source))
    (same-session literal '(source find-file-submitted "untitled")
      (selected 'source (zipper untitled-order target)))
    (check-equal? (unbox literal-calls) '((resolve "untitled")))
    (check-equal? (ev literal 'source) original)
    (set-box! literal-calls '())))

(test-case "save and save-as retain ID and full state, counted success/refusal/Return"
  (define-values (st calls) (state))
  (rich! st)
  (define original (ev st 'source))
  (define contents (ev st '((source text) to-string)))
  (same st '(source save) '(Option Some source))
  (check-equal? (unbox calls) (cdr (write-calls "/cwd/b.txt" "/cwd/b.txt" contents)))
  (set-box! calls '())
  (same-session st '(source save-as-submitted "./relative/../new")
    (rebuild 'source #:buffers (replace 'source 'rich-editor '(Option Some (Path new "/cwd/new"))) #:echo "saved"))
  (check-equal? (unbox calls) (write-calls "./relative/../new" "/cwd/new" contents #t))
  (for ([name '("" "dir" "link")])
    (set-box! calls '())
    (same-session st `(source save-as-submitted ,name) (rebuild 'source #:echo "failed"))
    (check-equal? (unbox calls)
      (if (equal? name "") '() (list (list 'resolve name) (list 'kind (string-append "/cwd/" name))
                                     (list 'resolve (string-append "/cwd/" name))))))
  (set-box! calls '())
  (def! st 'draft (rebuild 'source #:searching #f #:pending no-pending
    #:prompt '(Option Some (AloemacsPrompt new "Save as: " "new.txt" 7))))
  (same-session st '(draft handle-key "return")
    (rebuild 'draft #:buffers (replace 'draft 'rich-editor '(Option Some (Path new "/cwd/new.txt")))
      #:echo "saved" #:prompt no-prompt #:submission '(Option Some "new.txt") #:waiting no-command))
  (check-equal? (unbox calls) (write-calls "new.txt" "/cwd/new.txt" contents #t))
  (check-equal? (ev st 'source) original)
  (define-values (bad bad-calls) (state #:fail 'write))
  (rich! bad)
  (check-exn exn:fail? (lambda () (ev bad '(source save-as-submitted "new"))))
  (check-equal? (unbox bad-calls) (write-calls "new" "/cwd/new" contents #t))
  (same bad 'source (session (zipper '(a b c) 1))))

(test-case "fresh checked file load has no capabilities/effects; main is exact cold ID zero"
  (define out (open-output-string))
  (define err (open-output-string))
  (define st (parameterize ([current-output-port out] [current-error-port err]) (loaded)))
  (for ([name '(fs-host term)])
    (check-false (env-bound? (driver-runtime-environment st) name))
    (check-false (type-environment-bound? (driver-type-environment st) name)))
  (check-equal? (get-output-string out) "")
  (check-equal? (get-output-string err) "")
  (check-exn exn:fail:aloe-type? (lambda () (ev (make-driver) `(load ,(path->string main-path)))))
  (define-values (main calls) (state))
  (ev main `(load ,(path->string main-path)))
  (same-session main 'aloemacs-editor
    `(AloemacsSession new ,(zipper (list `(AloemacsBuffer new ,(editor "" #t) ,no-path 0)) 0)
       (Fs new fs-host) "" #f "" (Position new 0 0) #f #f (List empty)
       ,no-pending ,no-prompt ,no-submission ,no-command
     (let ((buffer (,(zipper (list `(AloemacsBuffer new ,(editor "" #t) ,no-path 0)) 0) current-buffer)))
       (AloemacsWindows new
         (AloemacsWindowTree Leaf
           (AloemacsView new 0 (buffer id)
             ((buffer editor) scroll-row) ((buffer editor) scroll-col) #f))
         0 0 0))))
  (check-equal? (ev main '((aloemacs-editor current-buffer) id)) 0)
  (check-false (env-bound? (driver-runtime-environment main) 'term))
  (check-equal? (unbox calls) '()))
