#lang racket/base

(require racket/list racket/port racket/runtime-path rackunit
         "../../aloe/driver.rkt" "../../aloe/host.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/type.rkt" exn:fail:aloe-type? type-of type->datum)
         "../../host/racket/fs.rkt")

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define no-mark '(if #t (Option None) (Option Some (Position new 0 0))))
(define no-path '(if #t (Option None) (Option Some (Path new "/typed-none"))))
(define no-pending '(if #t (Option None) (Option Some aloemacs-global-keymap)))
(define no-prompt '(if #t (Option None) (Option Some (AloemacsPrompt new "" "" 0 "" (List empty) (List empty) 0))))
(define no-submission '(if #t (Option None) (Option Some "")))
(define no-command '(if #t (Option None) (Option Some (AloemacsCommand FindFile))))
(define fields
  '(buffers fs echo searching query origin wrapped failing kill-ring pending
            prompt last-submission waiting-command windows))
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))
(define (type st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))
(define (state #:fail [fail #f])
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  (define disk (make-fs-double "/cwd"
    (hash "/cwd" 'directory "/cwd/a.txt" 'file "/cwd/b.txt" 'file
          "/cwd/dir" 'directory "/cwd/link" 'symlink "/cwd/other" "socket")
    (hash "/cwd/a.txt" "λ\r\nb\n" "/cwd/b.txt" "disk b")))
  (define calls (box '()))
  (define (forward selector args)
    (set-box! calls (append (unbox calls) (list (cons selector args))))
    (when (eq? selector fail) (error 'windows-state "host failure"))
    (host-receiver-send disk selector args))
  (define interface
    (make-host-interface 'FsHost
      (for/list ([method (in-list (host-interface-methods fs-interface))])
        (define selector (host-method-selector method))
        (define params (host-method-parameter-types method))
        (make-host-method selector params (host-method-return-type method)
          (case (length params)
            [(0) (lambda (state) (forward selector '()))]
            [(1) (lambda (state a) (forward selector (list a)))]
            [(2) (lambda (state a b) (forward selector (list a b)))])))))
  (driver-inject-host! st 'fs-host (make-host-receiver interface #f))
  (values st calls))

;; Expected values are raw constructors. The model chooses leaves from a
;; concrete visit-order list, independently of the product's recursive sends.
(define views '((71 9 7 11 #t) (3 41 5 6 #f) (55 9 2 3 #t)
                (8 27 9 13 #t) (24 9 4 8 #f)))
(define (leaf v) `(AloemacsWindowTree Leaf (AloemacsView new ,@v)))
(define (tree vs)
  `(AloemacsWindowTree Below
     (AloemacsWindowTree Right ,(leaf (list-ref vs 0))
       (AloemacsWindowTree Below ,(leaf (list-ref vs 1)) ,(leaf (list-ref vs 2))))
     (AloemacsWindowTree Right ,(leaf (list-ref vs 3)) ,(leaf (list-ref vs 4)))))
(define (config [vs views] [selected 55] [columns 80] [rows 24])
  `(AloemacsWindows new ,(tree vs) ,selected ,columns ,rows))
(define (selected-views vs selected id row col)
  (for/list ([v vs])
    (if (= (car v) selected) (list selected id row col (list-ref v 4)) v)))
(define (removed-views vs removed id row col)
  (for/list ([v vs])
    (if (= (cadr v) removed) (list (car v) id row col (list-ref v 4)) v)))
(define (zipper order focus)
  `(AloemacsBuffers new (List of ,@(reverse (take order focus)))
     ,(list-ref order focus) (List of ,@(drop order (add1 focus)))))
(define lines '("first" "second" "third-long" "fourth" "fifth"))
(define rich-string "first\nsecond\nthird-long\nfourth\nfifth")
(define (indexed ls focus)
  `(Text indexed (List of ,@(reverse (take ls focus))) ,(list-ref ls focus)
     (List of ,@(drop ls (add1 focus))) ,focus))
(define rich-history
  '(List of (UndoFrame new (Text from-string "old") (Position new 0 2) 1 2)))
(define (editor #:text [text (indexed lines 2)] #:line [line 2] #:col [col 4]
                #:quit [quit #f] #:row [row 2] #:left [left 3]
                #:history [history rich-history]
                #:mark [mark '(Option Some (Position new 1 1))] #:rows [rows 4])
  `(AloemacsEditor new ,text (Position new ,line ,col) ,quit ,row ,left
     ,history ,mark ,rows))
(define (fresh contents)
  `(AloemacsEditor new ,(indexed (string-split-lines contents) 0)
     (Position new 0 0) #f 0 0 (List empty) ,no-mark 0))
;; Keep trailing empty lines without depending on Aloe Text construction.
(define (string-split-lines contents)
  (regexp-split #rx"\n" contents))
(define (buffer id ed [path no-path]) `(AloemacsBuffer new ,ed ,path ,id))
(define (session buffers [windows (config)])
  `(AloemacsSession new ,buffers (Fs new fs-host) "saved" #t "old query"
     (Position new 4 2) #t #t (List of "newest" "older")
     (Option Some aloemacs-ctrl-x-keymap)
     (Option Some (AloemacsPrompt new "draft: " "input" 2 "" (List empty) (List empty) 0))
     (Option Some "previous") (Option Some (AloemacsCommand SaveAs)) ,windows))
(define (rebuild s #:buffers [buffers `(,s buffers)] #:echo [echo `(,s echo)]
                 #:searching [searching `(,s searching)] #:query [query `(,s query)]
                 #:origin [origin `(,s origin)] #:wrapped [wrapped `(,s wrapped)]
                 #:failing [failing `(,s failing)] #:ring [ring `(,s kill-ring)]
                 #:pending [pending `(,s pending)] #:prompt [prompt `(,s prompt)]
                 #:submission [submission `(,s last-submission)]
                 #:waiting [waiting `(,s waiting-command)] #:windows [windows `(,s windows)])
  `(AloemacsSession new ,buffers (,s fs) ,echo ,searching ,query ,origin
     ,wrapped ,failing ,ring ,pending ,prompt ,submission ,waiting ,windows))
(define (replacement s ed [path `(,s path)])
  `(AloemacsBuffers new ((,s buffers) before)
     (AloemacsBuffer new ,ed ,path ((,s current-buffer) id)) ((,s buffers) after)))
(define (selection s buffers windows)
  (rebuild s #:buffers buffers #:echo "" #:searching #f #:query ""
    #:origin '(Position new 0 0) #:wrapped #f #:failing #f #:pending no-pending
    #:windows windows))
(define (visited s contents path windows)
  (rebuild s #:buffers (replacement s (fresh contents) `(Option Some ,path))
    #:echo "" #:searching #f #:query "" #:origin '(Position new 0 0)
    #:wrapped #f #:failing #f #:ring '(List empty) #:pending no-pending
    #:prompt no-prompt #:waiting no-command #:windows windows))
(define (fixture! st)
  (def! st 'rich (editor))
  (def! st 'a (buffer 41
    (editor #:text '(Text from-string "same\nother") #:line 1 #:col 2
            #:row 1 #:left 1) '(Option Some (Path new "/cwd/a.txt"))))
  (def! st 'b (buffer 9 'rich '(Option Some (Path new "/cwd/b.txt"))))
  (def! st 'c (buffer 27
    (editor #:text (indexed '("one" "three" "last") 1) #:line 1 #:col 3
            #:row 1 #:left 2 #:rows 5)))
  (def! st 'source (session (zipper '(a b c) 1))))
(define (logical s)
  `(((,s buffers) before) fold
     (((,s buffers) after) cons (,s current-buffer))
     (fn (buffers buffer) (buffers cons buffer))))
(define (same-session st actual expected)
  (def! st 'actual actual)
  (def! st 'expected expected)
  (same st 'actual 'expected)
  (for ([field fields]) (same st `(actual ,field) `(expected ,field)))
  (same st '(((actual windows) tree) leaves) '(((expected windows) tree) leaves))
  (same st (logical 'actual) (logical 'expected))
  ;; Every returned leaf resolves to a live buffer; selected/current stay aligned.
  (check-true (ev st
    '((((actual windows) tree) leaves) fold #t
       (fn (live view)
         (if live (((actual buffers) find-id (view buffer-id)) present?) #f)))))
  (same st
    '((((actual windows) tree) find-view ((actual windows) selected)) case
       (None () -1) (Some (view) (view buffer-id))) '((actual current-buffer) id))
  (for ([field '(scroll-row scroll-col)])
    (same st
      `((((actual windows) tree) find-view ((actual windows) selected)) case
         (None () -1) (Some (view) (view ,field))) `((actual editor) ,field))))
(define (assert-effects calls expected)
  (check-equal? (unbox calls) expected)
  (set-box! calls '()))
(define (read-calls typed resolved)
  (list (list 'resolve typed) (list 'kind resolved) (list 'resolve resolved)
        (list 'kind resolved) (list 'resolve resolved) (list 'read resolved)))
(define (write-calls typed resolved contents)
  (list (list 'resolve typed) (list 'kind resolved) (list 'resolve resolved)
        (list 'write resolved contents)))

(test-case "selected IDs at several visit positions; pure typed internal state sends"
  (define-values (st calls) (state))
  (fixture! st)
  (define original (ev st 'source))
  (define target (buffer 63 (editor #:row 12 #:left 16)))
  (for ([selected '(71 3 55 8 24)])
    (define consistent (selected-views views selected 9 2 3))
    (def! st 's (session (zipper '(a b c) 1) (config consistent selected)))
    (define changed (selected-views consistent selected 63 12 16))
    (same st `((s windows) with-buffer ,target) (config changed selected))
    (same st `(((s windows) tree) with-view-buffer ,selected ,target) (tree changed))
    (same st `(((s windows) tree) with-view-buffer 999 ,target) (tree consistent))
    (same st `((s windows) without-buffer 9 ,target)
      (config (removed-views consistent 9 63 12 16) selected)))
  (def! st 't (tree views))
  (same st '(t retarget-buffer 9 63 12 16) (tree (removed-views views 9 63 12 16)))
  (same st '(t retarget-buffer 999 63 12 16) (tree views))
  (for ([entry `(((t with-view-buffer 55 ,target) AloemacsWindowTree)
                ((t retarget-buffer 9 63 12 16) AloemacsWindowTree)
                (((source windows) without-buffer 9 ,target) AloemacsWindows)
                (((source windows) with-buffer ,target) AloemacsWindows))])
    (check-equal? (type st (car entry)) (cadr entry)))
  (for ([bad '((t with-view-buffer) (t with-view-buffer 55)
               (t with-view-buffer 55 b b) (t with-view-buffer "55" b)
               (t with-view-buffer 55 rich) (b with-view-buffer 55 b)
               (t retarget-buffer 9 27 1) (t retarget-buffer 9 27 1 2 3)
               (t retarget-buffer #f 27 1 2) (t retarget-buffer 9 "27" 1 2)
               (t retarget-buffer 9 27 #f 2) (t retarget-buffer 9 27 1 "2")
               (b retarget-buffer 9 27 1 2) ((source windows) without-buffer)
               ((source windows) without-buffer 9)
               ((source windows) without-buffer 9 b b)
               ((source windows) without-buffer "9" b)
               ((source windows) without-buffer 9 rich) (t without-buffer 9 b))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
  (check-equal? (ev st 'source) original)
  (assert-effects calls '()))

(test-case "all preserving reconstructions, prompt, submission, prefix and command slots"
  (define-values (st calls) (state))
  (fixture! st)
  (define original (ev st 'source))
  (for ([entry (list
    (list '(source unchanged) (rebuild 'source))
    (list '(source with-echo "failed") (rebuild 'source #:echo "failed"))
    (list '(source with-prefix aloemacs-global-keymap)
          (rebuild 'source #:echo "" #:pending '(Option Some aloemacs-global-keymap)))
    (list '(source clear-prefix) (rebuild 'source #:pending no-pending))
    (list '(source with-active-prompt (AloemacsPrompt new "new: " "x" 1 "" (List empty) (List empty) 0))
          (rebuild 'source #:prompt '(Option Some (AloemacsPrompt new "new: " "x" 1 "" (List empty) (List empty) 0))))
    (list '(source with-waiting-command (AloemacsCommand SelectBuffer))
          (rebuild 'source #:waiting '(Option Some (AloemacsCommand SelectBuffer))))
    (list '(source clear-waiting-command) (rebuild 'source #:waiting no-command))
    (list '(source cancel-prompt) (rebuild 'source #:prompt no-prompt #:waiting no-command))
    (list '(source with-current-path (Path new "/new"))
          (rebuild 'source #:buffers (replacement 'source 'rich '(Option Some (Path new "/new")))))
    (list '(source find) (rebuild 'source #:searching #t #:query "" #:origin '(source point)
                                #:wrapped #f #:failing #f))
    (list '(source end-search) (rebuild 'source #:searching #f #:query ""
                                      #:origin '(Position new 0 0) #:wrapped #f #:failing #f)))])
    (same-session st (car entry) (cadr entry)))
  (def! st 'draft (rebuild 'source #:searching #f #:pending no-pending #:waiting no-command))
  (for ([send '((prompt-key "λ") (prompt-key "backspace") (prompt-key "left")
                (prompt-key "right") (prompt-key "line-start") (prompt-key "line-end"))]
        [text '("inλput" "iput" "input" "input" "input" "input")]
        [column '(3 1 1 3 0 5)])
    (same-session st `(draft ,@send)
      (rebuild 'draft #:prompt `(Option Some (AloemacsPrompt new "draft: " ,text ,column "" (List empty) (List empty) 0)))))
  (same-session st '(draft handle-key "ctrl-x") (rebuild 'draft))
  (same-session st '(draft prompt-key "\n") (rebuild 'draft))
  (same-session st '(draft submit-prompt)
    (rebuild 'draft #:prompt no-prompt #:submission '(Option Some "input")))
  (same-session st '(draft prompt-key "escape")
    (rebuild 'draft #:prompt no-prompt #:waiting no-command))
  (def! st 'idle (rebuild 'draft #:prompt no-prompt))
  (same-session st '(idle start-prompt "Ask: ")
    (rebuild 'idle #:prompt '(Option Some (AloemacsPrompt new "Ask: " "" 0 "" (List empty) (List empty) 0))))
  (same-session st '(idle execute-command (AloemacsCommand FindFile) "find")
    (rebuild 'idle #:prompt '(Option Some (AloemacsPrompt new "Find file: " "/cwd/" 5 "" (List empty) (List empty) 0))
      #:waiting '(Option Some (AloemacsCommand FindFile))))
  (same-session st '(idle handle-key "ctrl-x")
    (rebuild 'idle #:echo "" #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (def! st 'prefixed (rebuild 'idle #:echo "" #:pending '(Option Some aloemacs-ctrl-x-keymap)))
  (same-session st '(prefixed handle-key "x") (rebuild 'prefixed #:pending no-pending))
  (same-session st '(prefixed handle-key "b")
    (rebuild 'prefixed #:pending no-pending
      #:prompt '(Option Some (AloemacsPrompt new "Buffer: " "" 0 "" (List empty) (List empty) 0))
      #:waiting '(Option Some (AloemacsCommand SelectBuffer))))
  (def! st 'slot (rebuild 'idle #:waiting '(Option Some (AloemacsCommand SaveAs))))
  (same-session st '(slot cancel-prompt) (rebuild 'slot #:waiting no-command))
  (same-session st '(slot run-submitted-command)
    (rebuild 'slot #:buffers (replacement 'slot 'rich '(Option Some (Path new "/cwd/previous")))
      #:echo "saved" #:waiting no-command))
  (assert-effects calls
    `((root? "/cwd/b.txt") (parent "/cwd/b.txt")
      (resolve "previous") (kind "/cwd/previous") (resolve "/cwd/previous")
      (root? "/cwd/previous") (parent "/cwd/previous") (kind "/cwd") (resolve "/cwd")
      (write "/cwd/previous" ,rich-string)))
  (check-equal? (ev st 'source) original))

(test-case "selected-only rich edit, motion, undo and quit with one shared editor"
  (define-values (st calls) (state))
  (fixture! st)
  (define original (ev st 'source))
  (define pushed
    `(List of (UndoFrame new ,(indexed lines 2) (Position new 2 4) 2 3)
       (UndoFrame new (Text from-string "old") (Position new 0 2) 1 2)))
  (define (at line col) (editor #:text (indexed lines line) #:line line #:col col))
  (define expected-editors
    (list
      (editor #:text (indexed '("first" "second" "thirλd-long" "fourth" "fifth") 2)
              #:col 5 #:history pushed)
      (editor #:text (indexed '("first" "second" "thir" "d-long" "fourth" "fifth") 3)
              #:line 3 #:col 0 #:history pushed)
      (editor #:text (indexed '("first" "second" "thid-long" "fourth" "fifth") 2)
              #:col 3 #:history pushed)
      (at 2 3) (at 2 5) (at 1 4) (at 3 4) (at 2 0) (at 2 10)
      (at 0 4) (at 4 4) (at 0 0) (at 4 5)
      (editor #:text '(Text from-string "old") #:line 0 #:col 2 #:row 1 #:left 2
              #:history '(List empty))
      (editor #:quit #t)))
  (for ([send '((insert "λ") (newline) (backward-delete) (move-left) (move-right)
                (move-up) (move-down) (line-start) (line-end) (page-up) (page-down)
                (buffer-start) (buffer-end) (undo) (request-quit))]
        [ed expected-editors])
    (define row (if (equal? send '(undo)) 1 2))
    (define col (if (equal? send '(undo)) 2 3))
    (same-session st `(source ,@send)
      (rebuild 'source #:buffers (replacement 'source ed)
        #:windows (config (selected-views views 55 9 row col))))
    ;; Resolve two inactive views of current: both see that very editor,
    ;; including its point/history/mark/quit, without installing their origins.
    (for ([id '(71 24)])
      (same st
        `(((actual buffers) find-id 9) case
           (None () ,(fresh "impossible")) (Some (buffers) ((buffers current-buffer) editor))) ed)
      (same st `(((actual windows) tree) find-view ,id)
        `(Option Some (AloemacsView new ,@(findf (lambda (v) (= (car v) id)) views))))))
  (same-session st '(source with-editor (a editor))
    (rebuild 'source #:buffers (replacement 'source '(a editor))
      #:windows (config (selected-views views 55 9 1 1))))
  (same-session st '(source with-kill-state (a editor) (List of "cut"))
    (rebuild 'source #:buffers (replacement 'source '(a editor)) #:echo "" #:ring '(List of "cut")
      #:windows (config (selected-views views 55 9 1 1))))
  (same-session st '(source with-search (a editor) #f "new" (Position new 3 1) #f #t)
    (rebuild 'source #:buffers (replacement 'source '(a editor)) #:searching #f #:query "new"
      #:origin '(Position new 3 1) #:wrapped #f #:failing #t
      #:windows (config (selected-views views 55 9 1 1))))
  ;; Cold current text remains cold through quit and origin-only mirroring.
  (def! st 'cold-ed (editor #:text `(Text from-string ,rich-string)))
  (def! st 'cold (rebuild 'source #:buffers (replacement 'source 'cold-ed)))
  (same-session st '(cold request-quit)
    (rebuild 'cold #:buffers (replacement 'cold (editor #:text `(Text from-string ,rich-string) #:quit #t))))
  (same-session st '(cold with-editor (AloemacsEditor new (cold-ed text) (cold-ed point)
                                      #f 99 101 (cold-ed history) (cold-ed mark) 4))
    (rebuild 'cold #:buffers (replacement 'cold
      (editor #:text `(Text from-string ,rich-string) #:row 99 #:left 101))
      #:windows (config (selected-views views 55 9 99 101))))
  (check-equal? (ev st 'source) original)
  (assert-effects calls '()))

(test-case "successful, failing, repeated and wrapped search preserve inactive origins"
  (define-values (st calls) (state))
  (fixture! st)
  (def! st 'search (rebuild 'source #:query "" #:origin '(source point) #:wrapped #f #:failing #f))
  (define hit (editor #:text (indexed lines 3) #:line 3 #:col 0))
  (same-session st '(search search-key "f")
    (rebuild 'search #:buffers (replacement 'search hit) #:query "f"))
  (same-session st '(search search-key "z") (rebuild 'search #:query "z" #:failing #t))
  (def! st 'hit (rebuild 'search #:buffers (replacement 'search hit) #:query "f"))
  (define second (editor #:text (indexed lines 4) #:line 4 #:col 0))
  (same-session st '(hit search-key "find") (rebuild 'hit #:buffers (replacement 'hit second)))
  (def! st 'second (rebuild 'hit #:buffers (replacement 'hit second)))
  (define final-match (editor #:text (indexed lines 4) #:line 4 #:col 2))
  (same-session st '(second search-key "find")
    (rebuild 'second #:buffers (replacement 'second final-match)))
  (def! st 'final-match (rebuild 'second #:buffers (replacement 'second final-match)))
  (define wrap (editor #:text (indexed lines 0) #:line 0 #:col 0))
  (same-session st '(final-match search-key "find")
    (rebuild 'final-match #:buffers (replacement 'final-match wrap) #:wrapped #t))
  (def! st 'wrap (rebuild 'final-match #:buffers (replacement 'final-match wrap) #:wrapped #t))
  (same-session st '(wrap search-key "find") (rebuild 'wrap #:failing #t))
  (same-session st '(hit search-key "backspace")
    (rebuild 'hit #:buffers (replacement 'hit (editor)) #:query ""))
  (same-session st '(hit search-key "return")
    (rebuild 'hit #:searching #f #:query "" #:origin '(Position new 0 0) #:wrapped #f #:failing #f))
  (assert-effects calls '()))

(test-case "mark, region/line kills and yank retain shared ownership and selected-only mirroring"
  (define-values (st calls) (state))
  (fixture! st)
  (same-session st '(source set-mark)
    (rebuild 'source #:buffers (replacement 'source (editor #:mark '(Option Some (Position new 2 4))))
      #:echo ""))
  (define pushed
    `(List of (UndoFrame new ,(indexed lines 2) (Position new 2 4) 2 3)
       (UndoFrame new (Text from-string "old") (Position new 0 2) 1 2)))
  (same-session st '(source kill)
    (rebuild 'source #:buffers (replacement 'source
      (editor #:text (indexed '("first" "sd-long" "fourth" "fifth") 1)
        #:line 1 #:col 1 #:history pushed #:mark no-mark))
      #:echo "" #:ring '(List of "econd\nthir" "newest" "older")))
  (same-session st '(source kill-line)
    (rebuild 'source #:buffers (replacement 'source
      (editor #:text (indexed '("first" "second" "thir" "fourth" "fifth") 2) #:history pushed))
      #:echo "" #:ring '(List of "d-long" "newest" "older")))
  (same-session st '(source yank)
    (rebuild 'source #:buffers (replacement 'source
      (editor #:text (indexed '("first" "second" "thirnewestd-long" "fourth" "fifth") 2)
              #:col 10 #:history pushed)) #:echo ""))
  (def! st 'empty-ring (rebuild 'source #:ring '(List empty)))
  (same-session st '(empty-ring yank) (rebuild 'empty-ring #:echo ""))
  (def! st 'unmarked (rebuild 'source #:buffers (replacement 'source (editor #:mark no-mark))))
  (same-session st '(unmarked kill) (rebuild 'unmarked #:echo ""))
  (assert-effects calls '()))

(test-case "both add arities, selected-buffers, switches, sparse IDs and duplicate names"
  (define-values (st calls) (state))
  (fixture! st)
  (define original (ev st 'source))
  (for ([path (list #f '(Path new "/new"))])
    (define added (buffer 42 (fresh "added") (if path `(Option Some ,path) no-path)))
    (same-session st `(source add-buffer "added" ,@(if path (list path) '()))
      (selection 'source (zipper (list 'a 'b added 'c) 2)
        (config (selected-views views 55 42 0 0)))))
  (same-session st '(source switch-buffer)
    (selection 'source (zipper '(a b c) 2) (config (selected-views views 55 27 1 2))))
  (same-session st '(source selected-buffers (source buffers))
    (selection 'source (zipper '(a b c) 1) (config)))
  (same-session st '(source selected-buffers (AloemacsBuffers new (List empty) a (List of b c)))
    (selection 'source (zipper '(a b c) 0) (config (selected-views views 55 41 1 1))))
  (for ([name '("/cwd/b.txt" "/cwd/a.txt" "untitled")]
        [focus '(1 0 2)] [id '(9 41 27)] [row '(2 1 1)] [col '(3 1 2)])
    (same-session st `(source select-buffer-submitted ,name)
      (selection 'source (zipper '(a b c) focus) (config (selected-views views 55 id row col)))))
  (for ([name '("" "missing" "b.txt")])
    (same-session st `(source select-buffer-submitted ,name) (rebuild 'source #:echo "failed")))
  (def! st 'duplicate (buffer 73 'rich '(Option Some (Path new "/cwd/b.txt"))))
  (def! st 'dups (session (zipper '(a duplicate b c) 2)))
  (same-session st '(dups select-buffer-submitted "/cwd/b.txt")
    (selection 'dups (zipper '(a duplicate b c) 2) (config)))
  (same-session st '(dups find-file-submitted "b.txt")
    (selection 'dups (zipper '(a duplicate b c) 2) (config)))
  (assert-effects calls '((resolve "b.txt")))
  ;; A scan from c wraps to the earlier duplicate, keeping logical order.
  (define cviews (selected-views views 55 27 1 2))
  (def! st 'last (session (zipper '(a duplicate b c) 3) (config cviews)))
  (same-session st '(last select-buffer-submitted "/cwd/b.txt")
    (selection 'last (zipper '(a duplicate b c) 1) (config (selected-views cviews 55 73 2 3))))
  (define added (buffer 74 (fresh "added")))
  (same-session st '(dups add-buffer "added")
    (selection 'dups (zipper (list 'a 'duplicate 'b added 'c) 3)
      (config (selected-views views 55 74 0 0))))
  (check-equal? (ev st 'source) original)
  (assert-effects calls '()))

(test-case "visit/find-file, direct save, save-as and refusals have exact counted effects"
  (define-values (st calls) (state))
  (fixture! st)
  (define original (ev st 'source))
  (define reset (config (selected-views views 55 9 0 0)))
  (same-session st '(source visited "visit" (Path new "/visit"))
    (visited 'source "visit" '(Path new "/visit") reset))
  (same st '(source visit (Path new "a.txt"))
    `(Option Some ,(visited 'source "λ\r\nb\n" '(Path new "/cwd/a.txt") reset)))
  (assert-effects calls (read-calls "a.txt" "/cwd/a.txt"))
  (same st '(source visit (Path new "missing"))
    `(Option Some ,(visited 'source "" '(Path new "/cwd/missing") reset)))
  (assert-effects calls '((resolve "missing") (kind "/cwd/missing") (resolve "/cwd/missing")))
  (for ([path '("dir" "link" "other")])
    (same st `(source visit (Path new ,path)) '(if #t (Option None) (Option Some source)))
    (assert-effects calls `((resolve ,path) (kind ,(string-append "/cwd/" path))
                           (resolve ,(string-append "/cwd/" path))))
    (same-session st `(source find-file-submitted ,path) (rebuild 'source #:echo "failed"))
    (assert-effects calls `((resolve ,path) (kind ,(string-append "/cwd/" path))
                           (resolve ,(string-append "/cwd/" path)))))
  (for ([name '("a.txt" "b.txt")] [focus '(0 1)] [id '(41 9)] [row '(1 2)] [col '(1 3)])
    (same-session st `(source find-file-submitted ,name)
      (selection 'source (zipper '(a b c) focus) (config (selected-views views 55 id row col))))
    (assert-effects calls `((resolve ,name))))
  (for ([name '("new.txt" "missing")] [contents '("" "")])
    (define path (string-append "/cwd/" name))
    (define added (buffer 42 (fresh contents) `(Option Some (Path new ,path))))
    (same-session st `(source find-file-submitted ,name)
      (selection 'source (zipper (list 'a 'b added 'c) 2)
        (config (selected-views views 55 42 0 0))))
    (assert-effects calls `((resolve ,name) (kind ,path) (resolve ,path))))
  ;; Existing regular file absent from the live collection is read and inserted.
  (def! st 'unbound-a (buffer 41 '(a editor)))
  (def! st 'no-a (session (zipper '(unbound-a b c) 1)))
  (same-session st '(no-a find-file-submitted "a.txt")
    (selection 'no-a
      (zipper (list 'unbound-a 'b (buffer 42 (fresh "λ\r\nb\n") '(Option Some (Path new "/cwd/a.txt"))) 'c) 2)
      (config (selected-views views 55 42 0 0))))
  (assert-effects calls (read-calls "a.txt" "/cwd/a.txt"))
  (same-session st '(source find-file-submitted "") (rebuild 'source #:echo "failed"))
  (same-session st '(source save-as-submitted "") (rebuild 'source #:echo "failed"))
  (assert-effects calls '())
  (same st '(source save) '(Option Some source))
  (assert-effects calls (cdr (write-calls "/cwd/b.txt" "/cwd/b.txt" rich-string)))
  (same-session st '(source save-as-submitted "a.txt")
    (rebuild 'source #:buffers (replacement 'source 'rich '(Option Some (Path new "/cwd/a.txt")))
      #:echo "saved"))
  (assert-effects calls (write-calls "a.txt" "/cwd/a.txt" rich-string))
  (same-session st '(source save-as-submitted "dir") (rebuild 'source #:echo "failed"))
  (assert-effects calls '((resolve "dir") (kind "/cwd/dir") (resolve "/cwd/dir")))
  (def! st 'untitled (rebuild 'source #:buffers (replacement 'source 'rich no-path)))
  (same st '(untitled save) '(if #t (Option None) (Option Some untitled)))
  (assert-effects calls '())
  (check-equal? (ev st 'source) original)
  (define-values (failed fcalls) (state #:fail 'write))
  (fixture! failed)
  (define before (ev failed 'source))
  (check-exn exn:fail? (lambda () (ev failed '(source save-as-submitted "a.txt"))))
  (check-equal? (ev failed 'source) before)
  (assert-effects fcalls (write-calls "a.txt" "/cwd/a.txt" rich-string)))

(test-case "kill retargets every matching ID with captured successor or predecessor origin"
  (define-values (st calls) (state))
  (fixture! st)
  (define original (ev st 'source))
  (for ([vs (list views '((71 9 7 11 #t) (3 27 5 6 #f) (55 9 2 3 #t)
                        (8 41 9 13 #t) (24 9 4 8 #f)))])
    (def! st 's (session (zipper '(a b c) 1) (config vs)))
    (same-session st '(s kill-buffer)
      (selection 's (zipper '(a c) 1) (config (removed-views vs 9 27 1 2)))))
  (define last-views '((71 27 7 11 #t) (3 9 5 6 #f) (55 27 1 2 #t)
                      (8 41 9 13 #t) (24 27 4 8 #f)))
  (def! st 'last (session (zipper '(a b c) 2) (config last-views)))
  (same-session st '(last kill-buffer)
    (selection 'last (zipper '(a b) 1) (config (removed-views last-views 27 9 2 3))))
  ;; Removed maximum 42 can legally be reused. Every old view already names c.
  (define reuse-views (removed-views views 9 42 2 3))
  (def! st 'maximum (buffer 42 'rich '(b path)))
  (def! st 'reuse (session (zipper '(a maximum c) 1) (config reuse-views)))
  (define survivor-views (removed-views reuse-views 42 27 1 2))
  (def! st 'killed '(reuse kill-buffer))
  (same-session st 'killed (selection 'reuse (zipper '(a c) 1) (config survivor-views)))
  (same-session st '(killed add-buffer "new")
    (selection 'killed (zipper (list 'a 'c (buffer 42 (fresh "new"))) 2)
      (config (selected-views survivor-views 55 42 0 0))))
  (for ([id '(71 24)])
    (same st `(((actual windows) tree) find-view ,id)
      `(Option Some (AloemacsView new ,id 27 1 2 ,(if (= id 71) #t #f)))))
  (check-equal? (ev st 'source) original)
  (assert-effects calls '()))

(test-case "singleton kill resets all shared views, preserving ID, shape, locks and session fields"
  (define-values (st calls) (state))
  (fixture! st)
  (define sole '((71 9 7 11 #t) (3 9 5 6 #f) (55 9 2 3 #t)
                 (8 9 9 13 #t) (24 9 4 8 #f)))
  (for ([size '((80 24) (0 0))])
    (def! st 's (session (zipper '(b) 0) (config sole 55 (car size) (cadr size))))
    (define original (ev st 's))
    (same-session st '(s kill-buffer)
      (selection 's (zipper (list (buffer 9 (fresh ""))) 0)
        (config (removed-views sole 9 9 0 0) 55 (car size) (cadr size))))
    (check-equal? (ev st 's) original))
  (assert-effects calls '()))

(test-case "waiting prompt selection/kill/add preserves line and slot; Return targets current then"
  (define-values (st calls) (state))
  (fixture! st)
  (def! st 'waiting (rebuild 'source #:searching #f #:pending no-pending
    #:prompt '(Option Some (AloemacsPrompt new "Save as: " "a.txt" 5 "" (List empty) (List empty) 0))))
  (define added (buffer 42 (fresh "inserted")))
  (for ([send '((select-buffer-submitted "untitled") (switch-buffer) (kill-buffer)
                (add-buffer "inserted") (select-buffer-submitted "/cwd/b.txt"))]
        [buffers (list (zipper '(a b c) 2) (zipper '(a b c) 2) (zipper '(a c) 1)
                       (zipper (list 'a 'b added 'c) 2) (zipper '(a b c) 1))]
        [vs (list (selected-views views 55 27 1 2) (selected-views views 55 27 1 2)
                  (removed-views views 9 27 1 2) (selected-views views 55 42 0 0) views)]
        [ed (list '(c editor) '(c editor) '(c editor) (fresh "inserted") 'rich)]
        [contents (list "one\nthree\nlast" "one\nthree\nlast" "one\nthree\nlast" "inserted" rich-string)])
    (def! st 'changed `(waiting ,@send))
    (same-session st 'changed (selection 'waiting buffers (config vs)))
    (same-session st '(changed handle-key "return")
      (rebuild 'changed #:buffers (replacement 'changed ed '(Option Some (Path new "/cwd/a.txt")))
        #:echo "saved" #:prompt no-prompt #:submission '(Option Some "a.txt") #:waiting no-command))
    (assert-effects calls (write-calls "a.txt" "/cwd/a.txt" contents)))
  ;; Find-file completion adds relative to the new current after direct kill.
  (def! st 'finding (rebuild 'waiting
    #:prompt '(Option Some (AloemacsPrompt new "Find file: " "new.txt" 7 "" (List empty) (List empty) 0))
    #:waiting '(Option Some (AloemacsCommand FindFile))))
  (def! st 'removed '(finding kill-buffer))
  (define killed-views (removed-views views 9 27 1 2))
  (same-session st 'removed (selection 'finding (zipper '(a c) 1) (config killed-views)))
  (same-session st '(removed handle-key "return")
    (rebuild 'removed
      #:buffers (zipper (list 'a 'c (buffer 42 (fresh "") '(Option Some (Path new "/cwd/new.txt")))) 2)
      #:prompt no-prompt #:submission '(Option Some "new.txt") #:waiting no-command
      #:windows (config (selected-views killed-views 55 42 0 0))))
  (assert-effects calls '((resolve "new.txt") (kind "/cwd/new.txt") (resolve "/cwd/new.txt")))
  ;; Selection completion reuses current-name after selection changed current.
  (def! st 'selecting (rebuild 'waiting
    #:prompt '(Option Some (AloemacsPrompt new "Buffer: " "untitled" 8 "" (List empty) (List empty) 0))
    #:waiting '(Option Some (AloemacsCommand SelectBuffer))))
  (def! st 'changed '(selecting switch-buffer))
  (same-session st '(changed handle-key "return")
    (rebuild 'changed #:prompt no-prompt #:submission '(Option Some "untitled") #:waiting no-command))
  (assert-effects calls '()))

(test-case "selected-rectangle/fallback fit, resize, repeated fit, unknown sizes and frame purity"
  (define-values (st calls) (state))
  (fixture! st)
  (for ([size '((1 2) (2 1) (12 4) (80 24))]
        [row '(2 2 2 2)] [col '(4 3 3 3)] [text-rows '(1 1 2 4)])
    (define ed (editor #:row row #:left col #:rows text-rows))
    (same-session st `(source ensure-visible ,@size)
      (rebuild 'source #:buffers (replacement 'source ed)
        #:windows (config (selected-views views 55 9 row col) 55 (car size) (cadr size))))
    (def! st 'fitted `(source ensure-visible ,@size))
    (same-session st `(fitted ensure-visible ,@size) (rebuild 'fitted)))
  (def! st 'small '(source ensure-visible 1 2))
  (same-session st '(small ensure-visible 12 4)
    (rebuild 'small #:buffers (replacement 'small (editor #:left 4 #:rows 2))
      #:windows (config (selected-views views 55 9 2 4) 55 12 4)))
  (for ([size '((0 0) (1 2))])
    (def! st 's (session (zipper '(a b c) 1) (config views 55 (car size) (cadr size))))
    (for ([send '((with-echo "failed") (move-left) (switch-buffer) (kill-buffer)
                  (add-buffer "new") (visited "new" (Path new "new")))])
      (same st `(((s ,@send) windows) columns) (car size))
      (same st `(((s ,@send) windows) rows) (cadr size))))
  ;; Retain the complete one-view golden and its purity proof. Multi-view
  ;; geometry/composition is owned by windows-layout-and-rendering.rkt.
  (define single `(AloemacsWindows new ,(leaf '(55 9 2 3 #t)) 55 0 0))
  (def! st 'one (rebuild 'source #:windows single))
  (define snapshot (ev st 'one))
  (check-equal? (ev st '(one frame 8 3))
    (string-append "\e[?25l\e[2J\e[Hrd-long\e[1;2H\e[?25h"
                   "\e[?25l\e[2;1H/cwd/b.t\e[3;1Hdraft: i\e[3;8H\e[?25h"))
  (check-equal? (ev st 'one) snapshot)
  (assert-effects calls '()))

(test-case "class/field/constructor shapes, commands and maps stay exact; no window entry"
  (define source (call-with-input-file file-path (lambda (in) (port->list read in))))
  (define classes (filter (lambda (d) (eq? (car d) 'define-class)) source))
  (define (decl name) (findf (lambda (d) (equal? (cadr d) name)) classes))
  (check-equal? (take source 2) '((load "editor.aloe") (load "../../lib/fs.aloe")))
  (check-equal? (map cadr classes)
    '(AloemacsPrompt AloemacsCompletionScan AloemacsBuffer AloemacsBuffers AloemacsModeLine AloemacsView AloemacsWindowTree
      AloemacsWindowRect AloemacsWindows AloemacsCommand (AloemacsKeymap B)
      AloemacsBinding AloemacsSearchScan (AloemacsSession H)))
  (for ([entry
         '((AloemacsView (fields (id Int) (buffer-id Int) (scroll-row Int) (scroll-col Int) (locked Bool)))
           (AloemacsWindowTree (constructors (Leaf (fields (view AloemacsView)))
             (Below (fields (top AloemacsWindowTree) (bottom AloemacsWindowTree)))
             (Right (fields (left AloemacsWindowTree) (right AloemacsWindowTree)))))
           (AloemacsWindowRect (fields (x Int) (y Int) (columns Int) (rows Int)))
           (AloemacsWindows (fields (tree AloemacsWindowTree) (selected Int) (columns Int) (rows Int)))
           (AloemacsBuffer (fields (editor AloemacsEditor) (path (Option Path)) (id Int)))
           ((AloemacsSession H) (fields (buffers AloemacsBuffers) (fs (Fs H)) (echo String)
             (searching Bool) (query String) (origin Position) (wrapped Bool) (failing Bool)
             (kill-ring (List String)) (pending (Option (AloemacsKeymap AloemacsBinding)))
             (prompt (Option AloemacsPrompt)) (last-submission (Option String))
             (waiting-command (Option AloemacsCommand)) (windows AloemacsWindows))))])
    (check-equal? (caddr (decl (car entry))) (cadr entry)))
  (check-equal? (map car (cdr (caddr (decl 'AloemacsCommand))))
    '(Newline BackwardDelete MoveLeft MoveRight MoveUp MoveDown LineStart LineEnd
      PageUp PageDown BufferStart BufferEnd RequestQuit Undo SetMark Kill KillLine
      Yank Find Save SelfInsert SwitchBuffer KillBuffer FindFile SaveAs SelectBuffer
      SplitBelow SplitRight DeleteWindow OtherWindow ToggleWindowLock))
  (define-values (st calls) (state))
  (fixture! st)
  (same st '((aloemacs-ctrl-x-keymap bindings) map (fn (binding) (binding key)))
    '(List of "save" "find" "kill" "b" "2" "3" "0" "o" "l"))
  (same st '((aloemacs-global-keymap bindings) map (fn (binding) (binding key)))
    '(List of "return" "backspace" "left" "right" "up" "down" "line-start" "line-end"
       "page-up" "page-down" "buffer-start" "buffer-end" "escape" "undo" "mark" "kill"
       "kill-line" "yank" "find" "save" "ctrl-x"))
  (for ([bad '((source select-view 3) (source lock-window))])
    (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
  (assert-effects calls '()))
