#lang racket/base

(require racket/list racket/port racket/runtime-path racket/string rackunit
         "../../aloe/driver.rkt" "../../aloe/host.rkt" "../../aloe/parse.rkt"
         (only-in "../../aloe/env.rkt" env-bound?)
         (only-in "../../aloe/type.rkt" exn:fail:aloe-type? type-of type->datum)
         "../../host/racket/fs.rkt" "../../host/racket/term.rkt"
         "../../host/racket/aloemacs-run.rkt")

(define-runtime-path file-path "../../examples/aloemacs/file.aloe")
(define-runtime-path main-path "../../examples/aloemacs/main.aloe")
(define no-mark '(if #t (Option None) (Option Some (Position new 0 0))))
(define no-path '(if #t (Option None) (Option Some (Path new ""))))
(define no-pending '(if #t (Option None) (Option Some aloemacs-global-keymap)))
(define no-prompt '(if #t (Option None) (Option Some (AloemacsPrompt new "" "" 0 "" (List empty)))))
(define no-submission '(if #t (Option None) (Option Some "")))
(define no-command '(if #t (Option None) (Option Some (AloemacsCommand SaveAs))))
(define (ev st expr) (driver-eval! st expr))
(define (def! st name expr) (ev st `(define ,name ,expr)))
(define (same st actual expected)
  (check-not-exn (lambda () (ev st `(check ,actual ,expected)))
                 (format "~s equals ~s" actual expected)))
(define (dtype st expr)
  (type->datum (type-of (parse-datum expr) (driver-type-environment st))))
(define (loaded)
  (define st (make-driver))
  (ev st `(load ,(path->string file-path)))
  st)
(define (counted-fs [host-name 'FsHost] [contents "abc\ndef"])
  (define disk (make-fs-double "/cwd"
    (hash "/cwd" 'directory "/cwd/a.txt" 'file "/cwd/b.txt" 'file)
    (hash "/cwd/a.txt" contents "/cwd/b.txt" "disk b")))
  (define calls (box '()))
  (define (forward selector args)
    (set-box! calls (append (unbox calls) (list (cons selector args))))
    (host-receiver-send disk selector args))
  (define interface
    (make-host-interface host-name
      (for/list ([method (in-list (host-interface-methods fs-interface))])
        (define selector (host-method-selector method))
        (define params (host-method-parameter-types method))
        (make-host-method selector params (host-method-return-type method)
          (case (length params)
            [(0) (lambda (_) (forward selector '()))]
            [(1) (lambda (_ a) (forward selector (list a)))]
            [(2) (lambda (_ a b) (forward selector (list a b)))])))))
  (values (make-host-receiver interface #f) calls disk))
(define (state [host-name 'FsHost])
  (define st (loaded))
  (define-values (host calls disk) (counted-fs host-name))
  (driver-inject-host! st 'fs-host host)
  (values st calls))

;; Expected values use raw constructors and selectors only. In particular,
;; allocation, dispatch, split, fit and paint never build an expected value.
(define (indexed lines [focus 0])
  `(Text indexed (List of ,@(reverse (take lines focus))) ,(list-ref lines focus)
     (List of ,@(drop lines (add1 focus))) ,focus))
(define rich-history
  '(List of (UndoFrame new (Text from-string "previous") (Position new 0 2) 1 2)))
(define (editor text [line 0] [column 0] [row 0] [left 0] [rows 0]
                #:quit [quit #f] #:history [history rich-history]
                #:mark [mark '(Option Some (Position new 0 1))])
  `(AloemacsEditor new ,text (Position new ,line ,column) ,quit ,row ,left
     ,history ,mark ,rows))
(define (buffer id ed [path no-path]) `(AloemacsBuffer new ,ed ,path ,id))
(define (zipper bs [focus 0])
  `(AloemacsBuffers new (List of ,@(reverse (take bs focus))) ,(list-ref bs focus)
     (List of ,@(drop bs (add1 focus)))))
(define (leaf id [bid 41] [row 0] [col 0] [lock #f])
  `(AloemacsWindowTree Leaf (AloemacsView new ,id ,bid ,row ,col ,lock)))
(define (below a b) `(AloemacsWindowTree Below ,a ,b))
(define (right a b) `(AloemacsWindowTree Right ,a ,b))
(define (config tree selected [columns 9] [rows 6])
  `(AloemacsWindows new ,tree ,selected ,columns ,rows))
(define (rect x y columns rows) `(AloemacsWindowRect new ,x ,y ,columns ,rows))
(define active-prompt '(Option Some (AloemacsPrompt new "P\t" "x\ry" 2 "" (List empty))))
(define waiting '(Option Some (AloemacsCommand SaveAs)))
(define pending '(Option Some aloemacs-ctrl-x-keymap))
(define (session bs tree [selected 7] #:columns [columns 9] #:rows [rows 6]
                 #:echo [echo "saved"] #:searching [searching #f]
                 #:prompt [prompt no-prompt] #:pending [prefix no-pending]
                 #:waiting [slot waiting])
  `(AloemacsSession new ,bs (Fs new fs-host) ,echo ,searching "q\tlong"
     (Position new 4 2) #t #t (List of "newest" "older") ,prefix ,prompt
     (Option Some "/must-not-write") ,slot ,(config tree selected columns rows)))
(define (rebuild s #:buffers [bs `(,s buffers)] #:windows [w `(,s windows)]
                 #:echo [echo `(,s echo)] #:searching [searching `(,s searching)]
                 #:query [query `(,s query)] #:origin [origin `(,s origin)]
                 #:wrapped [wrapped `(,s wrapped)] #:failing [failing `(,s failing)]
                 #:ring [ring `(,s kill-ring)] #:pending [prefix `(,s pending)]
                 #:prompt [prompt `(,s prompt)] #:submission [sub `(,s last-submission)]
                 #:waiting [slot `(,s waiting-command)])
  `(AloemacsSession new ,bs (,s fs) ,echo ,searching ,query ,origin ,wrapped ,failing
     ,ring ,prefix ,prompt ,sub ,slot ,w))
(define fields '(buffers fs echo searching query origin wrapped failing kill-ring
                         pending prompt last-submission waiting-command windows))
(define (same-session st actual expected)
  (def! st 'actual actual)
  (def! st 'expected expected)
  (same st 'actual 'expected)
  (for ([field fields]) (same st `(actual ,field) `(expected ,field))))
(define (cursor row col) (format "\e[~a;~aH" row col))
(define (multi lines row col [echo-row 6] [echo ""])
  (string-append "\e[?25l\e[2J\e[H" (string-join lines "\r\n")
                 (if echo-row (string-append (cursor echo-row 1) echo) "")
                 (cursor row col) "\e[?25h"))
;; Independent name and text allocation from the supplied fixture and size.
(define (mode-row name width)
  (define label (substring (string-append name " ") 0
                          (min width (add1 (string-length name)))))
  (list->string
    (for/list ([c (in-string (string-append label
                              (make-string (- width (string-length label)) #\-)))])
      (if (or (< (char->integer c) 32) (= (char->integer c) 127)) #\space c))))
(define (text-body body rows)
  (define lines (string-split body "\r\n" #:trim? #f))
  (string-join (take lines (min (length lines) (if (>= rows 3) (- rows 2) 1))) "\r\n"))
(define (single lines row col [echo-row #f] [echo ""] [final-row row] [final-col col]
                #:name [name "untitled"] #:width [width 0])
  (string-append "\e[?25l\e[2J\e[H"
    (if echo-row (text-body (string-join lines "\r\n") echo-row) (string-join lines "\r\n"))
    (format "\e[~a;~aH\e[?25h" row col)
    (if echo-row
        (string-append "\e[?25l"
          (if (>= echo-row 3) (format "\e[~a;1H~a" (sub1 echo-row) (mode-row name width)) "")
          (format "\e[~a;1H~a\e[~a;~aH\e[?25h" echo-row echo final-row final-col)) "")))
(define (paint st s columns rows expected)
  (define before (for/list ([expr (list s `(,s buffers) `(,s windows) `((,s editor) text))])
                   (ev st expr)))
  (check-equal? (ev st `(,s frame ,columns ,rows)) expected)
  (check-equal? (for/list ([expr (list s `(,s buffers) `(,s windows) `((,s editor) text))])
                  (ev st expr)) before))
(define ab-text (indexed '("abc" "def")))
(define (simple! st)
  (def! st 'a (buffer 41 (editor ab-text)))
  (def! st 's (session (zipper '(a)) (leaf 7))))

(define commands
  '(Newline BackwardDelete MoveLeft MoveRight MoveUp MoveDown LineStart LineEnd
    PageUp PageDown BufferStart BufferEnd RequestQuit Undo SetMark Kill KillLine
    Yank Find Save SelfInsert SwitchBuffer KillBuffer FindFile SaveAs SelectBuffer
    SplitBelow SplitRight DeleteWindow OtherWindow ToggleWindowLock))
(define (datums path) (call-with-input-file path (lambda (in) (port->list read in))))
(define (selection s bs tree [id 7] [columns 9] [rows 6])
  (rebuild s #:buffers bs #:windows (config tree id columns rows)
    #:echo "" #:searching #f #:query "" #:origin '(Position new 0 0)
    #:wrapped #f #:failing #f #:pending no-pending))
(define (fresh contents)
  (editor (indexed (if (equal? contents "") '("")
                      (string-split contents "\n" #:trim? #f)))
          #:history '(List empty) #:mark no-mark))
(define (effects calls expected)
  (check-equal? (unbox calls) expected)
  (set-box! calls '()))

(test-case "exact zero-payload command, concrete typed sends, ordered maps and cold startup"
  (define st0 (loaded))
  (for ([name '(fs-host term aloemacs-editor)])
    (check-false (env-bound? (driver-runtime-environment st0) name)))
  (define source (datums file-path))
  (define classes (filter (lambda (d) (eq? (car d) 'define-class)) source))
  (define (decl name) (findf (lambda (d) (equal? (cadr d) name)) classes))
  (check-equal? (take source 2) '((load "editor.aloe") (load "../../lib/fs.aloe")))
  (check-equal? (map cadr classes)
    '(AloemacsPrompt AloemacsCompletionScan AloemacsBuffer AloemacsBuffers AloemacsModeLine AloemacsView AloemacsWindowTree
      AloemacsWindowRect AloemacsWindows AloemacsCommand (AloemacsKeymap B)
      AloemacsBinding AloemacsSearchScan (AloemacsSession H)))
  (check-equal? (caddr (decl 'AloemacsCommand))
    `(constructors ,@(map (lambda (c) `(,c (fields))) commands)))
  (define methods (cdr (cadddr (decl '(AloemacsSession H)))))
  (define executions (cddr (last (assoc 'execute-command methods))))
  (define names (cddr (last (cadr (cadddr (decl 'AloemacsCommand))))))
  (check-equal? (assoc 'ToggleWindowLock executions)
                '(ToggleWindowLock () (self toggle-window-lock)))
  (check-equal? (assoc 'ToggleWindowLock names)
                '(ToggleWindowLock () "toggle-window-lock"))
  (check-equal? (and (assoc 'toggle-window-lock methods)
                     (drop-right (assoc 'toggle-window-lock methods) 1))
                '(toggle-window-lock () (AloemacsSession H)))
  (for ([host-name '(FsHost WindowDisk)])
    (define-values (st calls) (state host-name))
    (simple! st)
    (check-equal? (ev st '((AloemacsCommand ToggleWindowLock) name)) "toggle-window-lock")
    (for ([expr '((s toggle-window-lock)
                  (s execute-command (AloemacsCommand ToggleWindowLock) "ignored"))])
      (check-equal? (dtype st expr) `(AloemacsSession ,host-name)))
    (for ([bad '((s toggle-window-lock 0) (s toggle-window-lock "x")
                 (s toggle-window-lock #f) (s toggle-window-lock 0 1)
                 (AloemacsSession toggle-window-lock) (AloemacsCommand ToggleWindowLock 0)
                 (AloemacsCommand ToggleWindowLock "x")
                 ((AloemacsCommand ToggleWindowLock) run s)
                 ((AloemacsCommand ToggleWindowLock) name 0)
                 (s execute-command (AloemacsCommand ToggleWindowLock))
                 (s execute-command (AloemacsCommand ToggleWindowLock) 0)
                 (s execute-command (AloemacsCommand ToggleWindowLock) "x" "y"))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
    (for ([receiver '(a (s editor) (s windows) (s buffers) 0 "x")])
      (check-exn exn:fail:aloe-type? (lambda () (ev st `(,receiver toggle-window-lock)))))
    (same st '(aloemacs-ctrl-x-keymap bindings)
      '(List of (AloemacsBinding Command "save" aloemacs-save-command)
                (AloemacsBinding Command "find" (AloemacsCommand FindFile))
                (AloemacsBinding Command "kill" (AloemacsCommand SaveAs))
                (AloemacsBinding Command "b" (AloemacsCommand SelectBuffer))
                (AloemacsBinding Command "2" (AloemacsCommand SplitBelow))
                (AloemacsBinding Command "3" (AloemacsCommand SplitRight))
                (AloemacsBinding Command "0" (AloemacsCommand DeleteWindow))
                (AloemacsBinding Command "o" (AloemacsCommand OtherWindow))
                (AloemacsBinding Command "l" (AloemacsCommand ToggleWindowLock))))
    (same st '(aloemacs-ctrl-x-keymap default) no-command)
    (same st '((aloemacs-global-keymap bindings) map (fn (b) (b key)))
      '(List of "return" "backspace" "left" "right" "up" "down" "line-start" "line-end"
         "page-up" "page-down" "buffer-start" "buffer-end" "escape" "undo" "mark" "kill"
         "kill-line" "yank" "find" "save" "ctrl-x"))
    (same st '(aloemacs-global-keymap default) '(Option Some (AloemacsCommand SelfInsert)))
    (same st '(aloemacs-ctrl-x-keymap lookup "save") '(aloemacs-global-keymap lookup "save"))
    (for ([bad '((s lock-window) (s select-view 0) (AloemacsCommand LockWindow))])
      (check-exn exn:fail:aloe-type? (lambda () (ev st bad))))
    (ev st `(load ,(path->string main-path)))
    (same-session st 'aloemacs-editor
      `(AloemacsSession new
         ,(zipper (list (buffer 0 (editor '(Text from-string "")
           #:history '(List empty) #:mark no-mark))))
         (Fs new fs-host) "" #f "" (Position new 0 0) #f #f (List empty)
         ,no-pending ,no-prompt ,no-submission ,no-command ,(config (leaf 0 0) 0 0 0)))
    (effects calls '())))

(test-case "bit-only toggle and involution preserve rich raw state, mixed trees and beyond-EOF origins"
  (define-values (st calls) (state))
  (define text (indexed '("first" "second" "third" "last") 2))
  (define a (buffer 41 (editor text 1 3 6 8 17 #:quit #t) '(Option Some (Path new "/a"))))
  (define b (buffer 12 (editor text 3 2 5 9 22) '(Option Some (Path new "/b"))))
  (define bs (zipper (list b a) 1))
  (for* ([locked? '(#f #t)] [size '((0 0) (19 12))] [mixed? '(#f #t)])
    (define (tree bit)
      (if mixed?
          (right (below (leaf 70 12 40 50 #t) (leaf 2 41 99 101))
                 (below (leaf 40 41 1 2 bit) (leaf 1 12 30 40 #t)))
          (leaf 40 41 1 2 bit)))
    (def! st 'raw (session bs (tree locked?) 40 #:columns (car size) #:rows (cadr size)
                          #:searching #t #:prompt active-prompt #:pending pending))
    (same-session st '(raw toggle-window-lock)
      (rebuild 'raw #:windows (config (tree (not locked?)) 40 (car size) (cadr size))))
    (same-session st '((raw toggle-window-lock) toggle-window-lock) 'raw)
    (same-session st '(raw execute-command (AloemacsCommand ToggleWindowLock) "unused")
      (rebuild 'raw #:windows (config (tree (not locked?)) 40 (car size) (cadr size))))
    (check-equal? (ev st '(raw frame 19 12))
                  (ev st '((raw toggle-window-lock) frame 19 12))))
  (effects calls '()))

(test-case "locked edits, undo, scrolling, fit and resize preserve shared ownership and inactive origins"
  (define-values (st calls) (state))
  (define text (indexed '("abcdef" "ghijkl" "mnopqr" "stuvwx") 2))
  (define a (buffer 41 (editor text 2 5 2 3 2)))
  (define b (buffer 12 (editor (indexed '("Z")))))
  (define (t row col [bit #t])
    (right (below (leaf 7 41 row col bit) (leaf 2 41 40 50)) (leaf 40 12)))
  (def! st 'raw (session (zipper (list a b)) (t 2 3 #f) 7 #:echo ""))
  (def! st 's '(raw toggle-window-lock))
  (same-session st 's (rebuild 'raw #:windows (config (t 2 3) 7)))
  (define pushed `(List of (UndoFrame new ,text (Position new 2 5) 2 3)
    (UndoFrame new (Text from-string "previous") (Position new 0 2) 1 2)))
  (same-session st '(s insert "λ") (rebuild 's #:buffers (zipper (list
    (buffer 41 (editor (indexed '("abcdef" "ghijkl" "mnopqλr" "stuvwx") 2)
      2 6 2 3 2 #:history pushed)) b))))
  (def! st 'edited '(s insert "λ"))
  (same-session st '(edited undo) 's)
  (same-session st '(s page-up) (rebuild 's #:buffers (zipper (list
    (buffer 41 (editor (indexed '("abcdef" "ghijkl" "mnopqr" "stuvwx") 1) 1 5 2 3 2)) b))))
  (same-session st '(s page-down) (rebuild 's #:buffers (zipper (list
    (buffer 41 (editor (indexed '("abcdef" "ghijkl" "mnopqr" "stuvwx") 3) 3 5 2 3 2)) b))))
  ;; Start fitted. Shrink forces selected-only fallback and changes nominal geometry
  ;; despite the lock; growth restores composition, keeping inactive EOF origins.
  (paint st 's 9 6 (multi '("pqr |Z   " "unti|    " "----+    " "    |    " "unti|unti")
                         1 3 6 ""))
  (def! st 'small '(s ensure-visible 2 3))
  (same-session st 'small (rebuild 's #:buffers (zipper (list
    (buffer 41 (editor text 2 5 2 4 1)) b)) #:windows (config (t 2 4) 7 2 3)))
  (paint st 'small 2 3 (single '("qr" "wx") 1 2 3 "" #:name "untitled" #:width 2))
  (same st `(((s windows) tree) rect-for 7 ,(rect 0 0 9 5))
    `(Option Some ,(rect 0 0 4 2)))
  (same st `(((small windows) tree) rect-for 7 ,(rect 0 0 2 2))
    `(Option Some ,(rect 0 0 1 1)))
  ;; A nominal split is still refused even though fallback occupies the whole screen.
  (same-session st '(small split-below) (rebuild 'small #:echo "failed"))
  (def! st 'tiny '(small ensure-visible 1 1))
  (same-session st 'tiny (rebuild 'small #:buffers (zipper (list
    (buffer 41 (editor text 2 5 2 5 1)) b)) #:windows (config (t 2 5) 7 1 1)))
  (paint st 'tiny 1 1 (single '("r") 1 1 #f #:name "untitled" #:width 1))
  (def! st 'grown '(tiny ensure-visible 13 8))
  (same-session st 'grown (rebuild 'tiny #:buffers (zipper (list
    (buffer 41 (editor text 2 5 2 5 2)) b)) #:windows (config (t 2 5) 7 13 8)))
  (paint st 'grown 13 8 (multi '("r     |Z     " "x     |      " "untitl|      "
                               "------+      " "      |      " "      |      " "untitl|untitl")
                             1 1 8 ""))
  (same-session st '(grown ensure-visible 13 8) 'grown)
  (effects calls '()))

(test-case "waiting prompts retain lock and slot; Return acts on the directly selected current buffer"
  (define-values (st calls) (state))
  (define a (buffer 41 (editor ab-text) '(Option Some (Path new "/a"))))
  (define bt (indexed '("B")))
  (define b (buffer 12 (editor bt) '(Option Some (Path new "/b"))))
  (define (t [bid 41] [bit #t]) (right (leaf 7 bid 0 0 bit) (leaf 2 41 20 30)))
  (def! st 'raw (session (zipper (list a b)) (t 41 #f) 7 #:pending pending
    #:prompt '(Option Some (AloemacsPrompt new "Save as: " "/cwd/a.txt" 10 "" (List empty)))))
  (def! st 'locked '(raw toggle-window-lock))
  (def! st 'selected `(locked selected-buffers ,(zipper (list a b) 1)))
  (same-session st 'selected (selection 'locked (zipper (list a b) 1) (t 12)))
  (same-session st '(selected handle-key "return") (rebuild 'selected
    #:buffers (zipper (list a (buffer 12 (editor bt) '(Option Some (Path new "/cwd/a.txt")))) 1)
    #:echo "saved" #:prompt no-prompt #:submission '(Option Some "/cwd/a.txt") #:waiting no-command))
  (effects calls '((resolve "/cwd/a.txt") (kind "/cwd/a.txt") (resolve "/cwd/a.txt")
                  (write "/cwd/a.txt" "B")))
  (same-session st '(selected handle-key "escape")
    (rebuild 'selected #:prompt no-prompt #:waiting no-command))
  (same-session st '(locked handle-key "ctrl-x") 'locked)
  (effects calls '())
  ;; Full prompt lifecycle under a public lock, with no old-buffer target stored.
  (def! st 'idle (rebuild 'locked #:prompt no-prompt #:waiting no-command #:pending no-pending))
  (for ([command '(FindFile SaveAs SelectBuffer)] [label '("Find file: " "Save as: " "Buffer: ")]
        [text '("/" "/a" "")])
    (same-session st `(idle execute-command (AloemacsCommand ,command) "ignored")
      (rebuild 'idle #:prompt `(Option Some (AloemacsPrompt new ,label ,text ,(string-length text) "" (List empty)))
        #:waiting `(Option Some (AloemacsCommand ,command)))))
  (effects calls '((root? "/a") (parent "/a")))
  (def! st 'find-p (rebuild 'idle #:prompt
    '(Option Some (AloemacsPrompt new "Find file: " "b.txt" 5 "" (List empty)))
    #:waiting '(Option Some (AloemacsCommand FindFile))))
  (define found (buffer 42 (fresh "disk b") '(Option Some (Path new "/cwd/b.txt"))))
  (same-session st '(find-p handle-key "return")
    (rebuild (selection 'find-p (zipper (list a found b) 1) (t 42))
      #:prompt no-prompt #:submission '(Option Some "b.txt") #:waiting no-command))
  (effects calls '((resolve "b.txt") (kind "/cwd/b.txt") (resolve "/cwd/b.txt")
                  (kind "/cwd/b.txt") (resolve "/cwd/b.txt") (read "/cwd/b.txt")))
  (def! st 'select-p (rebuild 'idle #:prompt
    '(Option Some (AloemacsPrompt new "Buffer: " "/b" 2 "" (List empty)))
    #:waiting '(Option Some (AloemacsCommand SelectBuffer))))
  (same-session st '(select-p handle-key "return")
    (rebuild (selection 'select-p (zipper (list a b) 1) (t 12))
      #:prompt no-prompt #:submission '(Option Some "/b") #:waiting no-command))
  (effects calls '()))

(test-case "production runner: lock, both refused splits, refused delete, unlock, split/delete and quit"
  (for ([split-key '("2" "3")])
    (define below? (equal? split-key "2"))
    (define keys '("ctrl-x" "l" "ctrl-x" "2" "ctrl-x" "3" "ctrl-x" "0"
                  "ctrl-x" "l" "ctrl-x" "SPLIT" "ctrl-x" "0" "escape"))
    (define actual-keys (map (lambda (key) (if (equal? key "SPLIT") split-key key)) keys))
    (define start (single '("abc" "def" "" "" "") 1 1 6 "" #:name "/cwd/a.txt" #:width 9))
    (define failed (single '("abc" "def" "" "" "") 1 1 6 "failed: /" #:name "/cwd/a.txt" #:width 9))
    (define split-frame (multi (if below?
      '("abc      " "/cwd/a.tx" "---------" "abc      " "/cwd/a.tx")
      '("abc |abc " "def |def " "    |    " "    |    " "/cwd|/cwd")) 1 1 6 ""))
    ;; Frames precede the corresponding key, so each refusal is visible next turn.
    (define frames (list start start start start failed start failed start failed start
                         start start split-frame split-frame start))
    (define-values (host calls disk) (counted-fs))
    (define iteration 0)
    (define events (box '()))
    (define (record event) (set-box! events (append (unbox events) (list event))))
    (define output (make-output-port 'lock-runner always-evt
      (lambda (bytes start end _non-block? _breakable?)
        (unless (= start end) (record (list 'write (bytes->string/utf-8 (subbytes bytes start end)))))
        (- end start)) void))
    (define term (make-term-receiver output
      (lambda () (record 'read)
        (when (>= iteration (length actual-keys)) (error 'lock-runner "read after quit"))
        (begin0 (list-ref actual-keys iteration) (set! iteration (add1 iteration))))
      (lambda () (record 'size)
        (when (>= iteration (length actual-keys)) (error 'lock-runner "size after quit"))
        (values 9 6))))
    (run-aloemacs-with-hosts term host "/cwd/a.txt")
    (check-equal? iteration (length actual-keys))
    (check-equal? (unbox events)
      (append-map (lambda (frame) (list 'size 'size (list 'write frame) 'read)) frames))
    (effects calls '((resolve "/cwd/a.txt") (resolve "/cwd/a.txt") (kind "/cwd/a.txt")
                     (resolve "/cwd/a.txt") (kind "/cwd/a.txt") (resolve "/cwd/a.txt") (read "/cwd/a.txt")))
    (check-equal? (host-receiver-send disk 'read '("/cwd/a.txt")) "abc\ndef")
    ;; Complement the opaque runner with exact independent states at every key.
    (define st (make-driver))
    (define-values (direct-host direct-calls _) (counted-fs))
    (driver-inject-host! st 'fs-host direct-host)
    (ev st `(load ,(path->string main-path)))
    (def! st 's '(aloemacs-editor visited "abc\ndef" (Path new "/cwd/a.txt")))
    (for ([key actual-keys] [frame frames] [i (in-naturals)])
      (def! st 's '(s ensure-visible 9 6))
      (define split? (and (>= i 12) (< i 14)))
      (define locked? (and (>= i 2) (< i 10)))
      (define expected-tree (if split?
        ((if below? below right) (leaf 0 0) (leaf 1 0))
        (leaf (if (= i 14) 1 0) 0 0 0 locked?)))
      (same st '(s windows) (config expected-tree (if (= i 14) 1 0)))
      (same st '(s echo) (if (memq i '(4 6 8)) "failed" ""))
      (same st '(s point) '(Position new 0 0))
      (paint st 's 9 6 frame)
      (def! st 's `(s handle-key ,key)))
    (same st '(s quit) #t)
    (same st '(s windows) (config (leaf 1 0) 1))
    (same st '(s text) (indexed '("abc" "def")))
    (effects direct-calls '())))

;; Visit order is supplied by each fixture, independently of tree traversal.
;; Return to the original selection so a surviving descendant is unselected.
(define (lock-through-cycle! st source order target)
  (define start (index-of order 7))
  (define steps (modulo (- (index-of order target) start) (length order)))
  (def! st 'locked source)
  (for ([_ (in-range steps)]) (def! st 'locked '(locked other-window)))
  (def! st 'locked '(locked toggle-window-lock))
  (for ([_ (in-range (modulo (- (length order) steps) (length order)))])
    (def! st 'locked '(locked other-window))))

(test-case "public descendant locks guard all nominal coordinates and permit exact zero-extent promotion"
  (define-values (st calls) (state))
  (simple! st)
  ;; make-tree/make-candidate are independent literal constructor fixtures.
  ;; Each row records old/new x,y,width,height, including position-only changes.
  (define cases
    (list
      (list (lambda (bit) (right (leaf 7) (below (leaf 2 41 0 0 bit) (leaf 3))))
            (lambda (bit) (below (leaf 2 41 0 0 bit) (leaf 3))) '(7 2 3) 9 6
            (rect 5 0 4 2) (rect 0 0 9 2) #f 2)
      (list (lambda (bit) (below (right (leaf 3) (leaf 2 41 0 0 bit)) (leaf 7)))
            (lambda (bit) (right (leaf 3) (leaf 2 41 0 0 bit))) '(3 2 7) 9 6
            (rect 5 0 4 2) (rect 5 0 4 5) #f 3)
      (list (lambda (bit) (right (leaf 7) (right (leaf 2 41 0 0 bit) (leaf 3))))
            (lambda (bit) (right (leaf 2 41 0 0 bit) (leaf 3))) '(7 2 3) 1 2
            (rect 1 0 0 1) (rect 0 0 0 1) #f 2)
      (list (lambda (bit) (below (leaf 7) (below (leaf 2 41 0 0 bit) (leaf 3))))
            (lambda (bit) (below (leaf 2 41 0 0 bit) (leaf 3))) '(7 2 3) 9 2
            (rect 0 1 9 0) (rect 0 0 9 0) #f 2)
      (list (lambda (bit) (right (right (right (leaf 2 41 0 0 bit) (leaf 3)) (leaf 4)) (leaf 7)))
            (lambda (bit) (right (right (leaf 2 41 0 0 bit) (leaf 3)) (leaf 4)))
            '(2 3 4 7) 7 6 (rect 0 0 0 5) (rect 0 0 1 5) #f 2)
      (list (lambda (bit)
              (right (right (right (right (right (leaf 2 41 0 0 bit) (leaf 3))
                                   (leaf 4)) (leaf 5)) (leaf 6)) (leaf 7)))
            (lambda (bit)
              (right (right (right (right (leaf 2 41 0 0 bit) (leaf 3)) (leaf 4))
                            (leaf 5)) (leaf 6)))
            '(2 3 4 5 6 7) 9 6 (rect 0 0 0 5) (rect 0 0 0 5) #t 2)
      (list (lambda (bit) (right (below (leaf 7) (leaf 3)) (leaf 2 41 0 0 bit)))
            (lambda (bit) (right (leaf 3) (leaf 2 41 0 0 bit))) '(7 3 2) 9 6
            (rect 5 0 4 5) (rect 5 0 4 5) #t 3)))
  (for ([c cases])
    (define make-tree (list-ref c 0)) (define make-candidate (list-ref c 1))
    (define columns (list-ref c 3)) (define rows (list-ref c 4))
    (define root (rect 0 0 columns (sub1 rows)))
    (def! st 'raw (session (zipper '(a)) (make-tree #f) 7 #:columns columns #:rows rows
      #:pending pending))
    (lock-through-cycle! st 'raw (list-ref c 2) 2)
    (same-session st 'locked (rebuild 'raw #:windows (config (make-tree #t) 7 columns rows)))
    (same st `(((locked windows) tree) rect-for 2 ,root) `(Option Some ,(list-ref c 5)))
    (same st `(,(make-candidate #t) rect-for 2 ,root) `(Option Some ,(list-ref c 6)))
    (same-session st '(locked delete-window)
      (if (list-ref c 7)
          (rebuild 'locked #:windows (config (make-candidate #t) (list-ref c 8) columns rows))
          (rebuild 'locked #:echo "failed")))
    ;; The locked leaf can be entered again, with no buffer pin or selection ban.
    (define steps (modulo (- (index-of (list-ref c 2) 2) (index-of (list-ref c 2) 7))
                          (length (list-ref c 2))))
    (def! st 'entered 'locked)
    (for ([_ (in-range steps)]) (def! st 'entered '(entered other-window)))
    (same-session st 'entered (rebuild 'locked #:windows (config (make-tree #t) 2 columns rows))))
  ;; A public lock outside the local split's parent cannot prevent either split.
  (define (t bit) (right (below (leaf 7) (leaf 3)) (leaf 2 41 0 0 bit)))
  (def! st 'raw (session (zipper '(a)) (t #f) 7 #:rows 10 #:echo ""))
  (lock-through-cycle! st 'raw '(7 3 2) 2)
  (for ([op '(split-below split-right)] [height '(1 3)])
    (define expected-tree (right (below ((if (eq? op 'split-below) below right)
                                        (leaf 7) (leaf 8)) (leaf 3)) (leaf 2 41 0 0 #t)))
    (same-session st `(locked ,op) (rebuild 'locked
      #:buffers (zipper (list (buffer 41 (editor ab-text 0 0 0 0 height))))
      #:windows (config expected-tree 7 9 10)))
    (same st `(,expected-tree rect-for 2 ,(rect 0 0 9 9)) `(Option Some ,(rect 5 0 4 9))))
  ;; Unknown-size fixtures keep the conservative sibling-only guard.
  (for ([size '((0 0) (0 6) (9 0))])
    (define (t bit) (right (leaf 7) (below (leaf 3) (leaf 2 41 0 0 bit))))
    (def! st 'raw (session (zipper '(a)) (t #f) 7 #:columns (car size) #:rows (cadr size)))
    (lock-through-cycle! st 'raw '(7 3 2) 2)
    (same-session st 'locked (rebuild 'raw #:windows (config (t #t) 7 (car size) (cadr size))))
    (same-session st '(locked delete-window) (rebuild 'locked #:echo "failed"))
    (def! st 'p (rebuild 'locked #:prompt active-prompt))
    (same-session st '(p delete-window) 'p))
  (for ([size '((0 0) (0 6) (9 0))])
    (define (t bit) (right (below (leaf 7) (leaf 3)) (leaf 2 41 0 0 bit)))
    (def! st 'raw (session (zipper '(a)) (t #f) 7 #:columns (car size) #:rows (cadr size)))
    (lock-through-cycle! st 'raw '(7 3 2) 2)
    (same-session st '(locked delete-window) (rebuild 'locked #:windows
      (config (right (leaf 3) (leaf 2 41 0 0 #t)) 3 (car size) (cadr size)))))
  (effects calls '()))

(test-case "public locks survive selected-only retargeting, exact file effects and all-view buffer kills"
  (define-values (st calls) (state))
  (define a (buffer 41 (editor ab-text) '(Option Some (Path new "/cwd/a.txt"))))
  (define b (buffer 12 (editor ab-text 1 1 1 1 17) '(Option Some (Path new "/b"))))
  (def! st 'a a)
  (def! st 'b b)
  (define (t [id 41] [row 0] [col 0] [bits #t])
    (right (below (leaf 7 id row col bits) (leaf 2 41 20 30 bits)) (leaf 40 12 1 1 bits)))
  (def! st 'raw (session (zipper (list a b)) (t 41 0 0 #f) 7 #:pending pending
    #:prompt active-prompt #:searching #t))
  (def! st 'first '(raw toggle-window-lock))
  (lock-through-cycle! st 'first '(7 2 40) 2)
  (lock-through-cycle! st 'locked '(7 2 40) 40)
  ;; Cross-buffer entry clears search/pending, but preserves prompt and echo.
  (def! st 's 'locked)
  (same-session st 's (rebuild 'raw #:windows (config (t) 7) #:searching #f #:query ""
    #:origin '(Position new 0 0) #:wrapped #f #:failing #f #:pending no-pending))
  (define bs (zipper (list a b)))
  (for ([path (list #f '(Path new "/added"))])
    (define added (buffer 42 (fresh "added") (if path `(Option Some ,path) no-path)))
    (same-session st `(s add-buffer "added" ,@(if path (list path) '()))
      (selection 's (zipper (list a added b) 1) (t 42))))
  (same-session st '(s switch-buffer) (selection 's (zipper (list a b) 1) (t 12 1 1)))
  (same-session st '(s selected-buffers (s buffers)) (selection 's bs (t)))
  (same-session st '(s selected-buffers (AloemacsBuffers new (List of a) b (List empty)))
    (selection 's (zipper (list a b) 1) (t 12 1 1)))
  (for ([name '("/cwd/a.txt" "/b")] [focus '(0 1)] [id '(41 12)] [origin '(0 1)])
    (same-session st `(s select-buffer-submitted ,name)
      (selection 's (zipper (list a b) focus) (t id origin origin))))
  (effects calls '())
  (same-session st '(s find-file-submitted "a.txt") (selection 's bs (t)))
  (effects calls '((resolve "a.txt")))
  (define found (buffer 42 (fresh "disk b") '(Option Some (Path new "/cwd/b.txt"))))
  (same-session st '(s find-file-submitted "b.txt")
    (selection 's (zipper (list a found b) 1) (t 42)))
  (effects calls '((resolve "b.txt") (kind "/cwd/b.txt") (resolve "/cwd/b.txt")
                  (kind "/cwd/b.txt") (resolve "/cwd/b.txt") (read "/cwd/b.txt")))
  (same-session st '(s find-file-submitted "new.txt")
    (selection 's (zipper (list a (buffer 42 (fresh "")
      '(Option Some (Path new "/cwd/new.txt"))) b) 1) (t 42)))
  (effects calls '((resolve "new.txt") (kind "/cwd/new.txt") (resolve "/cwd/new.txt")))
  (same-session st '(s with-current-path (Path new "/renamed"))
    (rebuild 's #:buffers (zipper (list (buffer 41 (editor ab-text)
      '(Option Some (Path new "/renamed"))) b))))
  (same st '(s save) '(Option Some s))
  (effects calls '((kind "/cwd/a.txt") (resolve "/cwd/a.txt") (write "/cwd/a.txt" "abc\ndef")))
  (same-session st '(s save-as-submitted "a.txt") (rebuild 's #:echo "saved"))
  (effects calls '((resolve "a.txt") (kind "/cwd/a.txt") (resolve "/cwd/a.txt")
                  (write "/cwd/a.txt" "abc\ndef")))
  (same-session st '(s save-as-submitted "b.txt") (rebuild 's #:buffers
    (zipper (list (buffer 41 (editor ab-text) '(Option Some (Path new "/cwd/b.txt"))) b))
    #:echo "saved"))
  (effects calls '((resolve "b.txt") (kind "/cwd/b.txt") (resolve "/cwd/b.txt")
                  (write "/cwd/b.txt" "abc\ndef")))
  (for ([send '((save-as-submitted "") (save-as-submitted "/cwd")
                (find-file-submitted "") (find-file-submitted "/cwd")
                (select-buffer-submitted "missing"))])
    (same-session st `(s ,@send) (rebuild 's #:echo "failed"))
    (effects calls (if (equal? (cadr send) "/cwd")
                      '((resolve "/cwd") (kind "/cwd") (resolve "/cwd")) '())))
  (same st '(s visit (Path new "/cwd")) '(if #t (Option None) (Option Some s)))
  (effects calls '((resolve "/cwd") (kind "/cwd") (resolve "/cwd")))
  (define (visited contents path)
    (rebuild 's #:buffers (zipper (list (buffer 41 (fresh contents) `(Option Some ,path)) b))
      #:windows (config (t) 7) #:echo "" #:searching #f #:query ""
      #:origin '(Position new 0 0) #:wrapped #f #:failing #f #:ring '(List empty)
      #:pending no-pending #:prompt no-prompt #:waiting no-command))
  (same-session st '(s visited "visit" (Path new "/visit")) (visited "visit" '(Path new "/visit")))
  (same st '(s visit (Path new "b.txt")) `(Option Some ,(visited "abc\ndef" '(Path new "/cwd/b.txt"))))
  (effects calls '((resolve "b.txt") (kind "/cwd/b.txt") (resolve "/cwd/b.txt")
                  (kind "/cwd/b.txt") (resolve "/cwd/b.txt") (read "/cwd/b.txt")))
  ;; Both locked views of killed ID 41 retarget; the pre-existing view of 12 stays exact.
  (define killed-tree (right (below (leaf 7 12 1 1 #t) (leaf 2 12 1 1 #t))
                            (leaf 40 12 1 1 #t)))
  (same-session st '(s kill-buffer) (selection 's (zipper (list b)) killed-tree))
  ;; A surviving replacement view's own origin must not be overwritten by the
  ;; captured replacement editor origin, even when both are publicly locked.
  (def! st 'kill-s (rebuild 's #:windows
    (config (right (below (leaf 7 41 0 0 #t) (leaf 2 41 20 30 #t))
                   (leaf 40 12 77 88 #t)) 7)))
  (same-session st '(kill-s kill-buffer) (selection 'kill-s (zipper (list b))
    (right (below (leaf 7 12 1 1 #t) (leaf 2 12 1 1 #t)) (leaf 40 12 77 88 #t))))
  (def! st 'one (rebuild 's #:buffers (zipper (list a)) #:windows
    (config (right (leaf 7 41 0 0 #t) (leaf 2 41 20 30 #t)) 7)))
  (same-session st '(one kill-buffer) (selection 'one (zipper (list (buffer 41 (fresh ""))))
    (right (leaf 7 41 0 0 #t) (leaf 2 41 0 0 #t))))
  (effects calls '()))

(test-case "all stored tokens and active rows: toggle only, public refusals and unlock successes"
  (define-values (st calls) (state))
  (simple! st)
  (define t (right (leaf 7) (leaf 2)))
  (define locked-t (right (leaf 7 41 0 0 #t) (leaf 2)))
  (define rows '("abc |abc " "def |def " "    |    " "    |    " "unti|unti"))
  (for* ([token '("" "saved" "failed")] [mode '(idle prompt search both)])
    (define prompt? (and (memq mode '(prompt both)) #t))
    (define search? (and (memq mode '(search both)) #t))
    (define active? (or prompt? search?))
    (define shown (cond [prompt? "P x y"] [search? "failing: "]
                       [(equal? token "saved") "saved: un"]
                       [(equal? token "failed") "failed: u"] [else ""]))
    (def! st 'raw (session (zipper '(a)) t #:echo token #:searching search?
      #:prompt (if prompt? active-prompt no-prompt) #:pending pending))
    (def! st 'locked '(raw toggle-window-lock))
    (same-session st 'locked (rebuild 'raw #:windows (config locked-t 7)))
    (same-session st '(locked toggle-window-lock) 'raw)
    (paint st 'raw 9 6 (multi rows (if prompt? 6 1) (if prompt? 5 1) 6 shown))
    (paint st 'locked 9 6 (multi rows (if prompt? 6 1) (if prompt? 5 1) 6 shown))
    (for ([op '(split-below split-right delete-window)])
      (same-session st `(locked ,op) (if active? 'locked (rebuild 'locked #:echo "failed")))
      (def! st 'refused `(locked ,op))
      (paint st 'refused 9 6
        (multi rows (if prompt? 6 1) (if prompt? 5 1) 6 (if active? shown "failed: u"))))
    ;; Unlock, then all three existing operations succeed, preserving active state.
    (def! st 'unlocked '(locked toggle-window-lock))
    (for ([op '(split-below split-right)])
      (define split-t (right ((if (eq? op 'split-below) below right) (leaf 7) (leaf 8)) (leaf 2)))
      (define ed (editor ab-text 0 0 0 0 (if (eq? op 'split-below) 1 4)))
      (same-session st `(unlocked ,op) (rebuild 'unlocked
        #:buffers (zipper (list (buffer 41 ed))) #:windows (config split-t 7)
        #:echo (if active? token "")))
      (def! st 'success `(unlocked ,op))
      (paint st 'success 9 6
        (multi (if (eq? op 'split-below)
                   '("abc |abc " "unti|def " "----+    " "abc |    " "unti|unti")
                   '("ab|a|abc " "de|d|def " "  | |    " "  | |    " "un|u|unti"))
               (if prompt? 6 1) (if prompt? 5 1) 6 (if active? shown ""))))
    (same-session st '(unlocked delete-window)
      (rebuild 'unlocked #:windows (config (leaf 2) 2)))
    (def! st 'deleted '(unlocked delete-window))
    (paint st 'deleted 9 6 (single '("abc" "def" "" "" "") 1 1 6 shown
                                 (if prompt? 6 1) (if prompt? 5 1) #:name "untitled" #:width 9)))
  ;; The sole leaf remains protected by the last-view rule after unlocking.
  (def! st 'one (session (zipper '(a)) (leaf 7) #:echo ""))
  (same-session st '(((one toggle-window-lock) toggle-window-lock) delete-window)
    (rebuild 'one #:echo "failed"))
  (effects calls '()))

(test-case "direct/execute/chord, pending consumption, plain l, misses and input precedence"
  (define-values (st calls) (state))
  (simple! st)
  (def! st 's (rebuild 's #:echo ""))
  (define locked (config (leaf 7 41 0 0 #t) 7))
  (for ([actual '((s toggle-window-lock)
                 (s execute-command (AloemacsCommand ToggleWindowLock) "unused")
                 ((s handle-key "ctrl-x") handle-key "l"))])
    (same-session st actual (rebuild 's #:windows locked)))
  (for ([token '("" "saved" "failed")])
    (def! st 'raw (rebuild 's #:echo token #:pending pending))
    (same-session st '(raw toggle-window-lock) (rebuild 'raw #:windows locked))
    (same-session st '(raw execute-command (AloemacsCommand ToggleWindowLock) "l")
      (rebuild 'raw #:windows locked))
    (same-session st '(raw handle-key "l")
      (rebuild 'raw #:windows locked #:pending no-pending))
    (same-session st `(((s with-echo ,token) handle-key "ctrl-x") handle-key "l")
      (rebuild 's #:windows locked #:echo "")))
  (define inserted (editor (indexed '("labc" "def")) 0 1
    #:history `(List of (UndoFrame new ,ab-text (Position new 0 0) 0 0)
                       (UndoFrame new (Text from-string "previous") (Position new 0 2) 1 2))))
  (same-session st '(s handle-key "l") (rebuild 's #:buffers (zipper (list (buffer 41 inserted)))))
  (for ([key '("x" "escape" "unknown" "" "left" "ctrl-x")])
    (same-session st `((s handle-key "ctrl-x") handle-key ,key) 's))
  (same-session st '(s handle-key "toggle-window-lock") 's)
  (def! st 'p (rebuild 's #:prompt active-prompt #:pending pending))
  (same-session st '(p handle-key "ctrl-x") 'p)
  (same-session st '(p handle-key "l") (rebuild 'p #:prompt
    '(Option Some (AloemacsPrompt new "P\t" "x\rly" 3 "" (List empty)))))
  (def! st 'search (rebuild 's #:searching #t #:query "" #:wrapped #f #:failing #f
    #:origin '(Position new 0 0)))
  (same-session st '(search handle-key "l") (rebuild 'search #:query "l" #:failing #t))
  (same-session st '((search handle-key "ctrl-x") handle-key "l")
    (rebuild 'search #:searching #f #:query "" #:origin '(Position new 0 0)
      #:wrapped #f #:failing #f #:windows locked))
  (def! st 'both (rebuild 'search #:prompt active-prompt))
  (same-session st '(both handle-key "l") (rebuild 'both #:query "l" #:failing #t))
  (same-session st '((both handle-key "ctrl-x") handle-key "l")
    (rebuild 'both #:searching #f #:query "" #:origin '(Position new 0 0)
      #:wrapped #f #:failing #f #:pending pending
      #:prompt '(Option Some (AloemacsPrompt new "P\t" "x\rly" 3 "" (List empty)))))
  (def! st 'quit-s (rebuild 'both #:buffers
    (zipper (list (buffer 41 (editor ab-text #:quit #t))))))
  (for ([key '("ctrl-x" "l")]) (same-session st `(quit-s handle-key ,key) 'quit-s))
  (same-session st '(quit-s toggle-window-lock) (rebuild 'quit-s #:windows locked))
  (same-session st '(quit-s execute-command (AloemacsCommand ToggleWindowLock) "ignored")
    (rebuild 'quit-s #:windows locked))
  (effects calls '()))
