#lang racket/base

(require racket/runtime-path
         rackunit
         (only-in "../aloe/env.rkt" env-define!)
         "../aloe/eval.rkt"
         (only-in "../aloe/main.rkt" make-top-level-env)
         "../aloe/parse.rkt"
         "../host/racket/term.rkt")

(define-runtime-path gel-main-path "../gel/main.aloe")
(define-runtime-path point-path "../examples/point.aloe")

(define (load-runtime! path environment)
  (eval-expr
   (parse-datum `(load ,(path->string path)))
   environment))

(define environment (make-top-level-env))
(define remaining-keys (box '("1" "q")))
(define output (open-output-string))
(env-define!
 environment
 'term
 (make-term-receiver
  output
  (lambda ()
    (define keys (unbox remaining-keys))
    (unless (pair? keys)
      (error 'fake-term "script exhausted"))
    (set-box! remaining-keys (cdr keys))
    (car keys))))
(load-runtime! gel-main-path environment)
(load-runtime! point-path environment)

(void
 (eval-expr
  (parse-datum
   '(gel-main call
      (gel-empty-stack push (Point new 10 20))))
  environment))

(define transcript (get-output-string output))
(check-regexp-match #rx"key 1\r\n" transcript)
(check-regexp-match #rx"key q\r\n" transcript)
;; Echo precedes the TOS/menu generated by the following loop iteration.
(check-regexp-match #rx"key 1\r\nTOS: 10\r\n" transcript)
