#lang racket/base

(require racket/runtime-path
         rackunit
         (only-in "../aloe/env.rkt" env-define!)
         "../aloe/eval.rkt"
         "../aloe/host.rkt"
         (only-in "../aloe/main.rkt" make-top-level-env)
         "../aloe/parse.rkt")

(define-runtime-path gel-main-path "../gel/main.aloe")
(define-runtime-path point-path "../examples/point.aloe")

(struct fake-term-state ([keys #:mutable] output) #:transparent)

(define fake-read-key
  (host-message
   0
   (lambda (receiver _arguments)
     (define state (host-receiver-state receiver))
     (define keys (fake-term-state-keys state))
     (unless (pair? keys)
       (error 'fake-term "script exhausted"))
     (set-fake-term-state-keys! state (cdr keys))
     (car keys))))

(define fake-write-line
  (host-message
   1
   (lambda (receiver arguments)
     (define value (car arguments))
     (unless (string? value)
       (error 'fake-term "write-line expects a String"))
     (define output
       (fake-term-state-output (host-receiver-state receiver)))
     (display value output)
     (display "\r\n" output)
     value)))

(define (load-runtime! path environment)
  (eval-expr
   (parse-datum `(load ,(path->string path)))
   environment))

(define environment (make-top-level-env))
(define state (fake-term-state '("1" "q") (open-output-string)))
(env-define!
 environment
 'term
 (host-receiver
  'Term
  (hasheq 'read-key fake-read-key
          'write-line fake-write-line)
  state))
(load-runtime! gel-main-path environment)
(load-runtime! point-path environment)

(void
 (eval-expr
  (parse-datum
   '(gel-main call
      (gel-start call (Point new 10 20))))
  environment))

(define transcript (get-output-string (fake-term-state-output state)))
(check-regexp-match #rx"key 1\r\n" transcript)
(check-regexp-match #rx"key q\r\n" transcript)
;; Echo precedes the TOS/menu generated by the following loop iteration.
(check-regexp-match #rx"key 1\r\nTOS: 10\r\n" transcript)
